Azure/AgentBaker

vhdbuilder/packer/install-dependencies.sh

the version string is changed in the new binary. revert it.

revert back to use the old kubelet binary.

---

.pipelines/.vsts-vhd-builder.yaml
vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/vhd-image-builder-gen2.json

This change enables us to bake the sgx device plugin to the GEN2 VHDs

Bake SGX device plugin to GEN2 VHDs

---

parts/linux/cloud-init/artifacts/cse_install.sh
vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/vhd-image-builder-gen2.json
vhdbuilder/packer/vhd-image-builder-sig.json
vhdbuilder/packer/vhd-image-builder.json
vhdbuilder/scripts/linux/tool_installs.sh

1.  it is only used in VHD baking, not part of cse
2. we want to keep cse_install.sh as small as possible to avoid exceeding cloud-init content size limit

Move bpf/bcc installation out of cse

---

vhdbuilder/publish/sig-version-publish.sh

we're missing the \ sign when publishing premium image, this change fixes that issue

Fix: add \ for publishing premium images

---

Makefile
pkg/templates/templates_generated.go

get rid of unnecessary size/timestamp info in template_generated.go

chore: go-bindata to not save size/timestamp

---

vhdbuilder/packer/install-dependencies.sh

Adds a new version of the openvpn image and a new legacy (v2) tunnel version that includes a small iptables rule fix.

Add some new tunnel images

---

parts/linux/cloud-init/nodecustomdata.yml
pkg/templates/templates_generated.go

https://github.com/Azure/aks-engine/blob/b6ea0dc5755d1d4566f9dc412d73d22f175a3d10/pkg/api/common/types.go#L38
Due to the difference in implementation between agentbaker and aks-engine, I failed to convert this properly when updating the templates. This causes node provisioning to fail.
How can I test this better? I guess I should use the test VHD pipeline to try to provision a cluster based off my branch? What's the best practice?

fix: inconsistency in data-root

---

parts/linux/cloud-init/artifacts/cse_config.sh
pkg/templates/templates_generated.go
vhdbuilder/scripts/linux/tool_installs.sh

Make sure nvidia utility and compute bins can be mounted into container as documented in nvidia-container-runtime readme.
ref:
https://github.com/Azure/aks-engine/pull/3029

Make sure nvidia utility and compute bins can be mounted into container

---

vhdbuilder/packer/install-dependencies.sh

Have a task to upgrade ip-masq-agent to at least v2.2.0 because the current version caused a few incidents

Add a new ip-masq-agent version to the VHD

---

parts/linux/cloud-init/nodecustomdata.yml
pkg/agent/variables.go
pkg/templates/templates_generated.go

There is an extra double quote for AZURE_ENVIRONMENT_FILE env variable in /etc/default/kubelet. 
Also, the outbound connection test command needs to include port 443 for MCR.

fixing extra quote and missing ports for custom clouds

---

parts/linux/cloud-init/artifacts/cse_cmd.sh
pkg/templates/templates_generated.go

For this command we actually can't put in cse_main.sh, since it doesn't print(due to /bin/bash /opt/azure/containers/provision.sh >> /var/log/azure/cluster-provision.log 2>&1).
Also because L68 uses nohup, everything after it might not get executed.
Therefore it has to be in the same command executed with nohup.
I've tested in standalone env this is working.

Fix an issue that kubelet status doesn't print

---

pkg/agent/variables.go

In some case, we noticed that CSE failed to check outbound connectivity because the network is not yet ready in 50 seconds. increasing the retries to wait for longer.

Retry more times for outbound connection checking

---

cmd/generate.go
cmd/root.go
pkg/agent/baker_test.go
pkg/agent/datamodel/addons.go
pkg/agent/datamodel/addons_test.go
pkg/agent/datamodel/defaults-apiserver.go
pkg/agent/datamodel/defaults-apiserver_test.go
pkg/agent/datamodel/defaults-cloud-controller-manager.go
pkg/agent/datamodel/defaults-cloud-controller-manager_test.go
pkg/agent/datamodel/defaults-controller-manager.go
pkg/agent/datamodel/defaults-controller-manager_test.go
pkg/agent/datamodel/defaults-custom-cloud-profile.go
pkg/agent/datamodel/defaults-kubelet.go
pkg/agent/datamodel/defaults-kubelet_test.go
pkg/agent/datamodel/defaults-scheduler.go
pkg/agent/datamodel/defaults-scheduler_test.go
pkg/agent/datamodel/defaults.go
pkg/agent/datamodel/defaults_test.go
pkg/agent/datamodel/mocks.go
pkg/agent/datamodel/types.go
pkg/agent/datamodel/types_test.go
pkg/agent/types.go
pkg/agent/utils.go
pkg/agent/variables.go

This change copies the ContainerService struct and related functions that are used by us. It also ported the necessary defaults-***.go code and their tests (defaults-custom-cloud-profile.go has no test in aks-engine code base).
Not all aks-engine datastructs are ported in this change because it would make the change list too big. After this code goes in, I'll immediately start working on porting other structs such as Properties, AgentPoolProfile, etc. The end goal is to port over all data structs so that we don't depend on aks-engine's data model.

Port aks-engine's ContainerService struct into our code base.

---

cmd/generate.go

AgentBaker doesn't use this command line value.

Remove the code handling apiVersion=="vlabs" command line.

---

pkg/agent/datamodel/defaults-kubelet_test.go
pkg/agent/datamodel/defaults_test.go

Add some fake certificates to bypass the "SetDefaultCerts" part of setting default values, which accelerates the test cases dramatically. The two test cases that test setting cert defaults, TestSetCertDefaults and TestSetCertDefaultsVMSS, are the only two left that still generates certificates during the test run. Now those two test cases take the vast majority of the test run time.
After this change, the entire datamodel unit test run time is reduced from 5 minutes to about 20 seconds on my machine.

Bypass the "SetDefaultCerts" code in test to make test cases run much faster.

---

pkg/aks-engine/api/apiloader.go
pkg/aks-engine/api/apiloader_test.go

Removed support for 2017-08-31 and 2018-03-31 in LoadContainerServiceFromFile.

Remove support for old API versions in ApiLoader's LoadContainerServiceFromFile

---

cmd/generate.go
pkg/aks-engine/api/apiloader.go
pkg/aks-engine/api/apiloader_test.go
pkg/aks-engine/api/strictjson_test.go

The only place we use LoadContainerServiceFromFile is in cmd/generate.go, with this call:
apiloader.LoadContainerServiceFromFile(gc.apimodelPath, false, false, nil)
Since "validate", "isUpdate" params are always false and existingContainerService is always nil, we can simplify the code a lot.

Remove unused params from apiloader.LoadContainerServiceFromFile

---

cmd/generate.go
pkg/agent/datamodel/types.go
pkg/aks-engine/api/apiloader.go
pkg/aks-engine/api/apiloader_test.go
pkg/aks-engine/api/strictjson_test.go

This removes the need for conversion functions for different ContainerService structs.
Also removed the check for "case vlabs.APIVersion". We'll just load the ContainerService regardless of the version.

Use AgentBaker's own ContainerService struct in ApiLoader's LoadContainerServiceFromFile.

---

cmd/generate.go
pkg/agent/datamodel/types.go
pkg/aks-engine/api/apiloader.go
pkg/aks-engine/api/apiloader_test.go
pkg/aks-engine/engine/engine.go
pkg/aks-engine/engine/engine_test.go
pkg/aks-engine/engine/output.go
pkg/aks-engine/engine/output_test.go

This removes the need to have conversion functions for data models.
Also in SerializeContainerService removed support for the older API versions v20170831 and v20180331.

Use our own ContainerService in ArtifactWriter.WriteTLSArtifacts.

---

cmd/generate.go
pkg/agent/baker_test.go
pkg/agent/datamodel/defaults-apiserver_test.go
pkg/agent/datamodel/defaults-kubelet_test.go
pkg/agent/datamodel/defaults.go
pkg/agent/datamodel/defaults_test.go
pkg/agent/datamodel/mocks.go
pkg/agent/datamodel/types.go
pkg/agent/datamodel/types_test.go
pkg/agent/utils.go
pkg/aks-engine/api/apiloader_test.go
pkg/aks-engine/engine/engine_test.go

This change copies the following data structs: ResourcePurchasePlan, ExtensionProfile, DiagnosticsProfile, JumpboxProfile, ServicePrincipalProfile, CertificateProfile, AADProfile, CustomProfile, HostedMasterProfile, AddonProfile, FeatureFlags, TelemetryProfile and CustomCloudEnv.
This removes our dependency on those data types from aks-engine. Our end goal is to remove all aks-engine dependencies.

Copy some aks-engine data structs into our code base.

---

cmd/root.go

AgentBaker doesn't support Azure Stack, so we don't need those code.

Remove Azure Stack related code from cmd/root.go

---

pkg/agent/baker.go
pkg/agent/baker_test.go
pkg/agent/datamodel/defaults-kubelet.go
pkg/agent/datamodel/defaults-kubelet_test.go
pkg/agent/datamodel/defaults.go
pkg/agent/datamodel/defaults_test.go
pkg/agent/datamodel/mocks.go
pkg/agent/datamodel/types.go
pkg/agent/datamodel/types_test.go
pkg/agent/params.go
pkg/agent/utils.go
pkg/aks-engine/api/apiloader_test.go

This ports the following: ResourceIdentifiers, UserAssignedIdentity, AuthenticatorType, KeyvaultSecretRef, OSType, VMDiagnostics, ImageReference, KeyVaultSecrets, KeyVaultID, KeyVaultCertificate, PublicKey, Distro, CustomSearchDomain and CustomNodesDNS.
This removes our dependency on those data types from aks-engine. Our end goal is to remove all aks-engine dependencies.

Port many types from aks-engine into our code base.

---

pkg/agent/baker.go
pkg/agent/datamodel/azenvtypes.go
pkg/agent/datamodel/types.go
pkg/agent/params.go

This removes our dependency on aks-engine's azenvtypes.go. Our end goal is to remove all aks-engine dependencies.

Port azenvtypes.go from aks-engine into our code base.

---

cmd/root.go
pkg/aks-engine/api/apiloader.go
pkg/aks-engine/api/apiloader_test.go

Copy apiloader.LoadDefaultContainerServiceProperties from aks-engine and use it in cmd/root.go.
This removes our dependency on that function from the aks-engine code base. Our end goal is to remove all aks-engine dependencies.

Copy apiloader.LoadDefaultContainerServiceProperties from aks-engine.

---

cmd/generate.go
pkg/agent/baker_test.go
pkg/agent/datamodel/mocks.go
pkg/agent/datamodel/types.go
pkg/aks-engine/engine/engine.go
pkg/aks-engine/engine/engine_test.go
pkg/aks-engine/engine/output.go
pkg/aks-engine/engine/output_test.go

Changed FormatProdFQDNByLocation to take a *AzureEnvironmentSpecConfig param because the code copied used the global "AzureCloudSpecEnvMap" that's no longer being used in AgentBaker.

Port FormatProdFQDNByLocation from aks-engine.

---

parts/linux/cloud-init/artifacts/init-aks-custom-cloud.sh
pkg/templates/templates_generated.go

When running the custom cloud init script to update ca certificates, we got command not found errors. Using full path fixes this issue.

using full path for update-ca-certificates

---

parts/linux/cloud-init/artifacts/init-aks-custom-cloud.sh
pkg/templates/templates_generated.go

Switch to chrony and local time source for LX clouds for now. Once we verified that the local timesource (hostvm) jittering bug is resolved and the change pushed to all clouds, we can make another change to switch ALL clouds to use host clock as time source.

switch to chrony and local time source for AKS custom clouds

---

.pipelines/.vsts-vhd-builder-release.yaml
.pipelines/.vsts-vhd-builder.yaml

We need build id so that the ev2 pipeline can pick up the artifact from the release pipeline

Add build number for the AKS VHD Linux Pipeline - Release

---

vhdbuilder/packer/install-dependencies.sh

we do not use the v3.0.16/v4.0.14
instead we bump the image with the ipv6 fix together.

baking the new tunnel image with ipv6 fix.

---

parts/linux/cloud-init/nodecustomdata.yml
pkg/templates/templates_generated.go

feat: Support multiple vnetCidrs
Current code only support one vnetCidr. With this change, we can pass multiple vnetCidrs with the format `vnetCidr1` or `vnetCidr1,vnetCidr2,vnetCidr3`.

feat: Support multiple vnetCidrs

---

parts/linux/cloud-init/nodecustomdata.yml
pkg/agent/testdata/AKSUbuntu1604+DynamicKubelet/CustomData
pkg/agent/testdata/AKSUbuntu1604+EnablePrivateClusterHostsConfigAgent/CustomData
pkg/agent/testdata/AKSUbuntu1604+GPUDedicatedVHD/CustomData
pkg/agent/testdata/AKSUbuntu1604+K8S115/CustomData
pkg/agent/testdata/AKSUbuntu1604+K8S117/CustomData
pkg/agent/testdata/AKSUbuntu1604+K8S118/CustomData
pkg/agent/testdata/AKSUbuntu1604+TempDisk+Containerd/CustomData
pkg/agent/testdata/AKSUbuntu1604+TempDisk/CustomData
pkg/agent/testdata/AKSUbuntu1804+Containerd+NSeriesSku/CustomData
pkg/agent/testdata/RawUbuntu/CustomData
pkg/templates/templates_generated.go

168.63.129.16 is a special Azure IP that hosts various info, including priviledged settings, thus we need to block container/pod's access to it.

Block container's TCP traffic to the special IP address 168.63.129.16.

---

vhdbuilder/packer/install-dependencies.sh

Alright these are published to the share
https://dev.azure.com/AzureContainerUpstream/Kubernetes/_build/results?buildId=12437&view=results
Do have a customer asking for this in icm 205269699 so want to make the next vhd publish.

[CHORE]bake 1.1.7 cni into vhd.

---

vhdbuilder/publish/sig-version-create.sh

Update windows image version used in SIG as `${WINDOWS_VERSION}.$(date +"%y%m%d")`, e.g. 17763.678.190905
Linux image version is unchanged.
WINDOWS_VERSION is obtained from vhd-publishing-info.json in VHD building artifact list

adjust windows image version pattern in SIG

---

pkg/agent/datamodel/types.go
pkg/agent/datamodel/types_test.go
pkg/agent/params.go

When running in the context of AgentBaker, IsHostedMasterProfile() always returns true so we don't need it.

Remove IsHostedMasterProfile function because it always returns true.

---

parts/linux/cloud-init/nodecustomdata.yml
pkg/agent/testdata/AKSUbuntu1604+DynamicKubelet/CustomData
pkg/agent/testdata/AKSUbuntu1604+EnablePrivateClusterHostsConfigAgent/CustomData
pkg/agent/testdata/AKSUbuntu1604+GPUDedicatedVHD/CustomData
pkg/agent/testdata/AKSUbuntu1604+K8S115/CustomData
pkg/agent/testdata/AKSUbuntu1604+K8S117/CustomData
pkg/agent/testdata/AKSUbuntu1604+K8S118/CustomData
pkg/agent/testdata/AKSUbuntu1604+TempDisk+Containerd/CustomData
pkg/agent/testdata/AKSUbuntu1604+TempDisk/CustomData
pkg/agent/testdata/AKSUbuntu1804+Containerd+NSeriesSku/CustomData
pkg/agent/testdata/RawUbuntu/CustomData
pkg/templates/templates_generated.go

Commit [e7ec045c9a95](https://github.com/Azure/AgentBaker/commit/e7ec045c9a956543f2204d759c13a5631f368e8b) blocked all TCP connections to 168.63.129.16, which caused failures for  LoadBalancer probe requests and container DNS resolving requests with TCP protocol.
This PR fixed the issue by only blocking its TCP 80 port.

Only block 80 port for Azure DNS/LoadBalancer probe IP 168.63.129.16

---

pkg/agent/baker.go
pkg/agent/const.go
pkg/agent/testdata/AKSUbuntu1604+CustomKubeletConfig+CustomLinuxOSConfig/CustomData
pkg/agent/testdata/AKSUbuntu1604+KubeletConfigFile/CustomData
pkg/agent/utils.go
pkg/agent/utils_test.go

We need to delete this flag for kubelet config file, since we disabled DynamicKubeletConfig feature gate.

Delete dynamic-config-dir if using config file

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/vhd-content-test.ps1

1. chore: Add Windows signedscripts-v0.0.4
1. chore: Adding csi-proxy-v0.2.2 to Windows VHD
1. chore: Remove unsupported k8s version v1.15.x

Update Win cached packages

---

vhdbuilder/packer/sysprep.ps1
vhdbuilder/packer/windows-vhd-builder.json

fix: Windows VHD pipeline tests
https://github.com/Azure/aks-engine/pull/3977
```
Removes Azure VM agents from the sysprep process
- this fixes an issue where there was a missing DLL on recent upgrade of the Azure VM agents that caused sysprep to fail: 
azure-arm: IMAGE_STATE_UNDEPLOYABLE - missing VMAgentDisabler.dll. The VM agent doesn't do anything during sysprep so it is ok to remove it. If the image is deployed to Azure as a VM the agent will redeployed.
```

fix: Windows VHD pipeline tests

---

vhdbuilder/packer/windows-image.env

chore: update Windows base image versions
1. 2019
```
az vm image show --urn MicrosoftWindowsServer:WindowsServer:2019-Datacenter-Core-with-Containers-smalldisk:latest
{
"automaticOsUpgradeProperties": {
"automaticOsUpgradeSupported": false
},
"dataDiskImages": [],
"disallowed": {
"vmDiskType": "None"
},
"hyperVgeneration": "V1",
"id": "/Subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/Providers/Microsoft.Compute/Locations/westus/Publishers/MicrosoftWindowsServer/ArtifactTypes/VMImage/Offers/WindowsServer/Skus/2019-Datacenter-Core-with-Containers-smalldisk/Versions/17763.1577.2011031610",
"location": "westus",
"name": "17763.1577.2011031610",
"osDiskImage": {
"operatingSystem": "Windows",
"sizeInBytes": 32214352384,
"sizeInGb": 31
},
"plan": null,
"tags": null
}
```
2. 2004
```
az vm …
```

chore: update Windows base image versions

---

parts/linux/cloud-init/nodecustomdata.yml
pkg/agent/testdata/AKSUbuntu1804+Containerd+Teleport/CustomData
pkg/templates/templates_generated.go

Since the default value of the flag changed from `false` to `true`, we need to explicitly set it to `false`
https://github.com/containerd/cri/commit/99015cca6155121ea0924e7e73d1b3022d919efb
cc: @eriksywu

add DisableSnapshotAnnotation flag

---

vhdbuilder/packer/install-dependencies.sh

We're upgrading this addon image in RP side, need to bake the 1.7.0 image into VHD.

Add aad pod identity 1.7.0 image

---

vhdbuilder/release-notes/AKSWindows/2019/17763.1579.201208.txt

We forget to update the release notes of the Windows VHD built from https://github.com/Azure/AgentBaker/pull/465

chore: Add missing windows release notes

---

.pipelines/scripts/verify_shell.sh

It will throw below error when running `make generate` in WSL.
```
In ./.pipelines/scripts/verify_shell.sh line 4:
installed=$(which shellcheck 2>&1 >/dev/null)
^---^ SC2230: which is non-standard. Use builtin 'command -v' instead.
```

fix: Fix shellcheck in WSL

---

cmd/generate.go
cmd/generate_test.go

I tried to run the generate command from local, but it failed because of missing value for the `K8sComponents` property. This pull request fixed by adding the default value and added a simple unit test for generate cmd.

fix: add missing default value for `K8sComponents`

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/vhd-content-test.ps1

update Azure CNI to v1.2.0_hotfix

chore: update Azure CNI to v1.2.0_hotfix

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/vhd-content-test.ps1

Reference: https://github.com/Azure/aks-engine/pull/4134
Contains updates to powershell code used to start kubelet for kube-proxy
- feat: Updating kubelet/kube-proxy to run with as high priority processes (#4073)
- feat: Add WinDSR support (#4104)
- fix: fix that kubeproxy cannot parse featuregates #4145

chore: Use signed scripts v0.0.8 for Windows deployments

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/vhd-content-test.ps1

Update AKS Windows 2019 VHD with 2021 1B patch [kb4598230](https://support.microsoft.com/en-us/help/4598230/windows-10-update-kb4598230)
- URL: http://download.windowsupdate.com/d/msdownload/update/software/secu/2021/01/windows10.0-kb4598230-x64_f69498ce0cac1307eb0e6701ca334ff332364289.msu
- The latest Windows 2019 base image is still `17763.1637.2012040632`

chore: Update AKS Windows 2019 VHD with 2021 1B patch

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/vhd-content-test.ps1

Cache k8s 1.20.0 in AKS Windows VHD

chore: Cache k8s 1.20.0 in AKS Windows VHD

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/vhd-content-test.ps1

Add Windows Azure CNI v1.2.2. Below tests passed.
1. ran aks-engine: ` make test-kubernetes` with "examples/windows/kubernetes-windsr.json"
2. Ran E2E Windows and VHD tests

chore: Add Windows Azure CNI v1.2.2

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/vhd-content-test.ps1
vhdbuilder/packer/windows-vhd-builder-sig.json
vhdbuilder/packer/windows-vhd-builder.json
vhdbuilder/scripts/windows/collect-windows-logs.ps1

1. fix: fix network cleanup code on windows for contianerd nodes (#[4154](https://github.com/Azure/aks-engine/pull/4154))
2. fix: Adding csi-proxy logs to prevent access denied errors (#[4029](https://github.com/Azure/aks-engine/pull/4029))
3. feat: collect hyperv logs (#[3737](https://github.com/Azure/aks-engine/pull/3737))
4. feat: Collect calico logs

feat: collect more logs for Windows

---

README.md
vhdbuilder/cgmanifest.json

- Calico Windows is from https://docs.projectcalico.org/release-notes/
- calico-windows-v3.17.1.zip is signed by Microsoft aks-engine team
- We use `./vhdbuilder/cgmanifest.json` to register this third party package.

doc: Registering calico-windows-v3.17.1

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/vhd-content-test.ps1
vhdbuilder/packer/windows-image.env

Changes included in this PR:
- Add k8s 1.19.6 hotfix and new 1.19.7 and 1.20.2 cache
- Remove deprecated k8s 1.16
- Update base image
```
➜  AgentBaker git:(qinhao/vhd-plan-2021-02-01) ✗ az vm image show --urn MicrosoftWindowsServer:WindowsServer:2019-Datacenter-Core-with-Containers-smalldisk:latest 
{
"automaticOsUpgradeProperties": {
"automaticOsUpgradeSupported": false
},
"dataDiskImages": [],
"disallowed": {
"vmDiskType": "None"
},
"hyperVgeneration": "V1",
"id": "/Subscriptions/109a5e88-712a-48ae-9078-9ca8b3c81345/Providers/Microsoft.Compute/Locations/westus/Publishers/MicrosoftWindowsServer/ArtifactTypes/VMImage/Offers/WindowsServer/Skus/2019-Datacenter-Core-with-Containers-smalldisk/Versions/17763.1697.2101090203",
"location": "westus",
"name": "17763.1697.2101090203", …
```

chore: Add k8s 1.19.6 hotfix and new 1.19.7 and 1.20.2 cache and update base image

---

vhdbuilder/packer/configure-windows-vhd.ps1

Reference https://github.com/Azure/aks-engine/pull/4206

fix: use curl.exe and add retries when downloading artifacts to Windows VHD

---

vhdbuilder/packer/install-dependencies.sh

only node an cni can be patched. So this fails to pull v3.8.9.1 for typha and pod2daemon. This should allow us to fail fast https://github.com/Azure/AgentBaker/pull/501

Bring in 3.8.9.2 and remove 3.8.9.1 for images we can't patch

---

vhdbuilder/packer/generate-vhd-publishing-info.sh

This is a bug we're currently facing, that prevents automated builds from creating correct artifacts successfully

Fix wrong image version generation issue

---

vhdbuilder/packer/install-dependencies.sh

The implementation of SGX device plugin daemonset, which advertises EPC memory as an additional resource type in Kubernetes, has been updated to allow better integration with Intel's Icelake. With this implementation, in addition to the daemonset itself, there is also an SGX admission webhook service and deployment to ensure backward compatibility for customer workloads. This was required as the new implementation also updates the name of the EPC memory resource being advertised to the AKS cluster nodes.

updated sgx-device-plugin image and added webhook image

---

vhdbuilder/packer/install-dependencies.sh

Trying to release a new calico version v3.17.1
It updates 2 old images calico/node and calico/typha
It has 2 new images calico/kube-controllers and tigera/operator
pod2daemon and cni are not included

Cache calico v3.17.1 images

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/vhd-content-test.ps1
vhdbuilder/packer/windows-image.env

changes included in this PR:
- Add Windows server 2019 patch of Feb 16, 2021
- Align left brackets with the function name in vhd test PS script
- Update Windows containerD. containerD VHD is for testing only
- Update base image to 17763.1757.2102060435

chore: add Windows server 2019 patch of Feb 16, 2021 

---

vhdbuilder/packer/install-dependencies.sh

A few days ago I cached Calico 3.17.1 https://github.com/Azure/AgentBaker/pull/581/files for Windows Calico preview (for k8s version 1.20 and above)
A lot of things changed and now we need Calico 3.17.2 and tigera operator 1.13.5 instead
I am removing 3.17.1 images from the cache because no customer is using them

Cache Calico 3.17.2 instead

---

.pipelines/.vsts-vhd-builder-windows.yaml
.pipelines/.vsts-vhd-builder.yaml
.pipelines/templates/.builder-release-template-windows.yaml

Currently, the cleanup stage for the windows build is failing since my earlier change (#574) broke this behavior.
This PR tries to address this issue.
Tests performed:

Fix windows build issue

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/test/linux-vhd-content-test.sh

In our VHD build we're not correctly retrieving azure-cloud-node-manager images, this fixes the issue

Correct wrong image name

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1

Upgrade calico Windows to v3.17.2

chore: Upgrade calico Windows to v3.17.2

---

pkg/agent/baker.go
pkg/agent/baker_test.go
pkg/agent/const.go
pkg/agent/datamodel/types.go

* move parse vmss cse logic to agent baker
* change parseVMSSCSE
* change error format
* fix the comment
Co-authored-by: Jianping Zeng <jizen@microsoft.com>

Parse VMSS CSE in agentbaker (#607)

---

pkg/agent/baker.go
pkg/agent/baker_test.go
pkg/agent/datamodel/types.go
pkg/agent/utils.go
pkg/agent/utils_test.go

To avoid depending on agent profile, this pull request decoupled the TLS bootstrap token to set in the `NodeBootstrappingConfiguration`. I also removed the unused `TLSBootstrapToken` struct from agent pool profile.

tlsbootstrap: read TLS bootstrap token from `NodeBootstrappingConfiguration`

---

vhdbuilder/packer/install-dependencies.sh

Move kubelet/kubectl logging to bottom so that it doesn't appear in middle of the images pulled.
Also moved hyperkube since they usually updated together with kubelet/kubectl.

chore: Better logging for kubelet/kubectl

---

pkg/agent/baker.go
pkg/agent/baker_test.go
pkg/agent/const.go
pkg/agent/datamodel/types.go
pkg/agent/utils.go
pkg/agent/utils_test.go

* rename ParseCSE
* change comment to ParseCSE
* make parseCSEMessage general
* fix some minor comments
* create a new error struct
* make error specific
Co-authored-by: Jianping Zeng <jizen@microsoft.com>

Rename ParseVMSSCSEMessage to ParseCSE (#631)

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/test/linux-vhd-content-test.sh
vhdbuilder/packer/test/windows-vhd-content-test.ps1

Update Azure CNI to [v1.2.7](https://github.com/Azure/azure-container-networking/releases/tag/v1.2.7)

chore: Update Azure CNI to v1.2.7

---

.pipelines/.vsts-vhd-builder-release.yaml
vhdbuilder/packer/vhd-image-builder-mariner.json

install-dependencies.sh is failing because ENABLE_FIPS is unset during the Mariner VHD build.
Setting it this way even if ENABLE_FIPS is undefined during Packer invocation is enough to unblock the script.

Create ENABLE_FIPS env var for Mariner VHD builds

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh

From March 18, there might be some repo/packages changes on Ubuntu repo side, so the apt_get_dist_upgrade in installDeps() installs some extra systemd related packages, and it causes dns resolving issue in following installation on FIPS vhd.

Fix dns resolving issue after installDeps on FIPS build

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/init-variables.sh
vhdbuilder/packer/vhd-image-builder-sig.json
vhdbuilder/packer/windows-vhd-builder-sig.json

When building SIG image in our SIG mode pipeline,  sig image creation time out occurs frequently. The answer to this is that `shared_image_gallery_timeout` with default value 1hour is overwritten by `polling_duration_timeout` which actually defaults to 15 minutes, and the sig image creation is normally more than 15 minutes, but 30 minutes or so.
I have a [fix of this issue in packer](https://github.com/hashicorp/packer/pull/10816), but to not block our more incoming sig image test, I here use polling_duration_timeout instead. Also, as the SIG image pipeline is for testing, not for production, the influence is limited.

chore: enlarge sig timout

---

vhdbuilder/packer/install-dependencies.sh

During the refactor we removed the logging part for each cni download so the refactor wasn't fully correct, and for completeness of our tests with CSE it's better to keep the previous logic

Add back cni downloads to install dependency script

---

vhdbuilder/packer/components.json

This new image removes owner references from resources created by the addon because v1.20 clusters have conflicts with cross-namespaced owner references. They are not needed anymore as root issue with gatekeeper has been fixed.

Update image - removes owner references for cluster v1.20 compatibility

---

pkg/agent/baker.go

Currently most clusters do not have an OSSKU property set, so checking OSSKU=Ubuntu isnt a good indicator of IsUbuntu. Since the function is not used anywhere yet, remove it for now to avoid confusion.

Remove IsUbuntu OSSKU check

---

pkg/agent/datamodel/types.go
pkg/agent/utils_test.go

* Change execDuration to correct type
* validate all fields in test
* update ExecDuration comment
* add another test when ExecDuration is int
Co-authored-by: Jianping Zeng <jizen@microsoft.com>

cherrypick Change execDuration to correct type (#718)

---

vhdbuilder/packer/components.json
vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1

update secrets-store-provider-azure to 0.0.14 and secrets-store-csi-driver to v0.0.21

chore: update secrets store csi driver related images

---

vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.1879.20210414.txt
vhdbuilder/release-notes/AKSWindows/2019/17763.1879.20210414.txt

Add release notes for AKS Windows VHD with 4B for both docker and containerd.
Add a new folder for the release notes of 2019 with containerd

doc: Add release notes for AKS Windows VHD with 4B

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1

- cache signedscripts v0.0.13 (fix the issue https://github.com/Azure/aks-engine/issues/4351)
- remove signedscripts-v0.0.10.zip since AKS Windows does not use it

chore: cache signedscripts v0.0.13

---

vhdbuilder/packer/components.json

This is for the April OMS agent release (Container Insights)
pkg/agent/k8s_versions_for_baker_test.go also has a reference to omsagent, but it doesn't look like that file should be updated to have the newest agent (please correct me if I'm wrong)
/assign @ganga1980

updating omsagent for April release

---

pkg/agent/k8s_versions_for_baker_test.go
vhdbuilder/packer/components.json

Cache Image to fix egress test/not pull for new clusters.
Hoping we can actually remove network monitor soon.

new cve fix fo networkmanger

---

.pipelines/templates/.builder-release-template.yaml

revert vhd tests in weekly build pipelines(gen2, mariner, 1604 failing)

revert added test-building-vhd to weekly builds (#769)

---

.pipelines/.vsts-vhd-builder.yaml
.pipelines/templates/.builder-release-template-windows.yaml
.pipelines/templates/.builder-release-template.yaml
vhdbuilder/packer/test/run-test.sh

Currently, if the previous step fails, still some of the steps to publish artifacts continue. 
This may break a re-run of the failed step caused by the existing published artifact, like the error below:
`##[error]Artifact publishing-info-2019 already exists for build 41753757.`
We can benefit from re-running the failed job considering we have multiple jobs in one build, and the failure is caused by intermittent and recoverable errors.
tests have been done:
- Linux check-in pipeline
https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=41831847&view=results
- [TEST All VHDs] AKS Linux VHD Build - Msft Tenant
https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=41831846&view=logs&jobId=35680035-4ba4-5771-0c56-b9253365da62&j=35680035-4ba4-5771-0c56-b …

fix: don't publish artifacts if previous steps fail

---

vhdbuilder/scripts/windows/collect-windows-logs.ps1

kubeclusterconfig.json does not contain any credentials but it contains some parameters for trouble shooting, for example, `WinDSR=true, WinOverlay=false` is included in FeatureGates when enabling WinDSR.

feat: Collect kubeclusterconfig.json

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1

Cache below k8s versions in Windows VHD
1.  v1.18.17-hotfix.20210505 (update)
2.  v1.18.18-hotfix.20210504 (new)
3. v1.19.9-hotfix.20210505 (update)
4. v1.19.10-hotfix.20210504 (new)
5. v1.20.5-hotfix.20210505 (update)
6. v1.20.6-hotfix.20210504 (new)

chore: Add k8s hotfixes

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1

1. Separate images for containerd from docker's.
2. Remove PauseImage 1.4.1 since we have updated it to 3.4.1 with last Windows VHD in AKS
3. Remove old versions v0.5.1, v0.6.0, for azure-cloud-node-manager
3. Only keep one latest version for each image for containerd as a workaround for the issue that disk space is not enough in the VHD since containerd is in public preview

chore: remove old Windows images

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1

Add Windows update 2021-5B. 
- [KB5003243](https://support.microsoft.com/en-us/topic/may-11-2021-kb5003171-os-build-17763-1935-3f03e74b-4759-4ca3-b9f1-4bc0d5ab5d27)
- [KB5003171](https://support.microsoft.com/en-us/topic/kb5003243-servicing-stack-update-for-windows-10-version-1809-may-11-2021-0941fe82-b9f4-40fb-845d-63e70c1f9242)

chore: Add Windows update 2021-5B

---

vhdbuilder/packer/components.json

Use metrics-server v0.4.4 and remove unused version v0.3.5.

Use metrics-server v0.4.4 and remove unused version

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/scripts/linux/mariner/tool_installs_mariner.sh
vhdbuilder/scripts/linux/tool_installs.sh

CSE is successfully deploying 11-containerd.conf to Mariner nodepools, but the Mariner base image has a security hardening config at priority 50 that's explicitly setting `net.ipv4.ip_forward = 0`. Because ip_forward is disabled, Mariner nodepools with AzureCNI networking have DNS issues.
This change puts a priority 99 sysctl configuration into the Mariner VHD with the same settings as 11-containerd.conf. Because this config is a higher priority than the hardening config it ensures that the expected containerd sysctl settings are active.
Verified by building a test image and successfully deploying an AzureCNI cluster with it.

Add sysctl IP forwarding config for Mariner

---

vhdbuilder/packer/components.json

Updating azure-cns to v1.3.3 because of a race found during pod scale up in SWIFT.

Update azure-cns image to v1.3.3

---

vhdbuilder/publish/Marketplace/new-sku-and-add-image-version.sh

`No subscriptions found for xxxx.` will be reported when we login to get token from cloudpartner. as the sp is used to talk to marketplace and no use for sub-level operations, so we did not attach any sub to this sp and don't have to.

fix pir publish issue

---

vhdbuilder/packer/components.json

CVE's in found in pod2daemon-flexvol so we need to go from v3.8.9 -> v3.8.9.1
Tigera-operator also needs updating so adding that in with the relevant Calico images. I will list what images tigera-operator pulls below:
```
Calico v3.17.2 via tigera-operator v1.13.5
Calico v3.18.1 via tigera-operator v1.15.1
Calico v3.19.0 via tigera-operator v1.17.1
```

Update calico images for CVE

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

Fix write-log is not used before defined.
Use `throw` instead of `log & exit 1` in `windows-vhd-configuration.ps1`

fix: Fix write-log is not used before defined

---

vhdbuilder/packer/components.json

Adding the Container Insights 5-20-2021 release. This release is also Linux only, so there is no updated Windows image to add.
I left the 03262021 image and removed the other two newer images because CI rolled back to 03262021 in production. We discovered an issue in the following two images and abandon those two releases. They will never be deployed again, so no need to have them in the agent baker.
@microsoft/docker-provider-devs

added linux container insights agent image 05202021

---

vhdbuilder/packer/install-dependencies.sh

Uses this release: https://github.com/Azure/azure-container-networking/releases/tag/v1.4.0

Update Azure CNI to v1.4.0

---

parts/linux/cloud-init/artifacts/mariner/cse_install_mariner.sh
pkg/templates/templates_generated.go

Updating the fixed value of CONTAINERD_VERSION in CBLMariner's version of installStandaloneContainerd to match the moby-containerd available in the Mariner package repository.
A value of 1.4.4 was causing CSE to uninstall moby-containerd-1.3.4 then reinstall moby-containerd-1.3.4 on Mariner. This caused unnecessary package repo access during CSE, since the VHD already has all required packages installed.
In the future when Mariner's moby-containerd version is incremented I'll revisit this logic.

Set CONTAINERD_VERSION for Mariner to match available version

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

Remove ciprod:win-ciprod04222021 in Windows containerd VHD since there is no enough space in it.

chore: Remove ciprod:win-ciprod04222021 in Windows containerd VHD

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

James fixed https://github.com/kubernetes/kubernetes/issues/98509 in this PR [Ignore transient errors when gathering stats for Windows Containers in Dockershim by jsturtevant · Pull Request #98510 · kubernetes/kubernetes (github.com)](https://github.com/kubernetes/kubernetes/pull/98510)
They are included in below k8s patch versions.
- v1.19.12 Kubernetes v1.19.12
- v1.20.8 Kubernetes v1.20.8
- v1.21.2 Kubernetes v1.21.2
Cache this in next AKS Windows VHD so we do not need to release a new AKS Windows VHD when AKS supports above versions. We can replace/remove these binaries when AKS supports above versions with hotfix or skip them.

Cache v1.19.12, v1.20.8 and v1.21.2 in AKS Windows VHD

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/scripts/linux/mariner/tool_installs_mariner.sh

The default systemd-networkd configuration in CBLMariner is matching on the Mellanox virtual function and is waiting for a 2 minute timeout for DHCP to assign it an IP address. This virtual device isn't supposed to get an IP address so it's an unnecessary 2 minute delay during cluster provisioning.
This change updates the default 99-dhcp-en.network config to only match on eth0, which matches the behavior on Ubuntu.

Add workaround for networkd config in CBLMariner

---

vhdbuilder/packer/install-dependencies.sh

This change adds support for k8s 1.21.2 and removes 1.17(as it is already deprecated)

Add support for k8s version 1.21.2

---

cmd/generate_test.go
e2e/e2e_test.go
pkg/agent/baker_test.go
pkg/agent/datamodel/mocks.go
pkg/agent/datamodel/types.go
pkg/agent/datamodel/types_test.go
pkg/agent/params.go
pkg/aks-engine/api/apiloader.go
pkg/aks-engine/api/apiloader_test.go
pkg/aks-engine/api/testdata/simple/kubernetes.json
pkg/aks-engine/engine/testdata/simple/kubernetes.json

Remove the "Count" field from AgentPoolProfile as it is not used by our templates.
The count value is put into a parameter <agentPoolName>Count, but that parameter is not used anywhere.

Remove the "Count" field from AgentPoolProfile as it is not used

---

cmd/generate_test.go
pkg/agent/baker_test.go
pkg/agent/datamodel/types.go
pkg/agent/datamodel/types_test.go
pkg/agent/params.go
pkg/aks-engine/api/apiloader.go
pkg/aks-engine/api/apiloader_test.go

Removed the following fields:
AvailabilityZones, Subnet, DiskSizesGB, ScaleSetEvictionPolicy, ScaleSetPriority, and OSDiskSizeGB.
Some of them were put into the parameters or variables map, but those parameters or variables were never used.

Remove unused fields from AgentPoolProfile.

---

pkg/agent/bakerapi.go
pkg/agent/bakerapi_test.go
pkg/agent/datamodel/const.go
pkg/agent/datamodel/osimageconfig.go
pkg/agent/datamodel/types.go

This is the preparation step to separate AgentBaker into a standalone service. RP will call the API provided by AgentBaker to get CustomData, CSE, and VHD image to provision nodes.
We'll use protocol buffer and gRPC for the API definition. For now, use straight Go interface as API to help testing the end to end flow.

Add an AgentBaker interface for RP to use.

---

pkg/agent/datamodel/const.go
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

The issue https://github.com/microsoft/Windows-Containers/issues/106 is fixed in the docker 20.10. Update Windows docker version to 20.10.6 which is the latest docker version in DockerMsftProvider 
I will merge this PR after https://github.com/Azure/aks-engine/pull/4556 is merged

chore: Update Windows docker version to 20.10.6

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

Remove old omsagent image in Windows VHD since that it seems like that the disk is not enough
https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=44526225&view=logs&j=4cae91f8-9300-5d2a-325c-cec7e691ae6d&t=ba6e6658-3216-5a7b-1df5-e991efde6751

fix: Remove old omsagent image in Windows containerd VHD

---

vhdbuilder/packer/components.json

Fix https://github.com/Azure/AKS/issues/2426

Add CoreDNS 1.8.4 into VHD and cleanup the unused

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/generate-windows-vhd-configuration.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1

Disk is not enough in building Windows 2019 docker image. https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=45352208&view=logs&j=15a94705-2dfe-51ff-b195-e5f5cdf037b6&t=12803780-4248-5d28-29fb-fc69ebac29b6&l=1403
1. Remove old images
2. Do not download containerd package when building docker image

chore: Remove old images and packages

---

.pipelines/scripts/verify_shell.sh

Running `make generate` on MacOS/Darwin leads to this error:
```
./.pipelines/scripts/verify_shell.sh: line 65: shellcheck: command not found
make[1]: *** [validate-shell] Error 127
make: *** [generate] Error 2
```
as shellcheck was not installed. 
This PR adds the installation of shellcheck and removes this error during the execution of `make generate`.

Install shellcheck for Darwin

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

csi-proxy v1.0.0 GA binary is compatible with v0.2.2 beta interface.

chore: upgrade to csi-proxy v1.0.0 GA binary

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/test/linux-vhd-content-test.sh

Added patch versions to KUBE_BINARY_VERSIONS for caching. kube-proxy images are in kube-proxy-images.json.

Cache k8s versions: 1.19.13 and 1.20.9

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1

Actually the tls configuration in building Windows VHD does not work as expected. We have disabled insecure TLS protocols in node provisioning so I think that we can remove these code now.

remove unuseful code Set-AllowedSecurityProtocols

---

parts/linux/cloud-init/artifacts/mariner/cse_install_mariner.sh
pkg/templates/templates_generated.go

lsof and pstree are missing on the current CBLMariner VHDs causing some log-collection scripts to fail.
This commit adds those two tools into the CBLMariner VHD.

Add lsof and pstree tools to CBLMariner VHD

---

pkg/agent/bakerapi_test.go
pkg/agent/datamodel/osimageconfig.go
pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go

Cherry-picks #1021 onto the release branch

bump SIG image versions to align with the latest used (#1021)

---

vhdbuilder/packer/install-dependencies.sh

Removing from comments listing supported versions. Not removing from list of binaries pulled to "support VMAS scale up scenario" (as mentioned in `install-dependencies.sh`),

Remove k8s versions 1.19.9 and 1.20.5 from supported version comments

---

vhdbuilder/scripts/windows/collect-windows-logs.ps1

Collect CCGPlugin logs for Windows gMSAv2
C:/windows/system32/winevt/Logs/Microsoft-Windows-Containers-CCG%4Admin.evtx
disk inspector: https://github.com/Azure/azure-diskinspect-service/pull/202

feat: Collect CCGPlugin logs for Windows gMSAv2

---

vhdbuilder/packer/packer_source.sh
vhdbuilder/packer/vhd-image-builder-gen2.json
vhdbuilder/packer/vhd-image-builder-mariner-gen2.json
vhdbuilder/packer/vhd-image-builder-mariner.json
vhdbuilder/packer/vhd-image-builder-sig.json
vhdbuilder/packer/vhd-image-builder.json

this file contains Go templates and cannot be baked into the VHD as-is. remove it. more to come.

fix: remove templated files from VHD

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/test/linux-vhd-content-test.sh

Removing k8s version 1.18.8's kube binary for additional space. Currently 99% of the disk space is full for the `1804_fips_gen2_gpu_containerd` sku.

Remove k8s version: 1.18.8

---

vhdbuilder/packer/components.json

Title says it all. The only difference between ciprod08052021 and ciprod08052021-1 is the image tag
@ganga1980 @vishiy @rashmichandrashekar @gracewehner

adding omsagnet image ciprod08052021-1

---

pkg/agent/datamodel/types.go
pkg/agent/params.go

Fix windows node provision failure using feature combination: windows + private cluster + byo private dns zone + fqdnSubdomain.
When fqdnSubdomain is used, the dnsPrefix will be empty. This is by design. 
Tested in standalone env with this fix.

fix empty dnsprefix in windows cse

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

1. Remove v.17.x since AKS removed the support for v1.18.x
2. Remove v1.1.9.12 since it is never supported in AKS
3. Remove v1.20.8 since it is never supported in AKS
4. Remove v1.21.1-hotfix.20210713 since AKS has used v1.21.1-hotfix.20210827 for Windows
5. Remove v1.21.2-hotfix.20210816 since AKS has used v1.21.2-hotfix.20210830 for Windows

chore: Update cached k8s versions in AKS Windows VHD

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

1. Add k8s 1.22.1 in AKS Windows VHD. cc @ganeshkumar5699 
2. Remove azuredisk-csi:v1.4.0, azurefile-csi:v1.4.0. cc @andyzhangx @ZeroMagic 
3. Remove containerd-v0.0.41-windows-amd64.tar.gz. cc @mainred 
4. Remove ciprod:win-ciprod06112021
5. Remove azure-vnet-cni-singletenancy-windows-amd64-v1.4.0.zip
6. Update CCGAKVPlugin package to v1.1.1

Add k8s 1.22.1 and remove old cached files

---

vhdbuilder/packer/components.json

Add Policy images containing high severity CVE fixes CVE-2021-3711, CVE-2021-3712, CVE-2021-3121
Below 3 newly added images contains the security fixes...
mcr.microsoft.com/azure-policy/policy-kubernetes-addon-prod:prod_20210909.1
mcr.microsoft.com/azure-policy/policy-kubernetes-webhook:prod_20210714.1
mcr.microsoft.com/azure-policy/policy-kubernetes-webhook:prod_20210909.1
Policy webhook image prod_20210714.1 is used for clusters <1.18. This image supports v1beta1 version of validation webhook.
Policy webhook image prod_20210909.1 is used for clusters >=1.18. This image supports v1 version of validation webhook.

Add Policy images containing CVE fixes CVE-2021-3711, CVE-2021-3712, CVE-2021-3121

---

parts/windows/kuberneteswindowssetup.ps1
pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
pkg/templates/templates_generated.go

Remove telemetry code in Windows CSE code
1. AKS never uses it
2. CustomData is too long and it will reach the limit when adding new features (We will resolve this by using a package to download the ps files later)

Remove telemetry code in Windows CSE code

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go

Update AKS Windows SIG image version to 17763.2183.210915

chore: Update AKS Windows SIG image version to 17763.2183.210915

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/scripts/linux/mariner/tool_installs_mariner.sh

While enabling AMA and ASA we ran into several permissions issues.
These will be fixed in the base image in the future, but for the time being correct them in the AKS image.

Fix CBLMariner permissions on rsyslog.d and product_uuid

---

vhdbuilder/packer/components.json

chore: bump virtual-kubelet to 1.4.0

chore: bump virtual-kubelet to 1.4.0

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/scripts/linux/mariner/tool_installs_mariner.sh

Enabling auditd on the host by default has caused conflicts with some container based scanning.
Revert the change to enable it on the CBLMariner container host.

Remove CBLMariner Auditd enable

---

vhdbuilder/packer/components.json
vhdbuilder/packer/install-dependencies.sh

cache the v1.4.12 CNI for Linux (it is already cached for Windows)

chore: cache cni v1.4.12 for linux

---

vhdbuilder/packer/components.json

virtual-kubelet 1.4.1 has [fix](https://github.com/virtual-kubelet/azure-aci/pull/171) to ensure docker config auth deserialized to username/password

add virtual-kubelet 1.4.1 into VHD

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1
vhdbuilder/packer/windows-image.env

1. Upgrade Windows base image to 2021-11B
2. Remove HNS flag since it has existed since 2021-10C

chore: Upgrade Windows base image to 2021-11B

---

vhdbuilder/packer/components.json

Calico v3.21.0 images and tigera-operator v1.23.1
Release: https://github.com/tigera/operator/releases/tag/v1.23.1

Update Calico to v3.21.0

---

e2e/e2e-script.sh

This PR improves the e2e script.
Summary of changes:
- Avoid altering the user's global kubeconfig file.
- Explicitly use JSON output in all `az` commands to mitigate environment variations.
- Allow overriding script params using env vars.
- Wrap fragile API calls in retry logic.
- Fix masked exit codes in calls to the Azure API.
- Misc cleanups.

Improve e2e script

---

staging/cse/windows/configfunc.ps1

The fix which reduces dynamic port usage for non-DSR load balancers is shiped with KB4550969 in April 2020
Update the range to [33000, 65535] to avoid that it conflicts with NodePort range (30000 - 32767)
https://github.com/Azure/aks-engine/pull/4767

fix: Update Windows dynamic port range

---

staging/cse/windows/azurecnifunc.ps1

When WinDSR is enabled, we need to set enableLoopbackDSR in Azure CNI conflist. enableLoopbackDSR is only supported from v1.4.16.

fix: Set loopbackdsr in Azure CNI conflist for WinDSR

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

chore: Cache calico-windows-v3.21.2

---

vhdbuilder/packer/components.json

Calico v3.21.2 images and tigera-operator v1.23.3
Release: https://github.com/tigera/operator/releases/tag/v1.23.3

Update Calico to v3.21.2 on Linux

---

pkg/agent/utils.go
pkg/agent/utils_test.go

Add function parseWindowsCSEMessage to support Windows checkVMSSCSEMessage
[Task 12808128: Add Windows support in vmcheckVMSSCSEMessage](https://msazure.visualstudio.com/CloudNativeCompute/_workitems/edit/12808128/)

Add function parseWindowsCSEMessage to support Windows checkVMSSCSEMessage

---

vhdbuilder/packer/components.json
vhdbuilder/packer/kube-proxy-images.json

Remove some versions from amd64OnlyVersions because they are in multiArchVersions already

Remove versions from amd64OnlyVersions because they are in multiArchVersions already

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go

This reverts commit bd16ffcf645590df7aa94045ac927d107928bd4c.
gMSAv2 is blocked by 2022-1B. We need to revert this change to avoid others to bring this change to AKS RP before we figure out the solution.

Revert "chore: Update Windows SIG image version to 2022-1B (#1418)"

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go

Update AKS Windows SIG version to 17763.2366.220117
1. Windows base image is 2021-12B
2. New PauseImage

chore: Update AKS Windows SIG version to 17763.2366.220117

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

Remove old cache in AKS Windows VHD

chore: Remove old cache in AKS Windows VHD

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go

chore: Update Windows SIG image version to 2022-1B with patch 17763.2458.220120

chore: Update Windows SIG image version to 2022-1B with patch

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

Reference:https://github.com/Azure/AgentBaker/pull/1443/files
AKS RP is still using calico-windows-v3.20.0.

Add Windows Calico v3.21.4

---

vhdbuilder/scripts/automate_ev2pipeline_trigger.sh
vhdbuilder/scripts/automate_helpers.sh
vhdbuilder/scripts/automate_release_notes.sh
vhdbuilder/scripts/automate_version_bump.sh

This PR addresses the following:
1) Incorrect commit message for Release Notes PR - Added logic to correctly differentiate commit message for VersionBump vs ReleaseNotes
2) Added pipefail since the pipeline was falsely succeeding even on some git operations failure.

Automation Pipeline Bug Fixes

---

vhdbuilder/scripts/automate_version_bump.sh

As per discussion to stop publishing PIR images till needed, disable updating image version for PIR images in AB in the following file at 
1) https://github.com/Azure/AgentBaker/blob/dfaa2c90cc754c4da0d23a23c36ae73628e69f40/pkg/agent/datamodel/osimageconfig.go#L42
2) https://github.com/Azure/AgentBaker/blob/dfaa2c90cc754c4da0d23a23c36ae73628e69f40/pkg/agent/datamodel/osimageconfig.go#L21

dont replace PIR version in osimageconfig.go for VHD Automation

---

.pipelines/e2e.yaml

The original Ubuntu 1804 pool had a large queue on an average delaying testing. Changing to DevInfra pool.

Change e2e pool to DevInfra

---

e2e/e2e-script.sh

e2e script currently logs kubeconfig, ssh keys and certs.
set +x to avoid the above. 
https://msazure.visualstudio.com/CloudNativeCompute/_workitems/edit/13221115

set +x to avoid logging secrets in e2e script

---

vhdbuilder/scripts/automate_version_bump.sh

Since PIR is no longer being published and therefore not being updated in https://github.com/Azure/AgentBaker/blob/master/pkg/agent/datamodel/osimageconfig.go, changing the Automation Pipeline to use the version in sig_config.go instead.

bug: Fix Automation Pipeline to use sig_config.go to find current image version

---

staging/cse/windows/kubernetesfunc.ps1

Add kubeproxy and CNI binaries to defender exclusion list
This needs to build a new CSE package

fix: Add kubeproxy and CNI binaries to defender exclusion list

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

Remove unused cache in Windows VHD

chore: Remove unused cache in Windows VHD

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

chore: Cache Windows containerd 1.6
containerd-v0.0.45-windows-amd64.tar.gz contains upstream containerd 1.6.1

chore: Cache Windows containerd 1.6

---

staging/cse/windows/README
vhdbuilder/packer/generate-windows-vhd-configuration.ps1
vhdbuilder/packer/windows-vhd-builder-sig.json
vhdbuilder/packer/windows-vhd-builder.json

1. Cache new AKS Windows CSE scripts package v0.0.8
2. Remove unused Azure CNI v1.4.16 and CSE scripts package v0.0.6

chore: Cache new AKS Windows CSE scripts package v0.0.8

---

parts/linux/cloud-init/artifacts/mariner/cse_install_mariner.sh
pkg/templates/templates_generated.go
vhdbuilder/packer/install-dependencies.sh

A recent change to CBL-Mariner's cloud-init package enabled it to receive and apply networking configs from the Azure datasource. This introduced regressions on clusters using the azure network plugin.
Retrieving networking configs from the Azure datasource is intentionally disabled on the Ubuntu 18.04 images with the overrideNetworkConfig function, and this needs to be applied on Mariner as well now.
Additionally, this commit adds the cloud-init-azure-kvp config package to Mariner to enhance logging for VMs failing in cloud-init.

CBLMariner disable cloud-init networkconfig, add kvp

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go

The issue requiring that the Mariner image to be pinned to 2022.02.19 has been resolved in PR https://github.com/Azure/AgentBaker/pull/1636. Subsequent builds of the Mariner image out of the master branch are back to being healthy.
This commit reverts the change from PR https://github.com/Azure/AgentBaker/pull/1617, setting Mariner to use the same date tag as the other Linux images once again for upcoming releases.

Revert version pinning for Mariner SIG image

---

vhdbuilder/packer/components.json

upgrade azure disk driver to v1.14, azure file driver to v1.13,
current version:
- azure disk driver: v1.13
- azure file driver: v1.12

upgrade azure disk driver to v1.14, azure file driver to v1.13

---

hack/tools/Makefile

/kind bug
It updates `go get` to `go install`, as `go get` has been deprecated for installing executables since `go 1.17`:
https://go.dev/doc/go-get-install-deprecation. 
This fixes failures in `check-generate` test that is run for every Agentbaker PR. Go 1.18 is the go runtime environment for this Agentbaker check. 
Example failure: https://github.com/Azure/AgentBaker/runs/5820763299?check_suite_focus=true
```
make[1]: Leaving directory '/home/runner/work/AgentBaker/AgentBaker/hack/tools'
-mod=vendor
bash: go-bindata: command not found'
```
Fixes #
```
none
```

fix: check-generated tests: use `go install` instead of `go get`

---

vhdbuilder/packer/test/windows-vhd-content-test.ps1

/kind test
The test is unstable: It immediately uses the job(containerd.exe) after starting the job(containerd.exe).
Fixes #
Wait for a time before using the job(containerd.exe).
```
none
```

Windows VHD test case waits for containerd running before using containerd

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/kube-proxy-images.json
vhdbuilder/packer/test/linux-vhd-content-test.sh

Remove k8s 1.20 k8s binaries and images to reduce space used on VHD. k8s 1.20 on AKS has been deprecated so it does not need to be cached on the VHD now. 
Fixes #
```
none
```

chore: remove k8s 1.20 from VHD

---

vhdbuilder/packer/components.json

We still pull these images as part of a normal managed Calico cluster on AKS. 
Also removing Calico v3.20.0 since that is no longer in use.
Fixes #
```
none
```

Add updated calico pod2daemon and cni images

---

vhdbuilder/packer/components.json

Not used any more in aks. 
[8:55 AM] Paul Miller (AWESOME)
Time to rip out network monitor since its its no used in 1.21? Ace Eldeib noticied this in agentbaker recently...
{​​​​​​​​{​​​​​​​​- if semverCompare "<1.21.0" .Values.global.commonGlobals.Versions.Kubernetes }​​​​​​​​}​​​​​​​​
{​​​​​​​​{​​​​​​​​- include (print $.Template.BasePath "/addons/system-addons/_azure-cni-networkmonitor.yaml") . | nindent 2 }​​​​​​​​}​​​​​​​​
Fixes #
```
none
```

[Chore] remove network monitor and vnet telemetry

---

vhdbuilder/packer/components.json

Remove 0.6.0, 0.10.0
Add 0.10.2, 0.11.1
/kind cleanup
Update the cached images for external-dns
Fixes #
```
Update container image cache in the VHD for external-dns
Remove 0.6.0, 0.10.0
Add 0.10.2, 0.11.1
```

Update images for external-dns

---

vhdbuilder/packer/init-variables.sh

/kind flake
Linux VHDs are built in eastus region by default. However there is no arm64 support in eastus, so ARM64 vhd is built in westus2 explicitly. When a build pipeline run (contains amd64 ubuntu and mariner, as well as arm64 ubuntu) starts from clean state, the RG aksvhdtestbuildrg could be created in westus2 region. This could cause random failure to MarinerGen2 build while importing source VHD to an interim SIG (although this flake failure won't happen in weekly vhd build pipeline because in weekly vhd build, RG aksbhfbuilerrg was created in eastus and was there for long time). This PR is to fix this flake.
https://msazure.visualstudio.com/CloudNativeCompute/_build?definitionId=172842&_a=summary
**Which issue(s) …

Fix random marinergen2 failure in build pipeline run including arm64 build

---

staging/cse/windows/configfunc.ps1

/kind bug
When a DNS UDP request uses 65330 as the source port, the response will be dropped because UDP source port 65330 is reserved for the host.
Reference: [Azure Virtual Network FAQ | Microsoft Docs](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#what-protocols-can-i-use-within-vnets)
This only excludes the port in AKS Windows nodes but will not impact Windows containers.
Reference: https://github.com/Azure/AKS/issues/2988
Fixes #

fix: Exclude UDP source port 65330 in Windows nodes

---

vhdbuilder/packer/components.json

/kind cleanup
Add v3.23.1 images for Calico cni, node, typha,
pod2daemon-flexvol, and  kube-controllers.
Add v1.27.4 for tigera/operator, which is compatible
with v3.23.1 of Calico.
These images will be used for managed Calico clusters in AKS.
```
Add v3.23.1 images for Calico cni, node, typha,
pod2daemon-flexvol, and  kube-controllers. Add v1.27.4 for tigera/operator.
```

chore: add Calico images for v3.23.1

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind build
Windows are using new omsganet image, it needn't the old omsagent image cache
Windows VHD remove old omsagent image cache
```
none
```

chore:Windows VHD remove old omsagent image cache

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind build
- Windows containerd package updated to v0.0.46.
- Some caches are deprecated.
Windows use containerd v0.0.46 and remove useless cache
```
none
```

build: Windows use containerd v0.0.46 and remove useless cache

---

vhdbuilder/packer/init-variables.sh

/kind bug
Fixes Mariner vhd builds. The changes from https://github.com/Azure/AgentBaker/pull/1791 caused the IMPORTED_IMAGE_NAME variable value from the Mariner 'if' block to be overwritten. 
```
none
```

fix: Move imported_image_name="" into Windows block

---

staging/cse/windows/README
staging/cse/windows/configfunc.ps1

/kind bug
fix: Remove the code to exclude UDP source port 65330 in Windows nodes
The command may fail because the UDP source port 65330 is being used. Retry may still not work so let us remove it for now.
Fixes #
```
none
```

fix: Remove the code to exclude UDP source port 65330 in Windows nodes

---

vhdbuilder/scripts/windows/collect-windows-logs.ps1

/kind feature
It collects disk usage in the Windows node in disk-usage.txt with below content.
```
Size(GB)       : 199.509761810303
Free Space(GB) : 43.795825958252
Free (%)       :    22%
DeviceID       : C:
DriveType      : 3
Size(GB)       : 127.998043060303
Free Space(GB) : 118.38597869873
Free (%)       :    92%
DeviceID       : D:
DriveType      : 3
```
Fixes #
```
none
```

feat: Collect disk usage in the Windows node

---

staging/cse/windows/README
staging/cse/windows/azurecnifunc.tests.ps1
staging/cse/windows/containerdfunc.ps1
staging/cse/windows/containerdfunc.tests.ps1
staging/cse/windows/cse.tests.ps1

/kind feature
Support mutilple Windows containerd versions in cse package
In the past, $global:ContainerdUrl is a full URL to download Windows containerd package.
Example: "https://acs-mirror.azureedge.net/containerd/windows/v0.0.46/binaries/containerd-v0.0.46-windows-amd64.tar.gz"
To support multiple containerd versions, we only set the endpoint in $global:ContainerdUrl.
Example: "https://acs-mirror.azureedge.net/containerd/windows/"
We only set containerd package based on kubernetes version when $global:ContainerdUrl ends with "/" so we support:
1. Current behavior to set the full URL
2. Setting containerd package in toggle for test purpose or hotfix
When using new CSE package with this change, we will change …

feat: Support mutilple Windows containerd versions in cse package

---

.pipelines/.vsts-Marketpalce-win.yaml
.pipelines/.vsts-vhd-builder-release-windows.yaml
.pipelines/.vsts-vhd-builder-release.yaml
.pipelines/.vsts-vhd-builder-windows.yaml
.pipelines/.vsts-vhd-builder.yaml
Makefile

Fixes #
Packer fixes SSH issue for Ubuntu 22.04 in version 1.8.1 as noted here https://github.com/hashicorp/packer/issues/11656#issuecomment-1138011054
This is essential to build Ubuntu 22.04 VHD since currently, SSH to them is broken via packer. go-dev 1.34.7 has updated packer version as 1.8.1
```
none
```

Update go dev to 1.34.7 to get packer to 1.8.1

---

parts/windows/kuberneteswindowssetup.ps1
pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
pkg/templates/templates_generated.go

/kind feat
Use Install-Containerd-Based-On-Kubernetes-Version
Fixes #
Old AKS RP sets the full URL (https://acs-mirror.azureedge.net/aks/windows/cse/aks-windows-cse-scripts-v0.0.11.zip) in CSEScriptsPackageUrl
but it is better to set the CSE package version in Windows CSE in AgentBaker
since most changes in CSE package also need the change in Windows CSE in AgentBaker
In future, AKS RP only sets the endpoint with the pacakge name, for example, https://acs-mirror.azureedge.net/aks/windows/cse/
```
none
```

feat: Use Install-Containerd-Based-On-Kubernetes-Version

---

.pipelines/templates/.builder-release-template-windows.yaml
vhdbuilder/packer/cleanup.sh
vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/init-variables.sh
vhdbuilder/packer/sysprep.ps1
vhdbuilder/packer/test/run-test.sh
vhdbuilder/packer/windows-vhd-builder-sig.json

/kind bug
1. Fix the issue in building win vhd with sigmode
2. Fix the issue in cleanup when it fails in init-variables.sh
3. Remove code since WindowsAzureNetAgentSvc does not exist any more
Test passed in https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=57721511&view=results
Fixes #
Gen2Mode is not tested in this PR
required specially for SIG mod
SIG_GALLERY_NAME (give any valid name you want): WindowsTestGallery
SIG_IMAGE_NAME_PREFIX (give any valid name you want): 2022July
SIG_IMAGE_VERSION (give any valid version you want): 2022.07.15
```
none
```

fix: Fix the issue in building win vhd with sigmode

---

vhdbuilder/packer/components.json

/kind bug : hotfix image update
Container Insights has a bug with the ciprod06272021 agent version where the node allocatable metric for cpu and memory limits are not being sent correctly. It is fixed in the following image : ciprod06272021-hotfix. This PR aims to include this hotfix image in the baked VHD.
Fixes #
```
none
```

Fix: Update Image tag with hotfix version (ciprod06272022-hotfix) for container insights

---

vhdbuilder/packer/components.json

/kind cleanup
Reduce VHD space so VHD builds can be completed
Fixes #
```
none
```

chore: reduce VHD space by removing unused cluster proportional autoscaler and azure cni versions

---

vhdbuilder/packer/components.json

/kind feature
tigera-operator 1.23.8 installs Calico 3.21.6
related to https://github.com/Azure/AgentBaker/pull/2026
```
none
```

chore: add tigera-operator v1.23.8

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go
vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.3287.220810.txt
vhdbuilder/release-notes/AKSWindows/2019/17763.3287.220810.txt
vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.887.220810.txt

/kind doc
Add release notes for AKS Windows images with 2022.08B
We still update sig_config.go although we do not use it.
Reference: https://github.com/Azure/AgentBaker/pull/2067
- WS2019: [August 9, 2022—KB5016623 (OS Build 17763.3287)](https://support.microsoft.com/en-us/topic/august-9-2022-kb5016623-os-build-17763-3287-c7a0bb3a-4083-4cd0-b9ad-119d9267628b)
- WS2022: [August 9, 2022—KB5016627 (OS Build 20348.887)](https://support.microsoft.com/en-us/topic/august-9-2022-kb5016627-os-build-20348-887-ef67367f-fab3-4d0c-8e80-72ac5a66d7d9)
Fixes #
Do not add release note since we do not use agentbaker to set the latest AKS Windows …

doc: Add release notes for AKS Windows images with 2022.08B

---

vhdbuilder/packer/components.json

Add 1.12.1 images for cilium, cilium-operator, and cilium-operator-generic.
/kind cleanup
Add latest Cilium images.
```
Add 1.12.1 images for cilium, cilium-operator, and cilium-operator-generic.
```

chore: add Cilium images for 1.12.1

---

.pipelines/.vsts-vhd-builder-release-windows.yaml

/kind bug
Disable Windows WS2022 GEN2 VHD build before @wanqingfu fixes the issue #2147.
Fixes #
```
none
```

fix: Disable Windows WS2022 GEN2 VHD build

---

.pipelines/.vsts-vhd-builder-windows.yaml

/kind bug
Disabled Windows WS2022 GEN2 VHD build in release pipeline before @wanqingfu fixes the issue https://github.com/Azure/AgentBaker/issues/2147.
Disable Windows WS2022 GEN2 in check-in pipeline
Fixes #
```
none
```

fix: Disable Windows WS2022 GEN2 in check-in pipeline

---

pkg/agent/datamodel/sig_config.go

Freezes all docker images at their current version, as we'll no longer be building new docker VHDs. Moving forward, customers will need to be using containerd instead.
Fixes #

freezing docker images at current versions

---

.pipelines/.vsts-vhd-builder-release.yaml

No longer building docker vhds to support migration to containerd-only.
Fixes #

no longer building docker vhds

---

pkg/agent/datamodel/sig_config.go

This PR pins the Mariner 2.0 SIG image version to 2022.08.29.
An issue in Mariner 2.0 cloud-init-22.2-7 is causing AKS nodes to fail to persist their hostname across reboots. After a node reboots the hostname is localhost.localdomain, and kubelet fails to become Ready again.
We're close to publishing a fix, but in the meanwhile we need AKS to keep using the 2022.08.29 image which contains the cloud-init package from before the introduction of this issue.
There's no issue with existing clusters upgrading to this impacted version of cloud-init, since the proper hostname is permanently persisted by the time that can happen.
Fixes # …

fix: Pin Mariner 2.0 SIG image to 2022.08.29 temporarily

---

.pipelines/.vsts-vhd-builder-release-windows.yaml
.pipelines/.vsts-vhd-builder-windows.yaml
.pipelines/templates/.builder-release-template-windows.yaml
packer.mk
vhdbuilder/packer/convert-sig-to-classic-storage-account-blob.sh

Fix the issues of Gen 2 VHD building.
1. Gen 1 and Gen 2 VHD sig destinations are not differentiated.
2. Gen 2 VHD build succeeds but test failed.
Fixes #
```
none
```

fix: Build Windows 2022 Containerd Gen 2 VHD

---

pkg/agent/datamodel/sig_config.go

/kind bug
Unpin the Mariner 2.0 SIG image version because the fixed cloud-init-22.2-8 is included in the [2022.09.22 image builds](https://github.com/Azure/AgentBaker/blob/4375247303b55d0065fecdb23d0143dcfbd0cb5b/vhdbuilder/release-notes/AKSCBLMarinerV2/gen2/2022.09.22.txt#L394).
Reverts the version pinning introduced in https://github.com/Azure/AgentBaker/pull/2197 because the cloud-init package has been fixed and shipped.
```
none
```

fix: Unpin Mariner 2.0 SIG image version

---

vhdbuilder/packer/components.json

/kind feature
Uses the newest [ip-masq-agent-v2 release](https://github.com/Azure/ip-masq-agent-v2/releases/tag/v0.1.5), which includes the usage of a distroless-iptables image and a reduction in image size from 75.4MB to 34.2MB, a 45.4% decrease.
Keeping `v0.1.3` cached until AKS uses `v0.1.5` everywhere.

chore: cache v0.1.5 image for ip-masq-agent-v2

---

vhdbuilder/packer/components.json

/kind cleanup
cache azure-cns v1.4.35
N/A
```
Cache azure-cns v1.4.35, remove cached v1.4.22
```

chore: cache azure-cns v1.4.35

---

vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh

* Explicitly purge and hold non-fips kernel in FIPS VHD
* Explicitly purge and hold non-fips kernel in FIPS VHD
* Purge and hold all non-fips kernels installed in FIPS VHD
Co-authored-by: Charlie Li <charlili@microsoft.com>
Fixes #
```
none
```

Explicitly purge and hold non-fips kernel in FIPS VHD (#2276)

---

.pipelines/.vsts-vhd-builder-release-windows.yaml
.pipelines/.vsts-vhd-builder-windows.yaml
.pipelines/templates/.builder-release-template-windows.yaml
vhdbuilder/packer/generate-windows-vhd-configuration.ps1
vhdbuilder/packer/init-variables.sh

Add gen2 as suffix in `sku_name` so that the resulted VM image def for Gen 1 and Gen 2 will not have name conflicts. 
**Q**: How will it look like after this change?
**A**: Gen 1: windows-2022-containerd; Gen 2: windows-2022-containerd-gen2.
/kind bug
To fix the bug. Currently the prod. sub has the same "windows-2022-containerd" VM image def for both Gen 1 and Gen 2.
Fixes #
```
none
```

fix: add gen2 as suffix in generate-sas for sku_name

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go
vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.3534.221019.txt
vhdbuilder/release-notes/AKSWindows/2019/17763.3534.221019.txt
vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.1131.221019.txt
vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.1131.221019.txt

/kind doc
Added release notes for AKS Windows images with 2022.10OOB
We still updated sig_config.go although we do not use it.
Replaced the hard-coded value in #2338 with the existing sig image version. 
- WS2019: [October 17, 2022—KB5020438 (OS Build 17763.3534) Out-of-band](https://support.microsoft.com/en-us/topic/october-17-2022-kb5020438-os-build-17763-3534-out-of-band-cd499c1a-6d60-49a1-9a40-fad42c1d393a)
- WS2022: [October 17, 2022—KB5020436 (OS Build 20348.1131) Out-of-band](https://support.microsoft.com/en-us/topic/october-17-2022-kb5020436-os-build-20348-1131-out-of-band-18baa25a-5fc0-4118-9b89-ddbe9819e578)
Fixes #
a. …

doc: Add release notes for AKS Windows images with 2022.10OOB

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/scripts/linux/tool_installs.sh

/kind bug
Currently Mariner disables and stops the iptables.service because it conflicts with K8s' use of iptables for pod routing.
This is insufficient to permanently disable the service, when systemd takes a package update it reevaluates the vendor presets and reenables the iptables service after a reboot.
In order to permanently disable iptables.service we can mask it with "systemctl mask iptables", causing vendor preset evaluation to leave it disabled, and manual attempts to start it are blocked until the service is unmasked.
Fixes #
```
none
```

fix: Mask iptables systemd service

---

vhdbuilder/packer/components.json

/kind cleanup
tigera-operator v1.27.12 was cached [here](https://github.com/Azure/AgentBaker/pull/2348), this is the 2nd part which adds the Calico image which it expects to install.
Since we are going with different version (based on k8s version), this will cover the two cases fully:
v1.27.12 will install Calico v3.23.3
v1.23.8 will install Calico v3.21.6
```
none
```

chore: cache v3.23.3 images for Calico

---

pkg/agent/datamodel/sig_config.go
vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh

…ion or upgrading
1. UA tool is pre-installed in regular base os, no need to install ua tool
2. Provide right confirmation to the prompt of 'ua detach', in order that the first fips kernel entry in grub.cfg can survive arbitrary non-fips kernel package re-installation or upgrading just like good AKS FIPS VHDs some time back. There might be some UA behavior change on detaching.
Fixes #
```
none
```

fips image improvement to survive non-fips kernel package reinstallation

---

vhdbuilder/packer/convert-osdisk-snapshot-to-sig.sh

…lete by other Cleanup step
After PR https://github.com/Azure/AgentBaker/pull/2385, arm64 vhd build could fail randomly because its interim SIG version could be deleted by Cleanup step of other VHD build jobs. Add 'now' tag to interim arm64 SIG version in order that it will not be deleted by Cleanup steps of other jobs.
Fixes #
```
none
```

Add now tag to interim arm64 sig version in order that it won't be deleted by Cleanup

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
vhdbuilder/packer/windows-image.env

/kind build
Windows security patch 2022-10B
- WS2019: [November 8, 2022—KB5019966 (OS Build 17763.3650)](https://support.microsoft.com/en-gb/topic/november-8-2022-kb5019966-os-build-17763-3650-b09dad62-5cd7-47cd-992f-b7d01f2956c1)
- WS2022: [November 8, 2022—KB5019081 (OS Build 20348.1249)](https://support.microsoft.com/en-us/topic/november-8-2022-kb5019081-os-build-20348-1249-14345324-e5d1-4710-a364-76d69d7aaa7c)
Fixes #
```
none
```

chore: Update Windows base images with 2022.11B

---

staging/cse/windows/azurecnifunc.ps1

/kind feature
The feature ```DisableOutboundNAT``` is incompatible with an existing ```HNSControlFlag```.
Update RegKey to disable ```HNSControlFlag``` to keep feature ```DisableOutboundNAT``` working.
Fixes #
Tested in the standalone environment.
```
none
```

chore: Update RegKey HNSControlFlag when disable Windows OutboundNAT

---

staging/cse/windows/azurecnifunc.ps1
staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Overlay.conflist

/kind bug
Don't add VnetCidrs to exceptionlist when network plugin mode is overlay
Fixes #
Tested e2e with AKS-RP
```
none
```

fix: Don't add Vnet CIDRs to CNI Conflist if AzureCNIOverlay is Enabled 1/2

---

vhdbuilder/packer/components.json

Add Cilium 1.12.3 for cilium/operator-generic and cilium/cilium
/kind cleanup
Previous version 1.12.2.3 is still in use, but 1.12.2.2 is not.
```
cache cilium/cilium and cilium/operator-generic version 1.12.3
```

chore: cache cilium 1.12.3

---

vhdbuilder/packer/components.json

Removing the v0.0.32 image tag with v0.0.33-hotfix since we never switched to v0.0.32.
Signed-off-by: Imran Pochi <imranpochi@microsoft.com>
Fixes #
```
none
```

apiserver-network-proxy/agent: update image

---

vhdbuilder/packer/components.json

/kind cleanup
Cilium released patch version 1.12.5 before we were able to deploy 1.12.3. Cache 1.12.5 so we can update to the latest patch version.
Version 1.12.2 is currently used in AKS, but 1.12.3 is not.
```
Cache images for Cilium 1.12.5
```

chore: cache Cilium 1.12.5

---

staging/cse/windows/provisioningscripts/loggenerator.ps1

/kind bug
dumpVfpPolicies.ps1 always appends logs to the file instead of overriding the file.
Fixes #
```
none
```

fix: Remove vfpOutput.txt before generating new logs

---

.pipelines/.vsts-vhd-builder-release-windows.yaml
.pipelines/.vsts-vhd-builder-windows.yaml
vhdbuilder/packer/init-variables.sh
vhdbuilder/packer/windows-vhd-builder-sig.json
vhdbuilder/packer/windows-vhd-builder.json

Use self-created 1es hosted pools to build windows vhd so that we do not need to create security exception to expose WinRM port 5986 in the sub “AKS VHD Image Release”
Fixes #
```
none
```

chore: use self-created 1es hosted pools to build windows vhd

---

vhdbuilder/packer/post-install-dependencies.sh

fix content of /proc/sys/crypto/fips_enabled on FIPS VHDs. This regression is caused in PR https://github.com/Azure/AgentBaker/pull/2452
Fixes #
```
none
```

fix content of /proc/sys/crypto/fips_enabled on FIPS VHDs

---

parts/linux/cloud-init/artifacts/containerd.service
pkg/templates/templates_generated.go
vhdbuilder/packer/packer_source.sh
vhdbuilder/packer/vhd-image-builder-mariner-gen2.json
vhdbuilder/packer/vhd-image-builder-mariner.json
vhdbuilder/packer/vhd-image-builder-mariner2-arm64.json
vhdbuilder/packer/vhd-image-builder-mariner2-gen2-kata.json
vhdbuilder/packer/vhd-image-builder-mariner2-gen2.json

/kind bug
Explicitly provide a containerd.service file customized for AKS in the VHD build for Mariner so that cloud-init does not need to deliver it.
This config also explicitly sets LimitNOFILE=1048576. This is because LimitNOFILE=infinity on Mariner means 1073741816, which has caused issues running some software in containers such as mysql5 and sshd. The value 1048576 matches the behavior on the Ubuntu AKS host.
Fixes #
```
none
```

fix: Add containerd service file to Mariner

---

pkg/agent/baker.go

this removes e.g. dynamic-config-dir uniformly, where it was previously left in CSE but cleaned for 16 months from custom data
Fixes #
```
none
```

fix: clean cse as well as custom data for old flags

---

packer.mk

fix the wrong echo output of windowsvhdmode
/kind bug
`HYPERV_GENRATION` was incorrectly used in `packer.mk`. Output was always `Building with Hyper-v generation 2 VM and save to .....`
Should use `HYPERV_GENERATION`.
Fixes #
It does not affect the packer build. It's just an echo output typo.
```
none
```

fix: Wrong echo of Hyper-v generation in the Windows VHD build pipeline

---

staging/cse/windows/azurecnifunc.ps1

/kind feature
Log DNS servers in Windows CSE script
Fixes #
You can find the cse logs in https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=70062277&view=artifacts&pathAsName=false&type=publishedArtifacts
```
2023-03-14T08:09:10.2567712+00:00: It took 6 seconds to create the ext network.
2023-03-14T08:09:10.2567712+00:00: Log network adapter info after creating ext network
ComputerName         : winj53ma000000
InterfaceAlias       : vEthernet (Ethernet 2)
InterfaceIndex       : 9
InterfaceDescription : Hyper-V Virtual Ethernet Adapter
CompartmentId        : 1
NetAdapter           : MSFT_NetAdapter …
```

feat: Log DNS servers in Windows CSE script

---

e2e/nsenter.go
e2e/suite_test.go

test: use correct resource group name for vmss cleanup

---

vhdbuilder/packer/backfill-cleanup.sh

Fix the following issue
- backfill deletion step tries to free a sig image-def/gallery that is being used.
- This might happen when the current pipeline build creates a sig gallery & image-def but has not yet created a sig version (sig version would be empty). Or better yet, say there's another concurrent pipeline build just created a sig gallery & image def w/o attaching any sig versions.
Need to add some sort of check to see if the image def has older sig versions and if they can be reduced. If that's the case, the sig image-def can then be safely removed, hence the same about the sig gallery. o.w. we shouldn't delete the sig version => delete the sig image-def => delete the sig gallery if that makes sense.
/kind fix …

fix undesired sig versions/galleries cleanup in backfill deletion

---

e2e/scenarios/windows/property-windows-template.json

/kind bug
We have updated Windows PauseImage to 3.9 in production so we need to update it in e2e too.
Fixes #
```
none
```

fix: Update Windows PauseImage to 3.9 in E2E test case

---

vhdbuilder/packer/components.json

/kind cleanup
Cache CIlium 1.12.8
N/A
```
Cache images for Cilium 1.12.8
```

chore: cache Cilium 1.12.8

---

e2e/go.mod
e2e/go.sum
go.mod
go.sum
pkg/agent/datamodel/const.go
pkg/agent/datamodel/types.go
pkg/agent/datamodel/types_test.go
staging/cse/windows/provisioningscripts/kubeproxystart.ps1
staging/cse/windows/provisioningscripts/windowsnodereset.ps1

/kind bug
`IPv6DualStack` is removed from the Kubernetes FeatureFlag set
in 1.25.0 and has been enabled by default since 1.21.0. There are
some other places in CSE that depend on the feature flag being part
of the config so this change is just to remove it from kube-proxy's
list of args so it doesn't crash at startup.
Fixes #
```
none
```

fix: do not add IPv6DualStack to Windows kube-proxy feature-gates when K8s >= 1.25.0

---

.pipelines/templates/e2e-windows-template.yaml
e2e/windows/e2e-create-windows-nodepool.sh
e2e/windows/e2e-helper.sh
e2e/windows/e2e-scenario.sh
e2e/windows/e2e-starter.sh
e2e/windows/nodebootstrapping_template.json
e2e/windows/scenarios/windows/property-windows-template.json

Support to specify the k8s version since some feature may need the latest k8s version to validate.
To validate latest windows cse package on the latest k8s version.
To achieve this
- The resource group name will contain the version string and the cluster will be created with the specified k8s version.
- The windows vmss deployment will be associated with the set k8s version by updating `WindowsPackageURL` of `k8scomponents` in the template `property-windows-template.json` which is for generating windows cse related files i.e. CustomData file and CSECmd file.
Fixes #
```
none
```

feat: specify the k8s version to support windows cse validation

---

pkg/agent/datamodel/sig_config.go

re-pin CVM image due to reoccurrence of issue from https://github.com/Azure/AgentBaker/pull/2885
Fixes #
```
none
```

fix: pin CVM image to last version before nullboot issues

---

parts/linux/cloud-init/artifacts/cis.sh
pkg/templates/templates_generated.go
vhdbuilder/packer/test/linux-vhd-content-test.sh

/kind bug
We have code that modifies `/etc/default/useradd` `/etc/login.defs` to bring them into compliance with CIS benchmarks. However, the script does some weird things to those files and in the case of `mariner` actually fails to set the `INACTIVE` setting in `/etc/useradd`.
This change fixes the script to modify settings in place or append them, taking into account the fact that a file may not have a trailing new-line.
I also normalized the tab length in the file, which was different in different functions.
Fixes #
Here's the mariner `/etc/default/useradd` before this change. You can see that `INACTIVE` isn't actually set and …

fix: replace password-related settings properly

---

parts/linux/cloud-init/artifacts/sysctl-d-60-CIS.conf
pkg/templates/templates_generated.go
vhdbuilder/packer/test/linux-vhd-content-test.sh

/kind bug
We are out of compliance with certain CIS recommendations related to network parameter settings by changing and adding settings to the file that is installed to `/etc/sysctl.d/60-CIS.conf` to set the parameters to the correct values.
You can find before and after versions of the files mentioned above for both mariner and ubuntu in the attached zip file.
[cis-fix-network-settings.zip](https://github.com/Azure/AgentBaker/files/11314684/cis-fix-network-settings.zip)
```
none
```

fix: set network settings according to cis recommendations

---

parts/linux/cloud-init/artifacts/modprobe-CIS.conf
pkg/templates/templates_generated.go

/kind bug
Currently, `cramfs` is disabled by making it not actually load (loading command is `/bin/true`). As a defense-in-depth, the CIS recommendation is to further disable it by "blacklisting" it. This change does that.
```
none
```

fix: disable cramfs

---

.github/workflows/check-coverage.yml

Ensures no regression for #2815 
Fixes #
```
none
```

feat: add artifact upload for coverage e2e

---

parts/linux/cloud-init/artifacts/sshd_config
parts/linux/cloud-init/artifacts/sshd_config_1604
parts/linux/cloud-init/artifacts/sshd_config_1804_fips
pkg/templates/templates_generated.go
vhdbuilder/packer/packer_source.sh
vhdbuilder/packer/vhd-image-builder-mariner-gen2.json
vhdbuilder/packer/vhd-image-builder-mariner.json
vhdbuilder/packer/vhd-image-builder-mariner2-arm64.json
vhdbuilder/packer/vhd-image-builder-mariner2-gen2-kata.json
vhdbuilder/packer/vhd-image-builder-mariner2-gen2.json

/kind bug
CIS recommends restricting access to ssh and ensuring restrictive permissions on `/etc/ssh/sshd_config` itself. This change prevents certain known users from `ssh`-ing into a machine and fixes the permissions on the file.
I also took the opportunity to shore up what `sshd_config` files are referenced by the mariner-specific vhd config files and how we choose which config to us for ubuntu configs.
```
none
```

fix: ensure sshd configuration is correct and sshd_config has proper permissions

---

e2e/cluster.go
e2e/exec.go
e2e/opts.go
e2e/pollers.go
e2e/suite_test.go
e2e/template.go
e2e/validation.go
e2e/vmss.go

/kind feature
speeds up abe2e in cases where numerous clusters need to be created to support the chosen scenarios by parallelizing this process - added a little more caching in cases where new clusters are created as well
Fixes #
```
none
```

perf: parallelize abe2e cluster creation + some more caching

---

vhdbuilder/packer/pre-install-dependencies.sh

/kind bug
CIS recommendations is that any world-writable directory should have the "sticky-bit" turned on, which will prevent deletion of files in that directory by anyone but the file owner. This change does that.
This has been buddy tested with the processes that create and delete certs.
```
none
```

fix: add sticky bit /opt/certs to prevent malicious deletes

---

parts/linux/cloud-init/artifacts/cis.sh
pkg/templates/templates_generated.go
vhdbuilder/packer/test/linux-vhd-content-test.sh

/kind bug
CIS recommendations is to turn off storing any coredumps and to turn off backtraces in them. Since we don't actually use coredumps on the systems we build, this makes sense and will have no impact.
```
none
```

fix: disable coredump storage and backtraces

---

.pipelines/.vsts-kata-uvm-builder.yaml

/kind feature
This PR adds a minimal template for instantiating a pipeline for building Mariner AKS Kata Utility VM (UVM) collaterals. These collaterals will later be used as input for AgentBaker when transforming a standard Mariner Marketplace image into a Mariner Kata AKS image.
- Internal documents on planned implementation tasks and a dev proposal for the Mariner Kata AKS work stream exist

feat: Add initial UVM build pipeline definition file for the Mariner Kata AKS work stream

---

staging/cse/windows/README

Need to update the command to build the test Windows CSE script package. The original command will generate an unexpected folder `aks-windows-cse` after extracting the test Windows CSE script package
```
2023-05-15T08:52:31.8084661+00:00: Downloaded file https://.../aks-windows-cse-scripts-v0.0.24.1.zip to c:\csescripts.zip
2023-05-15T08:52:32.9218162+00:00: Set ExitCode to 1 and exit. Error: The term 'c:\AzureData\windows\azurecnifunc.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
Fixes # …

docs: fix the wrong folder structure after extracting the test Windows CSE script package

---

parts/linux/cloud-init/artifacts/cis.sh
pkg/templates/templates_generated.go
vhdbuilder/packer/test/linux-vhd-content-test.sh

/kind bug
CIS recommendation is to have the default `umask` set to `027` or more restrictive. They also recommend all user home directories have mode of `750` or more restrictive. This is a partial fix that sets the `UMASK` to `027` in `/etc/login.defs`, which will make user creation (like `azureuser`) create directories with `750`. The rest of the work on `umask` will come directly from `CBL-Mariner`.
```
none
```

fix: change default umask to enforce correct permissions when creating users

---

vhdbuilder/packer/components.json

Removing older versions of components with CVEs (node-manager version v1.23.24)
Fixes #
```
none
```

fix: remove older version of node-manager with CVEs

---

vhdbuilder/packer/test/linux-vhd-content-test.sh

/kind bug
In a [recent change](https://github.com/Azure/AgentBaker/pull/3123), we introduced a test to make sure `/etc/systemd/coredump.conf` is formatted correctly, but the regex was wrong and only allowed capital letters. This fixes that.

fix: false negative when testing coredump settings

---

vhdbuilder/packer/test/linux-vhd-content-test.sh

/kind bug
The PamD tests were only ever meant to be run against Mariner 2.0. Somewhere along the way, that guard was deleted and the tests as checked in run against all os/version combinations. This change makes them only run against Mariner 2.0.
```
none
```

fix: false negative when testing pamD settings on ubuntu

---

vhdbuilder/packer/components.json

/kind feature
chore: cache blob csi driver image
v1.19.5 is used on AKS 1.24, 1.25, and v1.21.3 is used on AKS 1.26
Fixes #
```
chore: cache blob csi driver image
```

add blob driver image into vhd image cache

---

vhdbuilder/packer/components.json

/kind cleanup
Remove ip-masq-agent-v2 0.1.6. RP is using v0.1.7 now, so we can remove 0.1.6
Fixes #
```
none
```

chore: remove ip-masq-agent-v2 0.1.6

---

vhdbuilder/packer/components.json
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind cleanup
chore: upgrade secret store driver to v1.3.4 in vhd cache
Secrets Store CSI Driver v1.3.4 release has been published. This image contains the signed windows binary.
`v1.3.3-2` was added yesterday in the AgentBaker as a security patch, this PR overwrites `v1.3.3-2` directly since `v1.3.4` already contains the security patch
Fixes #
```
none
```

chore: upgrade secret store driver to v1.3.4 in vhd cache

---

.pipelines/templates/.builder-release-template.yaml
vhdbuilder/packer/test/linux-vhd-content-test.sh
vhdbuilder/packer/test/run-test.sh

/kind test
In `linux-vhd-content-test.sh`, we clone `AgentBaker` to source a couple helper files. However, we clone `master`, which means that we can't test updating those files, and we can't iterate on adding tests that we would want to keep in other files in repo.
This change takes the git branch to clone on the command-line of the test script, passing it in through the pipeline in `run-tests.sh`.
```
none
```

test: clone the branch from the build rather main for testing

---

.pipelines/templates/.builder-release-template.yaml
vhdbuilder/packer/test/linux-vhd-content-test.sh
vhdbuilder/packer/test/run-test.sh

DRAFT -- IGNORE
/kind test
In `linux-vhd-content-test.sh`, we clone `AgentBaker` to source a couple helper files. However, we clone `master`, which means that we can't test updating those files, and we can't iterate on adding tests that we would want to keep in other files in repo.
This change takes the git branch to clone on the command-line of the test script, passing it in through the pipeline in `run-tests.sh`.
Note that this is the second attempt at this. The [first](https://github.com/Azure/AgentBaker/pull/3342) used a simpler method that doesn't work for pull request branches.
```
none
```

test: use git branch from build for tests

---

vhdbuilder/packer/components.json
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind cleanup
chore: add CSI driver windows host process images and remove unused images
Note:
v1.28.0 and v1.28.0-windows-hp are two different image tags now since to keep backward compatibility on Windows, we still tag 1809 and ltsc2022 images to v1.28.0
Fixes #
```
none
```

chore: add CSI driver windows host process images and remove unused images

---

vhdbuilder/packer/components.json

CNI versions were updated in install-dependencies.sh but not in components.json in this PR https://github.com/Azure/AgentBaker/pull/3369
Broken build: https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=75681317&view=logs&j=23db6aa5-8b12-5e7a-bc2f-e81abeaeb352&t=408a0f68-8718-5e1e-aa21-4dd249d1c401&l=124
Fixes #
```
none
```

fix: change cni versions in components.json

---

.pipelines/templates/e2e-windows-template.yaml

Use specified version of az cli as workaround of the issue: "az aks get-versions" cannot return "default" field when azure-cli >= 2.50.0.
Fixes #
```
none
```

chore: use specified version of az cli as workaround

---

vhdbuilder/scripts/linux/mariner/tool_installs_mariner.sh

/kind bug
Adding UseDomains=true to systemd-networkd's 99-dhcp-en.network config file to populate the search domain for /etc/resolve.conf
```
none
```

fix: set UseDomains to true for systemd-networkd on Azure Linux

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1
vhdbuilder/packer/windows-image.env
vhdbuilder/packer/write-release-notes-windows.ps1

/kind feature
1. update Windows base images to 2023.06B
WS2019: [July 11, 2023—KB5028168 (OS Build 17763.4645)](https://support.microsoft.com/en-us/topic/july-11-2023-kb5028168-os-build-17763-4645-eff2d1e1-5f91-4d9a-aef1-ae26bdf51321)
WS2022: [July 11, 2023—KB5028171 (OS Build 20348.1850)](https://support.microsoft.com/en-us/topic/july-11-2023-kb5028171-os-build-20348-1850-65cc2bda-a4a5-450f-adcb-d57ff9eb9835)
2. setting registry keys to enable some fixes
Fixes #
```
none
```

chore: update Windows base images to 2023-7B with registry key

---

vhdbuilder/packer/components.json

/kind bug
Cluster proportional autoscaler image needs a `v` prefix before the tag. Since the change, the image pull has been failing.
Fixes #
```
none
```

fix: add prefix for image pull - fix VHD build

---

vhdbuilder/packer/install-dependencies.sh

This PR installs blobfuse2 and fuse3 on ubuntu minimal VHD to support CSI drivers e2e.
Fixes #
```
none
```

fix: install blobfuse2, fuse3 on minimal vhd

---

vhdbuilder/packer/install-dependencies.sh

/kind bug
fix: fix SC2191 error raised in running `make generate`
```
In ./vhdbuilder/packer/install-dependencies.sh line 57:
required_pkg_list=(jq iptables netcat dnsutils blobfuse2=${BLOBFUSE2_VERSION} fuse3)
^--------^ SC2191: The = here is literal. To assign by index, use ( [index]=value ) with no spaces. To keep as literal, quote it.
Did you mean: 
required_pkg_list=(jq iptables netcat dnsutils "blobfuse2="${BLOBFUSE2_VERSION} fuse3)
```
Fixes #
```
none
```

fix: fix SC2191 error

---

vhdbuilder/scripts/linux/mariner/tool_installs_mariner.sh
vhdbuilder/scripts/linux/tool_installs.sh
vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh

Install bpftrace via dnf for mariner instead of
installing from binary
/kind cleanup
Install `bpftrace` in mariner using `dnf` instead of installing a binary.
Fixes # NA
```
none
```

fix: linux: install bpftrace for marier via dnf

---

parts/linux/cloud-init/artifacts/cis.sh
pkg/templates/templates_generated.go
vhdbuilder/packer/test/linux-vhd-content-test.sh

/kind bug
For CIS compliance, we need `umask` set to `027`. And, due to the CIS tooling, we need to not set it to anything else anywhere in `/etc/profile.d/`. This had initially been fixed in CBL-Mariner, but that was reverted because it broke some customers. Since we know that for AKS, we already technically have it set to `027` via `/etc/profile`, it's safe to make a change to work with the CIS tooling.
```
none
```

fix: set umask in a way that cis audits recognize

---

vhdbuilder/packer/test/linux-vhd-content-test.sh

/kind test
When I introduced tests for permissions on `cron`-related files, I had a typo in the array name for a set of files to check, which resulted in not actually checking the permissions on those files. Turns out the script that set the permissions worked properly, so there wasn't a bug -- this is a test-only issue.
```
none
```

fix: typos in testCronPermissions

---

.pipelines/.vsts-vhd-builder.yaml
vhdbuilder/packer/test/run-test.sh

/kind test
Recently, we started using an environment variable `GIT_BRANCH` to specify the `AgentBaker` branch to use when running tests. We've seen some pipelines that don't set that variable though, which results in tests not being run.
This change does two things:
1. Passes `GIT_BRANCH` through to one such pipeline.
2. Defaults to using `master` so we get tests no matter what.
```
none
```

test: default GIT_BRANCH to master so if a pipeline doesn't set it, we still get tests

---

parts/linux/cloud-init/artifacts/cis.sh
pkg/templates/templates_generated.go
vhdbuilder/packer/test/linux-vhd-content-test.sh

/kind test
A recently introduced test used the `diff` utility, which isn't installed by default on our mariner images.
In addition to normal checkin pipelines, I also ran a mariner-specific pipeline to test with the most recent build of mariner: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=398811&view=results
```
none
```

test: remove dependency on diff from tests

---

vhdbuilder/packer/components.json

Previously cached images are not in-use in prod. v1.4.45.1 is in canary and will soon be released to all regions.

chore: [Azure NPM] bump v1.4.45.1 for upcoming release

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1
vhdbuilder/packer/windows-image.env
vhdbuilder/packer/write-release-notes-windows.ps1

/kind feature
1. update Windows base images to 2023.08B
WS2019: [August 8, 2023-KB5029247 (OS Build 17763.4737)](https://support.microsoft.com/en-us/topic/august-8-2023-kb5029247-os-build-17763-4737-9f99a6da-ef38-4744-aef2-df38365f9203)
WS2022: [August 8, 2023-KB5029250 (OS Build 20348.1906)](https://support.microsoft.com/en-us/topic/august-8-2023-kb5029250-os-build-20348-1906-2db4a1ac-8e18-443e-b4d6-ee17435cf94c)
2. setting registry keys to enable some fixes
Fixes #
```
none
```

chore: update Windows base images to 2023-8B with registry key

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go
pkg/agent/datamodel/types.go

/kind feature
The AKS EgressLockdown E2E test is currently using a 18.04 AKS VHD. This PR is to add a distro for 22.04. We use the oldest version 2022.10.03 so that the latest image and binaries are not cached in the VHD. Then the EgressLockdown E2E test will download image and binaries during creating nodes.
```
none
```

feat: add a distro which maps to AKS VHD with the oldest version (2022.10.03)

---

.pipelines/.vsts-vhd-automation.yaml

seems like they changed the format:
```bash
root@Ubuntu-2204-jammy-amd64-base ~ # curl -s 'https://go.dev/VERSION?m=text'
go1.21.0
time 2023-08-04T20:14:06Z
root@Ubuntu-2204-jammy-amd64-base ~ # curl -s 'https://go.dev/VERSION?m=text' | head -n 1
go1.21.0
```
Fixes #
```
none
```

fix: trim timestamp from go version

---

staging/cse/windows/kubeletfunc.ps1

chore
Adds a specific check for windows kubeletfunc.ps1 so that it only enforces requirement for PrimaryScaleSetName and PrimaryAvailabilitySetName when the VM type is "vmss".
Test result:
```json
{
"authorization": {
"action": "Microsoft.Compute/virtualMachines/extensions/write",
"scope": "/subscriptions/<REDACTED>/resourcegroups/<REDACTED>/providers/Microsoft.Compute/virtualMachines/<REDACTED>/extensions/cse-agent-0"
},
// (...)
"status": {
"value": "Succeeded",
"localizedValue": "Succeeded"
},
}
```
```
none
```

chore: added check on Windows CSE for vmss type so we don't throw an error

---

.pipelines/templates/.builder-release-template-windows.yaml

Override the existing build date with a custom preset date in case of build conflicts. $i.e.$ 2 or more concurrent windows vhd builds going for production.
Addressing build image version conflicts.
Fixes #
```
none
```

chore: use custom build date for image version

---

e2e/README.md

Update the README to clarify that you need to run `make generate` before e2e-local.sh when changing CSE.
N/A
```
none
```

docs: document make generate in e2e-local.sh instructions

---

vhdbuilder/packer/components.json

/kind cleanup
remove cache of overlay cni since it's being installed via dropgz
cache [dropgz v0.0.4.1](https://github.com/Azure/azure-container-networking/releases/tag/dropgz%2Fv0.0.4.1) ([cni v1.4.39.1](https://github.com/Azure/azure-container-networking/releases/tag/v1.4.39.1)) and [cni v1.4.43.1](https://github.com/Azure/azure-container-networking/releases/tag/v1.4.43.1)
https://github.com/Azure/azure-container-networking/issues/2156
```
none
```

chore: cache cni and dropgz for hotfix

---

vhdbuilder/packer/components.json

/kind cleanup
In AKS kubernetes version 1.25 and later, kube-proxy init container runs busybox:1.35. We used to use the kube-proxy image, but had to switch when upstream started building from distroless.
The busybox image is 4.27 MB. This is downloaded by almost every AKS node on startup, so I think we should cache it in the VHD.
Fixes #
```
cache busybox 1.35 in the VHD for kube-proxy init container
```

chore: cache busybox in VHD

---

packer.mk
vhdbuilder/packer/packer-plugin.pkr.hcl
vhdbuilder/packer/windows-vhd-builder-sig.json

publish to shared image gallery only after packer v1.4.0 
For some contexts see this https://github.com/hashicorp/packer-plugin-azure/issues/41.
`azure-arm: ERROR: -> PropertyChangeNotAllowed : Changing property 'sourceVirtualMachine' is not allowed.`
Fixes #
```
none
```

fix: remove managed_image_resource_group_name and managed_image_name and publish SIG only

---

pkg/agent/datamodel/sig_config.go

This PR adds the SigAzureLinuxImageConfig field in the SIGAzureEnvironmentSpecConfig struct to host the new AzureLinux images
Fixes #
```
none
```

feat: Add new AzureLinux image config definition

---

.pipelines/.vsts-vhd-builder-release.yaml

This PR is meant to disable autobuilding AzureLinux CgroupV2 images temporarily before all the corresponding RP changes are merged in. The behavior will be set back to autobuilding mode once all related changes are merged in and well tested. Meanwhile, the Azure Linux CgroupV2 VHDs will be manually selected to build and handled in a separate release.
Fixes #
```
none
```

fix: Disable Autobuilding AzureLinux cgroupv2 images

---

.pipelines/templates/.builder-release-template-windows.yaml

/kind bug
fix branch name in Windows release notes
Fixes #
https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services. We only remove refs/heads when it is built from a branch. It is by design that we do not update build branch if the build is from a PR. We should not merge any release notes with `Build Branch: refs/pull/3626/merge`.
<html>
<body>
Build.SourceBranch | The branch of the triggering repo the build was queued for. Some examples:Git repo branch: refs/heads/mainGit repo pull request: refs/pull/1/mergeTFVC repo branch: $/teamproject/mainTFVC repo …

fix: fix branch name in Windows release notes

---

vhdbuilder/packer/init-variables.sh

/kind feature
Allow for setting of the VNET_RG_NAME, VNET_NAME, and SUBNET_NAME via environment variables. To allow for independent testing.
Fixes #
Linux build : [[Link](https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=79740785&view=results)]
Windows build : [[Link](https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=79740801&view=results)]
```
none
```

feat: allow the use of environment variables for packer vnet setup

---

vhdbuilder/packer/post-install-dependencies.sh

This PR moves the /etc/os-release info slightly higher in the VHD build log so that it will be included in the full [AKS release notes](https://github.com/Azure/AKS/blob/2023-09-10/vhd-notes/AzureLinux/202309.06.0.txt) txts. Typically "Install completed successfully on" and below is trimmed out for the main release notes.
This will help us more quickly correlate which Mariner release a given VHD was built with.
Fixes #
```
none
```

docs: move os-release earlier in vhd build log

---

vhdbuilder/packer/components.json

This PR removes calico 3.24.0 as it is no longer need by the supported tigera operator version as referenced here:
https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/toolkit/versioning/manifests/addon/calico/tigera-operator.yaml&version=GC9f0ebe62d3323b7ea00125301434030f635ddd1c&_a=contents
Fixes #
```
none
```

chore: remove calico 3.24.0 and tigera 1.28.0

---

vhdbuilder/packer/install-dependencies.sh

clamav is flagging this binary as malware on Mariner nodes... will need to investigate why this is the case. In the meantime we'll be removing this so we don't keep getting flagged.
Fixes #
```
none
```

chore: temporarily remove secure TLS bootstrap client from VHD builds

---

vhdbuilder/packer/components.json

/kind cleanup
AKS hasn't used upstream ip-masq-agent since k8s v1.19, when we switched to our fork ip-masq-agent-v2.
Fixes #
```
none
```

chore: remove legacy ip-masq-agent from VHD

---

staging/cse/windows/configfunc.ps1
staging/cse/windows/configfunc.tests.ps1

/kind feature
Resize-OSDrive can be slow due to Get-PartitionSupportedSize, replacing that call with diskpart
Fixes #
While inspecting node provision time – Resize-OSDrive was taking over 2min in some cases, the Windows Storage team informed us that Get-PartitionSupportedSize can be a slow call as it not only gets the maximum size but also the minimum size which requires a call into defrag. This change replaces that call and uses diskpart for the resize operation.
Unit tested against 2019 and 2022, generation 1 and generation 2, across 7 sku sizes. Specific unit test used a CSE script of just the old/new resize function against the …

feat: optimize resize-osdrive replacing get-partitionsupportedsize with diskpart

---

.pipelines/templates/.builder-release-template-windows.yaml
vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind fix
1. use containerd v1.7.9 when building 23H2 vhd.
2. use "unknown" instead of throwing error when windows version is not set.
Fixes #
```
none
```

fix: use containerd v1.7.9 when building 23H2 vhd

---

.pipelines/templates/.builder-release-template-windows.yaml
vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/generate-windows-vhd-configuration.ps1
vhdbuilder/packer/test/run-test.sh
vhdbuilder/packer/test/windows-vhd-content-test.ps1

/kind bug
Refine Windows VHD build steps to reset ReofferUpdate. We have to install the latest security patch after installing OpenSSH to avoid that ReofferUpdate is set to 1.
Fixes #
```
none
```

fix: refine Windows VHD build steps to reset ReofferUpdate.

---

staging/cse/windows/debug/collect-windows-logs.ps1

/kind feature
Collect kubectl information in AKS Windows node log
Fixes #
```
none
```

feat: collect kubectl information in AKS Windows node log

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/generate-windows-vhd-configuration.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1
vhdbuilder/packer/windows-image.env
vhdbuilder/packer/write-release-notes-windows.ps1

/kind feature
Update Windows base images to 2024.1B
- Windows 2019: [January 9, 2024—KB5034127 (OS Build 17763.5329)](https://support.microsoft.com/en-us/topic/january-9-2024-kb5034127-os-build-17763-5329-4de58ce5-eb0d-4b9a-95d1-aa15fe30b082)
- Windows 2022: [January 9, 2024—KB5034129 (OS Build 20348.2227)](https://support.microsoft.com/en-us/topic/january-9-2024-kb5034129-os-build-20348-2227-6958a36f-efaf-4ef5-a576-c5931072a89a)
```
none
```

feat: update Windows base images to 2024.1B

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind feature
This pre-cache's Windows dropgz for AKS nodes
This Windows dropgz is only used in Overlay nodes in AKS for now, but asked by Abel to start caching it

feat: adding in windows dropgz to pre-cache list

---

.pipelines/.vsts-vhd-builder-release.yaml

Since 1.29 is about to preview, this PR allows building AzureLinuxCgroupv2 images with regular VHD builds.
Fixes #
```
none
```

chore: unfreeze azlinux cgroupv2 skus

---

parts/windows/kuberneteswindowssetup.ps1
pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData
pkg/templates/templates_generated.go

/kind bug
should not start k8s-restart-job when reboot is needed for windows gpu
Fixes #
```
none
```

fix: should not start k8s-restart-job when reboot is needed for windows gpu

---

vhdbuilder/scripts/automate_version_bump.sh

This PR computes and stores VHD build timestamps in official branches during weekly automation runs to keep track of when a VHD build was run, to use the Canonical Snapshot service, in case the same VHD needs to be hotfixed later, thereby guaranteeing the same apt versions from when it was originally built.
Successful test run: https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=88140121&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=dee4e6ec-be1b-5671-4678-ab293b4004c5
Sample commit that creates the timestamp JSON file: https://github.com/Azure/AgentBaker/commit/b54f60aae914f90baf0e6b9a74398039455568a6
Fixes #
**Special notes for your …

feat: add VHD build timestamp in official branches for reproducible VHDs

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind feature
Validate the free space in AKS Windows VHDs. Based on below logs in building AKS Windows VHDs in the past months, we set `$global:lowestFreeSpace` to `2GB`. It can avoid that the node provisioning fails because the disk is full before resize-osdisk is called in AKS Windows CSE script.
```
2023-10B: azure-arm: 2023-10-11T02:05:47.3821397+00:00: Disk C: Free space: 2870341632, Total size: 37054574592
2023-11B: azure-arm: 2023-11-15T04:24:35.6762674+00:00: Disk C: Free space: 7530057728, Total size: 37054574592
2023-12B: azure-arm: 2023-12-13T07:15:49.5874780+00:00: Disk C: Free space: 4424978432, Total size: 37054574592
2024-01B: azure-arm: 2024-01-10T06:19:45.8406506+00:00: Disk C: Free space: 4901367808, …
```

feat: validate the free space in AKS Windows VHDs

---

vhdbuilder/packer/components.json
vhdbuilder/packer/install-dependencies.sh

/kind chore
Brings the latest azure-vnet binaries to AB in preparation to release it to AKS
Fixes #
```
none
```

chore: bring latest azure-vnet

---

vhdbuilder/packer/components.json

**What type of PR is this?** NPM Version Update
**What this PR does / why we need it**: Updates the NPM Linux image version from v1.4.45.3 to v1.5.23 to address Ubuntu repo updates/CVEs, remove building and publishing NPM images with certs/private keys, and aligns NPM's minor version with CNS/CNI versions.
**Release note**: https://github.com/Azure/azure-container-networking/releases/tag/v1.5.23

chore: update npm linux to v1.5.23

---

parts/linux/cloud-init/artifacts/aks-log-collector.sh
pkg/templates/templates_generated.go

/kind bug
Collect from /var/log/cilium-cni* instead of /var/log/cillium-cni* (one 'l' in cilium).
Fixes #
```
Update aks-log-collector script with correct glob pattern for cilium-cni logs.
```

fix: typo in aks-log-collector glob pattern for cilium-cni

---

parts/linux/cloud-init/artifacts/sync-container-logs.sh
pkg/templates/templates_generated.go

/kind feature
Add calico-system and tigera-operator namespaces to container logs collected by sync-container-logs.sh script. This will be used by AKS on-call to troubleshoot issues in clusters with Calico enabled.
Fixes #
```
Collect logs from containers in calico-system and tigera-operator namespaces.
```

feat: collect calico-system and tigera-operator logs

---

e2e/windows/scenarios/windows/property-windows-template.json

/kind fix
remove deprecated feature gate when default k8s version is 1.28
Fixes #
```
none
```

fix: remove deprecated feature gate when default k8s version is 1.28

---

vhdbuilder/packer/components.json
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind feature
chore: upgade Azure Disk, File, Blob CSI driver versions
This PR also removed old and unused CSI driver versions, Azure Disk driver v1.30.0 and Blob driver v1.24.0 (and v1.23.3-3) is not used on aks-rp due to track2 sdk issue, so this PR also removes those two versions
Fixes #
```
none
```

chore: upgade CSI driver versions

---

.pipelines/.vsts-vhd-builder.yaml

/kind chore
This PR changes 1 of the 3 VHDs used for the AB PR gate (1804_gen2_containerd => 2204_gen2_containerd).
This PR changes the PR gate so that when making a pull request, the pull request builds 2204_gen2_containerd instead of 1804_gen2_containerd, which is an older version that is used less by our customers.

chore: bump build_vhd to 2204_gen2_containerd

---

staging/cse/windows/configfunc.ps1
vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/generate-windows-vhd-configuration.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1
vhdbuilder/packer/windows-vhd-builder-sig.json

/kind feature
Before it, CSE extension is responsible for expanding os volume, but other extensions may run predates CSE, result in extension installation failure due to insufficient free space.
After it, VHD registers system startup task to expand os volume which run predates all extensions.
Fixes #
```
none
```

feat: add system startup task to expand os volume

---

vhdbuilder/packer/components.json

/kind cleanup
Prefetch the versions of Azure CNS (v1.5.23) and dropgz (v0.0.15) used in K8s 1.28+.
Fixes #
```
none
```

chore: prefetch dropgz v0.0.15 and azure-cns v1.5.23

---

vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
vhdbuilder/packer/vhd-image-builder-base.json
vhdbuilder/packer/vhd-image-builder-mariner-arm64.json
vhdbuilder/packer/vhd-image-builder-mariner.json

/kind performance
This PR increases the disk tier used on the Packer VMs from Standard_LRS to Premium_LRS. The Premium SSDs have notable performance increases and will allow the VM to take full advantage of future parallelization efforts. 
Additionally, this PR adds `img_sku` to the Azure Tags section of the builder template. This enables a developer to more easily find the packer resource group (VM, Disk, NIC) that is building any specific VHD in order to monitor performance metrics. 
Unsatisfactory VHD Build pipeline duration.

perf: increase packer disk tier, add img_sku tag

---

vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/test/windows-vhd-content-test.ps1
vhdbuilder/packer/write-release-notes-windows.ps1

/kind feature
Exclude 65330 in building 23H2 VHDs.
Fixes #
```
none
```

chore: exclude 65330 in building 23H2 VHDs

---

parts/linux/cloud-init/artifacts/cis.sh
pkg/templates/templates_generated.go
vhdbuilder/packer/install-dependencies.sh

/kind cleanup
This PR suppresses output from the assignRootPW function in cis.sh. This will prevent sensitive information from showing up in build logs. 
Prevents sensitive information from showing up in build logs.

cleanup: suppress output when assigning root pw

---

staging/cse/windows/kubernetesfunc.ps1
staging/cse/windows/provisioningscripts/cleanupnetwork.ps1
staging/cse/windows/provisioningscripts/kubeletstart.ps1
staging/cse/windows/provisioningscripts/kubeproxystart.ps1
staging/cse/windows/provisioningscripts/windowsnodereset.ps1

/kind feature
- kube-proxy upstream has the code for [waiting azure network](https://github.com/kubernetes/kubernetes/blob/11785bb815d58eb553be3a1fa305464c35d860cc/pkg/proxy/winkernel/proxier.go#L217-L225) which supported [1.22+](https://github.com/kubernetes/kubernetes/commit/d5d9327351de99e6068f62efb388a6ede38d944e)
- kube-proxy upstream has the code for [cleaning HNS policy](https://github.com/kubernetes/kubernetes/blob/fc7325fbec0fe379694e58b82e09f99f166c5e6d/pkg/proxy/winkernel/proxier.go#L685-L686) which supported [1.21+](https://github.com/kubernetes/kubernetes/commit/f3b9e8b10524abfddc52e06eb9a0040d2f1c09df)
- Retain HNS network which confirmed by Windows team and Upstream team
- Reuse toggle …

feat: support skipping legacy code CleanupNetwork in AKS Windows CSE

---

staging/cse/windows/debug/collect-windows-logs.ps1

/kind feature
Fixes #
```
none
```

feat: add parameters for collect-windows-logs.ps1

---

vhdbuilder/packer/components.json

This should remove about 1.8GB from the VHD.
The image sizes (according to crictl images) are:
Image                                                                   Version
13.9MB  mcr.microsoft.com/oss/kubernetes/coredns                                1.9.4
13.9MB  mcr.microsoft.com/oss/kubernetes/coredns                                v1.8.7
162MB   mcr.microsoft.com/containernetworking/azure-cns                         v1.4.50
171MB   mcr.microsoft.com/containernetworking/azure-cns                         v1.4.52
172MB   mcr.microsoft.com/containernetworking/azure-cns                         v1.5.17
12MB    mcr.microsoft.com/oss/azure/secrets-store/provider-azure                v1.4.1
72.2MB  mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver               v1.3.4-1
66.5MB …

chore: remove old container versions from the components

---

vhdbuilder/packer/components.json

/kind bug
This PR adds "v" into the container image URL so that it can be successfully pulled from MCR. Commit 618fc60, made yesterday, updated container images, and left out the "v" in version for this container image. This is resulting in numerous ctr retries and an eventual timeout / failed pull.
Failed container image pull.

fix: fix container image URL

---

parts/linux/cloud-init/artifacts/ipv6_nftables.service

/kind design
This will allow nftables to execute bfore kubelet, which is needed for cilium dual stack clusters. In substitution for these nftable rules, we will attach an ebpf program to cilium clusters that will do the IP conversion instead. Cilium clusters will have an init container which will remove the nftable rules and start the bpf program. This change will make sure nftable rules are executed before init container.
Fixes #
```
execute ipv6 nftable rules before kubelet
```

Execute ipv6 nftables before kubelet

---

.pipelines/.vsts-vhd-automation.yaml
.pipelines/.vsts-vhd-windows-automation.yaml
.pipelines/e2e.yaml

updates VHD automation pipeline to use dev infra's "devinfraassistant" service account for downloading artifacts from ADO, instead of personal accounts
TODO: investigate how to do the same for github PATs?
Fixes #
```
none
```

chore: use devinfra assistant PAT in VHD automation + abe2e pipelines

---

parts/linux/cloud-init/artifacts/components.json
vhdbuilder/packer/install-dependencies.sh

/kind cleanup 
Removes azure-vnet versions v(N-2) that were not dropped when the latest was added.
Fixes #
```
none
```

chore: drop outdated azure-vnet versions

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go
pkg/agent/datamodel/types.go

This PR adds 2404 SIG config for AMD64 images. These images are one-off test images published to AME to test with aks-rp node image selection logic, these wont be consumed until 24.04 hit preview in AKS.
Fixes #
```
none
```

chore: add 2404 sig config

---

pkg/agent/datamodel/types.go

/kind feature
NextGenNetworkingURL is the per-cloud URL for downloading Windows eBPF assets.
Next-gen networking is enabled only when NextGenNetworkingURL is non-nil.
Fixes #
```
none
```

feat: add datamodel field for Windows next-gen networking

---

parts/linux/cloud-init/artifacts/components.json
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind feature
chore: upgrade Azure Disk CSI driver and node-driver-registrar image in vhd image
azure disk driver v1.29.5 is not used, upgrade to v1.29.6 directly in this PR.
Fixes #
```
none
```

chore: upgrade Azure Disk CSI driver and node-driver-registrar image

---

parts/linux/cloud-init/artifacts/components.json

What type of PR is this?
/kind feature
What this PR does / why we need it:
To add coreDNS hotfix image (coredns:v1.9.4-hotfix.20240520) to cache that contains fix for CVE - CVE-2023-45288, CVE-2024-24788.
Requirements:
uses [conventional commit messages](https://www.conventionalcommits.org/)
includes documentation
adds unit tests
tested upgrade from previous version
Special notes for your reviewer:
https://mcr.microsoft.com/en-us/product/oss/kubernetes/coredns/tags
docker pull mcr.microsoft.com/oss/kubernetes/coredns:v1.9.4-hotfix.20240520
```
none
```

Add coredns image v1.9.4-hotfix.20240520

---

pkg/agent/baker.go
pkg/agent/datamodel/types.go
pkg/agent/datamodel/types_test.go

This PR adds 2404 distros to the list of VHDs using cgroupv2.
https://kubernetes.io/docs/concepts/architecture/cgroups/#check-cgroup-version
Fixes #
```
none
```

chore: add 2404 to cgroupv2 usage

---

pkg/agent/common/gpu.go

/kind bug
This PR updates the GRID driver container to fix this issue affecting Linux kernels 5.15.1063+ versions.
It's a new driver based on vGPU 16.5.
Modpost issue tracking:
https://forums.developer.nvidia.com/t/linux-6-7-3-545-29-06-550-40-07-error-modpost-gpl-incompatible-module-nvidia-ko-uses-gpl-only-symbol-rcu-read-lock/280908/4
Update based on: https://github.com/Azure/aks-gpu/pull/40
Fixes #
```
GRID driver updated to 535.161.08.
```

Update GRID driver to 535.161.08 for kernel compat issue

---

.pipelines/.vsts-vhd-windows-automation.yaml
vhdbuilder/scripts/windows/automate_release_notes.sh
vhdbuilder/scripts/windows/automate_version_bump.sh

/kind feature
update windows VHD automation pipeline to use dev infra's "devinfraassistant" service account for downloading artifacts from ADO, instead of personal accounts
Fixes #
```
none
```

chore: use devinfra assistant PAT in windows VHD automation pipeline

---

parts/linux/cloud-init/artifacts/components.json
pkg/agent/vhd/cache/cache_test.go
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind feature
Caches `azure-cni` and `azure-ipam`, which replace and deprecate `cni-dropgz` as the preferred containers for installing the CNI plugins in AKS.
https://github.com/Azure/azure-container-networking/issues/2333
```
none
```

chore: cache azure-cni and azure-ipam

---

.pipelines/.vsts-vhd-builder.yaml
parts/linux/cloud-init/artifacts/components.json

…ration
fixes an issue just introduced which attempts to prefetch an azure-cns version on the VHD which is not being cached - this issue should've been caught by the linux VHD check-in build pipeline, thus this PR also fixes the path triggers to make sure that doesn't happen again
Fixes #
```
none
```

fix: linux VHD build check-in pipeline trigger + prefetch script generation

---

.pipelines/templates/.builder-release-template.yaml

**What type of PR is this?** The placement of files was necessary for release pipelines. Adding back to unblock release
https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=95238523&view=results - running
Fixes #
```
none
```

bug: Add artifacts back to root in staging dir

---

.gitignore
e2e/artifact/download.go
e2e/pollers.go
e2e/scenario/base_vhd_catalog.json
e2e/scenario/scenario.go
e2e/scenario/scenario_azurelinuxv2-chrony-restarts.go
e2e/scenario/scenario_marinerv2-chrony-restarts.go
e2e/scenario/scenario_ubuntu1804-chrony-restarts.go
e2e/scenario/scenario_ubuntu2204-chrony-restarts.go
e2e/scenario/validators.go
e2e/scenario/vhd.go
e2e/suite_test.go
e2e/validation.go
vhdbuilder/packer/install-dependencies.sh

/kind bug
Fixes #27616556
* Have manually tested by creating VMs with the VHDs for mariner2, azurelinux2, ubuntu1804, and ubuntu2204, ssh'd to it, checked chrony was running, killed it, and checked it restarted.
* Have e2e tests verifying the contents of the systemd drop-in for those 3 distros
* have e2e tests replicating the automated tests.
```
Add drop-in for systemd so Chrony will restart if it crashes
```

bug: add systemd dropon for chrony so it will restart

---

e2e/suite_test.go

fixes a bug in abe2e's where the suite would fail due to failures when generating RSA private keys using mrand.Rand - this stems from the fact that mrand.Rand is not thread-safe, though the e2e's were using it as such.
these errors would manifest like the following:
```
--- FAIL: Test_All (23.15s)
--- FAIL: Test_All/azurelinuxv2-airgap (0.36s)
panic: runtime error: index out of range [-1] [recovered]
panic: runtime error: index out of range [-1]
goroutine 581 [running]:
testing.tRunner.func1.2({0x1a1b160, 0xc000ace018})
/usr/local/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1399 +0x39f
panic({0x1a1b160, 0xc000ace018})
/usr/local/go/src/runtime/panic.go:884 +0x212 …
```

fix: make abe2e's usage of mrand.Rand thread safe

---

e2e/airgap.go
e2e/cluster.go
e2e/suite/const.go
e2e/suite/suite.go

fixes incorrect security rules on airgap NSGs within agentbaker e2e's. this was caused by a change to the front-door IP address of `mcr.microsoft.com`, manifesting in provisioning failures with exit code 50.
this PR adds logic to dynamically lookup the IP address of each required DNS name so future changes of this nature no longer break anything
Fixes #
```
none
```

fix: dns resolution for abe2e airgrap security rules

---

parts/linux/cloud-init/artifacts/components.json

**What type of PR is this?** NPM Version Update
**What this PR does / why we need it**: Updates the NPM Linux image version from v1.5.23 to v1.5.29 to address Ubuntu repo CVEs. Merging both rp and ab simultaneously to address the customer CVE.
**Release note**: https://github.com/Azure/azure-container-networking/releases/tag/v1.5.29

chore: update npm linux to v1.5.29

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
vhdbuilder/packer/windows-image.env

/kind feature
bump Windows 2022 image versions to 2024.6OOB
- Windows 2022: [June 20, 2024—KB5041054 (OS Build 20348.2529) Out-of-band](https://support.microsoft.com/en-us/topic/june-20-2024-kb5041054-os-build-20348-2529-out-of-band-b746ffbd-934e-42ac-9c66-ed0636edf7f1)
Fixes #
```
none
```

feat: bump Windows 2022 image versions to 2024.6OOB

---

.pipelines/templates/.builder-release-template.yaml

uvm signing builds are in a "partiallySucceeded" state due to warnings caused by non-blocking supply-chain violations coming from RP, this change still allows the VHD build to go through even if the build we download UVM artifacts from is in a "partiallySucceeded" state
Fixes #
```
none
```

fix: allow partially-succeeded builds in UVM artifact download task

---

parts/linux/cloud-init/artifacts/components.json

/kind feature
To add coreDNS hotfix image (coredns:v1.9.4-hotfix.20240627) to cache that contains fixes for - CVE-2024-24790, CVE-2024-24789. Removing old image - v1.9.4-hotfix.20240327
Fixes # CVE-2024-24790, CVE-2024-24789
https://mcr.microsoft.com/en-us/product/oss/kubernetes/coredns/tags 
docker pull mcr.microsoft.com/oss/kubernetes/coredns:v1.9.4-hotfix.20240627
```
none
```

Add coredns image v1.9.4-hotfix.20240627

---

parts/linux/cloud-init/artifacts/components.json

/kind feature
To add the latest Addon-Resizer image (1.8.22) to cache that contains fixes for - CVE-2023-45288 and CVE-2024-24786 
Fixes #
CVE-2023-45288 and CVE-2024-24786 
This image is available in MCR - https://mcr.microsoft.com/en-us/product/oss/kubernetes/autoscaler/addon-resizer/tags 
trivy image --ignore-unfixed mcr.microsoft.com/oss/kubernetes/autoscaler/addon-resizer:1.8.22
mcr.microsoft.com/oss/kubernetes/autoscaler/addon-resizer:1.8.22 (debian 12.5)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
none
```

Add resizer image version 1.8.22

---

vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
vhdbuilder/packer/vhd-image-builder-base.json
vhdbuilder/packer/vhd-image-builder-mariner-arm64.json
vhdbuilder/packer/vhd-image-builder-mariner.json

so packer can distinguish between vnets with the same name in different resource groups
Fixes #
```
none
```

fix: disambiguate vnet resource group name for linux builds

---

staging/cse/windows/debug/collect-windows-logs.ps1

/kind bug
du.exe which was used to calculate the snapshot folder sizes was not accurate. Changing that to include a script to do the calculation.
The changes have been tested with the modified collect-windows-logs.ps1 script on an AKS windows node.
Fixes #
```
none
```

Edit containerd snapshot size calculation

---

e2e/vmss.go

per new requirements, we must create VMSS objects with upgrade mode set to automatic when running abe2e's
Fixes #
```
none
```

fix: set linux abe2e VMSS upgrade mode to automatic

---

parts/linux/cloud-init/artifacts/components.json

/kind feature
To add coreDNS hotfix image (coredns:v1.9.4-hotfix.20240704) to cache that contains fixes for - CVE-2024-24791
Fixes # CVE-2024-24791 
https://mcr.microsoft.com/en-us/product/oss/kubernetes/coredns/tags
docker pull mcr.microsoft.com/oss/kubernetes/coredns:v1.9.4-hotfix.20240704
```
none
```

Add coredns image v1.9.4-hotfix.20240704

---

.pipelines/.vsts-vhd-builder-release.yaml

/kind bug
dryrun parameter syntax error prevents release pipeline from executing. Error is not present in the PR check-in gate so that is probably how it got through. 
Running release pipeline now to ensure syntax works.

fix: invalid variable syntax in release pipeline

---

.github/renovate.json

/kind bug
no comment in renovate.json (even though config.js supported them)
fix #4634 
```
none
```

fix: remove comment from json

---

vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
vhdbuilder/packer/vhd-image-builder-base.json
vhdbuilder/packer/vhd-image-builder-mariner-arm64.json
vhdbuilder/packer/vhd-image-builder-mariner.json

/kind perf
This PR instructs packer to use premium SSDs when building our custom images. This greatly reduces VHD build time given the faster IOPS/Mbps of the Premium SSDs over Standard HDD. The average build time reduction across all SKUs is 00:07:10.
Unsatisfactory VHD Build times.

perf: use premium SSDs

---

vhdbuilder/packer/pre-install-dependencies.sh

We had originally skipped apt updates to CVM base image because the newer kernels were incompatible with the nullboot package, which relied on boot measurements from TPM hardware.
This seems to have been fixed upstream, therefore removing the conditional to skip updates for CVM.
Successful build: https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=99290941&view=results
Fixes #
```
none
```

fix: install upgrades for CVM images in pre-install dependencies

---

.pipelines/templates/e2e-template.yaml

/kind chore
Uploads test results to DevOps so we get a cleaner view of what failed. These appear in the ADO pipeline page under the "Tests" tab. This tab is only visible after the results are uploaded. Because that's ADO for you.
```
none
```

chore: upload test results in pipeline

---

e2e/config/config.go

/kind test
Increase agentbaker e2e timeout since logs are not printed for A10 e2es some times.
Fixes #
```
none
```

e2e: increase e2e timeout to 18 min

---

.github/workflows/validate-components.yml
Makefile
e2e/scenario_helpers_test.go
packer.mk
pkg/vhdbuilder/datamodel/component_configs.go
vhdbuilder/packer/components.json
vhdbuilder/packer/test/run-pretest.sh
vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
vhdbuilder/packer/vhd-image-builder-base.json
vhdbuilder/packer/vhd-image-builder-mariner-arm64.json
vhdbuilder/packer/vhd-image-builder-mariner.json
vhdbuilder/prefetch/main.go
vhdbuilder/prefetch/pkg/container/types.go

removes a dangling symlink for components.json located at vhdbuilder/packer/components.json - this was originally created to reduce the size of a previous PR's change-set
having a symlink to the actual components.json located at parts/linux/cloud-init/artifafts/components.json creates confusion for component owners and overall reduces maintainability, this PR aims to mitigate this by removing the symlink and all references to it altogether
Fixes #
```
none
```

chore: remove components.json symlink from vhdbuilder/packer

---

parts/linux/cloud-init/nodecustomdata.yml
pkg/agent/baker.go
pkg/agent/baker_test.go
pkg/agent/datamodel/types.go
pkg/agent/datamodel/types_test.go
pkg/agent/testdata/AKSUbuntu2204+SecurityProfile/CustomData

/kind feature
If bootstrap container registry is enabled, we need to pull the image from the bootstrap container registry instead of MCR. This PR is to add a containerd config to use the container registry as a registry mirror.
For example, when pulling `mcr.microsoft.com/mcr/hello-world`, the containerd will pull `{{GetBootstrapProfileContainerRegistryServer}}/mcr/hello-world`.
If bootstrap container registry is not enabled, nothing is changed.
Fixes #
```
Add the container registry as a registry mirror for mcr.microsoft.com when bootstrap container registry is enabled
```

feat: add the container registry as a registry mirror for mcr.microsoft.com when bootstrap container registry is enabled

---

e2e/template.go

/kind cleanup
AgentBaker E2E tests were using k8s 1.26, which is past EOL. Update to use k8s 1.29 which is the current default in AKS. This required two other changes to node bootstrapping config:
1. Switch from in-tree to external cloud-provider (`--cloud-config=""` and `--cloud-provider=external`). Otherwise kubelet exits with an error that in-tree cloud-provider is no longer supported ("built-in cloud providers are disabled").
2. Add kubernetes.azure.com/cluster node label. Otherwise, cloud-node-manager and other daemonsets won't schedule on the node, so the node gets stuck with "uninitialized" taint
Fixes #
``` …
```

cleanup: Use k8s 1.29 in AgentBaker E2E tests

---

e2e/exec.go

fix: return error first before accessing fields that might be nil in extractLogsFromVM

---

parts/linux/cloud-init/artifacts/aks-check-network.sh

/kind bug
Update the path to use the correct ca cert instead of kube-apiserver cert
Fixes #
```
none
```

fix: Update to use correct ca cert

---

vhdbuilder/packer/init-variables.sh

/kind cleanup
This switches packer to linking the build VMs to the new nodesig-pool-vnet-<region> vnet in the new prod agent pool RG. Without this the prod build can't use the new pool - the private endpoint SSH connection fails.
Fixes #
```
none
```

Switch over to using the new agent pool vnet in prod

---

.pipelines/.vsts-vhd-builder-release.yaml

This PR is a temporary change to disable building azlinux 3 by default.
It is a new image definition and we want to have all new image definitions tagged with diskControllerType = NVMe for v6 SKUs.
As soon as the change to incorporate the above is in, I will revert this PR to re-enable building azlinux 3 by default.
This is also to help @UtheMan proceed with this week's SIG release without delay.
Fixes #
```
none
```

temp: change azlinux 3 build to false temporarily

---

pkg/agent/datamodel/types.go
pkg/agent/utils.go
pkg/agent/utils_test.go

https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration
Allow user to configure extra kubelet parameter.
Test it manualy:
I created a new nodepool using e2e test. And created next DaemonSet:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
name: violating-daemonset
labels:
app: violating-app
spec:
selector:
matchLabels:
app: violating-app
template:
metadata:
labels:
app: violating-app
spec:
containers:
- name: seccomp-test
image: alpine:latest
command: ["/bin/sh", "-c"]
args:
- |
echo "Attempting to use unshare..."
unshare -r echo "This should fail"
echo "Exit code: $?"
```
I received different log message on seccomp-enabled node.
But I don't think it's something worth adding a new test to e2e suite.

feat: Add option to configure --seccompDefault property on kubelet

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/test/linux-vhd-content-test.sh

If the BCC install test fails it does not return "err", it just returns 1. This results in the az vm run command failing to recognize that the test failed. 
testBccTools test in linux-vhd-content-test.sh is failing to correctly return an error.

fix: correctly return error in testBccTools test if the test fails

---

parts/linux/cloud-init/artifacts/components.json
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind bug
add used sidecar images to vhd images
this PR is part of revert PR for https://github.com/Azure/AgentBaker/pull/4861
livenessprobe: v2.12.0 and csi-node-driver-registrar:v2.10.1 (v2.11.0 is unused now) are still used by aks 1.27, 1.28, add those sidecar images back to vhd images, 
Fixes #
```
none
```

chore: add used sidecar images to vhd images

---

e2e/scenario_test.go
e2e/validation.go

makes the kubelet node ip validator a common validator, though still excludes it from scenarios (privatepkg) that utilize older VHDs that aren't at least on k8s 1.29
Fixes #
```
none
```

feat(abe2e): move kubelet node IP validator to common validators

---

parts/linux/cloud-init/artifacts/components.json
vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind cleanup
Removes unused cni-dropgz images to free up space on the VHD
Dropgz v0.1.4 and v0.2.0 target k8 v1.28 and v1.30+ respectively, but for those k8 versions we already use azure-cni to install cni, not dropgz. So, we no longer need these dropgz images. k8s 1.27- still uses dropgz v0.0.x which is why it stays.
Fixes #
```
none
```

chore: remove unused dropgz versions

---

vhdbuilder/packer/install-dependencies.sh

cgroup-memory-telemetry.service has been failing on AzureLinux/Mariner images because the host uses cgroupfs driver instead of systemd's cgroupsv2 driver. Disable this service until support for AzureLinux/Mariner is added.
Fixes #
```
none
```

feat: Disable cgroup-memory-telemetry.service on AzureLinux

---

vhdbuilder/packer/trivy-scan.sh

**What this PR does / why we need it**: add --skip-db-update due to TOOMANYREQUESTS error coming from aquasecurity - https://github.com/aquasecurity/trivy/discussions/7591 
using the --skip-db-update means that the trivy db will download during the first scan on the vm, then it will keep using that db instead of looking for updates during every single container scanning. 
Fixes #
```
none
```

fix: trivy scanning hitting rate limit

---

vhdbuilder/packer/install-dependencies.sh

Teleportd is not supported anymore. 
Removing it to reduce VHD space and cleanup. This is also towards unblocking the weekly VHD build. 
Fixes #
```
none
```

cleanup: Remove teleportd download in VHD

---

vhdbuilder/packer/install-dependencies.sh

/kind cleanup
Preventing the nvidia device plugin container image from release notes as it gets removed later during the VHD build. 
Fixes #
```
none
```

preventing uncached nvidia device plugin image from being added to release notes

---

.pipelines/templates/.builder-release-template.yaml
vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
vhdbuilder/packer/vhd-image-builder-base.json
vhdbuilder/packer/vhd-image-builder-mariner-arm64.json
vhdbuilder/packer/vhd-image-builder-mariner.json

/kind test
This PR publishes bcc install logs after the completion of the VHD build in order to gain visibility into the installation process after failed downloads.
Lack of visibility into bcc tools installation process. 

test: publish bcc installation logs

---

vhdbuilder/packer/install-dependencies.sh

/kind bug
This PR will fail the build if BCC tools installation fails in order to address errors quicker.
BCC install failures were only caught during the testing phase of the VHD build. 

fix: exit when bcc install fails

---

.github/workflows/check-coverage.yml

Set coverage gh action to manual trigger only
Fixes #
```
none
```

chore: set coverage calculations to manual trigger only

---

parts/linux/cloud-init/artifacts/components.json
vhdbuilder/packer/generate-windows-vhd-configuration.ps1
vhdbuilder/prefetch/internal/containerimage/testdata/prefetch.sh

We have been using the `cni-dropgz` image in 1.27, this backports the `azure-ipam` and `azure-cni` images we're now building for 1.27 cluster so that we can migrate them. `cni-dropgz` image will be purged here afterwards.
Fixes #
```
none
```

Backport of AzCNI installer images for k8s 1.27

---

.pipelines/templates/.builder-release-template.yaml
vhdbuilder/packer/packer_source.sh
vhdbuilder/packer/vhd-image-builder-mariner.json

While AzL2 uses an initrd file for the Kata UVM, AzL3 will use an image file aligned with Kata CoCo where an image file is being used.

kata: Use image for AzL3 Kata UVM

---

e2e/scenario_test.go
e2e/validators.go
parts/linux/cloud-init/artifacts/nvidia-modprobe.service

/kind bug
Removes the  `kubelet restart` from nvidia-modprobe service and ensures nvidia-modprobe is run before kubelet.
Incident 487929399, 552859186
<!-- Common commit types:
build: Build 🏭
chore: Maintenance 🔧
ci: Continuous Integration 💜
docs: Documentation 📘
feat: Features 🌈
fix: Bug Fixes 🐞
perf: Performance Improvements 🚀
refactor: Code Refactoring 💎
revert: Revert Change ◀️
style: Code Style 🎶
security: Security Fix 🛡️
test: Testing 💚 
```
none
```

fix: Ensure nvidia modprobe is run before kubelet

---

parts/windows/windowscsehelper.tests.ps1
staging/cse/windows/kubeletfunc.ps1
staging/cse/windows/kubeletfunc.tests.ps1

/kind bug
fixes a bug in Add-KubeletNodeLabel where the log content is added to the return value by Write-Log, causing KubeletNodeLabels to contain unexpected content which ends preventing kubelet from starting:
```
"NodeLabels":  [
"2024-10-23T18:24:39.6797661+00:00: adding label kubernetes.azure.com/kubelet-serving-ca=cluster to kubelet node labels...",
"agentpool=npwin,kubernetes.azure.com/agentpool=npwin,agentpool=npwin,kubernetes.azure.com/agentpool=npwin,kubernetes.azure.com/cluster=MC_cameissebld106479871_wintester_eastus2,kubernetes.azure.com/consolidated-additional-properties=a3253cd6-916b-11ef-a610-6643c19b51dd,kubernetes.azure.com/kubelet-identity-client-id=78f4691a-f952-4bd3-83c0-0869e2821eed,kubernetes.azure. …
```

fix: do not use return in updating kubelet node labels

---

parts/linux/cloud-init/artifacts/components.json
schemas/components.cue
vhdbuilder/packer/install-dependencies.sh

/kind feature
/kind refactor
This PR moves GPU versions to a config file (components.json), so that Renovate bot can auto-update it. VHD builds will now consume the cuda version from components.json. It also adds a new schema to auto-update.
There are two new requirements: 
1) aks-gpu-cuda container image is only downloaded for particular combo of OS and arch (Ubuntu - amd64), 
2) aks-gpu-grid container image needs to be present in the config but is never downloaded in the VHD. It's only used in CSE, for certain SKUs.
Fixes #
```
none
```

GPU container images in components.json, add new schema for GPU images

---

parts/linux/cloud-init/artifacts/components.json

/kind bug
It was broken before and I believe containerd wasn't being installed
The build pipeline: https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=106974411&view=logs&j=1a7fdb86-c5de-518e-2b8c-8cb1b3b67828&t=b11d9101-f70d-5ba7-2e5a-9a338c0f3966
The cluster created with the image above:
Fixes #
```
none
```

Fix 24.04 ARM64 pipeline

---

vhdbuilder/packer/trivy-scan.sh

/kind bug
Adds multiple Trivy DB repositories to allow fallbacks in case of throttling
Fixes #
```
none
```

adding Trivy DB fallbacks

---

aks-node-controller/protoc.Dockerfile

/kind cleanup
avoid security warnings

use azurelinux from mcr as a base image for protoc

---

e2e/config/vhd.go
e2e/exec.go
e2e/scenario_helpers_test.go
e2e/scenario_node_controller_test.go
e2e/scenario_test.go
e2e/types.go
e2e/validation.go
e2e/validators.go
e2e/vmss.go

Previously, E2E scenarios were limited to executing shell scripts on the VM.
I updated the tests to support more complex validations, such as running a GPU-enabled pod and verifying its functionality.
This change made the tests more flexible and simplified the overall logic.

Make E2E validation more flexible.

---

vhdbuilder/packer/test/run-test.sh
vhdbuilder/packer/vhd-scanning.sh

- fixes incorrect "now" tag on VM scanning and testing resource groups
- has test VMs for linux builds use a nic referencing an already-existing subnet rather than always creating ephemeral vnets/subnets on the fly, reducing testing time and resource churn
- removes dead code from testing script
Fixes #
```
none
```

fix: scanning and resource group tags, use packer subnet for linux test VMs

---

e2e/cluster.go
e2e/config/config.go

unblock master e2e by having dev resource name since changing the cache was a breaking change
Fixes #
```
none
```

chore: rename airgap e2e resources with dev

---

e2e/aks_model.go
e2e/kube.go
e2e/scenario_test.go
e2e/template.go

our airgap e2e tests need to be able to pull docker images in order to ensure that pods are behaving as expected. A recent change in the URL provided from RP caused the needs for us to change the URL for our e2e tests. The path changed from privateACR/aks/* to just privateACR/*. 
This change is not customer facing and only impacts our e2e testing 
Fixes #
```
none
```

cherry-pick: fix airgapped cluster e2e image pull

---

vhdbuilder/packer/install-dependencies.sh

/kind bug
This PR fixes the conditional that controls whether or not the below code is executed in install-dependencies.sh:
`systemctlEnableAndStart cgroup-memory-telemetry.timer || exit 1`
`systemctl enable cgroup-memory-telemetry.service || exit 1`
`systemctl restart cgroup-memory-telemetry.service`
Because `isMarinerOrAzureLinux` is a function, the brackets prevent the conditional from executing correctly, resulting in the code not executing when it is supposed to.
If it is true, the code should skip, which it is because its failing. But if it is false, it should execute, but it isn't.

fix: cgroup enablement syntax bug

---

e2e/cluster.go
e2e/exec.go
e2e/kube.go
e2e/scenario_helpers_test.go
e2e/types.go
e2e/validation.go
e2e/validators.go

/kind test
Log instruction on how to easy SSH into VM.
Example:
```
...
exec.go:199: SSH Instructions: (VM will be automatically deleted after the test finishes, set KEEP_VMSS=true to preserve it or pause the test with a breakpoint before the test finishes)
========================
az account set --subscription 8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8
az aks get-credentials --resource-group abe2e-westus3 --name abe2e-kubenet-331fc --overwrite-existing
kubectl exec -it debug-mariner-gxh2f -- bash -c "chroot /proc/1/root /bin/bash -c 'ssh -i sshkey10224010 -o PasswordAuthentication=no -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=5 azureuser@10.224.0.10'"
...
```

test: log SSH instructions

---

hack/tools/go.mod
vhdbuilder/lister/go.mod
vhdbuilder/prefetch/go.mod

/kind cleanup
Update go reference to use patch version reported by codeql.

fix: codeql reports that go toolchain want 1.N.P format

---

e2e/cluster.go
e2e/go.mod
e2e/go.sum
e2e/template.go
go.mod
go.sum

unable to cherry pick - https://github.com/Azure/AgentBaker/commit/cc3145cb6b0a4d863d8c3955ded77abbaae40c8c since a lot of work has been done around the e2e framework. But it accomplishes the same goal, remove the depreciated --azure-container-registry-config flag if the kubelet version is >= 1.30.0
Fixes #
```
none
```

fix: remove depreciate kube flags for e2e

---

.pipelines/.vsts-vhd-builder-release-windows.yaml
.pipelines/.vsts-vhd-builder.yaml

/kind chore
Noticed that VHD builds were happening. They shouldn't because the VHDs don't include release notes.
```
none
```

chore: don't run PR e2e pipelines when merging release notes

---

vhdbuilder/packer/install-dependencies.sh

/kind bug
fix: install missing udev rules for v6 vm sku, source udev rules: https://github.com/Azure/azure-vm-utils/blob/main/udev/80-azure-disk.rules
this udev rules are only for detecting "Microsoft NVMe Direct Disk", and waagent team are asking for adding this rule in Ubuntu image, that requires long time, so we set this udev rules in aks image first
Fixes #
```
fix: install missing udev rules for v6 vm sku
```

fix: install missing udev rules for v6 vm sku

---

e2e/validators.go

/kind test 
with containerd 2.0 NRI plugin is enabled by default. 
however need to make sure other users are not using their own NRI plugins 
Fixes #30622519
```
none
```

test: Testing 💚 update e2e checks for NRI plugin enabled status

---

aks-node-controller/.gitignore
aks-node-controller/app.go
aks-node-controller/app_test.go
aks-node-controller/const.go
aks-node-controller/main.go

/kind feature
- Add --dry-run flag to aks-node-controller to log commands without executing.
- Log output to both stderr and a file.
- Ensure log directory is created if missing; fallback to current directory (for local mac use).

feat: Add --dry-run option to aks-node-controller

---

.pipelines/.vsts-vhd-builder-release.yaml
.pipelines/.vsts-vhd-builder.yaml
.pipelines/templates/.builder-release-template.yaml
pkg/agent/datamodel/sig_config.go
vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/packer_source.sh

This is a cherry pick to master from this PR: https://github.com/Azure/AgentBaker/pull/5548
Retires GPU Dedicated VHD. 

fix: retire gpu dedicated aks image (#5548)

---

.pipelines/templates/e2e-template.yaml
vhdbuilder/packer/configure-windows-vhd.ps1
vhdbuilder/packer/generate-windows-vhd-configuration.ps1
vhdbuilder/packer/windows-image.env

/kind chore: update base windows versions to 2025-1B
Fixes #
```
none
```

Update windows base VHD to 2025-1B

---

parts/linux/cloud-init/artifacts/components.json

/kind feature
We have created, tested and published coredns images v1.11.3-4 and v1.9.4-4 to MCR using the new Dalec framework. The new Dalec framework publish the images to MCR under oss/v2 path. We plan to use v1.11.3-4 on all AKS clusters with 1.32 versions and existing clusters will use v1.9.4-4.
mcr.microsoft.com/oss/v2/kubernetes/coredns:v1.11.3-4
mcr.microsoft.com/oss/v2/kubernetes/coredns:v1.9.4-4
Once the rollout is complete, I will submit another PR to remove -
```
{
"downloadURL": "mcr.microsoft.com/oss/kubernetes/coredns:*",
"amd64OnlyVersions": [],
"multiArchVersionsV2": [
{
"renovateTag": "registry=https://mcr.microsoft.com, name=oss/kubernetes/coredns",
"latestVersion": "v1.9.4-hotfix.20240704"
}
]
},
``` …

Update coredns images v1.11.3-4 and v1.9.4-4 from MCR oss/v2

---

.pipelines/.vsts-vhd-builder-release-windows.yaml
.pipelines/templates/.build-and-test-windows-vhd-template.yaml

/kind chore
set POOL_NAME which was missing for windows VHD prod build pipeline
ADO definition of MSIT pipeline: https://msazure.visualstudio.com/CloudNativeCompute/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=210712&view=Tab_Variables
ADO definition of AME pipeline: https://msazure.visualstudio.com/CloudNativeCompute/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=188674&view=Tab_Variables
Fixes #
```
none
```

chore: set pool name on windows pipelines

---

vhdbuilder/packer/generate-windows-vhd-configuration.ps1

/kind bug
After we found some issues, we rolled back the CNS image version for Windows on AKS, to 1.6.13. This PR updates AgentBaker to cache the image for Windows.
Fixes #
```
none
```

chore: match rollback of cns and cni images on AKS to 1.6.13 for windows

---

.pipelines/templates/.build-and-test-windows-vhd-template.yaml

/kind chore
Currently if someone runs the windows VHD build pipelines for 1 VHD, the e2e tests are run for all windows VHDs. This change disables the e2e tests for the VHDs not being built.
Sample pipeline: https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=113082893&view=results
Fixes #
```
none
```

chore: don't run e2e tests if the VHD isn't being built

---

aks-node-controller/parser/helper_test.go

/kind test
None of the cases in the `getTargetEnvironment` helper method were covered by tests.
(no issue created)
```
none
```

test(helper): add coverage on getTargetEnvironment method

---

.pipelines/.vsts-vhd-builder-release-windows.yaml

/kind chore
Currently on PR build we build gen1 and gen2 VHDs for windows 2022 and 23H2. We only need to build a single gen for testing. This will reduce resource demand on Windows related PR builds.
I've tested that all 5 VHDs are still built when producing prod VHDs.
Fixes #
```
none
```

Only build and run one of the gen1/gen2 windows VHDs on PR build

---

.github/renovate.json

/kind feature
- Configure renovate to automerge runc and containerd patch versions
- Tested in a fork. E.g., https://github.com/Devinwong/AgentBaker/pull/258
- Will double check in this official repo after merge.
Fixes #
```
none
```

configure renovate to automerge runc and containerd patch versions

---

.github/README-RENOVATE.md
.github/renovate.json

/kind bug
- Separated `extractVersions` as it's not allowed by Renovate. Error message is `packageRules cannot combine both matchUpdateTypes and extractVersion`
Fixes #
```
none
```

fix: separate extractVersion and update readme-renovate.md

---

.pipelines/.vsts-vhd-builder-release.yaml
.pipelines/.vsts-vhd-builder.yaml
.pipelines/e2e-windows.yaml
.pipelines/e2e.yaml
.pipelines/templates/.build-and-test-windows-vhd-template.yaml
.pipelines/templates/e2e-template.yaml

/kind chore
Currently all the pipeline jobs that run e2e tests have the same name. Which is confusing when bouncing between pipelines. This PR adds more detail to the e2e pipeline name.
Fixes #
```
none
```

add displayname to e2e pipeline

---

vhdbuilder/packer/convert-sig-to-classic-storage-account-blob.sh

/kind bug
This unblocks the `Convert Shared Image Gallery To VHD Blob In Classic Storage Account` step in our VHD build pipelines.
The parameter for `accessSas` changed to `accessSAS`, resulting in no SAS being present for the AzCopy command to execute.

fix: convert to VHD blob step fix

---

.github/README-RENOVATE.md
.github/renovate.json

/kind feature
Setting Renovate `"recreateWhen": "never"` if the PR is closed without merge. Without this, even we manually closed/abandoned a PR we don't intend to merge, Renovate will recreate the same PR in the next schedule.
Fixes #
```
none
```

feat: setting Renovate "recreateWhen": "never" if the PR is closed without merge

---

pkg/agent/datamodel/linux_sig_version.json
pkg/agent/datamodel/mariner_v2_kata_gen2_tl_sig_version.json
pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go

OSType is currently an unused field within linux_sig_version.json, this PR removes references to this field in code, as well as from linux_sig_version.json.
Fixes #
```
none
```

cleanup: remove unused OSType from linux_sig_version.json

---

e2e/cluster.go
e2e/exec.go
e2e/node_config.go

right now we extract all cluster params except for the bootstrap token using a privileged pod running a node of the e2e cluster's system pool - this is an error prone process and requires at least one node to be running in the system pool at the time of test execution. it turns out we can get the cluster CA certificate data and cluster fqdn directly from the `ListClusterAdminCredentials` API on the AKS ARM client instead
further, this PR removes the API server cert and client key cluster parameters, as they aren't strictly needed with how we bootstrap nodes for e2e tests
Fixes #
```
none
```

test(e2e): simplify cluster parameter extraction

---

.github/renovate.json

/kind feature
Add scheduled time to Renovate so that it won't trigger update at the same time during working hours.
Fixes #
```
none
```

add scheduled time to Renovate

---

.pipelines/.vsts-vhd-builder-pr-windows.yaml
.pipelines/.vsts-vhd-builder-release-windows.yaml
.pipelines/templates/.build-and-test-windows-vhds-template.yaml

/kind chore
We want to build fewer VHDs during a PR than during release - mostly becasue testing both gen1 and gen2 VHDs for a PR is too many. Linux already has seperate pipelines for PR vs release, so this PR makes the pipelines consistent.
Also, there's currently a bug in the windows pipeline where we can't override the parameters to build some VHDs for release. This PR fixes that too.
After this PR is merged, I'll have to update ADO to use the new pipeline for PRs.
Fixes #
```
none
```

chore: seperate windows PR VHD pipeline from VHD pipeline that creates VHDs for test or release

---

parts/common/components.json
schemas/components.cue
vhdbuilder/packer/windows/components_json_helpers.tests.ps1

/kind chore
Renovate identified nanoserver 1809 as a container that has a more recent version. It doesn't. Added a comment explaining why and have disabled renovate for nanoserver on ws2019.
Fixes #
```
none
```

chore: remove nanoserver from renovate and add a comment explaining why

---

.github/renovate.json
CODEOWNERS

/kind feature
1. Add owners for some components
2. Set components.json to no code-owner so that it can be approved and merged by component owner. Now every renovate changes to Renovate.json still needs code-owners to approve. This defeats the purpose of component owner to self-approve/merge their own PRs. If it ends up not going as expected, we can change it back.
Fixes #
```
none
```

Add owners for some components. Set compponents.json to no code-owner.

---

parts/common/components.json

/kind bug
chore: update Azure Disk CSI driver on Windows with hostprocess images
original version on Windows is not used any more, we only use `*-windows-hp` on Windows for Azure CSI drivers now.
Fixes #
```
none
```

chore: update Azure Disk CSI driver on Windows with hostprocess images

---

parts/common/components.json
vhdbuilder/packer/windows/components_json_helpers.tests.ps1

/kind chore
Updates ciprod container to 3.1.25. This made the windows 23H2 VHD become too large and fail the build. After much discussion, we realised that ciprod isn't supported on windows 23H2, so is not needed there.
Fixes #
```
none
```

chore: update ciprod to 3.1.25, exclude it from windows 23H2 SKU

---

schemas/windows_settings.cue
vhdbuilder/packer/windows/components_json_helpers.ps1
vhdbuilder/packer/windows/components_json_helpers.tests.ps1
vhdbuilder/packer/windows/windows-vhd-configuration.ps1
vhdbuilder/packer/windows/windows_settings.json

/kind chore
Furthers the migration from hard coded values in a powershell script into a json file that we can use renovate on. Will also make adding new versions of windows easier.
Fixes #
```
none
```

Chore: move windows patch and windows defender info into windows settings.json

---

.pipelines/.vsts-vhd-builder.yaml

/kind chore
Reduces number of linux VHD builds - I noticed an unnecessary one on a windows related PR so this fixes it.
Fixes #
```
none
```

chore: add exclusions so we don't build linux vhds when the windows settings cue file changes

---

parts/common/components.json
vhdbuilder/packer/windows/components_json_helpers.ps1
vhdbuilder/packer/windows/components_json_helpers.tests.ps1
vhdbuilder/packer/windows/windows-vhd-configuration.ps1

/kind chore
Currently windows components and linux components use different variable substitution mechanisms in components.json, which makes it hard to share urls and download sources. This PR makes Windows consistent with Linux and also sets CPU_ARCH for Windows so it can be used in urls.
Fixes #
```
none
```

chore: fix var substitution in components.json for windows and add CPU_ARCH substutition

---

parts/common/components.json
vhdbuilder/packer/windows/components_json_helpers.tests.ps1
vhdbuilder/packer/windows/windows-vhd-configuration.ps1

/kind cleanup
bump cloud-node-manager and acr-credential-provider to new release v1.28.14 v1.29.12 v1.30.8 v1.31.2
Fixes #
```
none
```

add acr-credential-provider release 1.31

---

parts/common/components.json

/kind chore
This PR splits the versions for azure-vnet-cni-windows into two blocks so we know they are different versions that need to be cached and not prev and next patch releases.
Fixes #
```
none
```

chore: split versions for azure-vnet-cni-windows component

---

parts/common/components.json
vhdbuilder/packer/windows/components_json_helpers.tests.ps1

/kind feature
Release notes: https://github.com/Azure/azure-container-networking/releases/tag/v1.6.21 
CNS: https://msazure.visualstudio.com/AzureWiki/_wiki/wikis/AzureWiki.wiki/754746/v1.6.21 
Fixes a bug when using vnet scale mode with cilium that would create incorrect iptables rules, causing connectivity to dns and imds to fail from the pod.
Could someone confirm `testdata/prefetch.sh` does not need to be updated for caching new images?
Noticed https://github.com/Azure/AgentBaker/actions/runs/13402631728/job/37436508667?pr=5873 failing-- should these values always be present, or can the test be modified? This looks new/different …

chore: bump cni and cns to v1.6.21 for Windows VHD

---

parts/windows/kuberneteswindowssetup.ps1
pkg/agent/testdata/AKSWindows2019+CustomCloud+ootcredentialprovider/CustomData
pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
pkg/agent/testdata/AKSWindows2019+KubeletServingCertificateRotation/CustomData
pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData
pkg/agent/testdata/AKSWindows2019+ootcredentialprovider/CustomData

/kind bug
AgentKey is being set both in the CSE and the run command. It only needs to be set in one place. And the run command is more secure.
Fixes #
```
none
```

bug: don't need to set agentkey in the cs

---

e2e/scenario_test.go

/kind test
`ls -al /var/run` doesn't show the contents since `/var/run` is a link to `/run`. So we need to run `ls -al /run` to check whether the file `outbound-check-skipped` exists.
```
$ ls -al /var/run
lrwxrwxrwx 1 root root 4 Aug 25  2021 /var/run -> /run
```
Fixes #
```
none
```

test: fix the validation of outbound-check-skipped

---

.pipelines/templates/.builder-release-template.yaml

/kind bug
This PR makes the name of the bcc logs artifact unique for each job attempt in order to prevent failed retries.
Erroring when publishing artifacts with the same name. 
Fixes #

fix: publishing artifact issue

---

parts/linux/cloud-init/artifacts/10-tlsbootstrap.conf
pkg/agent/const.go
pkg/agent/variables.go

parts/linux/cloud-init/artifacts/10-tlsbootstrap.conf is currently an unused artifact, not directly referenced by our cloud-init template. Regardless, we already write the same drop-in content out at provisioning time based on TLS bootstrapping settings within CSE directly. This PR removes the unused artifact and its corresponding references.
Fixes #
```
none
```

cleanup: remove unused tls bootstrap kubelet drop-in

---

vhdbuilder/packer/install-dependencies.sh

/kind cleanup 
Since the GPU VHD has been deprecated, we don't need to cache this device plugin on the VHD. Downloading the device-plugin now is unnecessary, takes up the limited VHD space, increases build time and augments the security attack surface area (ex: this is not being auto-updated). 
Fixes #
```
none
```

Remove Nvidia device plugin from being download in the VHD

---

parts/common/components.json
schemas/windows_settings.cue
vhdbuilder/packer/init-variables.sh
vhdbuilder/packer/windows/configure-windows-vhd.ps1
vhdbuilder/packer/windows/windows_settings.json

We should be enforcing a minimum VHD size of 30GB unless a particular VHD overrides this. This default went missing during a refactor. Adding back. It only impacts WS2019 as that VHD doesn't have an override size set.
Fixes #
```
none
```

regression: set windows 2019 disk size

---

parts/common/components.json
vhdbuilder/packer/windows/windows_settings.json

Product limit for WS2019 to have max 30GB VHD size. We had to increase it to 31 GB recently to re-enforce a size (as VHD size validation wasn't working), this PR fixes the size.
Fixes #
```
none
```

regression: get the WS2019 VHD back to 30GB

---

parts/common/components.json

Reverts Azure/AgentBaker#5966
This seems to breaking e2e test `Test_Ubuntu2204_AirGap_NonAnonymousACR`. The symptom is that the node will be tainted with `Taints:             node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule`. Reverting this for further investigation.

Revert "chore(deps): update azure-cloud-node-manager (patch)"

---

parts/common/components.json

/kind feature
chore: upgrade CSI driver versions for AKS 1.32
Fixes #
```
none
```

chore: upgrade CSI driver versions for AKS 1.32

---

.pipelines/templates/.builder-release-template-windows.yaml
vhdbuilder/packer/windows/windows-vhd-builder-sig.json

For e2e tests, we lookup the image to run the tests on by the build id tag on VHD images. These are not being set for Windows. This PR adds the tags in.
There are likely other issues with e2e tests and windows, but this is the first thing I noticed.
Fixes #
```
none
```

chore: tag windows images

---

parts/common/components.json

/kind cve
Bump moby-containerd for azlinux2 and containerd2 for azlinux3

bumping azlinux containerd to latest

---

.pipelines/.vsts-vhd-builder.yaml

/kind test
This adds arm64 and FIPs coverage to the PR gate for AgentBaker code changes.
This is accomplished by replacing the azurelinuxV3gen2 VHD with the azurelinuxV3arm64gen2fips VHD. This maintains coverage for azurelinuxV3gen2, while also adding coverage for Arm64 and FIPs.
Prevents changes from unexpectedly failing builds for certain features that don't have PR gate test coverage.

feat: add arm64 and fips to PR gate

---

aks-node-controller/go.mod

Bump Go version in aks-node-controller, CVE-2024-45336

chore: bump go version for node-controller

---

aks-node-controller/go.mod
e2e/go.mod

bump go version to maintained one for aks-node-controller

chore: bump go for node-controller to 1.23

---

vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh

/kind cleanup
This PR removes the asc-baseline package from Ubuntu images after its job is done. This reduces the number of packages in the final image that need to be checked for CVEs.
Fixes #
```
none
```

Purge asc-baseline after execution

---

vhdbuilder/packer/install-dependencies.sh
vhdbuilder/packer/test/linux-vhd-content-test.sh

feature
This PR adds a function to extract a coredns binary from cached coredns container images in the VHD. It extracts binary of n-1 coredns image version and latest revision version (v.Major.Minor.Patch-Revision) and copies it to /opt/azure/containers/localdns/binary/coredns path. This binary will be used by localdns systemd unit. The function also handles the cleanup of temporary directories and unmounting of images.
Fixes # None
Build
Not sure if there is a way to write unit tests for this file. 
```
none
```

Add function to extract and cache CoreDNS Binary in VHD for localdns

---

e2e/node_config.go
e2e/scenario_test.go
e2e/validators.go
pkg/agent/utils.go

/kind test
after k8s 1.29 the evictionHard is set to 100Mi by default
https://learn.microsoft.com/en-us/azure/aks/node-resource-reservations
the PR update the default node config in e2e test to match the default, so that the node created are closer to real life.
```
none
```

test: update e2e config to match evictionHard default value to 100Mi

---

.github/workflows/tidy.yaml

remove toolchain from automated PRs, like so: https://github.com/Azure/AgentBaker/pull/6112/commits/baf2aafe45705d929c551ce2e8fdcb992ed5ed26
Fixes #
```
none
```

fix: remove toolchain line from go.mod via auto-tidy

---

pkg/agent/datamodel/gpu_components.go

/kind bug
This enables nvidia fabric manager for H200 GPUs. Fabric manager is used for GPU-to-GPU connectivity. 
Fixes #
```
none
```

Enable fabric manager for H200 GPUs

---

staging/cse/windows/azurecnifunc.ps1
staging/cse/windows/azurecnifunc.tests.ps1

/kind feature 
**What this PR does / why we need it**: 
The SDNRemoteArpMacAddress needs to be set for HNS when AzureCNI is enabled in certain scenarios. We have done this in CNS for a very long time (https://github.com/Azure/azure-container-networking/pull/1306) but some recent changes (https://github.com/Azure/azure-container-networking/pull/2993) have exposed how very fragile HNS is and how dangerous it is to restart it unnecessarily (https://github.com/Azure/azure-container-networking/pull/3498).
This change will move setting the regkey to the CSE scripts so that it is complete and HNS is restarted well before CNS lands, and guarantees it only happens once for the lifetime of the Node.
**Release note**: 
```
set SDNRemoteArpMacAddress for HNS during AzCNI …
```

feat: set SDNRemoteArpMacAddress for HNS during AzCNI setup

---

parts/linux/cloud-init/artifacts/localdns.sh
spec/parts/linux/cloud-init/artifacts/localdns_spec.sh

/kind test
Fine tuning the localdn UT timeout and max attempt for shorter test time.
This shorten shellspec unit test time from 47sec to 13sec while not changing the logic.
Sync'd with Sri Harsha and he is good with that changes.
Fixes #
```
none
```

Fine tuning the localdns UT timeout and max attempt for shorter test time

---

.pipelines/.vsts-vhd-builder-pr-windows.yaml
parts/common/components.json

/kind feature
This PR removes the ciprod container and replaces it with the current servercore container and the previous servercore container. This was agreed with the ciprod team as a way to support their ciprod rollouts.
It also works around a issue with the subscription the PR builds now run in.
servercore tags list is here: https://mcr.microsoft.com/v2/windows/servercore/tags/list
Fixes #
```
none
```

chore: replace ciprod with latest and latest-1 of servercore

---

staging/cse/windows/kubernetesfunc.ps1

/kind bug
This PR fixes a logging bug in the Windows CSE.
Currently during Windows CSE, we check API server connectivity. However, when that fails, there is a code path that only prints:
2025-04-08T23:30:48.5157611+00:00: Retry 0 : Failed to connect to API server asdfasdf-asdfasdfasdf.privatelink.eastus.azmk8s.io. Error: Exception calling "Wait" with "1" argument(s): "One or more errors occurred."
This is due to the way powershell prints exceptions of the type "AggregateException". So this PR prints them properly. Hopefully.
```
C:\Users\wrightt> Check-ApiServerConnectivity -MasterIP www.google.com -MaxRetryCount 5
2025-04-14T16:50:03.7516430+12:00: Retry 0/5: Trying to connect to API server www.google.com …
```

bug: better catch in windows cse

---

packer.mk

/kind chore
Adds timestamps to logs produced by packer. This will make debugging VHD builds (particularly how long steps take) a bit easier. And it might give us a chance to investigate intermittent failures as we'll know when something happenned.
Fixes #
```
none
```

chore: add packer timestamps

---

spec/parts/linux/cloud-init/artifacts/cse_helpers_retry_timeout_spec.sh

Adds shellspec tests that verify exit codes returned by helper functions with timeouts that are used in long running operations

test: add spec for shellspec tests, checking exit codes for helper commands used in long running operations

---

e2e/scenario_test.go

bug
This PR will cause LocalDNS to not be enabled for ContainerdAirgappedK8sNotCached and PrivateKube. These VHDs do not contain coredns binaries and LocalDNS is not supported on these VHDs. 
Fixes #
```
none
```

Dont enable LocalDNS for ContainerdAirgappedK8sNotCached and PrivateKube

---

.github/README-RENOVATE.md
.github/renovate.json

/kind feature
- Update Renovate to support auto-updating kubernetes-cri-tools for Ubuntu.
- Update debugging steps in readme too.
- Tested in self-hosted fork.
Fixes #
```
none
```

update Renovate to support auto-updating kubernetes-cri-tools for Ubuntu

---

parts/common/components.json

/kind bug
Found out that this makes the VHD image look for
mcr.microsoft.com/oss/v2/kubernetes/apiserver-network-proxy/agent:v0.30.3 mcr.microsoft.com/oss/v2/kubernetes/apiserver-network-proxy/agent:v0.30.3-hotfix.20240819
which is incorrect as the hotfix image path is without `v2`
mcr.microsoft.com/oss/kubernetes/apiserver-network-proxy/agent:v0.30.3-hotfix.20240819
Fixes #
```
none
```

fix: apiserver-network-proxy

---

.github/release.yaml

fix: exclude components label from the Changes category of official release notes

---

vhdbuilder/packer/test/linux-vhd-content-test.sh

Specify `DEBIAN_FRONTEND=noninteractive` when installing git during tests, to prevent dpkg from trying to bring up a user dialog. The other attempt at fixing the issue (installing dialog/readline) is not needed with this fix so remove those lines again.
Fixes #6357
Fixes #6115
```
none
```

fix(vhdbuilder): Pass DEBIAN_FRONTEND when installing git during test

---

.pipelines/.vsts-vhd-builder-pr-windows.yaml
.pipelines/e2e-windows.yaml

/kind cleanup
re-enables windows e2e tests
Have scheduled the windows VHD Test Pipeline to build at 1am NZST every day.
https://msazure.visualstudio.com/CloudNativeCompute/_build?definitionId=210712&_a=summary
Fixes #
```
none
```

enable tests

---

e2e/scenario_test.go
e2e/validators.go

Adding an E2E for Ubuntu 24.04 with GRID GPU driver (A10 family). Currently there are no GRID + 24.04 e2e tests. 
Makes kubelet log validation case insensitive since the casing changed with k8s 1.31. 
Fixes #
```
none
```

24.04 GRID E2E + case-insensitive check for kubelet

---

.github/renovate.json
parts/common/components.json

/kind chore
This PR adds renovate rules for servercore and nanoserver.
The tags for these containers are strange. They always start with "10.0" and then have a number indicating the windows container version, and then the patch version. Example:
* 10.0.20348.3328
20348 means "windows 2022 style container". Wheras 26100 means "windows 2025 style container" and "17763" means "windows 2019 style container"
To ensure that the upgrade does not upgrade between windows versions - ie a WS2019 container doesn't get changed to 2025, we use the windows version as the major version, and the 4th part as the patch version. Yeah, it's odd, but it seems to work.
I also made WS2025 cache both WS2022 and WS2025 style containers as it …

renovate rules for servercore and nanoserver

---

vhdbuilder/packer/test/run-test.sh

/kind test
This PR removes the `--debug` flag from the `az vm create` command during Linux content tests in the VHD Build pipeline.
The `--debug` flag has caused significant clutter in the logs and is not needed.

fix: remove debug flag from test vm create command

---

.pipelines/scripts/e2e_run.sh
packer.mk
vhdbuilder/packer/trivy-scan.sh

Az CLI now reports:
```
Passing the managed identity ID with --username is deprecated and will be removed in 2.73.0. Use --client-id, --object-id or --resource-id instead.
```
This causes the test/scan/cleanup step to fail.
Fix the failure by being specific in what kind of ID we're passing.
Fixes #
```
none
```

fix: Stop passing managed identity ID with --username

---

parts/common/components.json

bug
ci team has frequent incident https://portal.microsofticm.com/imp/v5/incidents/details/630890690/summary, we believe it is because of old CI agent version - linux.
update ci release Linux version (3.1.25) to 3.1.27.
```
none
```

fix: update ci agent linux version from 3.1.25 to 3.1.27

---

.github/workflows/labeler.yaml

have labeler workflow use GITHUB_TOKEN secret instead of aks-node-assistant so the labeler workflow will also work properly with dependabot PRs (since workflows triggered by dependabot PRs don't have access to repo secrets if triggered via pull_request instead of pull_request_target).
labels will now be added by the "github-actions" bot instead of aks-node-assistant, for example: https://github.com/Azure/AgentBaker/pull/6429
this change also greatly simplifies and speeds up the runtime of the labeler workflow by removing the need to interact with Azure
Fixes #
```
none
```

cleanup: have labeler workflow use GITHUB_TOKEN secret instead of aks-node-assistant

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go

/kind feature
pin UbuntuContainerd2404CVMGen2 vhd version temporarily because the current bhd build is broken.
Fixes #
```
none
```

chore: pin UbuntuContainerd2404CVMGen2 vhd version temporarily

---

.pipelines/.vsts-vhd-builder-release.yaml

/kind bug
the ubuntu 2404 cvm vhd build is broken
temporarily disable auto-build for the broken vhd
Fixes #
```
none
```

chore: disable default build for 2404 cvm vhd

---

.config/CredScanSuppressions.json
e2e/kubelet/README.md

/kind bug
Upstream 1ES publishing pipelines are failing due to false CredScan alerts: https://dev.azure.com/AzureContainerUpstream/Kubernetes/_build/results?buildId=182763&view=results
Supressing the invalid flags as per: https://www.owiki.ms/wiki/Credscan/Suppress_False_Positives#placeholder
Fixes #
```
none
```

chore: Credscan rules to supress 1ES checks - failing Upstream pipelines

---

e2e/node_config.go
parts/windows/windowscsehelper.tests.ps1
staging/cse/windows/azurecnifunc.tests.ps1
staging/cse/windows/configfunc.tests.ps1
staging/cse/windows/credentialProvider.tests.suites/credential-provider-config.yaml
staging/cse/windows/nvidiagpudriverfunc.tests.ps1

/kind test
the current default e2e windows profile is using an outdated version of cse script. use folder path so that the current one is  used in e2e test.
previously this does not matter since e2e always uses the cse on the branch, however this has been fixed by another PR.
```
none
```

fix: use current cse pacakge in e2e as defined in componts.json

---

.pipelines/.vsts-vhd-builder-release.yaml

/kind feature
re-enable build2404cvmgen2containerd VHD build by default
Fixes #
```
none
```

chore: re-enable build2404cvmgen2containerd VHD build by default

---

e2e/aks_model.go
e2e/kube.go
e2e/node_config.go
e2e/vmss.go

/kind bug
In the subscription I used for the pipeline run, I do not have the hard coded standard_d2ds_v5 for e2e test, so make it configurableconf
Fixes #
Replace the hardcoded VM SKU with the one configured in the config file.
Make the "nvidia-device-plugin" deployed in linux node only. It is not able to deploy to windows node, although it will not fail the test
```
none
```

minor change: Replace the hardcoded VM SKU 

---

.pipelines/templates/.builder-release-template.yaml
pkg/agent/const.go
pkg/agent/variables.go
vhdbuilder/packer/cis-report.sh
vhdbuilder/packer/post-install-dependencies.sh
vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
vhdbuilder/packer/vhd-image-builder-base.json
vhdbuilder/packer/vhd-image-builder-cvm.json
vhdbuilder/packer/vhd-scanning.sh
vhdbuilder/scripts/linux/mariner/tool_installs_mariner.sh
vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh

/kind feature
This PR introduces scanning for CIS L1 compliance to those Ubuntu 22.04 and Ubuntu 24.04 builds that rely on the `-base` packer template. Scanning is performed during `test-scan-cleanup`. The CIS report is publish to ADO artifacts. This PR will be followed by config changes that increase our CIS compliance.
We can also finally clean up the `asc-baseline` package that is not used any longer.
Fixes #
```
none
```

feat: Add CIS compliance scanning to Ubuntu 22/24-base builds

---

pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go

/kind feature
unpin UbuntuContainerd2404CVMGen2 vhd version because the vhd build failure is fixed
Fixes #
```
none
```

chore: unpin UbuntuContainerd2404CVMGen2 vhd version

---

e2e/node_config.go
e2e/scenario_win_test.go

/kind test
The windows e2e tests have been using outdated default  config.
this PR brings default up to date; it aligns with production environment more closely.
it will save a lot of time since now all binaries are installed on the VHD and we don't have to download them again while running e2e.
Fixes #
```
none
```

test: update windows e2e default config

---

.pipelines/.vsts-vhd-builder-release-windows.yaml
.pipelines/templates/.build-and-test-windows-vhd-template.yaml
.pipelines/templates/.build-and-test-windows-vhds-template.yaml
.pipelines/templates/.builder-release-template-windows.yaml
vhdbuilder/packer/WINDOWS-CONTAINERIMAGE-JSON.MD
vhdbuilder/packer/produce-packer-settings.sh

/kind feature
/kind cleanup
**What this PR does / why we need it:**
This PR introduces an automation feature that streamlines the process of populating Windows image URLs (base, nano, and servercore) in AgentBaker. Instead of manually updating each image URL during every Patch Tuesday, this feature enables automatic population using a JSON payload file. The payload is downloaded from the WCCT Agentbaker Storage account and parsed to extract the latest image URLs.
**Which issue(s) this PR fixes:**
This reduces manual intervention, minimizes the risk of human error, and ensures consistency across image updates. It also includes comments and conditions in the case where a valid URL is not available for use, falling back to the pipeline's initial [manually filled] …

Auto-fill Windows image URLs using WCCT JSON

---

parts/linux/cloud-init/artifacts/10_azure_nvidia
parts/linux/cloud-init/artifacts/51-azure-nvidia.cfg
vhdbuilder/packer/packer_source.sh
vhdbuilder/packer/pre-install-dependencies.sh
vhdbuilder/packer/vhd-image-builder-arm64-gen2.json

/kind feature
GB200 instances require a different kernel to other arm64 instances. It would be most efficient to include both kernel types in the same image. This feature uses GRUB's `smbios` command to decide which kernel to boot by default based on the CPU manufacturer.
I am not familiar with AgentBaker. The feature has been tested manually by myself using the latest Canonical:ubuntu-24_04-lts:specialized-hardware:latest image under QEMU. It has also been manually tested by @abenn135 on real Azure instances. The packer changes are untested.

feat: support dynamically booting from NVIDIA/non-NVIDIA Ubuntu kernels

---

e2e/config/azure.go
e2e/scenario_test.go
e2e/test_helpers.go
e2e/validators.go

/kind test
- Introduced VMExtensionImagesClient to Azure client and implemented helper to fetch latest VM extension image version.
- Added GetLatestVMExtensionImageVersion utility to programmatically retrieve the most recent version of the AKS Linux VM extension.
- Implemented helper functions to attach VM extensions to VMSS definitions.
- Introduced validators to check NPD service status and simulate filesystem corruption, asserting correct condition reporting on the node.
- Added new E2E test Test_Ubuntu2404_NPD_Basic to validate Node Problem Detector functionality on Ubuntu 24.04 with AKS extension enabled.
Fixes #
While we try to …

e2e: Add support for testing NPD w/ AKS VM Extension

---

e2e/aks_model.go
e2e/cluster.go
e2e/config/azure.go
e2e/config/config.go
e2e/config/vhd.go
e2e/exec.go
e2e/kube.go
e2e/node_config.go
e2e/scenario_helpers_test.go
e2e/scenario_node_controller_test.go
e2e/scenario_test.go
e2e/test_helpers.go
e2e/types.go
e2e/vmss.go

/kind test
e2e refactor: Add support for running E2E tests in alternate locations
This PR refactors the E2E test framework to support running tests in multiple Azure locations, not just a single, hardcoded location. This enables better test coverage, validation of location-specific behavior, and the potential for parallel test execution across different geographies. This would be particularly useful when we are facing capacity constraints for a certain VM SKUs in our default location, especially when we have capacity in other locations for the said VM SKU.
Key changes include:
- **Location-Aware Scenarios:**
- A `Location` string field has been added to the `Scenario` struct. Tests can now specify a target location, …

e2e: Allow test to specify the location

---

spec/shellspec.Dockerfile

The previous repo is no longer accessible.
The shellspec action is failing because the previous debian repo is no longer accessible. Switch to using the debian archive.
Fixes #
```
none
```

ci: Use debian archive mirror in shellspec dockerfile

---

parts/linux/cloud-init/artifacts/10_azure_nvidia
parts/linux/cloud-init/artifacts/51-azure-nvidia.cfg

/kind feature
Specifies certain boot-time flags to Linux kernel necessary for GPU drivers to work.
```
none
```

Add Linux kernel commandline flags to GRUB on GB200

---

e2e/cluster.go
e2e/config/vhd.go
e2e/test_helpers.go

/kind test
This PR introduces two main improvements to the E2E test framework: it refactors the VHD (Virtual Hard Disk) caching to be location-specific and enhances test stability by replacing `panic`-inducing error handling with standard test assertions.
1. **Per-Location VHD Caching:**
- The previous implementation cached a single VHD resource ID per `Image` object. This caused issues when tests were run across multiple Azure locations, as a Shared Image Gallery (SIG) image version might not be replicated to all locations at the same time. A lookup failure in one location would be incorrectly cached and reused for subsequent tests in other locations where the image might actually be available.
- This has been fixed by …

Fix location-specific image caching

---

vhdbuilder/packer/cis-report.sh
vhdbuilder/packer/test-scan-and-cleanup.sh
vhdbuilder/packer/test/linux-vhd-content-test.sh
vhdbuilder/packer/trivy-scan.sh
vhdbuilder/packer/vhd-scanning.sh

test-scan-and-cleanup is failing because:
- can't install az-cli on Flatcar and subsequently
- we're unexpectedly running cis-scanning
- some vhd-content-tests were not handling flatcar correctly
I missed this in testing because I was passing `GALLERY_SUBSCRIPTION_ID` in my testing, and `test-scan-and-cleanup` swallows the error and returns success after cleanup.
Fixes #
```
none
```

fix test-scan-and-cleanup for flatcar

---

pkg/agent/baker.go
pkg/agent/datamodel/types.go

/kind feature
We need to enable a systemd service that blocks iptables rule installation on nodes of clusters that uses Cilium eBPF host routing. This PR exposes a flag to pass that information from RP to AgentBaker.
Fixes #
```
none
```

feat: expose iptables block to agentbaker

---

parts/common/components.json

/kind feature
chore: upgrade Azure Disk CSI driver versions in vhd image
This PR also removes vhd image in aks 1.30 which is EOL in July.2025
Fixes #
```
none
```

chore: upgrade Azure Disk CSI driver versions in vhd image

---

e2e/exec.go

/kind test
Subscription and cluster name parameters got swapped. This string is only for documentation.
Fixes #
```
none
```

e2e: Fix order of parameters in ssh instructions string

---

parts/linux/cloud-init/artifacts/ubuntu/cse_helpers_ubuntu.sh
vhdbuilder/packer/pre-install-dependencies.sh

/kind bug
This PR adds front end locks to the `wait_for_apt_locks` function. This will prevent multiple processes from trying and failing to get a lock on the front end while conducting package updates and modifications.
The kernel purge and reinstall logic in `pre-install-dependencies` is occasionally failing due to multiple processes each trying to get a lock on the front end.

fix: add front end lock to wait_for_apt_locks function

---

vhdbuilder/packer/trivy-scan.sh

/kind flake
The package installation of azure-cli during trivy-scan may also fail like this:
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
We have wrappers that handle this (and other issues) - use them in the trivy-scan script.
Fixes #
```
none
```

test(scan): Switch to apt_get_xxx helpers

---

.pipelines/.vsts-vhd-builder-pr-windows.yaml
.pipelines/scripts/windows-sub-cleanup.sh
.pipelines/templates/.build-and-test-windows-vhds-template.yaml

Remove "Old Windows VHD Cleanup" step from release pipeline.
This should be run for release. The step is skiped based on this condition inside a shell script:
```bash
if [ ${SUBSCRIPTION_ID} = ${PROD_SUBSCRIPTION_ID} ]; then
echo "Shouldn't do backfill clean up in production subscription."
exit 1
fi
```
A single env variable change may lead to a deletion attempt.
/kind cleanup

Remove "Old Windows VHD Cleanup" step from release pipeline.

---

.pipelines/.vsts-vhd-builder-release-windows.yaml
.pipelines/templates/.build-and-test-windows-vhd-template.yaml
.pipelines/templates/.build-and-test-windows-vhds-template.yaml
.pipelines/templates/.builder-release-template-windows.yaml
spec/parts/linux/cloud-init/artifacts/json_parser.sh
spec/parts/linux/cloud-init/artifacts/json_parser_spec.sh
spec/parts/linux/cloud-init/artifacts/sample_payload.json
vhdbuilder/packer/WINDOWS-CONTAINERIMAGE-JSON.MD
vhdbuilder/packer/produce-packer-settings.sh

/kind cleanup
/kind feature
This PR introduces an automation feature that streamlines the process of populating Windows image URLs (base, nano, and servercore) in AgentBaker. Instead of manually updating each image URL during every Patch Tuesday, this feature enables automatic population using a JSON payload file. The payload is downloaded from the WCCT Agentbaker Storage account and parsed to extract the latest image URLs.
This reduces manual intervention, minimizes the risk of human error, and ensures consistency across image updates. It also includes comments and conditions in the case where a valid URL is not available for use, falling back to the pipeline's initial [manually filled] …

Build Image Autofill Using JSON Url

---

e2e/scenario_test.go
e2e/validators.go

/kind test
Add end-to-end tests to validate NPD (Node Problem Detector) InfiniBand link flapping detection functionality:
- ValidateNPDIBLinkFlappingCondition: Verifies NPD reports initial stable IB link condition (IBLinkFlapping=False with NoIBLinkFlapping reason)
- ValidateNPDIBLinkFlappingAfterFailure: Simulates IB link flapping by injecting "lost carrier" events into syslog and validates NPD detects the condition (IBLinkFlapping=True with fault code NHC2005)
These validators are called after the GPU plugin is validated.
Fixes #
```
none
```

e2e: Add InfiniBand link flapping validation tests

---

pkg/agent/datamodel/types.go
pkg/agent/datamodel/types_test.go
pkg/agent/variables.go
pkg/agent/variables_test.go

/kind feature
Data model changes needed so that AKS-RP can pass Windows cilium enablement flag and configuration when enabled.
Fixes #
```
none
```

feat: add node bootstrapping fields for Windows Cilium feature

---

e2e/aks_model.go
e2e/cluster.go

make e2e a bit smoother..
when garbage collection deleted MC resource group, the cluster is useless and e2e fails.
Fixes #
```
none
```

delete cluster and retrying when MC resource group is gone

---

.github/workflows/check-windows-packages-change.yml
parts/common/components.json
vhdbuilder/packer/windows/components_json_helpers.ps1
vhdbuilder/scripts/windows/generate_cached_stuff_list.ps1

/kind chore
Fixes auto-windows comment on PR to contain cpu arch.
Fixes #
```
none
```

chore: fix auto windows comment when cpu-arch is in components.json

---

vhdbuilder/packer/pre-install-dependencies.sh

/kind bug
Canonical confirmed that there is regression in the latest kernel packages for Ubuntu 22.04. This PR implements a simplified approach to pin Ubuntu 22.04 to kernel version 5.15.0-1092 until the issues are resolved.
**Implementation approach:**
1. **Package Selection Phase**: Choose appropriate kernel packages based on Ubuntu version
2. **Installation Phase**: Same purge/install logic for all cases
Related to kernel regression issues in Ubuntu 22.04
This is a simplified alternative to PR #6938 that achieves the same functionality with significantly less code duplication.
```
Pin Ubuntu 22.04 kernel to …
```

fix: pin Ubuntu 22.04 kernel to 5.15.0-1092 due to regression

---

.pipelines/.vsts-vhd-builder-release.yaml
pkg/agent/datamodel/sig_config.go
pkg/agent/datamodel/sig_config_test.go

Freezing the Kata AzL2 VHD since the build pipeline is no longer working since AzL2 is has begun deprecation and is being actively removed from ACRs. Additionally, can't migrate to AzL3 because components required to run Kata-CC have been getting removed in Kata-CC, and we need to support the feature at least until ~March 2026. This PR freezes the VHDs in a previous already working build.
Fixes #
```
none
```

Freezing kata mariner vhd for kata-cc.

---

e2e/node_config.go
e2e/scenario_test.go
parts/linux/cloud-init/artifacts/aks-node-controller.service

/kind feature
Add Flatcar support for "scriptless"/aks-node-controller. Not introducing anything new into the contract because the only change in control-flow that we need is to skip waiting for `cloud-init` to complete. This code is guarded by `DisableCustomData` , so we'll make sure to set that to true for Flatcar.
The other change that would be necessary is to generate customdata in ignition format, but we can also rely on the limited `coreos-cloudinit` fallback implementation that Flatcar ships with. It doesn't support enough for the non-scriptless mode but in scriptless mode the customdata is so simple that we can use this approach.
To make `coreos-cloudinit` work we need to tweak `aks-node-controller.service` …

Flatcar "scriptless" support

---

vhdbuilder/packer/pre-install-dependencies.sh
vhdbuilder/packer/test/linux-vhd-content-test.sh

Install FDE LTS kernel and handle nullboot for CVM builds
/kind feature
This PR adds support for installing Full Disk Encryption (FDE) LTS kernel packages specifically for CVM (Confidential VM) builds, while maintaining the existing kernel selection logic for other builds.
**Changes made:**
- For CVM builds, install `linux-image-azure-fde-lts-${UBUNTU_RELEASE}` instead of regular LTS kernel
- Add nullboot package purge/reinstall sequence for CVM builds to prevent boot errors
- Update conditional logic to handle CVM-specific kernel requirements
- Use LTS kernel packages for CVM (more stable for production AKS nodes vs latest kernel)
- Update test to reflect the modified conditional logic …

feat: install FDE LTS kernel and handle nullboot for CVM builds

---

parts/common/components.json

/kind cleanup
update cilium latest version to the images that are currently rolling out
Fixes #
```
bump cilium v1.16.13-250826 and v1.17.7-250821
```

chore: bump cilium v1.16.13-250826 and v1.17.7-250821

---

aks-node-controller/README.md
aks-node-controller/app.go

/kind feature
Fail fast to unblock aks-node-controller provision-wait from waiting until timeout.
Now if the aksnodeconfig is invalid, it will fail immediately.
Fixes #
```
none
```

Fail fast to unblock aks-node-controller provision-wait from waiting until timeout

---

.github/renovate.json

/kind cleanup
We found that people like Renovate to detect the version update asap.
Remove Renovate schedule for creating PR as it's not needed now. We needed it before because every PR needed rebase from master and it would trigger huge number of tests at the same time. We don't require rebase now so it should be fine to create PR even at daytime.
Fixes #
```
none
```

remove Renovate schedule as it's not needed now
