Azure/AgentBaker

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
cache window azure cni v1.5.6 in vhd.
Fixes #
```
none
```
=> chore: cache window azure cni v1.5.6 in vhd

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind Maintenance
Fixes #
```
none
```
=> chore: cache windows pause image 3.9-hotfix-20230808

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: upgrade Azure File CSI driver to v1.24.5 in vhd image
Fixes #
```
none
```
=> chore: upgrade Azure File CSI driver to v1.24.5 in vhd image

vhdbuilder/packer/components.json
=> feat: update managed prometheus image with configmap fix in july agent release

vhdbuilder/scripts/linux/tool_installs.sh, vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
/kind cleanup
chore: install right bpftrace binary on arm64 ubuntu 22.04
Fixes #
```
none
```
=> chore: install right bpftrace binary on arm64 ubuntu 22.04

e2e/vmss.go
/kind bug
The e2e-local.sh script has a SUBSCRIPTION_ID parameter, but if you change it from the default then the VMSS update fails with an error about the LB backend address pool using the wrong subscription.
Fix it by replacing the hard-coded subscription ID with opts.suiteConfig.subscription.
```
none
```
=> fix: configure subscription in e2e LB backend address pool ID

vhdbuilder/packer/list-images.ps1, vhdbuilder/packer/windows-vhd-builder-sig.json
/kind feature
Update AKS Windows VHD release note image list json to new format.
Fixes #
```
none
```
=> chore: update AKS Windows VHD release note image list json to new format

.pipelines/.vsts-vhd-windows-automation.yaml, vhdbuilder/scripts/windows/automate_helpers.sh, vhdbuilder/scripts/windows/automate_version_bump.sh
Bump version and create associated PR automatically.
Find current latest base image version by `az vm image show`. Update it in environment `windows-image.env`. For this update, create a pull request automatically.
/kind feature
Automate the process. Speeding up windows image release.
Fixes #
```
none
```
=> chore: bump windows base image version and create PR automatically

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: upgrade Azure File CSI driver versions in vhd image
Fixes #
```
none
```
=> chore: upgrade Azure File CSI driver versions in vhd image

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
=> feat: containerinsights 3.1.12 release

.pipelines/.vsts-vhd-builder-release-windows.yaml, .pipelines/.vsts-vhd-builder-windows.yaml, .pipelines/templates/.builder-release-template-windows-cleanup.yaml, .pipelines/templates/.builder-release-template-windows.yaml
/kind feature
1. Use the same variable names for different pipeline.
2. Add variables in pipeline variables and remove the variable group.
3. Add a new pipeline [TEST All VHDs] AKS Windows VHD Build - Msft Tenant and use microsoft tenant in it to build test images.
Fixes #
```
none
```
=> chore: add microsoft tenant and pipeline to build test windows images

e2e/windows/e2e-scenario.sh, e2e/windows/windows_vmss_template.json
Use latest image to deploy windows e2e vmss.
Fixes #
```
none
```
=> chore: use latest image to deploy windows e2e vmss

vhdbuilder/packer/install-dependencies.sh
/kind cleanup
forgot to update CNI install dependencies along with
https://github.com/Azure/AgentBaker/pull/3279
```
none
```
=> chore: update cni install dependencies

vhdbuilder/packer/list-images.ps1
/kind fix
Change format of windows repoDigests to list.
Fixes #
```
none
```
=> fix: change format of windows repoDigests to list

.pipelines/.vsts-vhd-builder-release-windows.yaml, .pipelines/.vsts-vhd-builder-windows.yaml, .pipelines/e2e-windows.yaml, .pipelines/templates/.builder-release-template-windows-cleanup.yaml, .pipelines/templates/.builder-release-template-windows.yaml, .pipelines/templates/e2e-windows-template.yaml, e2e/windows/e2e-create-windows-nodepool.sh, e2e/windows/e2e-helper.sh, e2e/windows/e2e-scenario.sh, e2e/windows/e2e-starter.sh
/kind feature
Simplify used variable groups for windows.
Fixes #
```
none
```
=> chore: simplify used variable groups for windows

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind bug
cache Windows packages for cve patches
Fixes #
```
none
```
=> fix: cache Windows packages for cve patches

.pipelines/e2e-windows.yaml, .pipelines/templates/e2e-windows-template.yaml, packer.mk
/kind feature
Use msi instead of sp in windows pipeline.
Fixes #
```
none
```
=> chore: use msi instead of sp in windows pipeline

.pipelines/.vsts-vhd-windows-automation.yaml, vhdbuilder/release-notes/autonotes/main.go, vhdbuilder/scripts/windows/automate_helpers.sh, vhdbuilder/scripts/windows/automate_release_notes.sh, vhdbuilder/scripts/windows/automate_version_bump.sh
self-create windows VHD release notes
/kind feature.
Automate the release note/image list publishing process.
Fixes #
Please don't review just yet.
```
none
```
=> chore: create windows vhd release notes automatically

vhdbuilder/packer/components.json
weekly image cve patching from Sec Pipelines
=> chore: weekly image cve patching from Sec Pipelines (kubernetes-csi/blob-csi)

vhdbuilder/packer/configure-windows-vhd.ps1
/kind fix
Avoid using WindowsServerCoreImageURL for iis image.
Fixes #
```
none
```
=> fix: avoid using WindowsServerCoreImageURL for iis image

vhdbuilder/packer/components.json
/kind chore
cache Windows gmsa webhook image. v0.7.1 supports multi-arch: amd64 and arm64.
Fixes #
```
none
```
=> chore: cache Windows gmsa webhook image

vhdbuilder/packer/components.json
weekly image cve patching from Sec Pipelines
=> chore: weekly image cve patching from Sec Pipelines (azuredisk-csi, blob-csi)

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
remove old unused Windows pause images
Fixes #
```
none
```
=> chore: remove old unused Windows pause images

pkg/agent/datamodel/sig_config.go
/kind cherry-pick
cherry-picking datamodel change
Fixes #
```
none
```
=> cherry-pick: AzureLinux SIG image config datamodel addition

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
feat: upgrade Azure File CSI driver versions in vhd image
Fixes #
```
feat: upgrade Azure File CSI driver versions in vhd image
```
=> feat: upgrade Azure File CSI driver versions in vhd image

vhdbuilder/packer/components.json
/kind cleanup
Fixes #
```
cache Cilium v1.13.5
```
=> chore: cache cilium 1.13.5

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
cache Windows Azure CNI v1.5.6.1
Fixes #
```
none
```
=> chore: cache Windows Azure CNI v1.5.6.1

.clusterfuzzlite/Dockerfile
/kind fix
remove cflite dockerfile to fix build warnings about gcr.io
Fixes #
```
none
```
=> fix: remove clusterfuzzlite dockerfile to fix build warnings

vhdbuilder/packer/components.json
/kind cleanup
Cache ip-masq-agent-v2 v0.1.8
Fixes #
```
none
```
=> chore: cache ip-masq-agent-v2 v0.1.8

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1, vhdbuilder/packer/windows-image.env, vhdbuilder/packer/write-release-notes-windows.ps1
/kind feature
Update Windows base images to 2023.09B.
- WS2019: [September 12, 2023—KB5030214 (OS Build 17763.4851)](https://support.microsoft.com/en-us/topic/september-12-2023-kb5030214-os-build-17763-4851-e6ae7551-49f4-428e-b2d4-caa73078fb06)
- WS2022: [September 12, 2023—KB5030216 (OS Build 20348.1970)](https://support.microsoft.com/en-us/topic/september-12-2023-kb5030216-os-build-20348-1970-34d4aff3-fd05-4270-b288-4ab6379c7f81)
Fixes #
```
none
```
=> chore: update Windows base images to 2023.09B #

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind feature
add function to get latest windows defender platform update.
Fixes #
```
none
```
=> chore: add function to get latest windows defender platform update

vhdbuilder/packer/components.json
/kind bug
/kind feature
Release notes -- https://github.com/Azure/prometheus-collector/blob/main/RELEASENOTES.md
- [* ] uses [conventional commit messages](https://www.conventionalcommits.org/)
**Special notes for your reviewer**: Regular monthly updates for azure monitor metrics/managed prometheus
=> Update image for azure monitor metrics/managed prometheus (09-12-2023)

e2e/windows/e2e_test.go
/kind fix
Add AKSAzureLinux in windows e2e test config, which is missed in #3427.
Fixes #
```
none
```
=> fix: add AKSAzureLinux in windows e2e test config

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
bump Windows CSE script package to v0.0.30
Fixes #
```
none
```
=> chore: bump Windows CSE script package to v0.0.30

pkg/agent/datamodel/edge_zone_sig_version.json, pkg/agent/datamodel/sig_config.go, pkg/agent/datamodel/sig_config_test.go
/kind fix
align edgezone image versions with LinuxSIGImageVersion
Fixes #
```
none
```
=> fix: align edgezone image versions with LinuxSIGImageVersion

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: back CSI driver versions for AKS 1.28
This PR also upgrades the Azure File CSI driver versions
Fixes #
```
none
```
=> chore: bake CSI driver versions for AKS 1.28

vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.4851.230914-image-list.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.4851.230914.txt, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.1970.230914-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.1970.230914.txt, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.1970.230914-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.1970.230914.txt
add release notes and image bom for AKS Windows images 2023.9B. Reference: https://github.com/Azure/AgentBaker/pull/3613
Fixes #
```
none
```
=> docs: add release notes and image bom for AKS Windows images 2023.9B

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
=> feat: containerinsights 3.1.13 release

.github/workflows/validate-windows-ut.yml, parts/windows/windowscsehelper.tests.ps1
/kind fix
fix inconsistent final output of windows ut pipeline. (ut pipeline will show success if the first ut test fails and the second ut test succeeds in the original code.)
Also update containerd url in test script to pass ut pipeline.
Fixes #
```
none
```
=> fix: fix inconsistent final output of windows ut pipeline

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind chore
bump AKS Windows CSE script package to v0.0.31
Fixes #
```
none
```
=> chore: bump AKS Windows CSE script package to v0.0.31

.pipelines/templates/.builder-release-template-windows.yaml
/kind fix
Provide prettier format for windows image bom json.
Fixes #
```
none
```
=> fix: prettier format for windows image bom json

.pipelines/.vsts-vhd-builder-release.yaml, pkg/agent/datamodel/sig_config.go, pkg/agent/datamodel/sig_config_test.go
/kind feature
Enable automatic builds of cgroupv2 AzureLinux images for the weekly VHD build and unpin the version.
```
none
```
=> feat: enable AzureLinux cgroupv2 image builds

.github/workflows/check-coverage.yml
=> chore: remove e2e coverage check to avoid timeouts

vhdbuilder/packer/install-dependencies.sh
/kind feature
Updating acr mirror to get bug fixes from overlaybd and newer acr-mirror configuration
Fixes #
```
none
```
=> chore: update mirror for artifact streaming - latest overlaybd and mirror

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Adding cns v1.4.44.5
[diff](https://github.com/Azure/azure-container-networking/compare/v1.4.44.4...v1.4.44.5)
Fixes #
```
none
```
=> chore: add cns v1.4.44.5

pkg/agent/datamodel/linux_sig_version.json
=> Revert "chore: automated PR to update VHDVersion for 202309.26.0 VHD"

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
=> feat: containerinsights 3.1.14 release

vhdbuilder/packer/components.json
/kind :bug
Regular monthly release for Azure managed Prometheus. This PR has image changes for the release.
Fixes #
```
Link to release notes is below :
https://github.com/Azure/prometheus-collector/blob/main/RELEASENOTES.md#release-10-05-2023
```
=> feat:managed prometheus monthly release (10/06/2023)

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1, vhdbuilder/packer/write-release-notes-windows.ps1
/feature
enable fixes in Windows 2023-10B
Fixes #
```
none
```
=> chore: enable fixes in Windows 2023-10B

staging/cse/windows/azurecnifunc.ps1, staging/cse/windows/azurecnifunc.tests.ps1
/kind feature
update regkey for disabling OutboundNAT on WS2022 nodes
Fixes #
```
none
```
=> chore: update regkey for disabling OutboundNAT on WS2022 nodes

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind chore
bump AKS Windows CSE script package to v0.0.32
Fixes #
```
none
```
=> chore: bump AKS Windows CSE script package to v0.0.32

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
=> chore:  cherry-pick bump AKS Windows CSE script package to v0.0.32 (#3689)

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind bug
cache signed version of cni v1.4.39.1 (unsigned) as v1.4.39.2 (signed)
Fixes #
```
none
```
=> fix: cache signed version of windows cni v2

vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.4974.231011-image-list.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.4974.231011.txt, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2031.231011-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2031.231011.txt, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2031.231011-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2031.231011.txt
add release notes for Windows images with 2023.10B. Reference the PR #3693 
Fixes #
```
none
```
=> docs: add release notes for Windows images with 2023.10B

vhdbuilder/packer/components.json
/kind cleanup
Patch addon CVE 
```
Patch CVE-2023-3978 and CVE-2023-39325
```
=> chore: patch addon

parts/linux/cloud-init/artifacts/init-aks-custom-cloud-mariner.sh, pkg/templates/templates_generated.go
Adds repo depot endpoints for mariner in air-gapped cloud environment for package updates.
Fixes #
```
none
```
=> chore: add repo depot for mariner in AGC

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
=> feat: containerinsights 3.1.15 release

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind update
bump AKS Windows CSE script package to v0.0.33.
Fixes #
```
none
```
=> chore: bump AKS Windows CSE script package to v0.0.33

vhdbuilder/release-notes/autonotes/main.go
=> fix: add mariner v2 gen1 to autonotes

vhdbuilder/packer/install-dependencies.sh
/kind chore
Bumps acr mirror for artifact streaming to fix an error in image reference parsing
Fixes #
```
none
```
=> chore: bump mirror to 0.2.3

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: upgrade CSI driver and sidecar image versions in vhd image
Fixes #
```
none
```
=> chore: upgrade CSI driver and sidecar image versions in vhd image

vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind feature
use Get-AuthenticodeSignature to validate whether binaries are signed in AKS Windows VHD test script.
Fixes #
```
none
```
=> chore: use Get-AuthenticodeSignature to validate whether binaries are signed

vhdbuilder/packer/components.json
/kind feature
Managed prometheus addon release - 10-19
Release notes here - https://github.com/Azure/prometheus-collector/blob/main/RELEASENOTES.md#release-10-19-2023
```
[none](https://github.com/Azure/prometheus-collector/blob/main/RELEASENOTES.md#release-10-19-2023)
```
=> feat: managed prometheus addon release

vhdbuilder/packer/components.json
=> chore: remove coredns versions

vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind fix
1. fix incomplete display of unsigned files.
2. fix duplicate output of the same files.
Fixes #
```
none
```
=> chore: fix incomplete display of unsigned files

vhdbuilder/packer/kube-proxy-images.json
=> chore: remove 1.24 kube-proxy versions

vhdbuilder/packer/components.json
Cleaning up old image - 6.7.5-main-09-12-2023-8fbde9ca
```
none
```
=> cleaning up old image

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
**What this PR does / why we need it**: cleanup older cns images to free up vhd
Fixes #
```
none
```
=> chore: cleanup older cns images to free up vhd

vhdbuilder/packer/components.json
=> chore: remove 1.4.43 azure cni binaries

vhdbuilder/packer/install-dependencies.sh
=> chore: fix cni versions in install deps

vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind supplement
add new k8s packages into skip map since unused win-bridge.exe is not removed yet.
Fixes #
```
none
```
=> chore: add new k8s packages into skip map

.github/workflows/validate-windows-binary-signature.yaml, vhdbuilder/packer/test/windows-binary-signature-check.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind feature
use workflow to check windows binary signature.
Fixes #
```
none
```
=> chore: use workflow to check windows binary signature

vhdbuilder/packer/install-dependencies.sh, vhdbuilder/packer/pre-install-dependencies.sh
This to revert back to the pinned LTS version to fix issues related to kernel 6.2. 
Fixes #
```
none
```
=> fix: revert to LTS kernel, from kernel 6.2

vhdbuilder/packer/install-dependencies.sh, vhdbuilder/packer/pre-install-dependencies.sh
/kind fix
Cherry pick with fix -- to kernel 5.15 LTS, from kernel 6.2 due to GPU issues
Fixes #
```
none
```
=> fix: cherry pick LTS kernel (5.15) 

vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
/kind bug
This is to fix VHD builds following base image updates
Fixes #
```
none
```
=> Cherry pick:  fix: check if systemd-timesyncd is dead, only stop+disable if not

vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
=> fix: cherry pick check systemd-timesyncd is dead, only stop+disable if not

pkg/agent/datamodel/linux_sig_version.json
=> fix: bump version after hotfix

e2e/go.mod, e2e/go.sum
=> fix: e2e go.mod/sum

.pipelines/.vsts-vhd-automation.yaml, vhdbuilder/release-notes/autonotes/main.go, vhdbuilder/scripts/automate_release_notes.sh
/kind feature
adds support for skipping updating latest versions of linux vhd artifacts during release notes generation, mainly for hotfixes
Fixes #
```
none
```
=> feat: add support for skipping latest version within linux autonotes

e2e/scenario/images.go
Updating VHD images used for agentbaker e2e testing
Need this for testing with newer VHDs -- the previous update was about 2 months ago.
Fixes #
```
none
```
=> test: update images for ab e2e testing

e2e/scenario/images.go, e2e/scenario/init.go, e2e/scenario/scenario_ubuntu2204-artifact-streaming.go
/kind test
Artifact streaming agentbaker e2e to test successful provisioning on enablement and existence of /etc/overlaybd which is only present when artifact streaming is present.
Fixes #
```
none
```
=> test: artifact streaming e2e

vhdbuilder/packer/components.json
**What type of PR is this?** NPM Version Update
**What this PR does / why we need it**: Updates the NPM Linux image version from v1.4.45.1 to v1.4.45.3 to address Ubuntu repo updates/CVEs.
Fixes https://msazure.visualstudio.com/One/_workitems/edit/25159534
**Release note**: https://github.com/Azure/azure-container-networking/releases/tag/v1.4.45.3
=> chore: update npm version

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
Updates cached CNS version in 1.4 branch to 1.4.50
Fixes #
```
none
```
=> chore: cache new CNS

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
bump AKS Windows CSE script package to v0.0.34
Fixes #
```
none
```
=> feat: bump AKS Windows CSE script package to v0.0.34

vhdbuilder/packer/list-images.ps1, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.4851.230914-image-list.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.4974.231011-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.1970.230914-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2031.231011-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.1970.230914-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2031.231011-image-list.json
/kind update
update windows sku to distro name in image-list.json
Fixes #
```
none
```
=> chore: update windows sku to distro name in image-list.json

.github/workflows/validate-windows-binary-signature.yaml, vhdbuilder/packer/test/windows-files-check.ps1
/kind feature
use workflow to check files on mooncake
Fixes #
```
none
```
=> chore: use workflow to check files on mooncake

.pipelines/.vsts-vhd-builder.yaml
only trigger linux VHD build check-in test when modifying specific paths
Fixes #
```
none
```
=> fix: trigger linux VHD check-in build  based on modified paths

.pipelines/.vsts-vhd-builder.yaml
=> chore: tune exclusion paths for linux VHD check-in test

vhdbuilder/packer/init-variables.sh, vhdbuilder/packer/windows-vhd-builder-sig.json
/kind fix
Move msi to be optional.
#3810 
Fixes #
```
none
```
=> fix: move msi to be optional

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1, vhdbuilder/packer/windows-image.env, vhdbuilder/packer/write-release-notes-windows.ps1
/kind feature
update Windows base images to 2023.11B
- WS2022: [KB5032198 (OS Build 20348.2113)](https://support.microsoft.com/en-gb/topic/november-14-2023-kb5032198-os-build-20348-2113-e3411fed-057d-402a-86fd-814124e5f26d)
- WS2019: [KB5032196 (OS Build 17763.5122)](https://support.microsoft.com/en-us/topic/november-14-2023-kb5032196-os-build-17763-5122-f613961d-cb3e-400a-a83f-024566260eaf)
Fixes #
```
none
```
=> feat: update Windows base images to 2023-11B with registry key

.pipelines/.vsts-vhd-builder-release-windows.yaml, .pipelines/.vsts-vhd-builder-windows.yaml, .pipelines/templates/.builder-release-template-windows.yaml
/kind feature
1. Fail the build if the release branch is not used in release pipeline
2. All Windows VHD build pipelines will use the same yaml .pipelines/.vsts-vhd-builder-release-windows.yaml
- Merge this PR
- Update three pipelines to use .pipelines/.vsts-vhd-builder-release-windows.yaml and add related variables
- Merge the second PR #3833
Fixes #
```
none
```
=> feat: validate windows release branch and reuse the same pipeline yaml

vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.5122.231115-image-list.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.5122.231115.txt, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2113.231115-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2113.231115.txt, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2113.231115-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2113.231115.txt
add release notes for Windows images with 2023.11B. Reference the PR #3831
Fixes #
```
none
```
=> docs: add release notes and image bom for AKS Windows images 2023.11B

e2e/scenario/images.go
=> fix: correct the URL for azurelinuxv2-arm64 image in abe2e

.pipelines/templates/.builder-release-template-windows.yaml
Add dry-run check for release pipeline to support test build.
Fixes #
```
none
```
=> chore: add dry-run check for release pipeline

vhdbuilder/packer/test/windows-files-check.ps1
Skip validation of win-bridge.exe in all k8s packages.
Fixes #
```
none
```
=> chore: skip validation of win-bridge.exe in all k8s packages

.pipelines/templates/.builder-release-template-windows.yaml, vhdbuilder/packer/list-images.ps1
rename artifact files in windows vhd pipelines.
Fixes #
```
none
```
=> chore: rename artifact files in windows vhd pipelines

pkg/agent/datamodel/sig_config.go, pkg/agent/datamodel/sig_config_test.go, pkg/agent/datamodel/types.go
/kind feature
Update sig config to support 23H2.
Fixes #
```
none
```
=> chore: update sig config to support 23H2

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/install-dependencies.sh
/kind cleanup
adds the latest CNS, CNI, and dropgz (of 1.4 family)
Fixes #
```
none
```
=> chore: update CNS, CNI, and dropgz

.pipelines/.vsts-vhd-builder-release-windows.yaml, .pipelines/.vsts-vhd-windows-automation.yaml, .pipelines/e2e-windows.yaml, e2e/windows/README.md, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/init-variables.sh, vhdbuilder/packer/windows-image.env
/kind feature
Support windows vhd build for 23H2.
Fixes #
```
none
```
=> chore: support windows vhd build for 23H2

e2e/windows/e2e-scenario.sh
/kind bug
Use the latest Windows image in Windows E2E. `/versions/latest` does not work to reference the latest version.
Fixes #
```
none
```
=> fix: use the latest Windows image in Windows E2E

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
bump AKS Windows CSE script package to v0.0.36
Fixes #
```
none
```
=> feat: bump AKS Windows CSE script package to v0.0.36

.pipelines/e2e.yaml
/kind cleanup
adds explicit path triggers for Linux AgentBaker E2E to ensure we only run it when relevant files are changed
Fixes #
```
none
```
=> chore: add path triggers for abe2e

vhdbuilder/packer/install-dependencies.sh
=> fix: gpu driver container image sha during VHD builds

.pipelines/templates/.builder-release-template-windows.yaml, vhdbuilder/packer/test/run-test.sh
/kind fix
clean up unused variables to resolve not-found issues in windows vhd build pipeline
Fixes #
```
none
```
=> fix: resolve not-found issues in windows vhd build pipeline

.github/workflows/validate-components.yml
=> fix: bump go version in validate-components workflow

vhdbuilder/release-notes/autonotes/main.go
=> fix: no longer include trivy artifacts in autonotes

pkg/agent/datamodel/sig_config.go
/kind  bug
Fixes #
```
none
```
=> freeze kata VHD to 202311.07.0

.pipelines/.vsts-vhd-builder-release-windows.yaml, packer.mk, vhdbuilder/packer/backfill-cleanup.sh, vhdbuilder/packer/cleanup.sh
/kind feature
1. Add "wait --deleted" for delete operations.
2. Add clean up for test sig image versions.
Fixes #
```
none
```
=> chore: improve windows backfill cleanup script

staging/cse/windows/debug/collect-windows-logs.ps1
/kind feature
add the output of collect-windows-logs-output into the node log
Fixes #
```
none
```
=> chore: add the output of collect-windows-logs-output into the node log

staging/cse/windows/debug/collect-windows-logs.ps1
/kind bug
check the path of nvidiaInstallLogFolder, otherwise, it will panic if the node doesn't enable gpu.
Fixes #
```
none
```
=> fix: check the path of nvidiaInstallLogFolder

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1, vhdbuilder/packer/write-release-notes-windows.ps1
/kind bug
remove invalid registry keys
Fixes #
```
none
```
=> fix: remove invalid registry keys

vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/windows-image.env
/kind feature
update Windows base images to 2023.12B
- WS2022: [KB5033118 (OS Build 20348.2159)](https://support.microsoft.com/en-gb/topic/december-12-2023-kb5033118-os-build-20348-2159-0f37ecad-fb53-4209-a05b-5e2cd0feeb98)
- WS2019: [KB5033371 (OS Build 17763.5206)](https://support.microsoft.com/en-us/topic/december-12-2023-kb5033371-os-build-17763-5206-aeb26a0a-536b-4bf8-9f5a-2749f4ba71fc)
Fixes #
```
none
```
=> feat: update Windows base images to 2023-12B

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
bump Windows CSE script package to v0.0.37
Fixes #
```
none
```
=> feat: bump Windows CSE script package to v0.0.37

vhdbuilder/packer/install-dependencies.sh
/kind bug
This newer version of acr-mirror contains newer overlaybd version that has the fix for parsing private ACR URLs appropriately.
Fixes #
```
none
```
=> bug: bump mirror to 0.2.7 for streaming bug fixes

e2e/README.md
=> fix: add details on arbitrary vhd builds in readme for e2e

e2e/windows/e2e-scenario.sh
/kind fix
remove sp for downloading windows e2e cse script package
Fixes #
```
none
```
=> fix: remove sp for downloading windows e2e cse script package

vhdbuilder/packer/configure-windows-vhd.ps1
/kind build
Pulling images in building Windows VHDs throws below confusing error 
```
azure-arm: 2024-01-10T04:02:33.8504072+00:00: Pulling images for windows server 2019-containerd
azure-arm: 2024-01-10T04:02:33.9285513+00:00: Pulling image mcr.microsoft.com/windows/servercore:ltsc2019
azure-arm: Retry-Command : The running command stopped because the preference variable "ErrorActionPreference" or common
azure-arm: parameter is set to Stop: time="2024-01-10T04:02:55Z" level=fatal msg="pulling image: rpc error: code = Unknown desc =
azure-arm: failed to pull and unpack image \"mcr.microsoft.com/windows/servercore:ltsc2019\": failed to copy: httpReadSeeker:
azure-arm: failed open: failed to do request: Get …
```
=> fix: fix the confusing logs in Windows VHD build

vhdbuilder/packer/write-release-notes-windows.ps1, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.5122.231115.txt, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.5206.231213.txt, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.5329.240110.txt
fix no reg key in WS2019
Fixes #
```
none
```
=> fix: fix no reg key in WS2019

.pipelines/e2e-windows.yaml
Use pipeline variable for windows gpu vm size so that we can change default value in pipeline variable without creating a new pull request when meeting capacity issues.
Fixes #
```
none
```
=> chore: use pipeline variable for windows gpu vm size

pkg/agent/datamodel/sig_config.go, pkg/agent/datamodel/sig_config_test.go
=> bump: update minimal image version for testing

.pipelines/templates/.builder-release-template-windows.yaml, vhdbuilder/packer/init-variables.sh, vhdbuilder/packer/windows-vhd-builder-sig.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.4851.230914-image-list.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.4974.231011-image-list.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.5122.231115-image-list.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.5206.231213-image-list.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.5329.240110-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.1970.230914-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2031.231011-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2113.231115-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2159.231213-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2227.240110-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.1970.230914-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2031.231011-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2113.231115-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2159.231213-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2227.240110-image-list.json
/kind fix
make the image version the same as file name of image bom files
Fixes #
```
none
```
=> fix: make the image version the same as file name of image bom files

vhdbuilder/packer/components.json
remove v0.0.30 and add v0.0.16-hotfix
Fixes #
```
none
```
=> feat(apiserver-network-proxy/agent): new version

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
Caches new CNS versions with a memory leak fix
Fixes #
```
none
```
=> cache CNS v1.4.52 and v1.5.17

e2e/windows/e2e-scenario.sh
/kind fix
add token for the deletion of test cse script packages
Fixes #
```
none
```
=> fix: add token for the deletion of test cse script packages

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind feature
Download du.exe tool to Windows VHD and this tool can be used for debugging AKS Windows node.
Fixes #
```
none
```
=> feat: get DU tool to Window VHD

vhdbuilder/scripts/prefetch-driver.sh
=> refactor: no-op in prefetch driver when prefetch script does not exist

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind bug
- Added cache in https://github.com/Azure/AgentBaker/pull/3988/files
- Wrong removed cache in https://github.com/Azure/AgentBaker/pull/3982/files
Fixes #
fix: restore cache for tool DU
```
none
```
=> fix: restore cache for tool DU

.pipelines/e2e-windows.yaml, .pipelines/templates/e2e-windows-template.yaml, e2e/windows/e2e-helper.sh
/kind fix
use latest cli to get default k8s version.
Fixes #
```
none
```
=> fix: use latest cli to get default k8s version

.pipelines/.vsts-vhd-builder-release-windows.yaml, packer.mk
/kind feature
add Windows VHD build auto trigger rules. After this PR is merged, we will add Windows VHD build as required for related PRs.
Fixes #
```
none
```
=> build: add Windows VHD build auto trigger rules

.pipelines/e2e-windows.yaml, parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go
/kind cleanup
1. clean up unused Get-KubeBinaries.
2. clean up unused rule in windows e2e yaml.
Fixes #
```
none
```
=> chore: clean up unused Get-KubeBinaries and unused rule in windows e2e yaml

vhdbuilder/packer/components.json
=> chore: bump policy/gk versions

pkg/agent/datamodel/linux_sig_version.json
=> chore: bump image version for 20240117

pkg/agent/datamodel/linux_sig_version.json
=> chore: cherry-pick 20240117 image bump

vhdbuilder/packer/components.json
Fixes #
from build pipeline - 
timeout 60 curl -fsSLv https://acs-mirror.azureedge.net/cri-tools/v1.29.0/binaries/crictl-v1.29.0-linux-amd64.tar.gz 
```
none
```
=> bug: upgrade crictl package for gRPC-Go vunl

vhdbuilder/packer/components.json
/kind cleanup
remove ip-masq-agent-v2 v0.1.8
Fixes #
```
none
```
=> chore: remove ip-masq-agent-v2 v0.1.8

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Fixes #
```
none
```
=> feat: containerinsights 3.1.17 release

.pipelines/templates/.builder-release-template-windows.yaml, vhdbuilder/packer/generate-vhd-publishing-info.sh, vhdbuilder/packer/init-variables.sh, vhdbuilder/packer/list-images.ps1, vhdbuilder/packer/windows-vhd-builder-sig.json
/kind fix
use correct windows image version in publishing info
Fixes #
```
none
```
=> fix: use correct windows image version in publishing info

pkg/agent/datamodel/sig_config.go, pkg/agent/datamodel/sig_config_test.go
=> chore: bump and pin CBLMariner to 202401.17.2

.pipelines/templates/.builder-release-template-windows.yaml
/kind bug
fix Windows image version in generating publishing info
```
none
```
=> fix: fix Windows image version in generating publishing info

e2e/windows/e2e-helper.sh, e2e/windows/e2e-scenario.sh, e2e/windows/e2e-starter.sh, e2e/windows/upload-cse-logs.ps1, e2e/windows/windows_vmss_template.json
/kind feature
use msi in az copy command.
Fixes #
```
none
```
=> chore: use msi in az copy command

pkg/agent/datamodel/sig_config.go, pkg/agent/datamodel/sig_config_test.go
This PR unpins azure linux cgroupv2 images, and aligns it with the latest VHD releases.
Fixes #
```
none
```
=> chore: unpin azure linux cgroupv2 image

pkg/agent/datamodel/sig_config.go, pkg/agent/datamodel/sig_config_test.go
=> chore: unpin azure linux cgroupv2 image (#4047)

vhdbuilder/packer/components.json
feat(prometheus-collector): release for 2/16
Fixes #
```
none
```
=> feat(prometheus-collector): release for 2/16

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1, vhdbuilder/packer/windows-image.env, vhdbuilder/packer/write-release-notes-windows.ps1
/kind feature
Update Windows base images to 2024.2B
- Windows 2019: [February 13, 2024—KB5034768 (OS Build 17763.5458)](https://support.microsoft.com/en-us/topic/february-13-2024-kb5034768-os-build-17763-5458-f06ecec0-23b0-4860-880b-74a2fd1b56c0)
- Windows 2022: [February 13, 2024—KB5034770 (OS Build 20348.2322))](https://support.microsoft.com/en-us/topic/february-13-2024-kb5034770-os-build-20348-2322-6ac88bee-2b14-44c3-b8b4-b185259a27f5)
Fixes #
```
none
```
=> feat: update Windows base images to 2024.2B

e2e/windows/e2e-scenario.sh
/kind fix
clean up typo in windows e2e.
Fixes #
```
none
```
=> fix: clean up typo in windows e2e

parts/windows/kuberneteswindowssetup.ps1, parts/windows/windowscsehelper.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/azurecnifunc.ps1, staging/cse/windows/calicofunc.ps1, staging/cse/windows/configfunc.ps1, staging/cse/windows/kubeletfunc.ps1, staging/cse/windows/kubernetesfunc.ps1, staging/cse/windows/nvidiagpudriverfunc.ps1
/kind feature
Support cse log for windows.
Fixes #
```
none
```
=> chore: support cse log for windows

vhdbuilder/scripts/automate_version_bump.sh
This PR reverts the Linux specific change from this PR https://github.com/Azure/AgentBaker/commit/8cadd53b3184e78e8b9d0cb6cc7fd696aa7ad9f4#diff-7d8b831d81d3404bc627633f7c8315f6c9d4ce43d68a7544aad787bca88caa4d since it broke VHD Automation
Fixes #
```
none
```
=> fix: revert branch name change to vhd automation pipeline

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
bump Windows CSE script package to v0.0.39
Fixes #
```
none
```
=> feat: bump Windows CSE script package to v0.0.39

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
remove unused azure-cns image versions.
Fixes #
```
none
```
=> chore: remove unused azure-cns image versions

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
remove unused Windows image versions and packages
Fixes #
```
none
```
=> chore: remove unused Windows image versions and packages

vhdbuilder/packer/components.json
/kind cleanup
cache ip-masq-agent-v2 v0.1.10
Fixes #
```
none
```
=> chore: cache ip-masq-agent-v2 v0.1.10

.pipelines/templates/.builder-release-template.yaml
=> chore: debug cue failures

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind bug
Update win sshd_config for CVE-2023-48795
Reference: https://github.com/cloudfoundry/stembuild/issues/25
Fixes #
```
none
```
=> fix: update win sshd_config for CVE-2023-48795

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
- regularly upgrade. cache secrets-store-csi-driver v1.4.1
- regularly upgrade. cache secrets-store-provider-azure v1.5.1
Fixes #
```
chore: cache secrets-store-provider-azure v1.5.1
```
=> chore: cache secrets-store-provider-azure v1.5.1

parts/linux/cloud-init/artifacts/aks-check-network.sh, pkg/templates/templates_generated.go
/kind feature
- Get apiserver fqdn from kubeconfig in node instead of through CLI
- Add more logging events for better readability
```
'Thu Mar 7 21:36:01 UTC 2024 - INFO: Starting network connectivity check'
'Thu Mar 7 21:36:01 UTC 2024 - SUCCESS: Successfully tested DNS resolution to management.azure.com'
'Thu Mar 7 21:36:01 UTC 2024 - SUCCESS: Successfully retrieved access token'
'Thu Mar 7 21:36:02 UTC 2024 - SUCCESS: Successfully tested management.azure.com with returned status code 200'
'Thu Mar 7 21:36:02 UTC 2024 - SUCCESS: Successfully tested DNS resolution to vmss-aks-check-networ-c0d4b9-tdoahtj3.hcp.westus2.azmk8s.io'
'Thu Mar 7 21:36:02 UTC 2024 - SUCCESS: Successfully tested apiserver …
```
=> feat: update aks-check-network script to get apiserver fqdn from kubeconfig

vhdbuilder/packer/backfill-cleanup.sh, vhdbuilder/packer/cleanup.sh
/kind fix
add wait step in cleanup.sh
Fixes #
```
none
```
=> fix: add wait step in cleanup.sh

.pipelines/e2e.yaml
/kind bug
exclude Windows test data in Linux e2e
Fixes #
```
none
```
=> chore: exclude Windows test data in Linux e2e

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
bump AKS Windows CSE script package to v0.0.40
Fixes #
```
none
```
=> chore: bump AKS Windows CSE script package to v0.0.40

CODEOWNERS
=> chore: add another team member to the code owners

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
cleanup unused cache in window vhd.
Fixes #
```
none
```
=> chore: cleanup unused cache

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
cache Windows containerinsights 3.1.18 image.
https://github.com/Azure/AgentBaker/pull/4165 is blocked by the failed Linux VHD build test.
Fixes #
```
none
```
=> feat: cache Windows containerinsights 3.1.18 image

.github/workflows/pull-request.yml
Validate whether PR is created from Azure/AgentBaker.
Fixes #
```
none
```
=> feat: validate PR source

.github/workflows/validate-pull-request-source.yml
/kind bug
Fix: validate pr source
Fixes #
```
none
```
=> fix: validate pr source

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
update npm windows to v1.5.5
Fixes #
```
none
```
=> chore: update npm windows to v1.5.5

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1, vhdbuilder/packer/windows-image.env, vhdbuilder/packer/write-release-notes-windows.ps1
/kind feature
update Windows base images to 2024.3B
- Windows 2019: [March 12, 2024—KB5035849 (OS Build 17763.5576)](https://support.microsoft.com/en-us/topic/march-12-2024-kb5035849-os-build-17763-5576-719f5f8d-51c6-43f0-a612-1c15802fed06)
- Windows 2022: [March 12, 2024—KB5035857 (OS Build 20348.2340)](https://support.microsoft.com/en-us/topic/march-12-2024-kb5035857-os-build-20348-2340-a7953024-bae2-4b1a-8fc1-74a17c68203c)
Fixes #
```
none
```
=> feat: update Windows base images to 2024.3B

e2e/windows/e2e-scenario.sh, e2e/windows/upload-cse-logs.ps1, parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go
/kind test
1. add comment for CSEResultFilePath generated by Windows CSE
2. add a test to assure that CSEResultFilePath is generated by Windows CSE
Fixes #
```
none
```
=> test: assure that CSEResultFilePath is generated by Windows CSE

.pipelines/.vsts-vhd-builder-release-windows.yaml, .pipelines/templates/.builder-release-template-windows.yaml, vhdbuilder/packer/init-variables.sh, vhdbuilder/packer/windows-vhd-builder-sig.json
/kind cleanup
clean up windows client secret used in building vhd.
Fixes #
```
none
```
=> chore: clean up windows client secret used in building vhd

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
use containerd v1.7.9 to build 23H2 VHD.
Fixes #
```
none
```
=> chore: use containerd v1.7.9 to build 23H2 VHD

e2e/scenario/base_vhd_catalog.json
=> chore: bump abe2e vhd versions

vhdbuilder/packer/components.json
/kind cleanup
Patch CVE on the addon + misc gk fixes
```
none
```
=> chore: patch addon and gk

.pipelines/templates/.builder-release-template.yaml
Fixes #
```
none
```
happy build - https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=90237000&view=results
=> feat: add retry on vhd build step

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
=> Bump cloud-node-manager 1.29.3, 1.28.8, 1.27.16, 1.26.22

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/init-variables.sh
/kind feature
enable msi for private container images.
Fixes #
```
none
```
=> chore: enable msi for private container images

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
cache azure cns v1.5.24 in windows vhd.
Fixes #
```
none
```
=> chore: cache azure cns v1.5.24 in windows vhd

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind feature
add functions to set/test Windows registry keys
Fixes #
```
none
```
=> chore: add functions to set/test Windows registry keys

vhdbuilder/packer/cleanup.sh
Change storage expiration from 12 hours to 4 hours for more aggressive clean up
Fixes #
```
none
```
=> fix: change storage expiration hours to 4hours

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1, vhdbuilder/packer/windows-image.env, vhdbuilder/packer/write-release-notes-windows.ps1
/kind feature
feat: update Windows base images to 2024.04B
- WS2019: [April 9, 2024—KB5036896 (OS Build 17763.5696)](https://support.microsoft.com/en-us/topic/april-9-2024-kb5036896-os-build-17763-5696-efb580f1-2ce4-4695-b76c-d2068a00fb92)
- WS2022: [April 9, 2024—KB5036909 (OS Build 20348.2402)](https://support.microsoft.com/en-us/topic/april-9-2024-kb5036909-os-build-20348-2402-36062ce9-f426-40c6-9fb9-ee5ab428da8c)
- WS23H2: [April 9, 2024—KB5036910 (OS Build 25398.830)](https://support.microsoft.com/en-us/topic/april-9-2024-kb5036910-os-build-25398-830-3be78748-f9a7-4ecc-abf0-822589f61d54)
Fixes #
```
none
```
=> feat: update Windows base images to 2024.04B

.pipelines/.vsts-vhd-builder-release-windows.yaml, vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/windows-image.env
/kind feature
update image version of 23H2 to 2024.4B.
- Windows 23H2: [April 9, 2024—KB5036910 (OS Build 25398.830)](https://support.microsoft.com/en-us/topic/april-9-2024-kb5036910-os-build-25398-830-3be78748-f9a7-4ecc-abf0-822589f61d54)
Fixes #
```
none
```
=> chore: update image version of 23H2 to 2024.4B

e2e/scenario/base_vhd_catalog.json
=> chore: bump abe2e default VHDs

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
cache azure cns v1.5.26 in linux and windows.
N/A
Fixes #
```
none
```
=> chore: Caching CNS v1.5.26

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: upgrade Azure Disk CSI driver versions into vhd image
this PR also removes deprecated versions
Fixes #
```
none
```
=> chore: upgrade Azure Disk CSI driver versions into vhd image

staging/cse/windows/debug/collect-windows-logs.ps1
/kind feature
This PR adds some more logging information that would be useful to have on windows
Fixes #
Tested by manually copying this script over to an AKS cluster
```
none
```
=> Add more containerd logs to collect-windows-logs.ps1

.pipelines/templates/.builder-release-template-windows.yaml, vhdbuilder/packer/backfill-cleanup.sh, vhdbuilder/packer/cleanup.sh
reuse gallery in windows vhd build.
Fixes #
```
none
```
=> chore: reuse gallery in windows vhd build

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
bump AKS Windows CSE script package to v0.0.41
Fixes #
```
none
```
=> chore: bump AKS Windows CSE script package to v0.0.41

vhdbuilder/packer/components.json
=> fix: keep prefetching azure-cns 1.5.23

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Fixes #
```
none
```
=> feat: containerinsights 3.1.20 release

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/datamodel/types.go, pkg/agent/testdata/AKSWindows2019+CustomCloud+ootcredentialprovider/CustomData, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/agent/testdata/AKSWindows2019+ootcredentialprovider/CustomData, pkg/agent/variables.go, pkg/templates/templates_generated.go, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
- CSE PR: https://github.com/Azure/AgentBaker/pull/4131
- Reuse the existing field `NotRebootWindowsNode` to control the release of code change
Fixes #
```
none
```
=> feat: bump new CSE and skip CleanupNetwork controlled by AKS toggle

vhdbuilder/packer/backfill-cleanup.sh
/kind bug
fix the wrong variable in windows VHD backfill script
Fixes #
```
none
```
=> fix: fix the wrong variable in windows VHD backfill script

e2e/windows/e2e-scenario.sh, e2e/windows/upload-cse-logs.ps1
/kind feature
run collect-windows-logs.ps1 in AgentBaker Windows E2E.
Fixes #
```
none
```
=> chore: run collect-windows-logs.ps1 in AgentBaker Windows E2E

.github/workflows/check-coverage.yml
Removes proto files from test coverage calculations
Fixes #
```
none
```
=> fix: remove proto files from coverage calculations

vhdbuilder/packer/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Bump cloud-node-manager: 1.30.0, 1.29.4, 1.28.9, 1.27.17
Fixes #
```
none
```
=> Bump cloud-node-manager

pkg/agent/toggles/types.go
=> feat: add further logging to absvc toggle resolution logic

CODEOWNERS
/kind cleanup
Adds @djsly as a new code owner
```
none
```
=> docs: adding myself (djsly) as new owner

.pipelines/templates/e2e-windows-template.yaml, e2e/windows/e2e-helper.sh
/kind fix
remove storage account key in az storage command.
Fixes #
```
none
```
=> fix: remove storage account key in az storage command

pkg/proto/nbcontract/v1/helper.go
/kind cleanup
cleanup: remove parseMinor which is no longer needed
Fixes #
```
none
```
=> cleanup: remove parseMinor which is no longer needed

e2e/windows/upload-cse-logs.ps1, staging/cse/windows/debug/collect-windows-logs.ps1
/kind feature
refine collect-windows-logs.ps1
- collect processes' info
- collect available memory
- can disable collecting containerd info
Fixes #
```
none
```
=> feat: refine collect-windows-logs.ps1

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/install-dependencies.sh
/kind feature
The pr updates windows and linux cni and dropgz versions, links:
dropgz/v0.1.4 (deploys v1.5.28 cni): https://github.com/Azure/azure-container-networking/releases/tag/dropgz%2Fv0.1.4 
dropgz/v0.0.20 (deploys v1.4.54 cni): https://github.com/Azure/azure-container-networking/releases/tag/dropgz%2Fv0.0.20 
v1.4.54: https://github.com/Azure/azure-container-networking/releases/tag/v1.4.54 
v1.5.28: https://github.com/Azure/azure-container-networking/releases/tag/v1.5.28 
Fixes #
```
none
```
=> chore: update cni and dropgz versions

staging/cse/windows/debug/collect-windows-logs.ps1, staging/cse/windows/provisioningscripts/loggenerator.ps1, staging/cse/windows/provisioningscripts/windowslogscleanup.ps1
/kind feature
feat: cse supports windows-exporter log
Fixes #
```
none
```
=> feat: cse supports windows-exporter log

parts/linux/cloud-init/artifacts/components.json
This PR removes certain calico packages after discussion with Will and Networking SIG:
https://teams.microsoft.com/l/message/19:9e8c1075b261459597d438acbff2d770@thread.skype/1715722713100?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=e121dbfd-0ec1-40ea-8af5-26075f6a731b&parentMessageId=1715722713100&teamName=Azure%20Container%20Compute&channelName=Networking%20Sig&createdTime=1715722713100
Fixes #
```
none
```
=> fix: remove certain calico packages

vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/windows-image.env
/kind feature
- WS2019: [May 14, 2024—KB5037765 (OS Build 17763.5820)](https://support.microsoft.com/en-us/topic/may-14-2024-kb5037765-os-build-17763-5820-82d1aefb-093c-4e4a-a729-cd4a829750ad)
- WS2022: [May 14, 2024—KB5037782 (OS Build 20348.2461)](https://support.microsoft.com/en-us/topic/may-14-2024-kb5037782-os-build-20348-2461-e4109269-b248-49cc-84fb-c2d0e2c86b36)
- WS23H2: [May 14, 2024—KB5037781 (OS Build 25398.887)](https://support.microsoft.com/en-us/topic/may-14-2024-kb5037781-os-build-25398-887-c10d3156-5ea0-41b7-a754-8ae1463ecc78)
Fixes #
```
none
```
=> feat: update Windows base images to 2024.05B

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
chore: remove unused CSI driver images in vhd
Fixes #
```
none
```
=> chore: remove unused CSI driver images in vhd

e2e/windows/e2e-scenario.sh
/kind feature
feat: use website url to download Windows CSE script package in e2e
Fixes #
```
none
```
=> feat: use website url to download Windows CSE script package in e2e

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/install-dependencies.sh
/kind bug
upgrade cni-plugin for security (CVE-2023-24538)
Fixes #
```
none
```
=> bug: upgrade cni-plugin package

parts/linux/cloud-init/artifacts/components.json
/kind feature
Upgrade policy/gk for AKS
Fixes #
```
none
```
=> chore: gk 3.16/policy 1.5

pkg/agent/common/gpu.go
=> cherry-pick: Update GRID driver to 535.161.08 for kernel compat issue (#4429)

e2e/windows/e2e-scenario.sh
/kind bug
refine windows e2e test
Fixes #
```
none
```
=> fix: refine windows e2e test

.pipelines/e2e-windows.yaml, staging/cse/windows/README
update Windows CSE script package doc
Fixes #
```
none
```
=> doc: update Windows CSE script package doc

.pipelines/templates/.builder-release-template.yaml, vhdbuilder/packer/convert-sig-to-classic-storage-account-blob.sh
fixes recent changes made to use the agent pool's identity for converting built VHDs from gallery image versions to classic storage account blobs
Fixes #
```
none
```
=> fix: blob conversion in VHD builds using MSI

parts/linux/cloud-init/artifacts/components.json
=> chore: update node-ca-watcher image version that is added to VHD

vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
**What type of PR is this?** Fips VHD builds were failing due to not being able to do more than one 'yes' prompt
successful testing - https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=94926063&view=results
Fixes #
```
none
```
=> bug: fix fips build

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
=> feat: container insights release 3.1.21 and win-3.1.21

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
cache Windows containerd v1.7.17
Fixes #
```
none
```
=> chore: cache Windows containerd v1.7.17

parts/linux/cloud-init/artifacts/components.json
/kind feature
Managed prometheus addon release - 05-31-2024
Fixes #
```
https://github.com/Azure/prometheus-collector/blob/main/RELEASENOTES.md#release-05-29-2024
```
=> feat: managed prometheus addon release for 05-31

.pipelines/templates/.builder-release-template-windows.yaml
/kind bug
Before #4459 is merged, we need this pr to unblock Windows VHD build. 
Fixes #
```
none
```
=> fix: unblock Windows VHD build

.gitignore
This is so that we never accidentally commit the json file manually or through automation, that can leak secrets.
Fixes #
```
none
```
=> fix: add vhd-publishing-info.json to gitignore 

parts/linux/cloud-init/artifacts/components.json
/kind cleanup
chore: cache ip-masq-agent-v2 v0.1.11
Fixes #
```
none
```
=> chore: cache ip-masq-agent-v2 v0.1.11

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud+ootcredentialprovider/CustomData, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/agent/testdata/AKSWindows2019+ootcredentialprovider/CustomData, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/windows-files-check.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind feature
bump Windows CSE script package version to v0.0.43
Fixes #
```
none
```
=> feat: bump Windows CSE script package version to v0.0.43

vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/windows-files-check.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind feature
use one ignore list for windows vhd test
Fixes #
```
none
```
=> feat: use one ignore list for windows vhd test

e2e/scenario/base_vhd_catalog.json
=> chore: update abe2e vhds

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Optionally add one or more of the following kinds if applicable:
/kind api-change
/kind flake
-->
caching new CNI/CNS image version V1.6.0
Fixes #
```
none
```
=> chore(deps): cache CNI/CNS V1.6.0

.pipelines/.vsts-vhd-builder.yaml, .pipelines/templates/.builder-release-template.yaml
modifies VHD build stage triggers to make the build more idempotent and retryable
Fixes #
```
none
```
=> fix: VHD build stage triggers for better idempotency/retry ability

vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/windows-image.env
/kind feature
cherry pick windows 2022 6ob
Fixes #
```
none
```
=> chore: cherry pick windows 2022 6ob

.pipelines/e2e-windows.yaml, e2e/windows/e2e-starter.sh
/kind test
update e2e vmsize
Fixes #
```
none
```
=> fix: update e2e vmsize

staging/cse/windows/provisioningscripts/loggenerator.ps1
/kind bug
do not collect vfp ports in loggenerator.ps1. It can cause some perf issue and memory leak for a known bug.
Fixes #
```
none
```
=> fix: do not collect vfp ports in loggenerator.ps1

vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2529.240621-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2529.240621.txt, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2529.240621-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2529.240621.txt
add Windows 2022 node image release notes for 2024-6OOB. Reference: https://github.com/Azure/AgentBaker/pull/4541
Fixes #
```
none
```
=> docs: add Windows 2022 node image release notes for 2024-6OOB

.pipelines/.vsts-vhd-scanning.yaml
feat: adding empty pipeline yaml so that I can start testing
Fixes #
```
none
```
=> feat: Add new scanning pipeline yaml

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud+ootcredentialprovider/CustomData, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/agent/testdata/AKSWindows2019+ootcredentialprovider/CustomData, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind bug
bump Windows CSE script package version to v0.0.44
Fixes #
```
none
```
=> feat: bump Windows CSE script package version to v0.0.44

.golangci.yaml, pkg/agent/baker.go, pkg/agent/bakerapi.go, pkg/agent/datamodel/types.go
Fix errors caused by a linter version upgrade
=> style: fix lint errors

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
clean up unused windows cache.
Fixes #
```
none
```
=> chore: clean up unused windows cache

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
clean up unused cni packages
Fixes #
```
none
```
=> chore: clean up unused cni packages

e2e/windows/e2e-scenario.sh, e2e/windows/upload-cse-logs.ps1
fix the issue in downloading windows e2e logs
Fixes #
```
none
```
=> fix: fix the issue in downloading windows e2e logs

.pipelines/e2e.yaml
right now we don't pass the LOCATION pipeline var into the abe2e environment when running the ADO pipeline, preventing us from running the suite in a separate location.
This PR fixes that issue.
Fixes #
```
none
```
=> fix: pass LOCATION env var to abe2es

e2e/windows/e2e-scenario.sh
/kind test
test: Windows E2E uses MSFT tenant image reference
Fixes #
```
none
```
=> test: Windows E2E uses MSFT tenant image reference

parts/linux/cloud-init/artifacts/components.json
/kind cleanup
Remove ip-masq-agent-v2 v0.1.10
Fixes #
```
none
```
=> chore: remove ip-masq-agent-v2 v0.1.10

vhdbuilder/packer/generate-vhd-publishing-info.sh, vhdbuilder/scripts/automate_version_bump.sh
This PR improves the file naming structure and changes some mapping information in publishing-info.json 
Fixes #
```
none
```
=> fix: update file names and mapping criteria for automation

e2e/vmss.go
=> fix: update default vm size for abe2es

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: upgrade CSI driver versions in vhd image
*-2 images are not used in aks-rp yet, so removed those images directly from vhd image
Fixes #
```
none
```
=> chore: upgrade CSI driver versions in vhd image

staging/cse/windows/debug/collect-windows-logs.ps1
What type of PR is this?
/kind bug
What this PR does / why we need it:
Which issue(s) this PR fixes:
Adds '--pids' option to shimdiag.exe log collection
Collects logs from hcsdiag.exe tool
Fixes #
Special notes for your reviewer:
Release note:
```
none
```
=> Add more containerd logs

e2e/windows/README.md, e2e/windows/e2e-scenario.sh
/kind fix
use different variables for vhd and e2e subscriptions
Fixes #
```
none
```
=> fix: use different variables for vhd and e2e subscriptions

.pipelines/e2e.yaml
=> fix: trigger abe2e's off master branch commits

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Fixes #
```
none
```
=> feat: remove public k8s packages

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud+ootcredentialprovider/CustomData, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/agent/testdata/AKSWindows2019+ootcredentialprovider/CustomData
/kind bug
do not override exitcode when there is no cse package
Fixes #
```
none
```
=> feat: do not override exitcode when there is no cse package

e2e/vmss.go
/kind cleanup
Adding required setting for VMSS resource that will be needed when the Deny Azure policy is applied over our SUBs
This setting was provided by Qian in an email
```
none
```
=> fix: adding required setting to comply to the deny policy

e2e/vmss.go
…635)"
This reverts commit 79b8e5a8f4bcb9841a07d84406579ea8b34cd13e.
Fixes #
```
none
```
=> Revert "fix: adding required setting to comply to the deny policy"

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
2024.7OOB needs the raw vhd to build
Fixes #
```
none
```
=> feat: remove VHD's patch for 2024.7OOB

vhdbuilder/packer/configure-windows-vhd.ps1
/kind feature
do not exit, just log
Fixes #
```
none
```
=> feat: remove exit in testing free space

vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind test
test: skip validating ReofferUpdate for the raw vhd 2024.07oob
Fixes #
```
none
```
=> test: skip validating ReofferUpdate for the raw vhd 2024.07oob

staging/cse/windows/configfunc.ps1, staging/cse/windows/kubernetesfunc.ps1
/kind feature
add log events in Windows CSE.
It still shows the event `AKS.WindowsCSE.EnableSecureTLS` when it fails in Check-APIServerConnectivity
Fixes #
```
none
```
=> feat: add log events in Windows CSE

vhdbuilder/packer/init-variables.sh
use msi instead of account key
Fixes #
```
none
```
=> feat: use msi instead of account key

vhdbuilder/packer/init-variables.sh
/kind feature
delete the failed image gallery
Fixes #
```
none
```
=> feat: delete the failed image gallery

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
update the free space size to 1gb in Windows VHDs
Fixes #
```
none
```
=> feat: update the free space size to 1gb in Windows VHDs

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind test
check Windows extensions in building VM
Fixes #
```
none
```
=> test: check Windows extensions in building VM

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/windows-vhd-builder-sig.json
/kind feature
avoid installing unexpected extensions
Fixes #
```
none
```
=> feat: add tags for skipping policy when building Windows VHD

.pipelines/templates/e2e-windows-template.yaml, e2e/windows/e2e-helper.sh, e2e/windows/e2e-starter.sh
1. Exit directly when e2e-starter.sh fails.
2. Check whether linux file already exists when cluster is already created.
3. Fix bug introduced by the change of csepackage folder name.
Fixes #
```
none
```
=> feat: modify windows AgentBaker E2E pipeline

vhdbuilder/release-notes/autonotes/main.go, vhdbuilder/scripts/windows/automate_helpers.sh, vhdbuilder/scripts/windows/automate_version_bump.sh
1. support 23H2 in windows automation pipeline.
2. fix some existing bugs.
Fixes #
```
none
```
=> chore: improve windows automation pipeline

vhdbuilder/packer/configure-windows-vhd.ps1
/kind bug
add logs and retry logic for windows vhd building
Fixes #
```
none
```
=> fix: add logs and retry logic for windows vhd building

.pipelines/templates/.builder-release-template-windows.yaml, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
disable validating ReofferUpdate when pausing Windows SecuritPatch
Fixes #
```
none
```
=> feat: disable validating ReofferUpdate when pausing Windows SecuritPatch

vhdbuilder/packer/vhd-scanning.sh
=> feat: add configuration required for private endpoint connection to scanning resources

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
1. Clear public k8s packages for caching private k8s packages
1. Update free space size
Fixes #
```
none
```
=> feat: build RAW VHD with fixes

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
update Kubernetes Windows packages
Fixes #
```
none
```
=> chore: update Kubernetes Windows packages

e2e/config/vhd.go, e2e/scenario_test.go, parts/linux/cloud-init/artifacts/cse_helpers.sh
/kind test
Adds e2e tests for containerd and runc versions
```
none
```
=> bug Make sure ubuntu 18.04 has the right version of containerd on it.

vhdbuilder/packer/configure-windows-vhd.ps1
/kind bug
Disable port exclusion change in 23H2 for a known Windows bug.
Fixes #
```
none
```
=> fix: disable port exclusion change in 23H2

vhdbuilder/packer/configure-windows-vhd.ps1
/kind fix
disable port exclusion in 2024 7b.
Fixes #
```
none
```
=> fix: disable port exclusion in 2024 7b

parts/linux/cloud-init/artifacts/components.json
=> feat: managed prometheus addon release for 07-22

.github/renovate.json
adds common labeling to renovate PRs to help with PR filtering
Fixes #
```
none
```
=> chore: add common label to renovate PRs

e2e/vmss.go
we always want vm/cse logs uploaded after agentbaker e2e runs to be able to confirm behavior expectations
Fixes #
```
none
```
=> fix(abe2e): always upload vm/cse logs

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1, vhdbuilder/packer/write-release-notes-windows.ps1
/kind fix
cherry pick free space change
Fixes #
```
none
```
=> fix: cherry pick free space change

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
cache Windows containerd v1.7.20
Fixes #
```
none
```
=> chore: cache Windows containerd v1.7.20

parts/linux/cloud-init/artifacts/components.json
VHD is getting full, removing old versions of cni 
Fixes #
```
none
```
=> cleanup: cleanup cni-dropgz versions

parts/linux/cloud-init/artifacts/components.json
/kind cleanup 
cleaning up old prometheus versions
Fixes #
```
none
```
=> cleanup: cleanup old prometheus version

vhdbuilder/packer/list-images.sh
simplifies list-images.sh
Fixes #
```
none
```
=> chore: further simplify list-images.sh

vhdbuilder/packer/write-release-notes-windows.ps1
/kind feature
Update logs in windows release notes.
Fixes #
```
none
```
=> feat: update logs in windows release notes

staging/cse/windows/azurecnifunc.ps1, staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Default.OverlayDualStack.conflist, staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Expect.DisableOutboundNat.conflist, staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Expect.DisableWinDSR.conflist, staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Expect.EnableWinDSR.conflist, staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Expect.Overlay.conflist, staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Expect.OverlayDualStack.conflist, staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Expect.Swift.DisableOutboundNAT.conflist, staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Expect.Swift.conflist, staging/cse/windows/calicofunc.ps1
/kind feature
block 32526 to wireserver on Windows nodes
Fixes #
```
none
```
=> feat: block 32526 to wireserver on Windows nodes

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
chore: Bump cloud-node-manager v1.30.5, v1.29.9, v1.28.11 and v1.27.19
Fixes #
```
none
```
=> chore: Bump cloud-node-manager v1.30.5, v1.29.9, v1.28.11 and v1.27.19

parts/linux/cloud-init/artifacts/components.json
/kind cleanup
cache ip-masq-agent v0.1.13
Fixes #
```
none
```
=> chore: cache ip-masq-agent v0.1.13

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
chore: restore iis cache in 23H2
Revert from https://github.com/Azure/AgentBaker/pull/4818
Fixes #
```
none
```
=> chore: restore iis cache in 23H2

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Overlooked adding cni installer image on windows in this PR: https://github.com/Azure/AgentBaker/pull/4690
This PR adds that image.
Fixes #
See previous PR linked above for details on cni 1.5.32.
=> chore: cache cni 1.5.32 in windows

vhdbuilder/cacher/cmd/cacher/main.go, vhdbuilder/cacher/pkg/env/env.go, vhdbuilder/cacher/pkg/exec/exec.go, vhdbuilder/cacher/pkg/exec/types.go, vhdbuilder/cacher/pkg/installers/containerimage/installer.go, vhdbuilder/cacher/pkg/installers/containerimage/pull.go, vhdbuilder/cacher/pkg/model/model.go, vhdbuilder/cacher/testdata/components.json
=> feat: cleanup + further testing

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud+ootcredentialprovider/CustomData, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/agent/testdata/AKSWindows2019+ootcredentialprovider/CustomData, staging/cse/windows/README, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
bump Windows CSE script package to v0.0.46
Fixes #
```
none
```
=> feat: bump Windows CSE script package to v0.0.46

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
update containerd 1.6 to v1.6.35
Fixes #
```
none
```
=> chore: update containerd 1.6 to v1.6.35

parts/linux/cloud-init/artifacts/components.json
=> chore: bump node-ca-watcher tag

staging/cse/windows/debug/collect-windows-logs.ps1
/kind feature
Enable crt by default for collecting containerd information. Give an option to disable since it costs time in some cases.
Fixes #
```
none
```
=> chore: refine collect-windows-logs.ps1 to enable crt by default

staging/cse/windows/provisioningscripts/loggenerator.ps1
/kind feature
add windowsnodereset.log in loggenerator.ps1
Fixes #
```
none
```
=> chore: add windowsnodereset.log in loggenerator.ps1

vhdbuilder/packer/configure-windows-vhd.ps1
/kind bug
fix the issue in parsing Windows defender version
Fixes #
```
none
```
=> fix: fix the issue in parsing Windows defender version

vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind bug
fix xml issue in win vhd test
Fixes #
```
none
```
=> fix: fix xml issue in win vhd test

staging/cse/windows/configfunc.ps1, staging/cse/windows/configfunc.tests.ps1
This reverts commit 5fa5e6f2a37fea1d5cf5469ebbba3bb9d013286e.
/kind feature
We need to hold on the UDP port change before more validation. Revert it to avoid releasing this change with new CSE script packages.
Fixes #
```
none
```
=> Revert "fix: exclude udp ports on Windows (#4886)"

vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
chore: remove du.zip cache in VHD because it was expanded to folder `DU`.
Fixes #
```
none
```
=> chore: remove du.zip cache in VHD because it was expanded to folder DU

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
clean up old Windows images
Fixes #
```
none
```
=> cleanup: clean up old Windows images

parts/linux/cloud-init/artifacts/components.json
=> cleanup: remove busybox container image from cache

vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.6293.240911-image-list.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.6293.240911.txt, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2700.240911-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2700.240911.txt, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2700.240911-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.2700.240911.txt, vhdbuilder/release-notes/AKSWindows/23H2-gen2/25398.1128.240911-image-list.json, vhdbuilder/release-notes/AKSWindows/23H2-gen2/25398.1128.240911.txt, vhdbuilder/release-notes/AKSWindows/23H2/25398.1128.240911-image-list.json, vhdbuilder/release-notes/AKSWindows/23H2/25398.1128.240911.txt
Add windows image release notes for new AKS Windows images with 2024-09B. Reference: #4921.
Fixes #
```
none
```
=> docs: update windows release notes for 2024-09B

vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/windows-image.env
/kind feature
update WS23H2 base image to 2024.9B
Fixes #
```
none
```
=> feat: update WS23H2 base image to 2024.9B

parts/linux/cloud-init/artifacts/components.json
bump add on and gatekeeper 3.17 image 
/kind cleanup
to bump the add on and gatekeeper version
Fixes #
```
none
```
=> chore: bump addon and gatekeeper 3.17

vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
clean up outdated cache in windows vhd.
Fixes #
```
none
```
=> chore: clean up outdated cache in windows vhd

parts/linux/cloud-init/artifacts/components.json
/kind feature
chore: upgrade Blob CSI driver on vhd image
Fixes #
```
none
```
=> chore: upgrade Blob CSI driver on vhd image

vhdbuilder/packer/init-variables.sh
This PR does some ugly but required refactoring to ensure all new Gen2 Image definitions created are tagged with DiskControllerType=NVMe
Gen1/Arm64/CVM do not need that tag, only Gen2 does.
Successful VHD build with new AzLinux v3 SKUs: https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=103962751&view=results
Fixes #
```
none
```
=> chore: add nvme disk controller type for gen2 images

pkg/agent/datamodel/sig_config.go, pkg/agent/datamodel/sig_config_test.go
/kind
- This PR pins the Azure Linux V3 images to 202409.23.0 in order to test with these images
VHD Test run - https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=104281319&view=results
Fixes #
```
none
```
=> chore: pin AzureLinux V3 images to 202409.23.0

e2e/windows/e2e-helper.sh, e2e/windows/e2e-starter.sh
/kind fix
upload new linux file when it's outdated after autoupgrade of linux node.
Fixes #
```
none
```
=> fix: upload new linux file when it's outdated after autoupgrade of linux node

e2e/scenario_test.go
=> fix: update expected containerd version for 2204 e2e

parts/linux/cloud-init/artifacts/components.json
/kind bug
Fixing the typo
Fixes #
```
none
```
=> chore: swap the latestVersion and previousLatestVersion for azure-cni

CODEOWNERS, parts/linux/cloud-init/artifacts/aks-log-collector.sh
Augment the collected logs from aks-log-collector to also collect the NVIDIA gpu  install logs
Fixes #
```
none
```
=> Augment globs to collect nvidia gpu logs

pkg/agent/bakerapi_test.go
=> fix: bakerapi unit tests after pinning AzLinux V3 SKUs

vhdbuilder/packer/windows-image.env
/kind feature
Update Windows base images to 2024-10B
- _[Pending] Windows 2019: [October 8, 2024—KB5044277 (OS Build 17763.6414)](https://support.microsoft.com/en-us/topic/october-8-2024-kb5044277-os-build-17763-6414-edccc872-2f4e-4ac6-b224-50ca8f1acd4f)_
- Windows 2022: [October 8, 2024—KB5044281 (OS Build 20348.2762)](https://support.microsoft.com/en-us/topic/october-8-2024-kb5044281-os-build-20348-2762-e063059c-9122-4324-86e8-4f6f3383a20a)
- Windows 23H2: [October 8, 2024—KB5044288 (OS Build 25398.1189)](https://support.microsoft.com/en-us/topic/october-8-2024-kb5044288-os-build-25398-1189-07468931-d90b-4566-9865-f435fe4c3ea8)
Fixes #
**Special notes for your …
=> feat: bump windows base image 2024-10B for Windows 2022 23H2

.pipelines/.vsts-vhd-builder.yaml
/kind bug
This PR fixes some syntax errors in the pipeline that were causing the PR Gate to fail
=> fix: PR gate pipeline failures

vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/windows-image.env
/kind feature
Based on https://github.com/Azure/AgentBaker/pull/5039 to install Windows 10b patch for Windows2019 base image - [October 8, 2024—KB5044277 (OS Build 17763.6414)](https://support.microsoft.com/en-us/topic/october-8-2024-kb5044277-os-build-17763-6414-edccc872-2f4e-4ac6-b224-50ca8f1acd4f)
Fixes #
```
none
```
=> feat: install Windows 10b patch for Windows2019 base image

.pipelines/templates/.builder-release-template-windows.yaml, vhdbuilder/packer/init-variables.sh, vhdbuilder/packer/list-images.ps1, vhdbuilder/packer/windows-vhd-builder-sig.json
/kind feature
Refine Windows image version. Read the image version from image-bom.json instead from windows-image.env since sometimes we update security patch without updating base image version.
Fixes #
```
none
```
=> feat: refine Windows image version

vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.6414.241010-image-list.json, vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.6414.241010.txt
Add windows image release notes for new AKS Windows images with 2024-10B. Reference: https://github.com/Azure/AgentBaker/pull/5051
Fixes #
```
none
```
=> docs: update windows release notes to 2024-10B for Window 2019

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: upgrade Azure Disk and File CSI driver versions in vhd image
Fixes #
```
none
```
=> chore: upgrade Azure Disk and File CSI driver versions in vhd image

CODEOWNERS
Adding Tim and Artur as reviewers 
Fixes #
```
none
```
=> [ci skip] adding Tim and Artur as owner

.pipelines/.vsts-vhd-builder-release.yaml, pkg/agent/datamodel/sig_config.go, pkg/agent/datamodel/sig_config_test.go
/kind cleanup
- This PR unpins the AzureLinux V3 images and builds these images by default
- Test VHD run - https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=105835730&view=results
Fixes #
```
none
```
=> chore: unpin the AzureLinux V3 images, and build them by default

.pipelines/scripts/verify_shell.sh
=> fix: ignore spec tests for shellcheck

e2e/aks_model.go, e2e/cluster.go
**What this PR does / why we need it**: We should add the cache rules only when creating the ACR
Fixes #
```
none
```
=> fix: put creating cache rules when creating acr 

node-bootstrapper/parser/templates/cse_cmd.sh.gtpl
=> fix: imds restriction contract fields in cse template

parts/linux/cloud-init/artifacts/components.json
/kind update
This PR updates the version in components.json to be in sync with the version used in CSE, so that the CUDA driver version that is cached in the VHD is what's used.  
Fixes #
```
none
```
=> Sync CUDA driver version between CSE and VHD, by updating to the same version

.github/workflows/go-test.yml, Makefile, node-bootstrapper/parser/templates/cse_cmd.sh.gtpl
=> chore: add node-bootstrapper to make test target

parts/linux/cloud-init/artifacts/components.json
=> sync(dev): Fix 24.04 ARM64 pipeline (#5181)

.pipelines/.vsts-vhd-builder.yaml, .pipelines/e2e.yaml, parts/linux/cloud-init/artifacts/components.json
=>  chore: add dev branch to required PR workflow triggers

node-bootstrapper/parser/parser.go
=> cherry-pick: fix: append existing env variables to provision cmd

.github/renovate.json
/kind bug
This fixes the Renovate config so that aks-gpu container images (CUDA and GRID) get automated updates for major, minor, patch, and "pre-release" updates of the container image.
Fixes #
```
none
```
=> Renovate config fix for AKS GPU CUDA and GRID updates (all types of versions)

.github/renovate.json
/kind bug
This fixes the Renovate config so that aks-gpu container images (CUDA and GRID) get automated updates for major, minor, patch, and "pre-release" updates of the container image.
Fixes #
```
none
```
=> Cherry pick Renovate config fix for AKS GPU CUDA and GRID updates

.pipelines/.vsts-vhd-automation.yaml, .pipelines/templates/.set-image-version-template.yaml, vhdbuilder/scripts/automate_helpers.sh, vhdbuilder/scripts/automate_release_notes.sh, vhdbuilder/scripts/automate_version_bump.sh
example PRs generated with the new changes:
https://github.com/Azure/AgentBaker/pull/5212
https://github.com/Azure/AgentBaker/pull/5213
Fixes #
```
none
```
=> feat: allow configuring base/target branch for automatic release notes and image bump PRs

vhdbuilder/packer/trivy-scan.sh
=> fix: add retry for initial trivy scan to handle 429's from ghcr on DB update

aks-node-controller/app.go, aks-node-controller/app_test.go, aks-node-controller/go.mod, aks-node-controller/go.sum
=> chore: add tests for aks-node-controller provision wait

parts/linux/cloud-init/artifacts/components.json
/kind cve
bump cri-tools/crictl to 1.3.1
Fixes #
```
none
```
=> bump to latest cri-tools 1.31.1 for CVE fixes

.pipelines/.vsts-vhd-automation.yaml
=> chore: set default automation target branch to dev

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/cve
Need this cve fix in for this week's VHD release.
Fixes #
```
none
```
=> cherry-pick: cve fix kube-proxy patch version bump

parts/linux/cloud-init/artifacts/components.json
/kind bug
Optionally add one or more of the following kinds if applicable:
/kind api-change
/kind flake
-->
Fixes #
```
none
```
=> fix components.json for aks 1.27.101

parts/linux/cloud-init/artifacts/components.json
/cve
The initial cve fix pr did not cover k8s binaries.
Fixes #
```
none
```
=> cherry-pick: patch version bump for k8s binaries

e2e/config/config.go
=> chore: set default abe2e branch selector to dev

parts/linux/cloud-init/artifacts/cse_benchmark_functions.sh
=> try not to fail if performance data file is not set

aks-node-controller/parser/parser_test.go, pkg/proto/aksnodeconfig/v1/helper_test.go
/kind test
Renamed leading `aKS` to `aks` for camel case in 2 test files
Fixes #
```
none
```
=> chore: rename leading aKS to aks in tests

vhdbuilder/packer/init-variables.sh
=> fix: packer vnet RG name resolution for prod builds

vhdbuilder/packer/init-variables.sh
=> cherry-pick: packer vnet RG name resolution for prod builds

.pipelines/.vsts-vhd-automation.yaml
=>  feat: use aks-node-assistant for VHD automation

.pipelines/templates/.builder-release-template-windows.yaml
/kind fix
add start and end symbols for source branch validation.
Fixes #
```
none
```
=> fix: add start and end symbols for source branch validation

vhdbuilder/packer/windows-image.env
/kind feature
Update WS2022 gen2 base image to 2024-11B. Reference #5260 
Fixes #
```
none
```
=> feat: Update WS2022 gen2 base image to 2024-11B

vhdbuilder/packer/windows-image.env
/kind feature
Update WS2022 gen2 base image to 2024-11B (#5291)
Fixes #
```
none
```
=> feat: Update WS2022 gen2 base image to 2024-11B (#5291)

vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2849.241119-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2849.241119.txt
add release notes for WS2022 gen2 with 2024.11B
Fixes #
```
none
```
=> docs: add release notes for WS2022 gen2 with 2024.11B

vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2849.241119-image-list.json, vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.2849.241119.txt
add release notes for WS2022 gen2 with 2024.11B
Fixes #
```
none
```
=> docs: add release notes for WS2022 gen2 with 2024.11B (#5308)

.pipelines/.vsts-vhd-builder-release-windows.yaml, .pipelines/e2e-windows.yaml, vhdbuilder/packer/configure-windows-vhd.ps1, vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind bug
Sets registry keys to enable greater certificate validation.  
https://msrc.microsoft.com/update-guide/vulnerability/CVE-2013-3900
```
none
```
=> bug: cve-2013-3900

.pipelines/.vsts-vhd-automation.yaml
cherry-picking #5287 
Fixes #
```
none
```
=> cherry-pick: use aks-node-assistant for VHD automation

vhdbuilder/scripts/automate_helpers.sh
correctly set git config to reference aks-node-assistant service account within automation helpers
Fixes #
```
none
```
=> fix: git config for VHD automation

.pipelines/.vsts-vhd-automation.yaml, .pipelines/templates/.set-image-version-template.yaml, vhdbuilder/scripts/automate_helpers.sh, vhdbuilder/scripts/automate_release_notes.sh, vhdbuilder/scripts/automate_version_bump.sh
=> cherry-pick: VHD automation fixes and enhancements

vhdbuilder/packer/post-install-dependencies.sh, vhdbuilder/packer/pre-install-dependencies.sh
This PR updates certain packages in CVM VHDs that have CVEs and are out of SLA.
Fixes #
```
none
```
=> fix: updates packages for cvm (#5328)

e2e/config/config.go, e2e/kube.go, e2e/node_config.go, e2e/pod.go, e2e/scenario_helpers_test.go, e2e/scenario_node_controller_test.go, e2e/scenario_test.go, e2e/validation.go, e2e/validators.go
/kind test
Update GPU scenarios to spawn a pod utilizing a real NVidia GPU.
=> test: run real GPU workload

vhdbuilder/packer/pre-install-dependencies.sh
/kind vuln
This PR adds python3-urllib3 to the list of packages manually installed for CVMs.
This PR will result in the new package version being installed on the VHDs.
=> fix: python package vuln

vhdbuilder/packer/pre-install-dependencies.sh
=> fix: python package vuln (#5357)

vhdbuilder/packer/pre-install-dependencies.sh
/kind vuln
This PR manually updates / installs packages known to have vulnerabilities.
CVEs present in confidential machines.
=> fix: confidential machine CVEs for December

parts/linux/cloud-init/artifacts/components.json
Cherry-pick of https://github.com/Azure/AgentBaker/pull/5365 
This is to update the aks-gpu container images for fixes. 
Fixes #
```
none
```
=> chore(deps): update aks/aks-gpu-grid docker tag to v535.161.08-20241204190836 

vhdbuilder/packer/init-variables.sh
=> cherry-pick: refactor: packer vnet resolution

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Optionally add one or more of the following kinds if applicable:
Fixes #
```
none
```
=> chore: update Kubernetes versions add binary for 1.29.11,1.30.7,1.31.3

CODEOWNERS
/chore 
This adds me as a codeowner in AgentBaker.
=> chore: add myself as a codeowner

packer.mk
=> fix: always specify agent identity ID when logging into azure for linux

packer.mk
…ux (#5408)
Fixes #
```
none
```
=> cherry-pick: fix: always specify agent identity ID when logging into azure for linux

vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/windows-image.env
/kind security
Cherry picks https://github.com/Azure/AgentBaker/pull/5409 for release during CCOA
```
none
```
=> security: Windows update to 2024-12b (#5409)

.github/workflows/auto-update.yml, .github/workflows/buf.yaml, .github/workflows/cflite_batch.yaml, .github/workflows/cflite_build.yaml, .github/workflows/cflite_prune.yaml, .github/workflows/check-coverage.yml, .github/workflows/codeql-analysis.yml, .github/workflows/generate-kubelet-flags.yaml, .github/workflows/go-test.yml, .github/workflows/golangci-lint.yml, .github/workflows/shellcheck.yml, .github/workflows/shellspec.yaml, .github/workflows/validate-components.yml, .github/workflows/validate-image-version.yml, .github/workflows/validate-pull-request-source.yml
/kind cleanup
Removing CodeQL reported Warning, by using a fixed version for the base image of the actions and using the non deprecated version of CodeQL
Fixes #
```
none
```
=> fixing codeql warnings

vhdbuilder/scripts/automate_version_bump.sh
/kind chore
Fixes issue bumping image version when the branch being run doesn't have the current image version.
Fixes #
```
none
```
=> chore: use jq to bump image version rather than string replace

.pipelines/templates/.builder-release-template-windows.yaml
/kind chore
sets the MODE variable in the "Getting Shared Access Signature URI" step in the pipeline. This variable is now used as part of the az authentication code, but is not being set in this one step.
```
none
```
=> bug: set mode

.pipelines/templates/.builder-release-template-windows.yaml
/kind chore
To enable windows VHD release
```
none
```
=> chore: cherry pick "mode in pipeline master"

.pipelines/.vsts-vhd-automation.yaml, .pipelines/.vsts-vhd-windows-automation.yaml, .pipelines/templates/.generate-github-token.yaml, vhdbuilder/scripts/automate_helpers.sh, vhdbuilder/scripts/automate_release_notes.sh, vhdbuilder/scripts/automate_version_bump.sh, vhdbuilder/scripts/windows/automate_helpers.sh, vhdbuilder/scripts/windows/automate_release_notes.sh, vhdbuilder/scripts/windows/automate_version_bump.sh
/kind chore
Cherry picks two commits from dev branch so we can build new Linux and Windows VHDs from master
Fixes #
```
none
```
=> feat: use github app for VHD automation tasks (#5379)

.pipelines/.vsts-vhd-builder-release.yaml, .pipelines/.vsts-vhd-builder.yaml, .pipelines/templates/e2e-template.yaml, e2e/config/config.go
=> chore: add dedicated pipeline variable for E2E location

vhdbuilder/owners.txt
This PR deletes an owners file with stale owners + given that we have proper reviewer enforcement in Github, we don't need an owners file.
Fixes #
```
none
```
=> cleanup: delete stale owners file

vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/run-test.sh
/kind chore
* Update .NET patch version for WS2019
* Prints out error messages from windows test script if the test script fails.
* Quote variables in VHD test script
```
none
```
=> chore: Update .NET patch version for Windows

vhdbuilder/packer/generate-windows-vhd-configuration.ps1, vhdbuilder/packer/test/run-test.sh
/kind chore
cherry pick of most of 97ff23a106a4f374cbdd28d76d2d5e49669ecd73 to fix ws2019 build - didn't want to cherry pick lots of quote changes.
```
none
```
=> chore: Update .NET patch version for Windows (#5445)

parts/linux/cloud-init/artifacts/components.json
=> chore: bump oras version

.pipelines/.vsts-vhd-builder-release.yaml, .pipelines/.vsts-vhd-builder.yaml, .pipelines/templates/e2e-template.yaml, e2e/config/config.go
Manually cherry pick - https://dev.azure.com/_public/_MsalSignedIn?itemType=VariableGroups&view=VariableGroupView&variableGroupId=5685&path=AgentBaker%20E2E to align pipeline vars
Fixes #
```
none
```
=> chore: add dedicated pipeline variable for E2E location (#5447)

parts/linux/cloud-init/artifacts/components.json
/kind cleanup
new addon version
Fixes #
```
none
```
=> chore: new addon version

parts/linux/cloud-init/artifacts/components.json
=> chore: new addon version (#5467)

.github/renovate.json, parts/linux/cloud-init/artifacts/components.json
/kind cleanup
Caches cilium agent from containernetworking subdirectory within MCR
Fixes #
```
none
```
=> ci: update cilium agent MCR usage to containernetworking

vhdbuilder/packer/cleanup.sh
/kind cleanup
Increasing the Garbage Collection timeout for SIG images to account for longer delays during releases. 
Fixes #
```
none
```
=> increase timeout for SIG image garbage collection

vhdbuilder/packer/cleanup.sh
/kind cherry-pick
Cherry pick of https://github.com/Azure/AgentBaker/pull/5372 so that VHD releases are less likely to be garbage collected before the safefly process finishes.
Fixes #
```
none
```
=> chore: increase vhd expiration

e2e/config/vhd.go, e2e/scenario_test.go, vhdbuilder/packer/README.md
=> bug: fix VHD 2204 to use correct distro 2204

parts/linux/cloud-init/artifacts/components.json
/kind feature 
this PR updates the runc version to 1.2 for ubuntu24.04 
Fixes #30630437
this is to update runc library to 1.2 for ubuntu24.04 to start VHD building so that when it is merged, we can build VHD and to test in the PR pipeline.
=> feat: use runc 1.2 for ubuntu24.04

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: upgrade Azure Disk CSI driver versions in vhd image
Fixes #
```
chore: upgrade Azure Disk CSI driver versions in vhd image
```
=> chore: upgrade Azure Disk CSI driver versions in vhd image

pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line105.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line112.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line119.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line127.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line134.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line141.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line149.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line156.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line163.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line170.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line18.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line215.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line222.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line26.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line308.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line322.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line33.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line40.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line47.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line54.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line62.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line70.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line77.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line9.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line91.sh, pkg/agent/testdata/AKSUbuntu2404+CustomLinuxOSConfigUlimit/line98.sh
/kind test
add the testData generated for the new baker_test scenario ubuntu 2404
=> test: add testData for new baker test scenario ubuntu 2404

parts/linux/cloud-init/artifacts/components.json
/kind cleanup
CVE patches
```
none
```
=> chore: new gk version

e2e/scenario_test.go, e2e/validation.go, e2e/validators.go
/kind chore
This PR improves logging in e2e tests to log stdout and stderr when a command run on a node fails
Fixes #
```
none
```
=> chore: log stderr and stdout in some e2e tests

pkg/agent/datamodel/linux_sig_version.json
=> Revert "chore: automated PR to update VHDVersion for 202501.05.0 VHD"

pkg/agent/datamodel/types.go
=> fix: add nolint stylecheck to ebpf consts

.pipelines/templates/.builder-release-template-windows.yaml
/kind chore
Hopefully fixes windows pipeline
Fixes #
```
none
```
=> fix pipeline step

.pipelines/.vsts-vhd-builder-release-windows.yaml, .pipelines/e2e-windows.yaml
/kind chore
Some pipeline triggers were missing for files used in the windows e2e pipelines. Fixed this.
Fixes #
```
none
```
=> fix pipeline triggers missing

.pipelines/.vsts-vhd-builder.yaml, .pipelines/templates/.build-and-test-windows-vhd-template.yaml, .pipelines/templates/e2e-template.yaml, e2e/config/config.go
=> fix: use variable group for static abe2e pipeline vars

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Fixes #
```
none
```
=> chore: add binaries for 1.31.5, 1.30.8, 1.29.12

e2e/scenario_test.go
/kind test
Add a new E2E test Test_Ubuntu2404_ScriptlessInstaller
Fixes #
```
none
```
=> Test: Add a new E2E test Test_Ubuntu2404_ScriptlessInstaller

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
- cve fix to bump secrets-store-csi-driver cache version to v1.4.7
- cve fix to bump secrets-store-provider-azure cache version to v1.6.2
```
- cve fix to bump secrets-store-csi-driver cache version to v1.4.7
- cve fix to bump secrets-store-provider-azure cache version to v1.6.2
```
=> chore: cache secrets-store-csi-driver v1.4.7

parts/linux/cloud-init/artifacts/components.json
/kind feature
chore: upgrade Azure Blob CSI driver versions in vhd image
Fixes #
```
none
```
=> chore: upgrade Azure Blob CSI driver versions in vhd image

e2e/types.go
/kind test
Remove a deprecated variable `scriptless` from e2e test
Fixes #
```
none
```
=> test: remove a deprecated variable from e2e test

parts/linux/cloud-init/artifacts/components.json
=> chore: bump cni-plugins to 1.6.2 for CVE fixes

.pipelines/templates/.build-and-test-windows-vhd-template.yaml
/kind chore
Makes the windows VHD e2e tests not run when the VHD build fails
Fixes #
```
none
```
=> chore: fix condition in windows pipeline

parts/linux/cloud-init/artifacts/components.json
/kind chore
bump moby-containerd
Fixes #
```
none
```
=> chore: bump moby-containerd version for azure linux

vhdbuilder/release-notes/autonotes/main.go
- Adds support for including AzureLinuxV3 Gen2 TrustedLaunch release notes during official releases
Fixes #
```
none
```
=> feat: add AzureLinuxV3 Gen2 TrustedLaunch to autonotes

parts/linux/cloud-init/artifacts/components.json
=> chore: cleanup cached binaries and container images for disk space

aks-node-controller/parser/helper.go, aks-node-controller/parser/helper_test.go
/kind bug
Remove unnecessary encoding from systctl content. Validated in a local e2e scenario test.
Fixes #
```
none
```
=> fix: remove encoding from scriptless systctl content

e2e/scenario_test.go
/kind test
add e2e test for Test_Ubuntu2204_ContainerdURL_Scriptless
Fixes #
```
none
```
=> add e2e test for Test_Ubuntu2204_ContainerdURL_Scriptless

e2e/scenario_test.go
/kind test
add e2e test for Test_AzureLinuxV2_Scriptless
Fixes #
```
none
```
=> add e2e test for Test_AzureLinuxV2_Scriptless

parts/linux/cloud-init/artifacts/components.json
/kind cleanup
fixes CVEs in 1.5
Fixes #
```
none
```
=> chore: bump cns 1.5

e2e/exec.go, e2e/validation.go, e2e/validators.go, e2e/vmss.go
/kind cleanup
Improves the API to exec scripts on VMs during e2e tests slightly.
Fixes #
```
none
```
=> chore: cleanup args to e2e exec calls

aks-node-controller/Makefile
/kind test
We changed the base branch. Update the linter task to reflect it.
Fixes #
```
none
```
=> test: Fix linter for breaking change in .proto files

.github/renovate.json
/kind feature
To further automate the process of merging these PRs. If the tests pass, then it should be good to automerge.
Fixes #
```
none
```
=> Automerge GPU container image PRs

e2e/scenario_test.go
/kind test
Add e2e test Test_AzureLinuxV2_ARM64_Scriptless
Fixes #
```
none
```
=> Add e2e test Test_AzureLinuxV2_ARM64_Scriptless

parts/linux/cloud-init/artifacts/components.json, vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Fixes #
```
none
```
=> chore 🔧: cache 1.27.102 and 1.28.100 for LTS program

.github/renovate.json
/kind feature
add owners for kubernetes-node and kube-proxy
Fixes #
```
none
```
=> feat: add owners for kubernetes-node and kube-proxy

vhdbuilder/packer/windows/components_json_helpers.tests.ps1
/chore add unit tests
Adds some unit tests that were requested in a prev PR review, but the PR auto-merged before I did them.
Fixes #
```
none
```
=> more windows tests

.pipelines/.vsts-vhd-builder-release-windows.yaml
/chore 
Missed adding the windows e2e test pipeline trigger now it uses components.json
Fixes #
```
none
```
=> chore: add pipeline trigger

e2e/scenario_test.go
/kind test
Add e2e scriptless test for azurelinuxv2 message of the day
Fixes #
```
none
```
=> Add e2e scriptless test for azurelinuxv2 message of the day

e2e/cluster.go, e2e/kube.go
=> test(e2e): optimize cluster credential extraction

parts/linux/cloud-init/artifacts/components.json
/kind feature
chore: upgrade CSI sidecar image versions
Fixes #
```
none
```
=> chore: upgrade CSI sidecar image versions

.pipelines/.vsts-vhd-builder-release.yaml
turning off 2404 cvm to fix build issue
Fixes #
```
none
```
=> chore: turn off 2404 CVM builds to investigate failures

e2e/scenario_test.go
/kind test
Fixes #
```
none
```
=> Add e2e scriptless test for MarinerV2 chrony restarts

CODEOWNERS
add myself to agentbaker owners 
```
none
```
=> chore: add myself to agentbaker owners

.pipelines/.vsts-vhd-builder-pr-windows.yaml, .pipelines/.vsts-vhd-builder-release-windows.yaml, .pipelines/.vsts-vhd-builder.yaml, .pipelines/e2e-windows.yaml, .pipelines/e2e.yaml
/kind chore
Reduces number of pipline runs as changes to windows e2e tests (at a high level) won't cause linux builds, and vice versa. Also fixes a bug in the windows PR pipeline yaml.
Fixes #
```
none
```
=> chore: add exclusions for scenario_test files

e2e/scenario_test.go
/kind test
Add scriptless e2e test for Test_Ubuntu2204_ChronyRestarts
Fixes #
```
none
```
=> Add scriptless e2e test for Test_Ubuntu2204_ChronyRestarts

.github/renovate.json, parts/linux/cloud-init/artifacts/components.json
/kind chore
Adds windows to renovate
Fixes #
```
none
```
=> chore: add some windows thigns for renovate

.github/workflows/validate-windows-binary-signature.yaml, vhdbuilder/packer/test/windows-files-check.ps1, vhdbuilder/packer/windows/windows-vhd-configuration.ps1
/kind fix
fixes a bug in the windows check pipeline. Also remove a long-running check that's now done in a different pipeline.
Fixes #
```
none
```
=> chore: fix a bug in windows files check pipeline

.pipelines/.vsts-vhd-builder-pr-windows.yaml, .pipelines/.vsts-vhd-builder-release-windows.yaml, .pipelines/templates/.build-and-test-windows-vhd-template.yaml, .pipelines/templates/.build-and-test-windows-vhds-template.yaml
/kind chore
Windows keeps running out of VM quota to build. I noticed that Linux uses a different SKU, so am switching to that.
Fixes #
```
none
```
=> chore: change windows build vm size to match linux

.github/renovate.json, parts/common/components.json
/kind chore
Add more windows containers to renovate.
Fixes #
```
none
```
=> chore: more windows renovate changes

.github/README-RENOVATE.md, .github/renovate.json, .github/workflows/validate-components.yml, .github/workflows/validate-windows-binary-signature.yaml, .pipelines/.vsts-vhd-builder-pr-windows.yaml, .pipelines/e2e-windows.yaml, .pipelines/e2e.yaml, .pipelines/templates/.builder-release-template.yaml, Makefile, e2e/scenario_helpers_test.go, packer.mk, pkg/vhdbuilder/datamodel/component_configs.go, vhdbuilder/packer/test/run-pretest.sh, vhdbuilder/packer/vhd-image-builder-arm64-gen2.json, vhdbuilder/packer/vhd-image-builder-base.json, vhdbuilder/packer/vhd-image-builder-cvm.json, vhdbuilder/packer/vhd-image-builder-mariner-arm64.json, vhdbuilder/packer/vhd-image-builder-mariner.json, vhdbuilder/packer/windows/components_json_helpers.tests.ps1, vhdbuilder/packer/windows/windows-vhd-builder-sig.json, vhdbuilder/packer/windows/windows-vhd-configuration.ps1, vhdbuilder/prefetch/internal/components/types.go
/kind chore
components.json moved directories recently and we setup a symlink. However, this symlink means our pipelines won't trigger properly, so this PR changes all references to components.json.
Fixes #
```
none
```
=> chore: rename path to components.json

vhdbuilder/packer/windows/windows_settings.json
/kind fix
Sets reg keys in prep for 2025-2b
Fixes #
```
none
```
=> fix: add 2025-2b reg keys

.github/renovate.json
=> add cloud provider assignees and reviewers

e2e/scenario_test.go
/kind test
Add scriptless e2e test for Test_Ubuntu2204_ArtifactStreaming_Scriptless
Fixes #
```
none
```
=> Add scriptless e2e test for Test_Ubuntu2204_ArtifactStreaming_Scriptless

vhdbuilder/packer/convert-sig-to-classic-storage-account-blob.sh
Chore
Fixes issues found during the windows 2025-2B release.
Fixes #
```
none
```
=> chore: fix deploy script

.github/renovate.json
/kind feature
feat: add owners of addon-resizer and cluster-proportional-autoscaler
Fixes #
```
none
```
=> feat: add owners of addon-resizer and cluster-proportional-autoscaler

e2e/cluster.go, e2e/config/azure.go, e2e/exec.go, e2e/pod.go, e2e/scenario_helpers_test.go, e2e/types.go, e2e/validation.go, e2e/validators.go, e2e/vmss.go
/kind test
Minor e2e tweaks and fixes.
=> test: E2E Tweaks

vhdbuilder/packer/install-dependencies.sh
/kind bug
Fixes #
```
none
```
=> fix: install missing udev rules for v6 vm sku

.github/renovate.json
/kind feature
Add azure-npm owners and disable minor version update as requested by owners
Fixes #
```
none
```
=> add azure-npm owners and disable minor version update

e2e/scenario_test.go
/kind test
Add e2e scriptless test for Ubuntu2204 IMDSRestrictionFilterTable
Fixes #
```
none
```
=> Add e2e scriptless test for Ubuntu2204 IMDSRestrictionFilterTable

.github/renovate.json
/kind bug
fixing the syntax in Renovate about assignees and reviewers
Fixes #
```
none
```
=> bug: fixing the syntax in Renovate about assignees and reviewers

.github/renovate.json
/kind cleanup
cleaning up more renovate configs
- Group component aks/aks-node-ca-watcher under Node SIG ownership
- For CNI/CNS: set reviewers the corresponding reviewer teams and assigness to individuals.  Github doesn't support setting assignees to a team.
- move coredns to an existing group
- fix syntax of csi related components
Fixes #
```
none
```
=> cleaning up more renovate configs

.pipelines/templates/.build-and-test-windows-vhds-template.yaml, vhdbuilder/packer/windows/configure-windows-vhd.ps1
/kind chore
* logs file sizes for downloaded binaries
* enables pipeline cleanup
Fixes #
```
none
```
=> chore: log file sizes that are cached on the windows VHD

.github/renovate.json, parts/common/components.json
=> chore: update windows-gsma-webhook to 0.12.1-2

parts/common/components.json
/kind feature
chore: upgrade Azure Disk CSI driver
Fixes #
```
none
```
=> chore: upgrade Azure Disk CSI driver versions

Makefile, vhdbuilder/packer/windows/components-test.json, vhdbuilder/packer/windows/components_json_helpers.tests.ps1
/kind chore
uses a test components.json for test cases. This will let us upgrade versions in the prod components.json without breaking unit tests.
Fixes #
```
none
```
=> chore: use a test components-json for testing

vhdbuilder/packer/convert-sig-to-classic-storage-account-blob.sh, vhdbuilder/packer/init-variables.sh
=> don't use azcopy-preview

.pipelines/.vsts-vhd-builder-pr-windows.yaml
/kind chore
Windows builds and e2e tests were not running when core windows files were changed.
Fixes #
```
none
```
=> chore: add missing trigger

.pipelines/templates/.builder-release-template-windows.yaml, README.md, e2e/scenario_win_test.go, e2e/validators.go, vhdbuilder/packer/windows/configure-windows-vhd.ps1
/kind chore
Add e2e tests to check windows VHDs are running the right version of windows. I'm constantly paranoid about this.
Fixes #
```
none
```
=> Add e2e tests to check the windows VHD is running the right version of Windows

.pipelines/templates/.build-and-test-windows-vhds-template.yaml, .pipelines/templates/.builder-release-template-windows.yaml, packer.mk, vhdbuilder/packer/init-variables.sh
/kind chore
Fixes the prod VHD build. Turned out to be the wrong subscription id.
Fixes #
```
none
```
=> chore: fix prod VHD build

vhdbuilder/packer/test/windows-vhd-content-test.ps1, vhdbuilder/packer/windows/configure-windows-vhd.ps1
/kind chore
I keep seeing curl fail with an exit code of 23. It's intermittent. Trying to get more logs as to why.
Fixes #
```
none
```
=> better logging

parts/common/components.json
/kind feature
Managed prometheus release
https://github.com/Azure/prometheus-collector/blob/main/RELEASENOTES.md#release-tbd
```
=> feat: managed prometheus addon release Feb 2025

vhdbuilder/packer/windows/configure-windows-vhd.ps1
/kind bug
fixes the windows install script to use the right last exit code
Fixes #
```
none
```
=> fix: use the right last exit code

.pipelines/.vsts-vhd-builder.yaml
=> test: augment linux VHD PR check-in gate with AzureLinux V2 + V3 builds

parts/common/components.json
/kind chore
Update the pause container to match what is in rp.
Fixes #
```
none
```
=> upgrade windows pause container

schemas/windows_settings.cue, vhdbuilder/packer/windows/components-test.json, vhdbuilder/packer/windows/components_json_helpers.tests.ps1, vhdbuilder/packer/windows/windows_settings.json
/kind cleanup
* WS2019 no longer exists. That was the docker version of WS2019. Now it's all containerd.
* the components-test.json file was too similar to components.json and people thought they had to update it. Hopefully this makes it different enough that no-one makes that mistake again.
Fixes #
```
none
```
=> chore: remove unnecessary things from windows_settings and a test file.

.github/renovate.json
/kind feature
enable cilium's pre-release update in renovate
Fixes #
```
none
```
=> enable cilium's pre-release update in renovate

e2e/scenario_test.go, e2e/types.go
=> test(e2e): add tags to scriptless scenarios

e2e/scenario_test.go
/kind test
Merge e2e test MarinerV2 CNI with ChronyRestart
Fixes #
```
none
```
=> Merge e2e test MarinerV2 CNI with ChronyRestart

parts/common/components.json
Remove old 1.27 and add new 1.32 cloud node manager cache.
Keep the previous latest version 1.28.13 1.29.11 1.30.7 and 1.31.1 which are still used in production and introduce new 1.29.13, 1.30.10, 1.31.4 and 1.32.3
Fixes #
```
none
```
=> bump cloud node manager and credential provider

parts/common/components.json
This PR updates image versions of coredns, CPA and addon-resizer for VHD caching. 
AKS clusters on 1.32+ versions use - 
mcr.microsoft.com/oss/v2/kubernetes/autoscaler/cluster-proportional-autoscaler:v1.9.0-1
mcr.microsoft.com/oss/v2/kubernetes/coredns:v1.11.3-6
AKS clusters on 1.24+ versions (but <1.32) use - 
mcr.microsoft.com/oss/v2/kubernetes/coredns:v1.9.4-5
AKS clusters on 1.27+ versions (but <1.32) use - 
mcr.microsoft.com/oss/v2/kubernetes/autoscaler/cluster-proportional-autoscaler:v1.8.11-5
All AKS clusters use - 
mcr.microsoft.com/oss/v2/kubernetes/autoscaler/addon-resizer:v1.8.23-2
Fixes #
```
none
```
=> Update image versions of coredns, CPA and addon-resizer for VHD caching

e2e/config/azure.go, e2e/config/vhd.go
/kind cleanup
I'm debugging a VHD issue with the e2e tests with Windows, so am adding logging to help figure out what's going on. Figure that some of the logging will be useful for the next developer debugging issues, so here is some of it.
Fixes #
```
none
```
=> chore: add logging for vhd lookup for e2e tests

parts/common/components.json, vhdbuilder/packer/windows/components-test.json, vhdbuilder/prefetch/internal/containerimage/testdata/prefetch.sh
/kind cleanup
Fixes #
```
none
```
=> chore: rm dropgz

.github/renovate.json, parts/common/components.json
/kind feature
enable minor version update for moby-runc, moby-containerd. Update moby-runc version to 1.2.5
Fixes #
```
none
```
=> enable minor version update for moby-runc, moby-containerd. Update moby-runc version to 1.2.5

.pipelines/.vsts-vhd-builder-release.yaml, pkg/agent/bakerapi_test.go, pkg/agent/datamodel/sig_config.go, pkg/agent/datamodel/sig_config_test.go, pkg/agent/datamodel/types.go, pkg/agent/datamodel/types_test.go, vhdbuilder/release-notes/autonotes/main.go
This PR changes 2404 Trusted Launch VHDs to be built weekly, along with adding SIG Config and Autonotes support.
Fixes #
```
none
```
=> chore: add 2404 trusted launch sig configs, autonotes

vhdbuilder/scripts/automate_generate_version.sh
=> fix: ensure single unique image_version within VHD automation

e2e/config/azure.go
/kind chore
Fixes #
```
none
```
=> chore: log version rather than memory address

.pipelines/.vsts-vhd-builder-release.yaml
Enable cvm azlinux build
/kind feature
need to support CVM
Fixes #
```
none
```
=> enable cvm azlinuxV3

vhdbuilder/packer/test/linux-vhd-content-test.sh, vhdbuilder/packer/test/windows-files-check.ps1
/kind test
This PR validates the packages installed in VHD can be downloadable from Azure China Cloud if their URL can be passed from control plane, and give hints to the next action when their proxy path is not defined the Azure China Cloud proxy server.
Fixes #
```
none
```
=> test: validate package URL root path for Azure China cloud

.pipelines/templates/.builder-release-template-windows.yaml
/kind chore
Bug in the windows prod VHD pipeline causing the prod VHDs not to be build properly.
It was basically shell quoting on a command that set a pipeline variable.
Fixes #
```
none
```
=> chore: fix issue in windows VHD prod pipeline

.pipelines/templates/.builder-release-template-windows.yaml
A pipeline test step got disabled accidently. This PR enables it again.
Fixes #
```
none
```
=> chore: enable step

parts/common/components.json
/kind bug
Reverting back to 535 drivers since 550 driver doesn't install the `nvidia-gridd` systemd unit and it has licensing issues.
The license status is set to `Unlicensed`, post provisioning.
Till we get confirmation from Nvidia/HPC team, we plan to back to the older version to limit impact.
Fixes #
```
none
```
=> Switch GPU GRID driver to 535

.github/renovate.json
/kind bug
Remove auto-merge for AKS GPU GRID driver container images given the frequency of issues encountered. Older container images with higher minor versions will be present in MCR but should not be consumed. 
Fixes #
```
none
```
=> Renovate: remove automerge for aks-gpu-grid drivers

parts/common/components.json
=> Switch GPU GRID driver to 535 (#6043)

.pipelines/.vsts-vhd-windows-automation.yaml, e2e/go.mod, vhdbuilder/lister/go.mod, vhdbuilder/release-notes/autonotes/main.go
This PR fixes the windows release notes pipeline:
* The previous code downloaded all release notes in parallel
* However, the az command version seems to have changed and it now crashes when called in parallel
* So this PR removes the parallelism from the go program.
I also had to disable release notes for WS2025 because they caused the pipeline to fail, I'm not sure why, but we don't need them yet anyway.
And I refactored the Windows VHD automation pipeline to be similar in structure to the Linux VHD Automation pipeline and have two independent stages that are conditional on the pipeline parameters rather than steps in the single stage that is conditional on the parameters. And my IDE automatically …
=> regression: fix release notes windows pipeline

parts/common/components.json, vhdbuilder/packer/windows/components-test.json
=> removing addon-token-adapter from being cached

parts/common/components.json
/kind cleanup
cache ip-masq-agent-v2 version v0.1.15-2 to address CVEs
Fixes #
```
none
```
=> chore: cache oss/v2/azure/ip-masq-agent-v2:v0.1.15-2

vhdbuilder/packer/trivy-scan.sh, vhdbuilder/packer/vhd-scanning.sh
/kind feature
fail vhd-scanning.sh when there is a cve. We could also make it a separate step within the pipeline.
Feel free to merge this pr at your preference.
```
none
```
=> feat: fail vhd-scanning on cve check

vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind test
This test validates binaries, normally the endpoint binary of the container, in the Windows container image are signed correctly.
Fixes #
```
none
```
=> test: validate windows image binary signature

e2e/e2e-local.sh, e2e/go.mod, e2e/go.sum, parts/common/components.json
=> chore: bump crictl-tools 1.32.0

.pipelines/.vsts-vhd-builder-pr-windows.yaml, .pipelines/.vsts-vhd-builder.yaml, .pipelines/e2e-windows.yaml, .pipelines/e2e.yaml, e2e/go.mod, e2e/go.sum
/kind chore
e2e tests were not being triggered when the root go.mod file changes. This caused a broken go.mod/go.sum getting into master. This PR fixes that - both the trigger and fixes go.sum.
Fixes #
```
none
```
=> chore: fix go mod

.github/workflows/tidy.yaml
=> feat: add auto-tidy workflow to support dependabot PRs

e2e/node_config.go, e2e/scenario_test.go, e2e/validators.go, pkg/agent/utils.go
/kind bug
Revert this PR where the E2E was failing once it was added: https://github.com/Azure/AgentBaker/pull/6094. This failing E2E is blocking PR merges for multiple PRs on master and is delaying the merge of a major fix. 
Fixes #
```
none
```
=> Revert e2e config: update e2e config to match evictionHard default value to 100Mi (#6094)

vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind chore
In a PR run, I noticed the run failed because write-log was not defined. So this PR makes sure it's defined so we can print the log message.
Fixes #
```
none
```
=> chore: predefine write-log

parts/common/components.json
/kind feature
chore: upgrade blob csi driver to v1.24.9
v1.24.7 is current version used in aks, we upgrade to v1.24.9 directly this time.
Fixes #
```
none
```
=> chore: upgrade blob csi driver to v1.24.9

parts/common/components.json
Add latest coredns image 1.12.1-1 to VHD used in 1.33 AKS clusters. This has the fix for reverse DNS lookup failure seen in 1.12.0. 
There are no CVEs - 
```
trivy image --ignore-unfixed mcr.microsoft.com/oss/v2/kubernetes/coredns:v1.12.1-1
2025-04-02T16:33:14-07:00       INFO    [vuln] Vulnerability scanning is enabled
2025-04-02T16:33:14-07:00       INFO    [secret] Secret scanning is enabled
2025-04-02T16:33:14-07:00       INFO    [secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2025-04-02T16:33:14-07:00       INFO    [secret] Please see also https://aquasecurity.github.io/trivy/dev/docs/scanner/secret#recommendation for faster secret detection
2025-04-02T16:33:16-07:00       INFO    Detected OS …
```
=> Add latest coredns image 1.12.1-1 to VHD used in 1.33 AKS clusters

.github/workflows/shellspec.yaml, Makefile, spec/parts/linux/cloud-init/artifacts/cse_helpers_spec.sh
/kind test
Now we can see a brief report for shellspec in the Github Action outputs
Fixes #
```
none
```
=> test: add shellspec report

.github/dependabot.yml, .github/release.yaml
=> feat: add GitHub release config file and modify dependabot labels

pkg/agent/datamodel/types.go, pkg/agent/datamodel/types_test.go
feature
This PR has types and tests for the new feature 'localdns'. 
Fixes #
```
none
```
=> Add types and tests for localdns

.github/release.yaml
chore: exclude PRs labeled with ignore-for-release from release notes
Fixes #
```
none
```
=> chore: exclude PRs labeled with ignore-for-release from release notes

vhdbuilder/packer/windows/windows_settings.json
add new reg key for 4B windows image building
Fixes #
```
none
```
=> Add 2025 4B non-sec keys

parts/common/components.json
This PR updates the revision version of coredns image 1.11.3 used in 1.32 AKS clusters from v1.11.3-6 to v1.11.3-7. This has the fix new CVE in openssl. Release notes are here - https://github.com/aks-lts/coredns/releases/tag/v1.11.3-7. 
There are no CVEs. 
```
trivy image --ignore-unfixed mcr.microsoft.com/oss/v2/kubernetes/coredns:v1.11.3-7
2025-04-11T14:45:49-07:00       INFO    [vuln] Vulnerability scanning is enabled
2025-04-11T14:45:49-07:00       INFO    [secret] Secret scanning is enabled
2025-04-11T14:45:49-07:00       INFO    [secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2025-04-11T14:45:49-07:00       INFO    [secret] Please see also https://aquasecurity.github.io/trivy/dev/docs/scanner/secret#recommendati …
```
=> Update coredns image v1.11.3-6 revision to v1.11.3-7

parts/linux/cloud-init/artifacts/aks-log-collector.sh
replacing @joshwright10's PR: #6187, addressing #6181  
Fixes #
```
none
```
=> fix: syntax errors in aks-log-collector.sh

staging/cse/windows/configfunc.ps1, staging/cse/windows/containerdfunc.ps1, vhdbuilder/packer/windows/configure-windows-vhd.ps1
/kind bug
tar is not a powershell command, and when we hit tar error it cannot be caught by try/catch logic, and the following scripts continues on the failed tar command, leading to undetermined error during CSE or VHD building.
Fix this by check the exit code of tar and explicitly throw error to let try/catch logic catch and block the further operations.
Fixes #
tested the folllowing code snippt
```ps
try{
$credentialproviderbinaryPackage="azure-acr-credential-provider-windows-amd64-v1.30.8.tar.gz"
tar -xzf $credentialproviderbinaryPackage -C c:\
if ($LASTEXITCODE -ne 0	) {
throw "Failed to extract the '$credentialproviderbinaryPackage' archive."
}
} catch {
Write-Host $_
}
```
- stop …
=> CSE: throw tar error on failure

.github/README-RENOVATE.md, README.md, spec/README.md
Update readme image and path.
Move the shellspec readme to under that folder
Fixes #
```
none
```
=> update readme image and path

.pipelines/.vsts-vhd-windows-automation.yaml
=> Adding back windows 2025 release note

.github/renovate.json
/kind feature
Adding back GRID GPU to renovate and enabling automerge for it, since GRID driver issues have been fixed for the most part (except kernel 6.11 compatibility).
Fixes #
```
none
```
=> Add GRID GPU container image to renovate and automerging it

parts/common/components.json
/kind feature
chore: upgrade Azure CSI driver versions
Fixes #
```
none
```
=> chore: upgrade Azure CSI driver versions

vhdbuilder/packer/test/run-test.sh, vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
/kind bug
This PR changes the timeout assigned to the retry command to enable Ubuntu Pro.
Timeout setting was causing retry issues.
=> fix: ua attach timeout bug

vhdbuilder/packer/test/linux-vhd-content-test.sh
/kind bug
This PR installs packages needed during the testing step for 18.04
This PR fixes the broken testing step for 18.04 due to missing packages
=> fix: download dialog and readline-common for 18.04

.github/PULL_REQUEST_TEMPLATE.md
The repo configuration enforces GPG signed commits, which is easy to forget for sporadic contributors. Add a note about this to the PR template.
```
none
```
=> chore: Add item about GPG signing to PR checklist

parts/common/components.json
/kind bug
Updating GRID driver version to 550.144.06-20250512225043
Fixes #
```
none
```
=> Bump GRID driver to 550.144.06-20250512225043

parts/common/components.json
- Removed non-windows-hpc images from Windows VHD
- Added new images 1.33.0 1.32.5 1.31.6 1.30.12 and 1.29.15
Fixes #
```
none
```
=> update cloud node manager images 1.33.0 1.32.5 1.31.6 1.30.12 and 1.29.15

.pipelines/scripts/e2e_run.sh, .pipelines/templates/.build-and-test-windows-vhds-template.yaml
/kind chore
Two fixes for windows pipelines:
* Use the right version of the VHD when using URL overrides
* Use the SIG_GALLERY_NAME when specified instead of GALLERY_NAME
Fixes #
```
none
```
=> Windows pipeline fixes

.pipelines/e2e-windows.yaml, .pipelines/e2e.yaml, .pipelines/scripts/e2e_run.sh
=> fix(e2e): fix unbound variables in e2e_run.sh

.github/renovate.json, parts/common/components.json
Fixes to servercore versioning string, and copy correct updates from forked repo as we need them.
From testing in forked repo:
Fixes #
```
none
```
=> change versioning regexp

.pipelines/.vsts-vhd-builder-release-windows.yaml
Adds SKIP_E2E_TESTS pipeline var to windows VHD build pipeline.
Fixes #
```
none
```
=> Add pipeline variable to skip e2e tests in windows VHD build pipeline

.pipelines/templates/.builder-release-template-windows.yaml
/kind bug
Prod releases are failing because the DRY_RUN variable isn't in scope for the ADO Task condition.
Fixes #
```
none
```
=> bug: Dry run variable is empty in prod releases

parts/windows/kuberneteswindowssetup.ps1, pkg/agent/testdata/AKSWindows2019+CustomCloud+ootcredentialprovider/CustomData, pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData, pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData, pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData, pkg/agent/testdata/AKSWindows2019+K8S116/CustomData, pkg/agent/testdata/AKSWindows2019+K8S117/CustomData, pkg/agent/testdata/AKSWindows2019+K8S118/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData, pkg/agent/testdata/AKSWindows2019+K8S119/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData, pkg/agent/testdata/AKSWindows2019+KubeletServingCertificateRotation/CustomData, pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData, pkg/agent/testdata/AKSWindows2019+SecurityProfile/CustomData, pkg/agent/testdata/AKSWindows2019+ootcredentialprovider/CustomData, staging/cse/windows/azurecnifunc.ps1, staging/cse/windows/azurecnifunc.tests.ps1, staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Expect.EnableIMDSRestriction.conflist
/kind feature
This PR add code support for Windows node IMDS restriction feature.
Fixes #
```
Update Windows CSE to support IMDS restriction for Windows node.
```
=> feat: support IMDS restriction on Windows node

.pipelines/templates/.builder-release-template.yaml
=> chore: explicitly specify latest kata UVM artifact built from master branch

.github/workflows/shellspec.yaml, spec/shellspec.Dockerfile
=> Fixing CSSC Warnings by using internal authenticated ACR

vhdbuilder/packer/install-dependencies.sh
/kind bug
/kind chore
This updates acr mirror to 0.2.12, which contains a fix I had made for acr-nodemon systemd unit definition.
Fixes #
```
none
```
=> fix: update acr mirror to 0.2.12 with fix for systemd unit

.pipelines/templates/.builder-release-template-windows.yaml, vhdbuilder/packer/test/run-test.sh, vhdbuilder/packer/test/windows-vhd-content-test.ps1, vhdbuilder/packer/windows/configure-windows-vhd.ps1
This is used for windows container base image cache validation through test pipeline running
Fixes #
```
none
```
=> Add the logic for cotainer base iamge cache validation

parts/common/components.json
/kind feature
chore: update Blob CSI driver versions
Fixes #
```
none
```
=> chore: update Blob CSI driver versions

.pipelines/templates/.builder-release-template.yaml
/kind bug
The kata-sign pipeline has a parameter called `isTestBuild`. If it is set, it signs the `igvm-measurement.cose` file with a dummy certification instead of an actual Microsoft approved signing task. However, AgentBaker will still pick it up as a production signed file, because the pipeline build is still coming from the master branch (only the signing certificate changes).
[PR 12355015](https://dev.azure.com/msazure/CloudNativeCompute/_git/aks-rp/pullrequest/12355015) sets a warning when the pipeline runs with the `isTestBuild` parameter as `True` and thus is able to run the pipeline but outputs as a `PartiallySucceeded` build. Which, with this PR, will not be picked up for release.
**Which issue(s) this PR …
=> feat: setting allowPartiallySucceededBuilds for kata to false.

parts/common/components.json
/kind feature
Upgrade policy addon images
Fixes #
```
none
```
=> chore: policy addon 1.12.1

.pipelines/scripts/windows_build_vhd.sh
this is based on the https://github.com/microsoft/onnxruntime/pull/15986
Fixes #
```
none
```
=> Fix the extra trailing quote

vhdbuilder/packer/windows/windows_settings.json
=> Add the 2025 6B reg key

parts/common/components.json
/kind feature
**What this PR does / why we need it**: 
We have created, tested and published coredns images v1.12.0-2, v1.11.3-8 and v1.9.4-6 to MCR using the new Dalec framework. The new Dalec framework publish the images to MCR under oss/v2 path. These images have CVE fixes. 
Fixes # CVEs
```
none
```
=> Update coredns images from MCR oss/v2

vhdbuilder/packer/windows/windows_settings.json
=> Add 23H2 reg key

e2e/cluster.go
/kind test
To fix this error.
```
RESPONSE 400: 400 Bad Request
                ERROR CODE: InvalidParameter
                --------------------------------------------------------------------------------
                {
                  "code": "InvalidParameter",
                  "details": null,
                  "message": "Only weekly schedule is supported for control plane upgrade maintenance configuration: default.",
                  "subcode": ""
                }
```
I guess it's some policy changed. With this change, I can run it successfully in local.
Fixes #
```
none
```
=> update maintenance configuration from monthly to weekly

.github/renovate.json
Add reviewers and allow automatic PRs for all new prod versions of ama-metrics images
Fixes #
```
none
```
=> ci: update renovate rules for ama-metrics addon images

.github/renovate.json, parts/common/components.json
/kind feature
Onboard RPM packages moby-containerd, containerd2 (for Ubuntu 24.04) and Kubernetes-cri-tools to Renovate for auto-upgrade.
Tested in a fork repo. Need to merge to master and double check.
Fixes #
```
none
```
=> feat: onboard RPM packages to Renovate

.github/renovate.json
/kind cleanup
Remove extra comma
Fixes #
```
none
```
=> remove extra comma

parts/common/components.json
/kind bug
Need to add this back because we are breaking down the default.current into all SKUs as they are using different versions of cri-tools.
AB e2e tests passed.
Fixes #
```
none
```
=> add crictl for marinerkata

staging/cse/windows/containerdfunc.ps1, staging/cse/windows/containerdfunc.tests.ps1
instead of choosing containerd template based on k8s + windows version, the logic now is refactored to use containerd runtime version, which is more accurate.
plus the choice of containerd runtime has been made elsewhere. it is redundant to make the choice again in the template selection and it opens a place for more bugs.
Fixes #
```
none
```
=> cleanup: refactor template selection for containerd.

parts/common/components.json
/kind feature
Fixes #
```
none
```
=> chore: update kube-proxy and kubernetes-node versions to latest

staging/cse/windows/azurecnifunc.tests.ps1
/kind chore
Previous PR had to be merged before writing unit tests.
Fixes #
```
none
```
=> Add unit tests for windows IP lookups

parts/common/components.json
chore(deps): bump aks-secure-tls-bootstrap-client to v0.1.0-alpha.7
Fixes #
```
none
```
=> chore(deps): bump aks-secure-tls-bootstrap-client to v0.1.0-alpha.7

parts/common/components.json
/kind feature
chore: upgrade Blob CSI driver versions in vhd image
Fixes #
```
none
```
=> chore: upgrade Blob CSI driver versions in vhd image

e2e/vmss.go
/kind feature
Fixes #
```
none
```
=> chore: Log the Azure portal Storage link in e2es

parts/common/components.json
/kind bug
Update RPM registry to the correct ones for cri-tools.
Tested in a fork.
Fixes #
```
none
```
=> update rpm registry to the correct ones for Azurelinux/Mariner

vhdbuilder/packer/windows/windows_settings.json
=> bump ws 2025

parts/common/components.json
bump aks-secure-tls-bootstrap-client to v0.1.0-alpha.8: https://github.com/Azure/aks-secure-tls-bootstrap/releases/tag/client%2Fv0.1.0-alpha.8
Fixes #
```
none
```
=> chore(deps): bump aks-secure-tls-bootstrap-client to v0.1.0-alpha.8

pkg/agent/datamodel/sig_config.go
=> cherry-pick: fix: use default gallery and resource group for Flatcar SIGImageConfig (#6680)

.github/renovate.json
/kind feature
This separates out the PRs created for aks-gpu-cuda and aks-gpu-grid, since we need to check for host/guest compatibility for GRID drivers for new driver branches. 
Fixes #
```
none
```
=> Auto-update renovate logic to separate grid/cuda PRs

e2e/config/azure.go, e2e/vmss.go
/kind test
* capture the output of `journalctl` from Flatcar test cases. There is no rsyslog on Flatcar, so /var/log/syslog is empty
* capture serial console content from Linux VMs in general
Fixes #
```
none
```
=> Capture more diagnostics from E2E tests

parts/common/components.json
| Package | Update | Change |
|---|---|---|
| containernetworking/azure-npm | patch | `v1.5.48` -> `v1.6.29` |
Fixes #
```
none
```
=> chore(deps): update containernetworking/azure-npm docker tag to v1.6.29

vhdbuilder/packer/trivy-scan.sh
Trivy-scan is currently failing on 20.04 CVM/FIPS image builds with:
az: error: unrecognized arguments: --object-id ...
This is because we're installing an old build of azure cli from the distro repo on Ubuntu 20.04 instead of pulling from PMC like we do for 22.04 and 24.04. Sync up 20.04 with the other Ubuntu versions.
Fixes #
```
none
```
=> fix(test): Install az-cli from PMC for Ubuntu 20.04 as well

pkg/agent/datamodel/const.go, pkg/agent/datamodel/osimageconfig.go, pkg/agent/datamodel/sig_config.go
feat: add support for bleu cloud regions
Fixes #
```
none
```
=> feat: add support for bleu cloud regions

pkg/agent/datamodel/const.go, pkg/agent/datamodel/osimageconfig.go, pkg/agent/datamodel/sig_config.go
cherry-pick: feat: add support for bleu cloud regions (#6708)
Fixes #
```
none
```
=> cherry-pick: feat: add support for bleu cloud regions (#6708)

.github/renovate.json
/kind feature
update ciprod's reviewers and assignees to the right group of people
Fixes #
```
none
```
=> update ciprod's reviewers and assignees to the right group of people

aks-node-controller/proto/README.md
update `AKSNodeConfig` doc
Fixes #
```
none
```
=> update `AKSNodeConfig` doc

.github/renovate.json
/kind feature
update cirpod reviewer to team containerinsights as requested
Fixes #
```
none
```
=> update cirpod reviewer to team containerinsights

.github/renovate.json
Onboards kubelet and kubectl packages from PMC to renovate. https://github.com/Azure/AgentBaker/blob/54f24627652589ad2765d2adeb4c2fda197af972/parts/common/components.json#L1317-L1499
Fixes #
```
none
```
=> chore: onboard kubelet and kubectl pkgs to renovate

CONTRIBUTING.md
Adds relevant information about GPG signing to repository for ease of use.
Fixes #
```
none
```
=> docs: Add contributing doc for GPG signing

parts/common/components.json
Updates the apiserver-network-proxy/agent image to v0.30.3-5 to mitigate CVEs
Fixes #
```
none
```
=> chore: update apiserver-network-proxy/agent image

parts/common/components.json, vhdbuilder/packer/windows/components_json_helpers.ps1, vhdbuilder/scripts/windows/generate_cached_stuff_list.ps1
/kind cleanup
secrets store drive 1.5.3 was duplicated in components.json causing some windows tests to fail.
Fixes #
```
none
```
=> chore: remove duplicate secrets store driver

.github/renovate.json
/kind feature
update the deb file repo to testing ones from originally production ones as the testing one contains containerd 2 package updates.
Fixes #
```
none
```
=> update the deb file repo to testing ones from originally production ones

.pipelines/.vsts-vhd-builder-release.yaml
=> fix: build gb200 VHD in existing build stage

.pipelines/templates/.builder-release-template.yaml, packer.mk, vhdbuilder/packer/gridcompatibility/evaluate-grid-compatibility.sh, vhdbuilder/packer/install-dependencies.sh, vhdbuilder/packer/vhd-image-builder-arm64-gen2.json, vhdbuilder/packer/vhd-image-builder-base.json, vhdbuilder/packer/vhd-image-builder-cvm.json, vhdbuilder/packer/vhd-image-builder-flatcar-arm64.json, vhdbuilder/packer/vhd-image-builder-flatcar.json, vhdbuilder/packer/vhd-image-builder-mariner-arm64.json, vhdbuilder/packer/vhd-image-builder-mariner-cvm.json, vhdbuilder/packer/vhd-image-builder-mariner.json
/kind feature
This is the scaffolding for analyzing GRID driver version compatibility of host/guest drivers across the Azure fleet.  The implementation will be updated incrementally. 
Fixes #
```
none
```
=> Add GRID driver analyzer stage scaffolding

vhdbuilder/packer/windows/windows_settings.json
=> feature: add non-sec reg key for 8B release

parts/common/components.json
chore(deps): bump aks-secure-tls-bootstrap-client to v0.1.0-alpha.11: https://github.com/Azure/aks-secure-tls-bootstrap/releases/tag/client%2Fv0.1.0-alpha.11
Fixes #
```
none
```
=> chore(deps): bump aks-secure-tls-bootstrap-client to v0.1.0-alpha.11

vhdbuilder/packer/windows/components-test.json
=> bug: fix test component json which fails latest schema update

parts/common/components.json
/kind feature
add CSI driver dalec image versions in vhd image
Fixes #
```
none
```
=> add CSI driver dalec image versions in vhd image

.github/workflows/check-windows-packages-change.yml, vhdbuilder/packer/windows/components_json_helpers.ps1, vhdbuilder/packer/windows/components_json_helpers.tests.ps1, vhdbuilder/packer/windows/windows_settings.json
/kind chore
* Improves auto comment
* Includes changes to windows VHD base versions
Fixes #
```
none
```
=> Chore: add windows base version to diff & improve comment

.github/workflows/validate-components.yml
/kind chore
ensure failure propogated
Fixes #
```
none
```
=> chore: set -ex

parts/linux/cloud-init/artifacts/localdns.sh, spec/parts/linux/cloud-init/artifacts/localdns_spec.sh
/kind bug
Fix an edge case where localdns replaces wrong IP in corefile.
Fixes #
```
none
```
=> Fix an edge case where localdns replaces wrong IP in corefile

.pipelines/.vsts-vhd-builder-release.yaml
=> feat: enable GB200 by default in VHD build

parts/common/components.json
Bump cilium to v1.16 and v1.17 to match N and (N-1) intent for versioning.
Fixes #
```
none
```
=> chore: bump cilium version to v1.16.10-250610 and v1.17.4-250610

vhdbuilder/vhd_build_timestamp.json
=> fix: use vhd build timestamp from 0811 release to revert kernel version bump

.pipelines/.vsts-vhd-builder-release-windows.yaml, .pipelines/templates/.builder-release-template-windows.yaml
/kind chore
sometimes the skip extension check variable defaults to an empty string which means the templates fail validation
Fixes #
```
none
```
=> chore: fix skip extension check logic

e2e/scenario_win_test.go, e2e/test_helpers.go, e2e/vmss.go
/kind chore
enables some ws2025 tests that were disabled
Fixes #
```
none
```
=> chore: enable ws2025 tests

.github/README-RENOVATE.md, .github/renovate.json, parts/common/components.json
/kind bug
Create custom.deb2404-test for containerd v2 as the version update metadata is only available in the PMC testing endpoint.
Validated in a fork repo.
Fixes #
```
none
```
=> create custom.deb2404-test for containerd v2

parts/common/components.json
/kind bug
Add Renovate's repository key to other deb packages so that it will use the correct PMC endpoint.
Read this for more info. https://github.com/Azure/AgentBaker/blob/master/.github/README-RENOVATE.md#:~:text=Alongside%20custom.deb2404,production%20(noble)%20endpoint.
Optional context: In case anyone is interested, the changes in this PR are required because of a recent merged PR. https://github.com/Azure/AgentBaker/pull/6982
Fixes #
```
none
```
=> add Renovate's repository key to other deb packages

parts/common/components.json
/kind cleanup
update policy addon image 
Fixes #
```
none
```
=> chore: update policy addon image

CODEOWNERS
chore: cleanup code owners
Fixes #
```
none
```
=> chore: cleanup code owners

parts/windows/kuberneteswindowssetup.ps1, parts/windows/windowscsehelper.ps1, parts/windows/windowscsehelper.tests.ps1, staging/cse/windows/azurecnifunc.ps1, staging/cse/windows/calicofunc.ps1, staging/cse/windows/configfunc.ps1, staging/cse/windows/containerdfunc.tests.ps1, staging/cse/windows/kubeletfunc.ps1, staging/cse/windows/nvidiagpudriverfunc.tests.ps1, staging/cse/windows/securetlsbootstrapfunc.ps1
/kind bug
This one came out of an IcM where we couldn't extract a zip file that was just downloaded. Eventually figured out it was a likely CRP host problem, but better logging in the scripts would be super handy. Also found some bugs because the powershel commands weren't throwing exceptions on failure.
Fixes #
```
none
```
=> /bug Better logging around file downloads and archive expansion in windows scripts

aks-node-controller/README.md
update stale link
Fixes #
```
none
```
=> update stale link

vhdbuilder/packer/test/windows-files-check.ps1
Existing binaries started failing validation on Tuesday last week. It appears that The new base windows version seems to have had a root cert removed. This PR adds the failing binaries to the validation skip list.
Fixes #
```
none
```
=> chore: improve signature skip checks

.pipelines/.vsts-vhd-builder.yaml
add 2004fipsgen2containerd to linux VHD check-in tests
Fixes #
```
none
```
=> test: add 2004fipsgen2containerd to linux VHD check-in tests

parts/common/components.json
/kind feature
Upgrade Azure Disk CSI driver v1.32.11
This PR also removes some old CSI driver images building with ado pipeline
Fixes #
```
none
```
=> Upgrade Azure Disk CSI driver v1.32.11

parts/common/components.json
/kind feature
chore: upgrade Azure Disk and File CSI driver versions
Fixes #
```
none
```
=> chore: upgrade Azure Disk and File CSI driver versions

e2e/config/azure.go
/kind bug
Add UTC to the signature expiry time
Fixes #
```
none
```
=> Add UTC to the signature expiry time

parts/linux/cloud-init/artifacts/aks-diagnostic.py, vhdbuilder/packer/imagecustomizer/azlosguard/azlosguard.yml, vhdbuilder/packer/packer_source.sh, vhdbuilder/packer/vhd-image-builder-arm64-gen2.json, vhdbuilder/packer/vhd-image-builder-base.json, vhdbuilder/packer/vhd-image-builder-cvm.json, vhdbuilder/packer/vhd-image-builder-flatcar-arm64.json, vhdbuilder/packer/vhd-image-builder-flatcar.json, vhdbuilder/packer/vhd-image-builder-mariner-arm64.json, vhdbuilder/packer/vhd-image-builder-mariner-cvm.json, vhdbuilder/packer/vhd-image-builder-mariner.json
This PR introduces a diagnostics script to support automatic customer diagnostics. It enables:
- Customer upload of log files.
- Triggering log collection on request.
This is part of the new AKS diagnostics feature to streamline support and improve issue resolution.
Not a fix
- https://www.conventionalcommits.org/
Initial implementation of AKS diagnostics. Feedback welcome on extensibility and integration.
```
none
```
=> feat: Add aks-diagnostic.py

.github/README-RENOVATE.md, .github/renovate.json, CODEOWNERS
=> cleanup: remove refs to old members

e2e/validators.go
/kind cleanup
Remove unused GPU resource validator for e2e 
Fixes #
```
none
```
=> Remove unused GPU resource e2e validator

parts/common/components.json
/kind feature
upgrade Azure File and Blob CSI drivers in vhd image
Fixes #
```
none
```
=> upgrade Azure File and Blob CSI drivers in vhd image

parts/common/components.json
/kind feature
Bump cni and cns cached versions to 1.7.4-- only roll out once these images are in mcr
Done: 
https://[mcr.microsoft.com/v2/containernetworking/azure-cni/tags/list](https://mcr.microsoft.com/v2/containernetworking/azure-cni/tags/list) https://[mcr.microsoft.com/v2/containernetworking/azure-cns/tags/list](https://mcr.microsoft.com/v2/containernetworking/azure-cns/tags/list)
Fixes #
```
none
```
=> chore: replace cni and cns versions with 1.7.4

.pipelines/templates/.builder-release-template.yaml, vhdbuilder/packer/vhd-image-builder-mariner-cvm.json
/kind cleanup
This is no longer needed. VHD builds fail if we don't remove this. Related PR: https://github.com/Azure/AgentBaker/pull/7044/files
Fixes #
```
none
```
=> Remove reference-info-base64 file for CVM

vhdbuilder/packer/pre-install-dependencies.sh
Reintroduce unpinned kernel for Ubuntu 2204
Fixes #
```
none
```
=> security: unpin LTS kernel for Ubuntu 2204

.vscode/settings.json
/kind cleanup
- Add trailing whitespace trimming for files and regex/strings
- Enable automatic final newline insertion
- Remove extra blank line in settings structure
=> chore: configure VSCode formatting settings

vhdbuilder/packer/gridcompatibility/evaluate-grid-compatibility.sh
/kind bug
Skip GRID compatibility check for prod environment till we resolve auth issue for prod.
Fixes #
```
none
```
=> Skip GRID compatibility check for prod environment
