- vhdbuilder/release-notes/AKSUbuntu/1604/2020.03.24.txt
- vhdbuilder/release-notes/AKSUbuntu/1804/2020.03.24.txt
This for syncing the RP repo with Agentbaker, these are the last changes to be synced
> add release notes for 2020.03.24

- vhdbuilder/release-notes/AKSUbuntu/1604/2020.04.06.txt
- vhdbuilder/release-notes/AKSUbuntu/1804/2020.04.06.txt
Refer1: https://github.com/Azure/AgentBaker/pull/13/files
Refer2: https://github.com/Azure/AgentBaker/pull/12/files
> Add release notes for 20200406 VHD

- parts/linux/cloud-init/artifacts/pam-d-common-auth
- parts/linux/cloud-init/artifacts/pam-d-common-password
- parts/linux/cloud-init/artifacts/pam-d-su
- vhdbuilder/packer/packer_source.sh
- vhdbuilder/packer/vhd-image-builder-gen2.json
- vhdbuilder/packer/vhd-image-builder-sig.json
- vhdbuilder/packer/vhd-image-builder.json
https://msazure.visualstudio.com/CloudNativeCompute/_workitems/edit/7072357
> (CIS): pam.d password enforcement

- vhdbuilder/packer/install-dependencies.sh
cleanup images we don't need in vhd
> vhd images cleanup

- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2020.05.06.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2020.05.06.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2020.05.06.txt
Add release notes for 2020.05.06 vhd
> Add release notes for 2020.05.06 vhd

- vhdbuilder/packer/install-dependencies.sh
Bake the new openvpn-based tunnel to avoid pulling at runtime.
> Add openvpn tunnel image

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/install-dependencies.sh
Mirroring from here: https://github.com/Azure/aks-engine/tree/c7109ed9931284f8b211b0f1062bb7bd8614c704/vhd/packer
> newer cni versions in agent baker 

- parts/linux/cloud-init/artifacts/cse_main.sh
- pkg/templates/templates_generated.go
Refer https://github.com/Azure/aks-engine/pull/3294: Increase apiserver connection timeout for private apiserver.
> Increase apiserver connection timeout for private apiserver

- vhdbuilder/packer/install-dependencies.sh
add back tunnelfront image version v1.9.2-v3.0.11 v1.9.2-v4.0.11
> add back tunnelfront image version v1.9.2-v3.0.11 v1.9.2-v4.0.11

- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2020.05.21.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2020.05.21.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2020.05.21.txt
Adding release notes for vhd 2020.05.21
> Release notes for vhd 2020.05.21

- vhdbuilder/packer/install-dependencies.sh
Update Azure Policy Add-on images
> Update Azure Policy Add-on images

- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2020.05.27.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2020.05.27.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2020.05.27.txt
Release notes 2020.05.27
removed 05.21 notes
> VHD Release notes 2020.05.27

- vhdbuilder/publish/sig-version-publish.sh
Add parameter to publish premium_lrs images for sig
> publish premium images

- vhdbuilder/packer/install-dependencies.sh
Cleanup more hyperkube images and CPA 1.3.0
https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-config?path=%2Ftoggles%2Fcluster-proportional-autoscaler-images-need-patch.yaml
> Cleanup more hyperkube images and CPA 1.3.0

- vhdbuilder/packer/install-dependencies.sh
Increase space limit to 99% for now
> [VHD] Increase space limit to 99% for now

- parts/linux/cloud-init/artifacts/cse_cmd.sh
- pkg/agent/variables.go
- pkg/templates/templates_generated.go
Please refer to https://github.com/Azure/aks-engine/pull/3400 for original changes
> log kubelet status and fix nc output stderr

- vhdbuilder/packer/install-dependencies.sh
- update azuredisk-csi-driver and azurefile-csi-driver image to the latest release
- add csi windows related images
/ping @andyzhangx @feiskyer @andyliuliming
> update csi drivers related image

- pkg/agent/utils.go
Add new NV v3 SKUs. Ref:
https://github.com/Azure/aks-engine/blob/54ce1f03c5dcef255a203cdd1ffedfe89f2d367d/pkg/api/common/helper.go#L24
> Add NV v3 SKUs

- parts/linux/cloud-init/nodecustomdata.yml
- pkg/templates/templates_generated.go
https://diffy.org/diff/ft8yjpt3rq19a2cnaoiq2awcdi
> reduce extra space from template params

- go.mod
- go.sum
- vendor/github.com/Azure/aks-engine/pkg/engine/templates_generated.go
- vendor/modules.txt
the functions exporting missing when merge the code manually.
> bump the aks engine version to v0.47.0-aks-gomod-69.

- vhdbuilder/packer/install-dependencies.sh
In this PR, we'll upgrade Calico related images to v3.8.0 and add a Calico pod2daemon.
> Update Calico releated images to v3.8.0

- .pipelines/.vsts-vhd-builder.yaml
This is a hack to unblock me publishing GPU VHDs to SIG.
Long term wise consider move this logic out of yaml file, and have a group of build_mode, then set variables based on build_mode.
> Create sku name for publishing GPU VHD to SIG

- parts/linux/cloud-init/artifacts/cse_install.sh
- pkg/templates/templates_generated.go
- vhdbuilder/packer/install-dependencies.sh
fix: downgrade blobfuse to 1.1.1 since there is breaking change on 1.2.3
more details could be found here: https://github.com/Azure/kubernetes-volume-drivers/issues/66#issuecomment-649188681
@xuto2
> fix: downgrade blobfuse to 1.1.1 since there is breaking change on 1.2.3

- vhdbuilder/packer/install-dependencies.sh
prebake new hotfix image ciprod07152020 for omsagent
> prebake new hotfix image ciprod07152020 for omsagent

- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2020.07.16.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2020.07.16.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpu/2020.07.16.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2020.07.16.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/2020.07.16.txt
Add release notes for 2020.07.16 VHD
> Add release notes for 2020.07.16 VHD

- vhdbuilder/publish/prepare-sig.sh
Fix an issue that SIG gen2 image definition is not specified gen2
> Fix SIG gen2 image definition create

- vhdbuilder/publish/sig-version-create.sh
Fix an issue that when create gen2 managed image generation was not specified
> Fix gen2 managed image create

- vhdbuilder/packer/install-dependencies.sh
> Revert "Free up space by removing unused images"

- parts/linux/cloud-init/artifacts/kubelet.service
- pkg/templates/templates_generated.go
remove this flag since RP is already setting it
> Remove dynamic kubelet config dir

- pkg/agent/const.go
- pkg/agent/utils.go
When get kubelet config flags string, also ensure kubelet flags value
> Ensure kubelet config flags value

- parts/linux/cloud-init/artifacts/kubelet.service
- pkg/agent/const.go
- pkg/agent/utils.go
- pkg/templates/templates_generated.go
* Remove dynamic kubelet config dir
* update generated
> [CherryPick] Remove dynamic kubelet config dir (#188)

- parts/linux/cloud-init/artifacts/cse_cmd.sh
- pkg/templates/templates_generated.go
Correctly exit error code that comes from provision.sh.
> Exit error code from provision.sh

- pkg/agent/utils.go
Two previous PRs went in resulted in this break.
> Fix a build break from code merge issue.

- pkg/agent/baker_test.go
- pkg/agent/datamodel/defaults-kubelet_test.go
- pkg/agent/datamodel/defaults_test.go
- pkg/agent/datamodel/mocks.go
- pkg/agent/datamodel/types.go
- pkg/agent/datamodel/types_test.go
- pkg/agent/params.go
- pkg/agent/utils.go
Also ported over the functions used in our code and their tests.
> Port the "Properties" struct from aks-engine into our code base.

- pkg/agent/const.go
- pkg/agent/datamodel/defaults_test.go
- pkg/agent/datamodel/mocks.go
- pkg/agent/datamodel/types.go
AgentBaker doesn't support Azure Stack (custom cloud), so all these code are dead code.
> Remove "CustomCloudProfile" and some other Azure Stack related code.

- vhdbuilder/packer/configure-windows-vhd.ps1
Use acs-mirrored artifacts. The existence of these artifacts have been tested and confirmed.
> use acs-mirror artifacts

- pkg/agent/baker_test.go
- pkg/agent/datamodel/defaults-kubelet_test.go
- pkg/agent/datamodel/defaults.go
- pkg/agent/datamodel/defaults_test.go
- pkg/agent/datamodel/mocks.go
- pkg/agent/datamodel/types.go
- pkg/agent/datamodel/types_test.go
- pkg/agent/utils.go
- pkg/aks-engine/api/apiloader_test.go
- pkg/aks-engine/engine/engine_test.go
This removes our dependency on those data structs. Our end goal is to remove all dependencies on aks-engine.
> Copy some data structs from aks-engine to our code base.

- cmd/generate.go
- pkg/agent/baker.go
- pkg/aks-engine/api/apiloader.go
- pkg/aks-engine/api/apiloader_test.go
- pkg/aks-engine/api/strictjson_test.go
- pkg/aks-engine/engine/engine_test.go
- pkg/aks-engine/engine/output.go
- pkg/aks-engine/engine/output_test.go
- pkg/aks-engine/helpers/helpers.go
- pkg/aks-engine/helpers/helpers_test.go
AgentBaker doesn't support internationalization so doesn't need those code.
> Remove all i18n related code.

- vhdbuilder/packer/install-dependencies.sh
https://github.com/kubernetes/kubernetes/pull/83507 fix on  	1.15.11	1.15.12	1.16.10	1.16.13	1.17.7	1.17.9	
https://github.com/kubernetes/kubernetes/pull/82300 fix on  	1.15.11	1.15.12	1.16.10	1.16.13
> Update kubelet image with fix to inaccurate pod CPU usage report 

- vhdbuilder/packer/configure-windows-vhd.ps1
Update windows vhd cache to https://github.com/Azure/aks-engine/pull/3725
> Update windows vhd cache to latest

- vhdbuilder/packer/install-dependencies.sh
* Add hotfix for 1.16.15 and 1.17.11
* update comments
> [Cherry-pick] Add hotfix for 1.16.15 and 1.17.11 (#292)

- vhdbuilder/packer/configure-windows-vhd.ps1
Context of this addition: https://teams.microsoft.com/l/message/19:461da7b575644fe79b19e02e4d9e07d6@thread.skype/1599109778430?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=e121dbfd-0ec1-40ea-8af5-26075f6a731b&parentMessageId=1598658311156&teamName=Azure%20Container%20Compute&channelName=AKS%20Overlay%20VHD%20Management&createdTime=1599109778430
> Add k8s hotfix

- vhdbuilder/packer/install-dependencies.sh
Disk usage 99%
Need to free up some space
> Free some disk space

- vhdbuilder/packer/init-variables.sh
- vhdbuilder/publish/Marketplace/new-windows-sku.sh
- vhdbuilder/publish/Marketplace/sku-template.json
This is a follow-up PR for https://github.com/Azure/AgentBaker/pull/287.
Last PR we merged August patch,  this br introduces July base image. For _windows patch contains changes based on the last month's base image_
> Update windows base image to July

- vhdbuilder/packer/install-dependencies.sh
removing 0824 patch since they have least usage
> remove two 1.15 hyperkube

- vhdbuilder/packer/configure-windows-vhd.ps1
Add 9B patch for August's Windows VHD. Qingchuan has updated base Windows image to August's.
> Add 9B patch for August's Windows VHD

- vhdbuilder/release-notes/AKSWindows/2019/17763.1457.200909.txt
Add release notes for AKS Windows VHD 17763.1457.200909
> doc: Add release notes for AKS Windows VHD 17763.1457.200909

- pkg/agent/baker.go
- pkg/agent/datamodel/types.go
- pkg/agent/datamodel/types_test.go
> Remove "IsSwarmMode".

- vhdbuilder/packer/install-dependencies.sh
> chore: upgrade AzureDisk/AzureFile CSI Drivers to v0.9.0

- .pipelines/.vsts-vhd-builder-release.yaml
- .pipelines/.vsts-vhd-builder.yaml
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/vhd-image-builder-gen2.json
- vhdbuilder/packer/vhd-image-builder-sig.json
- vhdbuilder/packer/vhd-image-builder.json
For VHD pipeline add hyperv generation to release notes, add dryrun option
> chore: Add hyperv generation to release notes, add dryrun option

- parts/linux/cloud-init/nodecustomdata.yml
- pkg/agent/testdata/AKSUbuntu1604+DynamicKubelet/CustomData
- pkg/agent/testdata/AKSUbuntu1604+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSUbuntu1604+GPUDedicatedVHD/CustomData
- pkg/agent/testdata/AKSUbuntu1604+K8S115/CustomData
- pkg/agent/testdata/AKSUbuntu1604+K8S117/CustomData
- pkg/agent/testdata/AKSUbuntu1604+K8S118/CustomData
- pkg/agent/testdata/AKSUbuntu1604+TempDisk+Containerd/CustomData
- pkg/agent/testdata/AKSUbuntu1604+TempDisk/CustomData
- pkg/agent/testdata/AKSUbuntu1804+Containerd+NSeriesSku/CustomData
- pkg/agent/testdata/RawUbuntu/CustomData
- pkg/templates/templates_generated.go
> remove single quote from cloud-init data

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/vhd-content-test.ps1
Cache Windows signedscripts v0.0.3 and cni v1.1.7
> Cache Windows signedscripts v0.0.3 and cni v1.1.7

- parts/linux/cloud-init/nodecustomdata.yml
- pkg/templates/templates_generated.go
Reverts Azure/AgentBaker#333
It's causing ARM template issue.
> Revert "feat: Support multiple vnetCidrs"

- pkg/agent/baker.go
- pkg/agent/datamodel/types.go
- pkg/agent/datamodel/types_test.go
- pkg/agent/utils.go
- pkg/aks-engine/engine/engine.go
- pkg/aks-engine/engine/engine_test.go
In the context of AgentBaker, MasterProfile is always nil, so we don't need those code removed in this change.
> Remove some code related to MasterProfile that AgentBaker doesn't need.

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/vhd-content-test.ps1
feat: Add k8s 1.17.12, 1.18.9, 1.19.1, 1.19.2; Remove CNI 1.1.7
> feat: Add k8s 1.17.12, 1.18.9, 1.19.1, 1.19.2; Remove CNI 1.1.7

- parts/linux/cloud-init/nodecustomdata.yml
- pkg/agent/testdata/AKSUbuntu1604+DynamicKubelet/CustomData
- pkg/agent/testdata/AKSUbuntu1604+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSUbuntu1604+GPUDedicatedVHD/CustomData
- pkg/agent/testdata/AKSUbuntu1604+K8S115/CustomData
- pkg/agent/testdata/AKSUbuntu1604+K8S117/CustomData
- pkg/agent/testdata/AKSUbuntu1604+K8S118/CustomData
- pkg/agent/testdata/AKSUbuntu1604+TempDisk+Containerd/CustomData
- pkg/agent/testdata/AKSUbuntu1604+TempDisk/CustomData
- pkg/agent/testdata/AKSUbuntu1804+Containerd+NSeriesSku/CustomData
- pkg/agent/testdata/RawUbuntu/CustomData
- pkg/templates/templates_generated.go
Cherry picking https://github.com/Azure/AgentBaker/pull/375 into official/v20201008 branch.
> Only block 80 port for Azure DNS/LoadBalancer probe IP 168.63.129.16

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/vhd-content-test.ps1
feat: Cache v1.19.1-hotfix.20200923-1int.zip in Windows VHD
> feat: Cache v1.19.1-hotfix.20200923-1int.zip in Windows VHD

- vhdbuilder/packer/test/vhd-content-test.ps1
fix: Fix log issue in Windows VHD test script
> fix: Fix log issue in Windows VHD test script

- vhdbuilder/release-notes/AKSWindows/2019/17763.1397.201014.txt
Add aks-windows2019 201014 release notes
> Add aks-windows2019 201014 release notes

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/vhd-content-test.ps1
Bake v1.1.8 cni for windows and linux
> chore: cache cni v1.1.8

- vhdbuilder/packer/install-dependencies.sh
Adding back in cni v1.1.7 for customer hotfixes.
@paulgmiller for verification
@xuto2 could you approve if Paul approves?
> chore: adding cni v1.1.7 back into agent baker

- vhdbuilder/packer/install-dependencies.sh
Add Azure Policy Add-on labelSelector image to VHD.
> Add Azure Policy Add-on labelSelector image to VHD

- pkg/agent/baker.go
- pkg/agent/const.go
- pkg/agent/testdata/AKSUbuntu1604+CustomKubeletConfig+CustomLinuxOSConfig/CustomData
- pkg/agent/testdata/AKSUbuntu1604+KubeletConfigFile/CustomData
- pkg/agent/utils.go
- pkg/agent/utils_test.go
* Delete dynamic-config-dir if using config file
* update to set before getting payload
> Delete dynamic-config-dir if using config file (#418)

- .pipelines/templates/.builder-release-template.yaml
Publish vhd-publishing-info.json as a universal package
> Publish artifacts as package

- vhdbuilder/packer/install-dependencies.sh
Signed-off-by: Sertac Ozercan <sozercan@gmail.com>
> add gatekeeper v3.1.3

- vhdbuilder/packer/install-dependencies.sh
> Add 1.19.1 hotfix image

- vhdbuilder/packer/install-dependencies.sh
should use `mcr.microsoft.com/k8s/flexvolume/blobfuse-flexvolume:1.0.15` with blobfuse driver `1.3.5`
> update blobfuse version

- vhdbuilder/packer/install-dependencies.sh
chrony is no longer installed on VHD
> chore: Remove chrony dead code

- vhdbuilder/packer/install-dependencies.sh
We are working on the AAD pod identity addon public review. We want to package this NMI image to the VHD.
> Add aad pod identity NMI image

- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2020.12.01.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2020.12.01.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804containerd/2020.12.01.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpu/2020.12.01.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpucontainerd/2020.12.01.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2020.12.01.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804containerd/2020.12.01.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/2020.12.01.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpucontainerd/2020.12.01.txt
Add release notes for VHD 2020.12.01
> Add release notes for VHD 2020.12.01

- vhdbuilder/packer/windows-image.env
chore: Update Windows 2019 base image to 17763.1579.2011180054
```
az vm image list --all --publisher  MicrosoftWindowsServer --offer WindowsServer --output table -s 2019-Datacenter-Core-smalldisk
Offer          Publisher               Sku                                Urn                                                                                           Version
-------------  ----------------------  ---------------------------------  --------------------------------------------------------------------------------------------  ---------------------
WindowsServer  MicrosoftWindowsServer  2019-Datacenter-Core-smalldisk     MicrosoftWindowsServer:WindowsServer:2019-Datacenter-Core-smalldisk:17763.1039.2002091844     17763.1039.2002091844
WindowsServer  MicrosoftWindowsServer …
```
> chore: Update Windows 2019 base image to 17763.1579.2011180054

- parts/linux/cloud-init/nodecustomdata.yml
- pkg/agent/testdata/AKSUbuntu1604+TempDisk+Containerd/CustomData
- pkg/agent/testdata/AKSUbuntu1804+Containerd+Kubenet/CustomData
- pkg/agent/testdata/AKSUbuntu1804+Containerd+NSeriesSku/CustomData
- pkg/agent/testdata/AKSUbuntu1804+Containerd+PrivateACR/CustomData
- pkg/agent/testdata/AKSUbuntu1804+Containerd+Teleport/CustomData
- pkg/templates/templates_generated.go
This reverts commit 18646a7ae63eaf49c627c48e22cfa16cd8bd14a7.
> Revert "update containerd/config.toml (#464)"

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/vhd-content-test.ps1
patch link: https://support.microsoft.com/en-us/help/4592440/windows-10-update-kb4592440
> chore: Add windows server 2019 12B patch

- parts/linux/cloud-init/nodecustomdata.yml
- pkg/agent/testdata/AKSUbuntu1604+TempDisk+Containerd/CustomData
- pkg/agent/testdata/AKSUbuntu1804+Containerd+Kubenet/CustomData
- pkg/agent/testdata/AKSUbuntu1804+Containerd+NSeriesSku/CustomData
- pkg/agent/testdata/AKSUbuntu1804+Containerd+PrivateACR/CustomData
- pkg/agent/testdata/AKSUbuntu1804+Containerd+Teleport/CustomData
- pkg/templates/templates_generated.go
`promisMode` should be `promiscMode`.
> Fix typo for promiscMode

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/vhd-content-test.ps1
- vhdbuilder/packer/windows-image.env
chore: Update Windows base image version to 17763.1637.2012040632
> chore: Update Windows base image version to 17763.1637.2012040632

- parts/linux/cloud-init/artifacts/cse_config.sh
- parts/linux/cloud-init/artifacts/cse_main.sh
- parts/linux/cloud-init/nodecustomdata.yml
- pkg/agent/baker.go
- pkg/agent/datamodel/types.go
- pkg/templates/templates_generated.go
HasNSeriesSKU used case sensitive matching, which cause driver configuration to be skipped if sku name doesn't match "Stardard_N"
> Remove HasNSeriesSKU

- vhdbuilder/release-notes/AKSWindows/2019/17763.1697.210113.txt
add release notes for AKS Windows VHD 17763.1697.210113
> doc: add release notes for AKS Windows VHD 17763.1697.210113

- vhdbuilder/release-notes/AKSWindows/17763.1697.210127.txt
VHD build link https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=38832474&view=results
> chore: add release notes

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/vhd-content-test.ps1
chore: add azure node manager image v0.7.0
> chore: add azure node manager image v0.7.0

- NOTICE.md
> doc: Add NOTICE for CalicoWindows

- NOTICE.md
Update NOTICE header per suggestion.
> fix: Update NOTICE header

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/vhd-content-test.ps1
chore: add secrets store csi driver related images
> chore: add secrets store csi driver related images

- pkg/agent/datamodel/const.go
- pkg/agent/testdata/AKSWindows2004+K8S119+hyperv/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- vhdbuilder/packer/configure-windows-vhd.ps1
> chore: update windows dockeree version to 19.03.14

- vhdbuilder/packer/install-dependencies.sh
https://github.com/Azure/application-gateway-kubernetes-ingress/releases
> [AGIC][Addon] Add AGIC image 1.2.0 / 1.3.0 to the agent baker

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/vhd-content-test.ps1
bump version of csi related images
> bump version of csi related images

- tools/dnsresolv.yaml
Temp mitigation to disable systemd-resolved on 1804
> Add dns resolv tool

- vhdbuilder/packer/install-dependencies.sh
This pull request added the nmi:v1.7.4 image to the VHD
> pi: bake nmi 1.7.4 image

- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/linux-vhd-content-test.sh
Made a mistake in specifying the MCR URL of tigera operator
> Correct tigera operator image path

- pkg/agent/baker.go
- pkg/agent/baker_test.go
- pkg/agent/const.go
- pkg/agent/datamodel/types.go
Move parse vmss cse logic into agent baker
> Parse VMSS CSE in agentbaker

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
> chore: Enable HNS fix in 2C

- vhdbuilder/release-notes/AKSWindows/2019/17763.1790.210302.txt
Add release notes for AKS Windows VHD 17763.1790.210302
> doc: Add release notes for AKS Windows VHD 17763.1790.210302

- vhdbuilder/publish/cleanup.sh
- vhdbuilder/publish/prepare-sig.sh
- vhdbuilder/publish/sig-version-create.sh
- vhdbuilder/publish/sig-version-scale.sh
Reverts Azure/AgentBaker#615
as it's still used by windows.
> Revert "Remove legacy sig publish related files"

- vhdbuilder/release-notes/AKSWindows/2019/17763.1757.210220.txt
This vhd is built as a hotfix for Feb security patch one week ago.
> Add win release notes 17763.1757.210220

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
> chore: Update Windows 3B patch

- pkg/agent/baker.go
- pkg/agent/baker_test.go
- pkg/agent/const.go
- pkg/agent/datamodel/const.go
- pkg/agent/datamodel/types.go
- pkg/agent/utils.go
- pkg/agent/utils_test.go
Two changes
(1) renaming
(2) move method to utils.go
> Rename ParseVMSSCSEMessage to ParseCSE

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/linux-vhd-content-test.sh
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
switch to use upstream team maintained csi driver images
> switch to use upstream team maintained csi driver images

- vhdbuilder/release-notes/AKSWindows/2019/17763.1817.210310.txt
Add release notes for AKS Windows VHD with 3B patch
> doc: Add release notes for AKS Windows VHD with 3B patch

- .pipelines/.vsts-vhd-builder-release.yaml
Enable FIPS VHDs build by default
> Enable FIPS VHDs build by default

- vhdbuilder/packer/install-dependencies.sh
Also to address CVE issue found in the old images
> Update nvidia device plugin image to latest from upstream

- vhdbuilder/packer/install-dependencies.sh
This removes dead k8s binary and kube proxy code from the install script
> refactor: remove dead code k8s install code from install-dependencies

- pkg/agent/k8s_versions_for_baker_test.go
- vhdbuilder/packer/components.json
> Chore: upgrade NPM to v1.2.8

- vhdbuilder/packer/install-dependencies.sh
Updated version required for the sgx webhook hotfix
> updating image versions for acc addon

- pkg/agent/datamodel/types.go
Update the distro string from Mariner to CBLMariner for more consistency in related code.
> Update distro string for cblmariner

- .pipelines/.vsts-vhd-builder-windows.yaml
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
- vhdbuilder/packer/write-release-notes-windows.ps1
- Enable windows containerD check in
- fix writing release notes error for containerD
> chore: enable windows containerd check-in

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
reference: https://github.com/kubernetes-sigs/windows-gmsa/issues/30
> fix: enables DNS resolution of SMB shares for containerD

- parts/linux/cloud-init/artifacts/cse_install.sh
- pkg/templates/templates_generated.go
- vhdbuilder/packer/components.json
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/linux-vhd-content-test.sh
1. this pr is to remove the hyperkube image.
because the images tags pulling here is not in use anymore.
2. bump some images with upstream patches.
> bumping the images which have more patches.

- vhdbuilder/packer/components.json
pause:3.5
ip-masq-agent:2.5.0.4
cluster-proportioanl-autoscaler:1.8.3
metrics-server:v0.4.2
> Add new image tags for patching

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
Update AKS Windows VHD with 4B
> Update AKS Windows VHD with 4B

- vhdbuilder/packer/write-release-notes-windows.ps1
Update registry settings in release notes
> Update registry settings in release notes

- .pipelines/templates/.builder-release-template.yaml
Small addition to include the test-building-vhd to the Weekly Release Pipelines.
> Add Post VHD Build Test to Weekly Release Pipeline

- vhdbuilder/packer/install-dependencies.sh
Added the GPU Driver version to vhdbuilder release notes
> Add GPU Driver Version to the release notes

- vhdbuilder/packer/configure-windows-vhd.ps1
Please reference more details in https://github.com/kubernetes-sigs/image-builder/pull/553
> Add retries while fetching Windows Defender signatures

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
- vhdbuilder/packer/windows-image.env
Update AKS Windows VHD with 4C
> chore: update AKS Windows VHD with 4C

- vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
Not install strongswan package to match the latest FIPS SBI image
> Not install strongswan to match the latest FIPS SBI image

- vhdbuilder/scripts/windows/collect-windows-logs.ps1
Fixes https://github.com/Azure/AgentBaker/issues/783
> ignore docker event collection if not exist

- vhdbuilder/scripts/windows/collect-windows-logs.ps1
Fixes: https://github.com/Azure/AgentBaker/issues/784
> chore: remove unused containerd log collection

- .pipelines/templates/.builder-release-template.yaml
- vhdbuilder/packer/test/run-test.sh
Skipping Gen2(for now), Mariner and 16.04
> Add VHD tests in weekly pipeline

- vhdbuilder/cgmanifest.json
- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
- Add Calico Windows v3.19.0
- Remove Calico Windows v3.17.2
> chore: Add Calico Windows v3.19.0

- vhdbuilder/scripts/windows/collect-windows-logs.ps1
Collect Azure CNI configurations: azure-vnet.json and azure-vnet-ipam.json
> Collect Azure CNI configurations

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
chore: add cloud-node-manager image versions
> chore: add cloud-node-manager image versions

- vhdbuilder/publish/Marketplace/new-sku-and-add-image-version.sh
Use token for MarketPlace operations
> fix: Use token for MarketPlace operations

- vhdbuilder/publish/Marketplace/new-sku-and-add-image-version.sh
need login before getting token with azure cli
> fix: need login before getting token with azure cli

- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.1935.210513.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.1935.210513.txt
Add release notes for AKS Windows VHD with 5B
> doc: Add release notes for AKS Windows VHD with 5B

- vhdbuilder/packer/configure-windows-vhd.ps1
Old code does not always work so fix it.
> fix: Log disk info of C drive

- vhdbuilder/release-notes/AKSCBLMariner/gen1/V1/2021.05.15.txt
- vhdbuilder/release-notes/AKSCBLMariner/gen2/V1/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804containerd/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipscontainerd/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipsgpucontainerd/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpu/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpucontainerd/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804containerd/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipscontainerd/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipsgpucontainerd/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/2021.05.15.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpucontainerd/2021.05.15.txt
Release notes for 2021.05.15 AKS Linux VHD release
> Release notes for 2021.05.15 AKS Linux VHD release

- parts/linux/cloud-init/artifacts/ubuntu/cse_install_ubuntu.sh
- pkg/agent/testdata/AKSUbuntu1604+CustomKubeletConfig+CustomLinuxOSConfig/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+Disable1804SystemdResolved=false/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+Disable1804SystemdResolved=true/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+EnablePrivateClusterHostsConfigAgent/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+GPUDedicatedVHD/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+K8S115/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+K8S117/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+K8S118/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+KubeletConfigFile/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+OSKubeletDisk/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+TempDisk+Containerd/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+TempDiskExplicit/line48.sh
- pkg/agent/testdata/AKSUbuntu1604+TempDiskToggle/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+Containerd+ContainerdVersion/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+Containerd+IPMasqAgent/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+Containerd+Kubenet+Calico/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+Containerd+Kubenet+FIPSEnabled/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+Containerd+Kubenet/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+Containerd+NSeriesSku/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+Containerd+PrivateACR/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+Containerd+Teleport/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+Disable1804SystemdResolved=false/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+Disable1804SystemdResolved=true/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+HTTPProxy/line48.sh
- pkg/agent/testdata/AKSUbuntu1804+KubeletClientTLSBootstrapping/line48.sh
- pkg/agent/testdata/RawUbuntu/line48.sh
- pkg/agent/testdata/RawUbuntuContainerd/line48.sh
- pkg/templates/templates_generated.go
- vhdbuilder/packer/install-dependencies.sh
> feat: install blobfuse 1.3.7 by default

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Add k8s hotfixes for Windows: 
1.21: https://github.com/kubernetes/kubernetes/pull/102001
1.20: https://github.com/kubernetes/kubernetes/pull/102000
1.19: https://github.com/kubernetes/kubernetes/pull/101999
> Add Windows k8s hotfixes

- vhdbuilder/packer/components.json
Updating CNS to v1.4.0 for fixing a connection reset issue that was found.
> Update azure-cns image to v1.4.0

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
This change is from the HNS team's request to coverage on the other codepath.
> Change HNSControlFlag to 3

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
> Cache Windows Azure CNI 1.4.0

- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.1999.210609.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.1999.210609.txt
This PR is created by https://msazure.visualstudio.com/DefaultCollection/CloudNativeCompute/_release?definitionId=716
> chore: add win release notes 17763.1999.210609

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
update with latest omsagent image
> update with latest omsagent image

- vhdbuilder/packer/components.json
Update HttpApplicationRouting images
> Update HttpApplicationRouting images

- vhdbuilder/release-notes/AKSCBLMariner/gen1/V1/2021.06.19.txt
- vhdbuilder/release-notes/AKSCBLMariner/gen2/V1/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804containerd/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipscontainerd/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipsgpucontainerd/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpu/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpucontainerd/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804containerd/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipscontainerd/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipsgpucontainerd/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/2021.06.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpucontainerd/2021.06.19.txt
AKS Linux 2021.06.19 VHD release notes
> AKS Linux 2021.06.19 VHD release notes

- vhdbuilder/packer/configure-windows-vhd.ps1
Windows containerd VHD building recently hit disk space insufficient issue and containerd is consuming more disk space compared to docker VHD even when docker caches more resources than containerd.
The reason is we are pulling images with default contained configuration with have discard_unpacked_layers  disabled, which _let Containerd stores the content of an image as is (the raw tars/tarballs and image manifests_, and eat 5GB or so disk space. 
We in this PR enable discard_unpacked_layers  when pre-pull images and use crictl to pull images instead which is required as discard_unpacked_layers is a cri option.
> discard unpacked layers to reduce disk space when building containerd VHD

- vhdbuilder/packer/components.json
Add ip-masq-agent 2.5.0.6 into the VHD
> Add ip-masq-agent 2.5.0.6

- .pipelines/scripts/verify_shell.sh
the script currently exits on failure from the initial attempt to locate shellcheck.
the output from the initial command also isn't a number, since it doesn't use the exit status `$?`, it just tries to use the output from the command which is the empty string since it redirects to /dev/null.
apt install requires sudo.
you can't return from bash when not inside a function -- that requires an `exit`
detecting the distro fails on WSL and for anyone with a custom kernel build (like yours truly), so adjusted the script to account for that a bit better.
Debian WSL:
```bash
ace@DESKTOP-TFSEIGE:/mnt/c/Users/alexe$ uname -r
5.4.72-microsoft-standard-WSL2
ace@DESKTOP-TFSEIGE:/mnt/c/Users/alexe$ uname
Linux
ace@DESKTOP-TFSEIGE:/mnt/c/Users/alexe$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 …
```
> fix: shellcheck validation + install

- pkg/agent/params.go
- pkg/agent/variables.go
The removed parameters and variables are not used when generating custom data and CSE.
> Remove unused parameters and variables.

- vhdbuilder/packer/components.json
Add latest policy images to VHD
Gatekeeper image: v3.4.1
Policy images: prod_20210713.1
> Add latest policy images to VHD

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/windows-image.env
https://support.microsoft.com/en-us/topic/july-13-2021-kb5004244-os-build-17763-2061-d2b763cb-fad4-4b0a-a67f-4e184e277b99
> chore: Add Windows security patch 2021-7B

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
https://github.com/Azure/aks-engine/pull/4581
- [fix: chore: Add windowssecuretls.ps1 #4567](https://github.com/Azure/aks-engine/pull/4567)
> chore: Cache Windows singed scripts v0.0.14

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache hotfix versions for v1.20.5, v1.20.7 and v1.21.1
> chore: Cache hotfix versions for v1.20.5, v1.20.7 and v1.21.1

- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
This is the result of running "make generate".
> Regenerate expected test data.

- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.2061.210714.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.2061.210714.txt
Add release notes for AKS Windows VHD 17763.2061.210714
> doc: Add release notes for AKS Windows VHD 17763.2061.210714

- vhdbuilder/packer/components.json
Azure Policy image: prod_20210719.1
> Add latest Azure Policy image

- vhdbuilder/release-notes/AKSCBLMariner/gen1/V1/2021.07.24.txt
- vhdbuilder/release-notes/AKSCBLMariner/gen2/V1/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804containerd/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipscontainerd/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipsgpucontainerd/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpu/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpucontainerd/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804containerd/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipscontainerd/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipsgpucontainerd/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/2021.07.24.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpucontainerd/2021.07.24.txt
AKS Linux VHD 2021.07.25 weekly release notes
> AKS Linux VHD 2021.07.25 weekly release notes

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/install-dependencies.sh
adds latest cni v1.4.7 to cache
> add cni v1.4.7

- parts/windows/kuberneteswindowssetup.ps1
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- pkg/templates/templates_generated.go
The old code does not convert it to bool so it will always enable Windows secure TLS by default.
$windowsSecureTlsEnabled = "false"
> Fix bool convert issue

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Upgrade AzureDisk/AzureFile CSI Drivers Versions to v1.5.0
> Upgrade AzureDisk/AzureFile CSI Drivers Versions to v1.5.0

- vhdbuilder/packer/components.json
Add Gatekeeper v3.5.2 and policy prod_20210806.1 images
> Add Gatekeeper v3.5.2 and policy prod_20210806.1 images

- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.2114.210811.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.2114.210811.txt
This PR is created by https://msazure.visualstudio.com/DefaultCollection/CloudNativeCompute/_release?definitionId=716
> chore: add win release notes 17763.2114.210811

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- Add calico v3.20.0
- Remove old signedscripts-v0.0.13 and calico-windows-v3.18.1
> Add calico 3.20.0 and remove old signedscripts-v0.0.13 and calico-windows-v3.18.1

- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/osimageconfig.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
bumps both linux and windows SIG versions
> bump SIG image versions

- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/linux-vhd-content-test.sh
> Add hotfixes for 1.20.7 and 1.21.2

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache CCGPlugin v1.1.0 in Windows VHD
> chore: Cache CCGPlugin v1.1.0 in Windows VHD

- Makefile
some missed cleanup from https://github.com/Azure/AgentBaker/pull/1015
> fix: remove go-build and adjust all target

- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/linux-vhd-content-test.sh
Co-authored-by: Ganeshkumar Ashokavardhanan <aganeshkumar@microsoft.com>
> add new k8s versions

- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/linux-vhd-content-test.sh
Co-authored-by: Ganeshkumar Ashokavardhanan <aganeshkumar@microsoft.com>
> Remove 1.18.8 kube binary (#1042)

- pkg/agent/const.go
I've also done a scan of RP and don't see these used anywhere there (they should not be...)
> cleanup: remove a bunch of unused constants

- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/osimageconfig.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
* Bump SIG image version to 2021.08.21
* Commit to re-trigger build
Co-authored-by: Ganeshkumar Ashokavardhanan <aganeshkumar@microsoft.com>
Co-authored-by: Liming Liu <andyliuliming@outlook.com>
> Bump SIG image version to 2021.08.21 (#1057)

- vhdbuilder/release-notes/AKSCBLMariner/gen1/2021.08.28.txt
- vhdbuilder/release-notes/AKSCBLMariner/gen2/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804containerd/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipscontainerd/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipsgpucontainerd/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpu/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpucontainerd/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804containerd/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipscontainerd/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipsgpucontainerd/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/2021.08.28.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpucontainerd/2021.08.28.txt
AKS Linux VHD release notes: 2021.08.28
> AKS Linux VHD release notes: 2021.08.28

- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/osimageconfig.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
Bump SIG image version to 2021.08.28
> Bump SIG image version to 2021.08.31

- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/osimageconfig.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
* Bump SIG image version to 2021.08.31
Co-authored-by: Charlie Li <charlili@microsoft.com>
> Bump SIG image version to 2021.08.31 (#1082)

- vhdbuilder/release-notes/AKSCBLMariner/gen1/2021.08.31.txt
- vhdbuilder/release-notes/AKSCBLMariner/gen2/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804containerd/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipscontainerd/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipsgpucontainerd/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpu/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpucontainerd/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804containerd/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipscontainerd/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipsgpucontainerd/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/2021.08.31.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpucontainerd/2021.08.31.txt
AKS Linux VHD release notes 2021.08.31
> AKS Linux VHD release notes 2021.08.31

- .pipelines/.vsts-Marketpalce-win.yaml
- .pipelines/.vsts-vhd-builder-release-windows.yaml
- .pipelines/.vsts-vhd-builder-release.yaml
- .pipelines/.vsts-vhd-builder-windows.yaml
- .pipelines/.vsts-vhd-builder.yaml
- Makefile
should get us a newer packer version, I think?
> chore: update go-dev to 1.34.0

- vhdbuilder/packer/components.json
> cache CNS v1.4.9 image

- vhdbuilder/packer/components.json
I'm merging it after the build tests pass as @daweim0 does not have write permissions to AgentBaker.
> adding omsagnet image ciprod08052021-1 (#1101)

- vhdbuilder/packer/components.json
Updating version to prevent issues from the older version.
> Cherry pick to update omsagent

- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/osimageconfig.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
bump sig image version to 2021.09.03
> bump sig image version to 2021.09.03

- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/osimageconfig.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
Co-authored-by: Charlie Li <charlili@microsoft.com>
> bump sig image version (#1116)

- vhdbuilder/release-notes/AKSCBLMariner/gen1/2021.09.03.txt
- vhdbuilder/release-notes/AKSCBLMariner/gen2/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804containerd/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipscontainerd/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipsgpucontainerd/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpu/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpucontainerd/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804containerd/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipscontainerd/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipsgpucontainerd/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/2021.09.03.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpucontainerd/2021.09.03.txt
AKS Linux VHD release notes - 2021.09.03
> AKS Linux VHD release notes - 2021.09.03

- vhdbuilder/packer/components.json
there's one bug in the old image tag(not in use yet).
replace it with a fixed one.
> replace the tunnel-front with a new tag with fix.

- parts/linux/cloud-init/artifacts/mariner/cse_install_mariner.sh
- pkg/templates/templates_generated.go
rsyslog is required by the AMA VM extension.
> Add rsyslog to CBLMariner

- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.2183.210915.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.2183.210915.txt
https://support.microsoft.com/en-us/topic/september-14-2021-kb5005568-os-build-17763-2183-d19b2778-204a-4c09-a0c3-23dc28d5deac
> doc: Add release notes for AKS Windows VHD with 2021-9B

- vhdbuilder/release-notes/AKSCBLMariner/gen1/2021.09.19.txt
- vhdbuilder/release-notes/AKSCBLMariner/gen2/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1604/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804containerd/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipscontainerd/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipsgpucontainerd/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpu/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpucontainerd/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804containerd/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipscontainerd/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipsgpucontainerd/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/2021.09.19.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpucontainerd/2021.09.19.txt
AKS Linux VHD release VHD - 2021.09.19
> AKS Linux VHD release VHD - 2021.09.19

- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/osimageconfig.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> Bump the Linux SIG version

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/windows-image.env
Add Windows 2021 9C
https://support.microsoft.com/en-us/topic/september-21-2021-kb5005625-os-build-17763-2210-preview-5ae2f63d-a9ce-49dd-a5e6-e05b90dc1cd8
> chore: Add Windows 2021 9C

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache Windows Azure CNI v1.4.12
https://github.com/Azure/azure-container-networking/releases/tag/v1.4.12
> chore: Cache Windows Azure CNI v1.4.12

- vhdbuilder/packer/components.json
weekly image cve patching from Sec Pipelines
> weekly image cve patching from Sec Pipelines

- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/osimageconfig.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
Weekly Release - Bump Image Version
> Bump SIG Image Version to 2021.09.25

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache Windows scripts to collect hns trace
> Cache Windows scripts to collect hns trace

- vhdbuilder/packer/components.json
bump the tunnel front image with cve fix.
> bump the tunnel front image with cve fix.

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Remove unused cahced omsagent windows image
> Remove unused cahced omsagent windows image

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
1. cache windows cse
2. Remove unused azure-cloud-node-manager
3. Remove unused azure cni v1.4.9 and v1.4.12
> Update cache files in Windows VHD

- vhdbuilder/packer/components.json
> update cns versions

- .pipelines/.vsts-vhd-builder-release.yaml
- pkg/agent/datamodel/sig_config.go
- Freeze 1604 to the latest image
- Not build 1604 anymore
> Freezing 1604

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache AKS Windows CSE scripts package v0.0.2
> Cache AKS Windows CSE scripts package v0.0.2

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- Cache AKS Windows CSE scripts package v0.0.3
- Update README for AKS Windows CSE scripts package v0.0.3
> chore: Cache AKS Windows CSE scripts package v0.0.3

- e2e/e2e-script.sh
- Print duration of Azure operations.
- Replace arbitrary sleeps with loops.
- Improve script output.
> Add timing info to e2e script

- .pipelines/.vsts-vhd-builder-release.yaml
- .pipelines/.vsts-vhd-builder.yaml
- .pipelines/templates/.builder-release-template.yaml
- packer.mk
- vhdbuilder/packer/init-variables.sh
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
1. Add a new vhd build skeletion for new arch
2. New vhd build VM for new arch is created and then install-dependencies.sh starts
3. new installation logic will be added in following PRs to keep each PR small.
> New Ubuntu VHD build skeleton for ARM arch

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Update cache in AKS Windows VHD
> chore: Update cache in AKS Windows VHD

- vhdbuilder/packer/windows-image.env
https://support.microsoft.com/en-us/topic/december-14-2021-kb5008218-os-build-17763-2366-0d9c500d-6e71-4cb4-99e2-416655622769
> chore: Update Windows base image to 2021-12b

- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.2366.211215.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.2366.211215.txt
Add release notes for AKS Windows VHD with 2021-12B
> doc: Add release notes for AKS Windows VHD with 2021-12B

- staging/cse/windows/configfunc.ps1
- staging/cse/windows/kubernetesfunc.ps1
Refine Get-LogCollectionScripts
> Refine Get-LogCollectionScripts

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- pkg/agent/datamodel/types.go
- vhdbuilder/packer/components.json
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804arm64containerd/2021.12.28.txt
Add arm distro sig info in order that AKS RP can consume it
> Add arm distro sig info in order that AKS RP can consume it

- vhdbuilder/packer/components.json
add csi-node-driver-registrar v2.0.1 back
> add csi-node-driver-registrar v2.0.1 back

- pkg/agent/datamodel/osimageconfig.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
update image version in v20220101 branch
> update image version in v20220101 branch

- vhdbuilder/release-notes/AKSCBLMariner/gen1/2022.01.07.txt
- vhdbuilder/release-notes/AKSCBLMariner/gen2/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804containerd/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipscontainerd/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipsgpucontainerd/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpu/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpucontainerd/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804containerd/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipscontainerd/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipsgpucontainerd/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/2022.01.07.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpucontainerd/2022.01.07.txt
> 2021.01.07 release notes

- vhdbuilder/packer/components.json
remove one more duplicate version
> remove one more duplicate version

- pkg/agent/datamodel/sig_config.go
- pkg/aks-engine/helpers/helpers.go
https://github.com/Azure/AgentBaker/commit/150bd9dda6ae1cf713c5ceb9c19afff47a8add64
> Cherry pick PR -> fix more china region detections (#1413)

- vhdbuilder/packer/windows-image.env
chore: Update Windows base image to 2022-1b
> chore: Update Windows base image to 2022-1b

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
> Add Windows 2022-1B patch

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/linux-vhd-content-test.sh
* update k8s hotfix
* update v1.21.2 hotfix
* fix test
> chore: update k8s hotfix for k8s >=1.21.0 (#1481)

- e2e/e2e-script.sh
This PR addresses the following:
1) Flaky permission error for cluster-provision.log, add sudo to always be able to fetch the log
2) Delete VMSS and subsequently also delete node from the cluster(since it turns to NotReady post VMSS deletion)
> e2e script improvement #2

- pkg/agent/datamodel/sig_config.go
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804arm64containerd/2022.02.05.txt
bump arm64 sig to 2022.02.05 and release notes
> bump arm64 sig to 2022.02.05 and release notes

- vhdbuilder/packer/test/run-test.sh
VHD content test logs the VM password.
set +x to avoid the above
https://msazure.visualstudio.com/CloudNativeCompute/_workitems/edit/13221115
> set +x for VHD test vm password

- pkg/agent/datamodel/sig_config.go
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804arm64containerd/2022.02.12.txt
bump arm64 sig to 2022.02.12 and release notes
> bump arm64 sig to 2022.02.12 and release notes

- staging/cse/windows/kubernetesfunc.ps1
fix: correct the file name for csi proxy
This needs to publish a new CSE pacakge
> fix: correct the file name for csi proxy

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache windows-gmsa-ccgakvplugin-v1.1.4.zip (Support AzureChinaCloud, AzureUSGovCloud, etc.)
> chore: Cache windows-gmsa-ccgakvplugin-v1.1.4.zip

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
1. Cache AKS Windows CSE package v0.0.5
2. Update release notes for AKS CSE package
> chore: Cache AKS Windows CSE package v0.0.5

- vhdbuilder/packer/components.json
cache multi-arch run-command image currently used by AKS RP
> cache multi-arch run-command image currently used by AKS RP

- vhdbuilder/packer/components.json
> upgrade cns to 1.4.19

- pkg/agent/datamodel/sig_config.go
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804arm64containerd/2022.02.19.txt
update arm64 sig version to 2022.02.19
> update arm64 sig version to 2022.02.19

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
Update AKS Windows VHD to 17763.2565.220222 with new cached pacakges.
> Update AKS Windows VHD to 17763.2565.220222

- staging/cse/windows/README
It should be merged with #1571
> chore: add release note for windows cse package v0.0.6

- vhdbuilder/scripts/windows/collect-windows-logs.ps1
collect bootstrap-config in Windows nodes
> chore: collect bootstrap-config in Windows nodes

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Update Windows VHD cache with adding Azure CNI v1.4.19
> Update Windows VHD cache with adding Azure CNI v1.4.19

- pkg/agent/datamodel/sig_config.go
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804arm64containerd/2022.03.05.txt
> Update ARM64 SIG version

- staging/cse/windows/kubernetesfunc.ps1
Exclude dockerd in Microsoft Defender
> Exclude dockerd in Microsoft Defender

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache AKS Windows CSE scripts package v0.0.7
- Exclude dockerd in Microsoft Defender #1600
> Cache AKS Windows CSE scripts package v0.0.7

- vhdbuilder/packer/components.json
> Add new Konnectivity image

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
omsagent march 11 2022 release
> omsagent march 11 2022 release

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache AKS Windows CNI v1.4.21 for #1625
> chore: Cache AKS Windows CNI v1.4.21

- vhdbuilder/packer/components.json
- vhdbuilder/packer/install-dependencies.sh
> update cni versions

- vhdbuilder/packer/windows-vhd-builder-sig.json
> Add tag in building VM

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/windows-vhd-builder.json
> Use Windows containerd 1.6

- parts/linux/cloud-init/artifacts/mariner/cse_install_mariner.sh
- pkg/templates/templates_generated.go
- vhdbuilder/packer/install-dependencies.sh
- update linux image to multiarch ciprod03172022
- update windows image to win-ciprod03172022
> update omsagent images

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/support.md
- .github/PULL_REQUEST_TEMPLATE.md
> doc: add issue and PR templates

- pkg/agent/datamodel/sig_config.go
Update ARM64 SIG version for next release
Fixes #
```
none
```
> Update ARM64 SIG version for next release

- pkg/agent/datamodel/sig_config.go
update the arm64 sig version for next release
Fixes #
```
none
```
> update the arm64 sig version for next release

- vhdbuilder/packer/components.json
> Updated CNS Version to v1.4.23

- pkg/agent/datamodel/sig_config.go
update the arm64 sig version for next release
Fixes #
```
none
```
> update the arm64 sig version

- vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
add missing disk_queue.service for arm64 pipeline
Fixes #
```
none
```
> add missing disk_queue.service for arm64 pipeline

- doc/WindowsGmsaCCGAKVPlugin.md
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
> chore: Cache Windows gMSA CCGAKVPlugin package v1.1.5

- parts/windows/kuberneteswindowssetup.ps1
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- pkg/templates/templates_generated.go
/kind design
Windows 2022 is the secure image, so it needn't run the SecureTLS.
Fixes #
Windows 2022 skip running the SecureTLS script
```
none
```
> Windows 2022 skip running the SecureTLS script

- vhdbuilder/packer/windows-image.env
/kind feature
Windows base image update to 2022-4B, it contains security patch from Windows OS:
https://msrc.microsoft.com/update-guide/releaseNote/2022-Apr
So this PR updates the base image from 2022-3B to 2022-4B.
```
none
```
> chore: Update AKS Windows base image to 2022-4b

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.2803.220413.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.2803.220413.txt
- vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.643.220413.txt
/kind feature
Windows SIG image update to 2022-4B, it contains security patch from Windows OS:
https://msrc.microsoft.com/update-guide/releaseNote/2022-Apr
So this PR updates the Windows SIG image from 2022-3B to 2022-4B.
```
none
```
> chore: Update AKS Windows SIG image to 2022-4b

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache k8s 1.23.5 for Windows, as it is supported by AKS.
Fixes #
```
none
```
> chore: Cache k8s 1.23.5 for Windows

- .pipelines/templates/.builder-release-template.yaml
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/run-test.sh
> Fix post VHD tests for 20.04, correct artifact name for gen2 SKUs

- .pipelines/templates/.builder-release-template.yaml
- vhdbuilder/packer/install-dependencies.sh
> Fix chrony install for Mariner, only install for 18.04/20.04

- pkg/agent/bakerapi.go
- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/types.go
> Add a check for customized image

- .pipelines/.vsts-vhd-builder-release-windows.yaml
- .pipelines/.vsts-vhd-builder-windows.yaml
- .pipelines/templates/.builder-release-template-windows.yaml
- vhdbuilder/packer/cleanup.sh
- vhdbuilder/packer/init-variables.sh
- vhdbuilder/packer/windows-vhd-builder-sig.json
- vhdbuilder/packer/windows-vhd-builder.json
/kind build
Create nsg for Windows build VM. Need to improve it for #1728
Fixes #
```
none
```
> build: create nsg for Windows build VM

- vhdbuilder/packer/convert-osdisk-snapshot-to-sig.sh
- vhdbuilder/packer/init-variables.sh
- vhdbuilder/packer/test/linux-vhd-content-test.sh
- vhdbuilder/packer/test/run-pretest.sh
- vhdbuilder/packer/test/run-test.sh
/kind test
azure-cli 2.35.0 published on April 6 2022 supports 'az sig image-definition create --architecture...'. With it, we can add vhd content test in arm64 build pipeline
https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=54443241
Fixes #
```
none
```
> Test: add vhd content test for arm64 build pipeline

- vhdbuilder/packer/init-variables.sh
- vhdbuilder/packer/windows-vhd-builder-sig.json
- vhdbuilder/packer/windows-vhd-builder.json
/kind build
build: Update nsg tag for Windows VHD build VM
Fixes #
```
none
```
> build: Update nsg tag for Windows VHD build VM

- vhdbuilder/packer/components.json
- vhdbuilder/packer/install-dependencies.sh
/kind feature
Fixes #
```
none
```
> feat: add multiArch node-ca-watcher image to vhd

- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/vhd-image-builder-mariner-gen2.json
- vhdbuilder/packer/vhd-image-builder-mariner.json
/kind bug
Fixes #
```
none
```
> fix: prepull images for mariner, fix watcher image

- vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
> fix: bcc by pinning to v0.24.0

- pkg/agent/datamodel/sig_config.go
> chore: update the arm64 sig version to 2022.04.25

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Add Windows 2022-4C patch. It equals updating the Windows base image to 2022-4C.
```
none
```
> chore: Add Windows 2022-4C patch for Windows2022

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.681.220426.txt
/kind design
Update Windows 2022 SIG image to 2022-4C and add release note.
```
none
```
> chore: Update Windows 2022 SIG image to 2022-4C

- vhdbuilder/packer/components.json
> Add new app routing images

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- pkg/agent/datamodel/types.go
- vhdbuilder/release-notes/AKSUbuntu/gen1/2004containerd/2022.04.16.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/2004containerd/2022.04.16.txt
> Add 20.04 distro SIG config for RP to consume

- vhdbuilder/packer/components.json
/kind cleanup 
Removing azure npm versions that are not used in RP, for space reduction in VHD (we are hitting max space thresholds)
Fixes #
```
none
```
>  azure npm - remove unused versions

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind build
Windows VHD build pipeline check Signature to avoid the VHD has wrong Signature 
```
none
```
> Build: Windows VHD Build pipeline check Windows Defender Signature

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.2803.220428.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.2803.220428.txt
- vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.681.220428.txt
/kind build
Update AKS Windows SIG image with correct MSDefender register settings
```
In code files
```
> chore: Update AKS Windows SIG image with correct MSDefender register settings

- .pipelines/.vsts-vhd-builder-release-windows.yaml
- .pipelines/.vsts-vhd-builder-windows.yaml
- .pipelines/templates/.builder-release-template-windows.yaml
- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/test/run-test.sh
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
- vhdbuilder/packer/windows-vhd-builder-sig.json
- vhdbuilder/packer/windows-vhd-builder.json
/kind build
Support to set windows patch by environment
Fixes #
```
none
```
> build: Support to set windows patch by environment

- pkg/agent/datamodel/sig_config.go
chore: update arm64 sig version for next release
Fixes #
```
none
```
> chore: update arm64 sig version for next release

- vhdbuilder/packer/test/windows-vhd-content-test.ps1
Test PackagesPlugins in Windows VHD build pipeline
> test: Check Azure Extensions in AKS Windows VHD build pipeline

- vhdbuilder/packer/components.json
Vendor new nmi image to VHD
Fixes #
```
Update NMI image to 1.8.8
```
> feat: update nmi image

- vhdbuilder/packer/generate-vhd-publishing-info.sh
- vhdbuilder/publish/Marketplace/new-sku-and-add-image-version.sh
/kind: build
1. remove list permission
2. redact token in logs
Fixes #
```
none
```
> chore: remove list permission and redact token in logs

- parts/linux/cloud-init/artifacts/update_certs.path
- pkg/templates/templates_generated.go
/kind bug
Changes activation of custom CA trust to speed it up
Fixes #
```
none
```
> Change systemd path unit activation criteria, make generate

- .pipelines/.vsts-vhd-builder-release-windows.yaml
- .pipelines/.vsts-vhd-builder-windows.yaml
- .pipelines/templates/.builder-release-template-windows.yaml
- vhdbuilder/packer/init-variables.sh
/kind build
Support setting Windows base image via pipeline variables
Fixes #
```
none
```
> build: Support setting Windows base image via pipeline variables

- .pipelines/.vsts-vhd-builder-release.yaml
> Add Ubuntu 20.04 CVM skeleton

- vhdbuilder/packer/components.json
> Add new multi-arch app routing operator image

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache k8s 1.24.0 for Windows
Fixes #
```
none
```
> chore: cache 1.24.0 for Windows

- pkg/agent/datamodel/osimageconfig.go
> Cherry pick "add to image map (#1799)" to official/v20220510

- pkg/agent/datamodel/sig_config.go
/kind feature
Fixes #
```
none
```
> Update ARM64 SIG version for next weekly release

- .github/workflows/codeql-analysis.yml
/kind cleanup
Setup codeql scan action 
Fixes #
```
none
```
> Chores:Setup codeql action

- vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
> fix: temporary dupe gpu install

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache new AKS Windows CSE scripts package v0.0.9
Fixes #
```
none
```
> chore: Cache new AKS Windows CSE scripts package v0.0.9

- vhdbuilder/packer/components.json
> bake the new tunnel images with cve.

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind bug
fix: Install cat file for Windows docker 20.10.9
Fixes #
```
none
```
> fix: Install cat file for Windows docker 20.10.9

- .pipelines/e2e.yaml
> switch to use the auto teardown pool.

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Cache AKS Windows containerd package v0.0.46 (v1.6.6)
Fixes #
```
none
```
> chore: Cache AKS Windows containerd package v0.0.46 (v1.6.6)

- vhdbuilder/packer/components.json
**What this PR does / why we need it**: Upgrade next cached version of CNS to 1.4.27
Fixes #
```
none
```
> cache cns 1.4.27

- vhdbuilder/packer/windows-image.env
/kind build
Windows has the security patch on 2022-6b: https://msrc.microsoft.com/update-guide/releaseNote/2022-Jun
Update Windows base image to 2022-6b
```
none
```
> chore: Update Windows base image to 2022-6b

- vhdbuilder/packer/components.json
- vhdbuilder/packer/install-dependencies.sh
/kind feature
**What this PR does / why we need it**: Adds the Overlay azure-vnet flavor to the VHD cache
Fixes #
```
none
```
> add overlay azure-vnet versions and download

- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/linux-vhd-content-test.sh
upgrade kubelet version
Fixes #
```
none
```
> Bump kubelet version

- vhdbuilder/packer/sha1rsa_custom_data
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2.json
/kind bug
readd sha1-custom-data to mariner2-gen2 builder to fix Mariner 2.0 builds
```
none
```
> fix: readd sha1-custom-data to mariner2-gen2 builder to fix Mariner 2.0 builds

- staging/cse/windows/configfunc.ps1
/kind feat
For #1913
Fixes #
```
none
```
> feat: Update the command to exclude UDP source port in Windows node

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/build
Cache new Windows CSE package v0.0.10
Fixes #
```
none
```
> chore: Cache new Windows CSE package v0.0.10

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.3046.220624.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.3046.220624.txt
- vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.768.220624.txt
/kind feature
- [build: Windows use containerd v0.0.46 and remove useless cache #1894](https://github.com/Azure/AgentBaker/pull/1894)
- [omsagent June 2022 release #1897](https://github.com/Azure/AgentBaker/pull/1897)
- [chore: Cache new Windows CSE package v0.0.10 #1925](https://github.com/Azure/AgentBaker/pull/1925)
Fixes #
```
Update AKS Windows SIG image versions to 17763.3046.220624 for WS2019 and 20348.768.220624 for WS2022
```
> chore: Update new AKS Windows SIG image versions

- .pipelines/.vsts-vhd-builder-release-windows.yaml
- .pipelines/.vsts-vhd-builder-windows.yaml
- .pipelines/templates/.builder-release-template-windows.yaml
- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/init-variables.sh
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
- vhdbuilder/packer/windows-vhd-builder-sig.json
- vhdbuilder/packer/windows-vhd-builder.json
/build
Support to load Windows container images from local tar files
Fixes #
```
none
```
> build: Support to load Windows container images from local tar files

- vhdbuilder/packer/configure-windows-vhd.ps1
/build
Remove temporary tar file after loading the image from the tar file. Otherwise, the disk space may not be enough.
Fixes #
Test Logs:
```
azure-arm: 2022-06-29T02:42:39.7599955+00:00: Removing tmp tar file C:\Users\packer\AppData\Local\Temp\servercore.tar
azure-arm: 2022-06-29T02:45:09.4436226+00:00: Removing tmp tar file C:\Users\packer\AppData\Local\Temp\nanoserver.tar
```
```
none
```
> fix: Remove temporary tar file

- vhdbuilder/packer/components.json
/kind cleanup
Some distro VHD content size is greater than 30GB now, so VHD build fails. Remove some image caches not used by RP for a while to free some VHD space.
Fixes #
```
none
```
> Remove some image caches not used by RP for a while to free some VHD space

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind vhd
Cache AKS Windows CSE package v0.0.11
Fixes #
```
none
```
> chore: Cache AKS Windows CSE package v0.0.11

- pkg/agent/datamodel/sig_config.go
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804arm64containerd/2022.07.12.txt
> arm64 sig 2022.07.12 release notes

- vhdbuilder/packer/windows-image.env
/kind feature
1. WS2019: [July 12, 2022—KB5015811 (OS Build 17763.3165)](https://support.microsoft.com/en-gb/topic/july-12-2022-kb5015811-os-build-17763-3165-f3bdb13c-d767-47dc-a077-0ea0e9421a96)
2. WS2022: [July 12, 2022—KB5015827 (OS Build 20348.825)](https://support.microsoft.com/en-us/topic/july-12-2022-kb5015827-os-build-20348-825-b115183f-66b8-4eea-a631-5255a39b5991) 
Fixes #
```
none
```
> chore: Update Windows base image to 2022.07B

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
Clean unused Windows cache
Fixes #
```
none
```
> chore: Clean unused Windows cache

- vhdbuilder/release-notes/AKSUbuntu/gen2/1804arm64containerd/2022.07.19.txt
> arm64 2022.07.19 release notes

- pkg/agent/baker.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- pkg/agent/datamodel/types.go
- pkg/agent/variables.go
/kind feature
Fixes #
```
none
```
> add marinerv2 sig config and distro

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.3232.220722.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.3232.220722.txt
- vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.859.220722.txt
/kind feature
Update AKS Windows images to 2022.07C. Reference: https://github.com/Azure/AgentBaker/pull/1997
Fixes #
```
Update the latest Windows image versions with 2022.7C
- Windows2019 docker: 17763.3232.220722
- Windows2019 contaienrd: 17763.3232.220722
- Windows2022 containerd: 20348.859.220722
```
> chore: Update AKS Windows images to 2022.07C

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
This reverts commit 46b7c892d181ab38dfc6ca58ec05584d99ea7e71.
Fixes #
```
none
```
> Revert "Bumping image version to 2022.07.25 (#2009)"

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
/kind feature
AKS RP always uses a configuration file to set the latest SIG image versions for Windows so we set the latest Windows SIG image versions to empty in AgentBaker
Fixes #
```
none
```
> chore: Set the latest Windows SIG image versions to empty

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
update secrets-store-csi-driver to 1.2
Fixes #
```
chore: cache secrets-store-csi-driver v1.2.2
```
> chore: cache secrets-store-csi-driver v1.2.2

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
cache windows (only supported on ws2022 in AKS) CNS and NPM images
Fixes #
```
none
```
> chore: cache windows CNS and NPM images

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Cache new Windows CSE package v0.0.12
Fixes #
```
none
```
> build: Cache new Windows CSE package v0.0.12

- .pipelines/.vsts-vhd-builder-release.yaml
- vhdbuilder/release-notes/autonotes/main.go
> set CVM to always build, add to autonotes

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> fix: cvm version sync

- vhdbuilder/packer/test/run-test.sh
> Enable VHD Test for arm64 22.04

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Better comments with the owner.
No fix.
```
none
```
> chore: Arrange Windows cache with comment owner

- vhdbuilder/packer/components.json
- vhdbuilder/packer/install-dependencies.sh
> remove some unused image versions

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/kube-proxy-images.json
- vhdbuilder/packer/test/linux-vhd-content-test.sh
/kind cleanup
Fixes #
```
none
```
> chore: removed unused k8s 1.21 components

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/windows-image.env
/kind feature
Update Windows base images to 2022.08B
- WS2019: [August 9, 2022—KB5016623 (OS Build 17763.3287)](https://support.microsoft.com/en-us/topic/august-9-2022-kb5016623-os-build-17763-3287-c7a0bb3a-4083-4cd0-b9ad-119d9267628b)
- WS2022: [August 9, 2022—KB5016627 (OS Build 20348.887)](https://support.microsoft.com/en-us/topic/august-9-2022-kb5016627-os-build-20348-887-ef67367f-fab3-4d0c-8e80-72ac5a66d7d9)
Fixes #
```
none
```
> chore: Update Windows base images to 2022.08B

- vhdbuilder/scripts/automate_version_bump.sh
> fix: ignore arm64 linux version in vhd automation

- vhdbuilder/scripts/automate_generate_version.sh
- vhdbuilder/scripts/automate_version_bump.sh
> add image version var in generate version; revert image generation

- vhdbuilder/scripts/automate_helpers.sh
> fix: force push automation branch

- vhdbuilder/scripts/automate_version_bump.sh
> fix: force push a few more places

- .pipelines/.vsts-vhd-builder.yaml
- .pipelines/templates/.builder-release-template.yaml
- e2e/e2e-scenario.sh
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
- vhdbuilder/packer/vhd-image-builder-gen2.json
- vhdbuilder/packer/vhd-image-builder-sig.json
- vhdbuilder/packer/vhd-image-builder-sigminimal.json
- vhdbuilder/packer/vhd-image-builder.json
- vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
> bump asc baseline to 1.1.0-168

- vhdbuilder/release-notes/AKSUbuntu/gen2/1804arm64containerd/2022.08.09-image-list.json
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804arm64containerd/2022.08.09.txt
> ARM64 Sig 2022.08.09 release notes

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Fixes #
```
Container Insights Aug Release
```
> ciprod08102022 release

- pkg/agent/baker.go
- pkg/agent/variables.go
> fix: cblmariner -> mariner for v2 (#2096)

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Cache new AKS Windows CSE package v0.0.13
Fixes #
```
none
```
> chore: Cache new AKS Windows CSE package v0.0.13

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- pkg/agent/datamodel/types.go
Add new sig image in AgentBaker for RP to use later.
To support Windows Gen 2 VM sizes. Currently AgentBaker does not have Windows Gen 2 sig.
Fixes #
```
none
```
> Add new Windows sig distro for gen 2

- staging/cse/windows/containerdfunc.ps1
- staging/cse/windows/containerdfunc.tests.ps1
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind upgradation
upgrade windows containerd to v0.0.47
Fixes #
```
none
```
> chore: upgrade windows containerd to v0.0.47

- vhdbuilder/scripts/automate_version_bump.sh
> fix: branch versioning for vhd automation

- vhdbuilder/scripts/automate_release_notes.sh
- vhdbuilder/scripts/automate_version_bump.sh
> fix typo, release notes generation in vhd automation

- vhdbuilder/scripts/automate_version_bump.sh
> fix: avoid bad branch check

- vhdbuilder/packer/sysprep.ps1
See if we should take care of WindowsAzureNetAgentSvc in sysprep.
/kind bug
Log says "cannot find any service with service name 'Windows Azure Guest Agent'". Will check the service status and stop it if it's running. Do nothing otherwise.
Fixes #
```
none
```
> fix: Handle WindowsAzureNetAgentSvc in sysprep

- .pipelines/.vsts-vhd-builder-release-windows.yaml
- .pipelines/.vsts-vhd-builder-windows.yaml
- .pipelines/templates/.builder-release-template-windows.yaml
- packer.mk
- vhdbuilder/packer/cleanup.sh
- vhdbuilder/packer/init-variables.sh
- vhdbuilder/packer/test/run-test.sh
- vhdbuilder/packer/windows-image.env
Build Gen2 VHD for 2022 containerd
/kind feature
To add support of building Windows 2022 containerd Gen 2 VHD in AgentBaker.
Fixes #
```
none
```
> feat: Build Windows 2022 Containerd Gen 2 VHD

- cmd/main.go
- cmd/starter/start.go
Co-authored-by: Ubuntu <andliu@devbox.rws0oxdtctoulkaanznumdrtch.ix.internal.cloudapp.net>
Fixes #
```
none
```
> setup one entrypoint for the agentbakersvc. (#2145)

- .pipelines/templates/.builder-release-template-windows.yaml
/kind fix
Set mode in cleanup
Fixes #
```
none
```
> fix: Set mode in cleanup

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Cache new AKS Windows CSE package v0.0.14
Fixes #
```
none
```
> chore: Cache new AKS Windows CSE package v0.0.14

- .pipelines/.vsts-vhd-builder.yaml
/kind test
Use 22.04 to run agentbaker PR arm6 validation because we switch from 18.04 to 22.04 for arm64 nodes
Fixes #
```
none
```
> Use 22.04 to run agentbaker PR arm6 validation

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
Remove unused cached packages in Windows VHD
Fixes #
```
none
```
> chore: Remove unused cached packages in Windows VHD

- .pipelines/e2e.yaml
> fix: only trigger on main/official PRs

- vhdbuilder/packer/windows-image.env
/kind feature
Update Windows base images to 2022.09B
- WS2019: [September 13, 2022—KB5017315 (OS Build 17763.3406)](https://support.microsoft.com/en-us/topic/september-13-2022-kb5017315-os-build-17763-3406-926525b2-750e-42e2-9845-49924d97281c)
- WS2022: [September 13, 2022—KB5017316 (OS Build 20348.1006)](https://support.microsoft.com/en-us/topic/september-13-2022-kb5017316-os-build-20348-1006-677d67d2-4b41-49ae-a67f-dd6c83583008)
Fixes #
```
none
```
> chore: Update Windows base images to 2022.09B

- .pipelines/.vsts-vhd-automation.yaml
Update go version to 1.18.6, for Agentbaker release notes creation
Fixes #
```
none
```
> [chore] bump go version to 1.18.6

- pkg/agent/datamodel/sig_config.go
> pin Mariner to a good 08/29 version

- pkg/agent/datamodel/sig_config.go
> Pin Mariner 2.0 SIG image to 2022.08.29 temporarily (#2197)

- parts/linux/cloud-init/nodecustomdata.yml
- pkg/templates/templates_generated.go
> systemdcgroup = true for nvidia conf

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> fix: frozen docker image

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> fix: frozen docker image (#2207)

- pkg/agent/datamodel/sig_config.go
> reorder LinuxSIGImageVersion to appear first for automation

- staging/cse/windows/azurecnifunc.ps1
- staging/cse/windows/azurecnifunc.tests.ps1
- staging/cse/windows/provisioningscripts/cleanupnetwork.ps1
- staging/cse/windows/provisioningscripts/kubeletstart.ps1
- staging/cse/windows/provisioningscripts/kubeproxystart.ps1
- staging/cse/windows/provisioningscripts/windowsnodereset.ps1
/kind feature
•	[HNS.v2.psm1](https://github.com/Microsoft/SDN/raw/master/Kubernetes/windows/hns.v2.psm1): New HNS PowerShell module, uses v2 (“HCN”) representation of objects by default. It should be default with containerD. 
Fixes #
```
none
```
> feat: Use hns.v2.psm1 for Windows containerd in CSE package

- parts/windows/kuberneteswindowssetup.ps1
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- pkg/templates/templates_generated.go
- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Update
Update the version of cse package to v0.0.16.
Fixes #
```
none
```
> chore: update the version of cse package to v0.0.16

- .pipelines/.vsts-vhd-builder-release.yaml
- vhdbuilder/release-notes/autonotes/main.go
> always build 2204 images

- vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
/kind bug
Fixes #
```
none
```
> Switch from apt install to purge for 2204 cleanup

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> Cherry pick - update 2204 version

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
update
cache the latest version of windows vnet cni (v1.4.35)
Release notes: https://github.com/Azure/azure-container-networking/releases
Fixes #
```
none
```
> chore: cache windows vnet cni v1.4.35

- vhdbuilder/packer/components.json
Update Linux NPM version to current version
Fixes #
```
none
```
> chore: update npm to current version

- vhdbuilder/packer/components.json
Adding a new repo link for azure monitor metrics addon
> Adding a new repo link for azure monitor metrics addon

- pkg/agent/datamodel/sig_config.go
> fix: naming of kata sku

- pkg/agent/datamodel/sig_config.go
> fix: naming of kata sku (#2269)

- pkg/agent/datamodel/sig_config.go
Add aks sig image publisher const
Fixes #
```
none
```
> add aks sig image publisher const

- pkg/agent/datamodel/sig_config.go
- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Update CI agent to oct release
Monthly CI release.
Fixes #
```
none
```
> update ci for october release

- vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
/kind bug
Explicitly purge and hold non-fips kernel in FIPS VHD
Fixes #
```
none
```
> Explicitly purge and hold non-fips kernel in FIPS VHD

- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/kube-proxy-images.json
- vhdbuilder/packer/test/linux-vhd-content-test.sh
/kind cleanup
AKS stopped publishing new Docker VHDs recently. To reduce manual changes needed while updating k8s versions, this PR removes the unused Docker images.
Fixes #
```
none
```
> Remove unused kube-proxy images for docker

- pkg/agent/datamodel/sig_config.go
> Use new fips sig version 

- pkg/agent/datamodel/sig_config.go
> Use new FIPS SIG version

- pkg/agent/datamodel/sig_config.go
> update arm64 sig for next weekly release

- pkg/agent/datamodel/sig_config.go
- vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
> Rebuild FIPS image set for v20220922

- vhdbuilder/packer/install-dependencies.sh
> fix: vhd build logging for wasm

- vhdbuilder/packer/install-dependencies.sh
> fix: vhd build logging for wasm (#2287)

- pkg/agent/datamodel/sig_config.go
> remove 2204 and cvm 2004 sig consts

- vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
> remove unattended-upgrades in fips vhds

- vhdbuilder/packer/test/windows-vhd-content-test.ps1
1. Only log error in testing Windows VHD since there is length limitation in the response run-command
2. Compare HASH instead of length of the cached package
Fixes #
```
none
```
> chore: Improve win vhd test

- vhdbuilder/packer/components.json
> Update custom ca watcher image version

- vhdbuilder/packer/windows-image.env
/kind feature
Update Windows base images to 2022.08B
- WS2019: [October 11, 2022—KB5018419 (OS Build 17763.3532)](https://support.microsoft.com/en-us/topic/october-11-2022-kb5018419-os-build-17763-3532-ca62cca7-b599-44c4-a2a6-347996662623)
- WS2022: [October 11, 2022—KB5018421 (OS Build 20348.1129))](https://support.microsoft.com/en-us/topic/october-11-2022-kb5018421-os-build-20348-1129-115b1147-9568-4924-83b8-d27ab5b495be)
Fixes #
```
none
```
> chore: Update Windows base images to 2022.10B

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.3532.221012.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.3532.221012.txt
- vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.1129.221012.txt
/kind doc
Add release notes for AKS Windows images with 2022.10B
We still update sig_config.go although we do not use it.
Reference: https://github.com/Azure/AgentBaker/pull/2302
- WS2019: [October 11, 2022—KB5018419 (OS Build 17763.3532)](https://support.microsoft.com/en-us/topic/october-11-2022-kb5018419-os-build-17763-3532-ca62cca7-b599-44c4-a2a6-347996662623)
- WS2022: [October 11, 2022—KB5018421 (OS Build 20348.1129))](https://support.microsoft.com/en-us/topic/october-11-2022-kb5018421-os-build-20348-1129-115b1147-9568-4924-83b8-d27ab5b495be)
Fixes #
```
none
```
> doc: Add release notes for AKS Windows images with 2022.10B

- .github/dependabot.yml
/kind cleanup
fix dependabot job 
Fixes #
```
none
```
> add time schedule for dependabot jobs

- vhdbuilder/packer/components.json
/kind cleanup
Removing unused prometheus-collector images to free up space in Linux VHD.
Fixes #
```
none
```
> Remove unused prometheus-collector images

- .pipelines/templates/.builder-release-template.yaml
> fix TL publishing info

- vhdbuilder/packer/test/windows-vhd-content-test.ps1
/build
Remove hash rules in Windows VHD test script
Fixes #
```
none
```
> build: Remove hash rules in Windows VHD test script

- .pipelines/.vsts-vhd-builder-windows.yaml
/kind build
Always set DRY_DRUN to True in Windows check-in test pipeline and do not expose it in the parameters
Fixes #
```
none
```
> build: Always set DRY_DRUN to True in Windows check-in test pipeline

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/windows-image.env
/kind feature
Update Windows base images to 2022.10OOB
- WS2019: [October 17, 2022—KB5020438 (OS Build 17763.3534) Out-of-band](https://support.microsoft.com/en-us/topic/october-17-2022-kb5020438-os-build-17763-3534-out-of-band-cd499c1a-6d60-49a1-9a40-fad42c1d393a)
- WS2022: [October 17, 2022—KB5020436 (OS Build 20348.1131) Out-of-band](https://support.microsoft.com/en-us/topic/october-17-2022-kb5020436-os-build-20348-1131-out-of-band-18baa25a-5fc0-4118-9b89-ddbe9819e578)
Fixes #
```
none
```
> chore: Update Windows base images to 2022.10OOB

- parts/linux/cloud-init/artifacts/update_certs.sh
- pkg/templates/templates_generated.go
> remove set -x from custom ca update script

- pkg/agent/datamodel/const.go
> fix: use grid drivers for nc_a10_v4 sku

- vhdbuilder/packer/components.json
Tigera-operator v1.27.12 installs Calico version v3.23.3, which has necessary CVE fixes.
Release: https://github.com/tigera/operator/releases?q=1.27&expanded=true
Manifest: https://projectcalico.docs.tigera.io/archive/v3.23/manifests/tigera-operator.yaml
Fixes #
```
none
```
> chore: cache v1.27.12 image for tigera-operator

- pkg/agent/datamodel/const.go
> fix: use grid drivers for nc_a10_v4 sku (#2345)

- .github/workflows/auto-update.yml
> add auto update gh action

- .github/workflows/auto-update.yml
> fix typo in auto update

- e2e/e2e-scenario.sh
- e2e/matrix.json
- e2e/scenarios/vanilla-gpu/property-vanilla-gpu.json
> update PIR image to fresher SIG image for AB e2e

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
- Windows 2022: [October 25, 2022—KB5018485 (OS Build 20348.1194) Preview](https://support.microsoft.com/en-us/topic/october-25-2022-kb5018485-os-build-20348-1194-preview-becf7d1a-9482-4d56-955d-097e35b992a4)
Fixes #
```
none
```
> chore: Install Windows 2022-10C patch

- vhdbuilder/packer/components.json
- vhdbuilder/packer/install-dependencies.sh
> rip out old cnis

- vhdbuilder/packer/install-dependencies.sh
> added --purge to apt-get autoremove call

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.1194.221026.txt
- vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.1194.221026.txt
/kind doc
Add release notes for AKS Windows images with 2022.10C
We still update sig_config.go although we do not use it.
Reference #2373 
- Windows 2022: [October 25, 2022—KB5018485 (OS Build 20348.1194) Preview](https://support.microsoft.com/en-us/topic/october-25-2022-kb5018485-os-build-20348-1194-preview-becf7d1a-9482-4d56-955d-097e35b992a4)
Fixes #
Do not add release note since we do not use agentbaker to set the latest AKS Windows images.
```
none
```
> doc: Add release notes for AKS Windows images with 2022.10C

- .pipelines/.vsts-vhd-builder.yaml
- .pipelines/templates/.builder-release-template.yaml
> fix missing SIG_GALLERY_NAME in convert SIG to blob step of linux VHD build pipeline

- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/scripts/linux/ubuntu/tool_installs_ubuntu.sh
> fix CVM grub-install; tweak command ordering for space/fips 

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind build
Enable a HNS fix in WS2019 with 2022.11B
Fixes #
```
none
```
> build: Enable a HNS fix in WS2019 with 2022.11B

- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipscontainerd/2022.10.06-image-list.json
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipscontainerd/2022.10.06.txt
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipsgpucontainerd/2022.10.06-image-list.json
- vhdbuilder/release-notes/AKSUbuntu/gen1/1804fipsgpucontainerd/2022.10.06.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipscontainerd/2022.10.06-image-list.json
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipscontainerd/2022.10.06.txt
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipsgpucontainerd/2022.10.06-image-list.json
- vhdbuilder/release-notes/AKSUbuntu/gen2/1804fipsgpucontainerd/2022.10.06.txt
> add fips hotfix vhd 2022.10.06 release notes

- vhdbuilder/packer/generate-vhd-publishing-info.sh
/kind build
Add list permission back for the sas_token.
AKS at Edge Zone still needs this list permission when publishing PIR images in the marketplace.
Fixes #
```
none
```
> Add list permission for sas token

- staging/cse/windows/azurecnifunc.ps1
- staging/cse/windows/azurecnifunc.tests.ps1
- staging/cse/windows/azurecnifunc.tests.suites/AzureCNI.Overlay.conflist
/kind bug
Don't add cluster CIDR to CNI conflist if AzureCNIOverlay is enabled
Fixes #
Part 2 of PR #2408 
```
none
```
> fix: Don't add cluster CIDR to CNI Conflist if AzureCNIOverlay is Enabled 1/2

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind build
Cache new Windows calico v3.23.3
Reference: https://github.com/Azure/AgentBaker/pull/2364
Fixes #
```
none
```
> chore: Cache new Windows calico v3.23.3

- .pipelines/.vsts-vhd-builder-release-windows.yaml
/feature
Use a different agentpool to build Windows VHDs for prod
Fixes #
```
none
```
> build: Use a different agentpool to build Windows VHDs for prod

- vhdbuilder/packer/cleanup.sh
> cleanup dead comment

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Cache new AKS Windows script pacakge v0.0.19
Fixes #
```
none
```
> chore: Cache new AKS Windows script pacakge v0.0.19

- parts/windows/kuberneteswindowssetup.ps1
- pkg/agent/baker.go
- pkg/agent/datamodel/types.go
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- pkg/templates/templates_generated.go
/kind bug
Pass overlay mode to azurecnifunc.ps1
Fixes #
ran 'make generate' with new CSE script package v0.0.19 including changes in #2428 
```
none
```
> fix: Don't add Vnet CIDRs to CNI Conflist if AzureCNIOverlay is Enabled 2/2

- parts/windows/kuberneteswindowssetup.ps1
- pkg/agent/baker.go
- pkg/agent/datamodel/types.go
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- pkg/agent/variables.go
- pkg/templates/templates_generated.go
/kind feature
1. Support collecting AKS Windows logs in GuestVMLogs
2. Remove wrong code in pkg/agent/variables.go
Fixes #
```
none
```
> feat: Support collecting AKS Windows logs in GuestVMLogs

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind update
update windows pause image to 3.9
Fixes #
```
none
```
> chore: update windows pause image to 3.9

- vhdbuilder/packer/components.json
> cache latest CNS v1.4.39

- pkg/agent/bakerapi.go
- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- pkg/agent/datamodel/types.go
This reverts commit daee669fd73cc8d95479907cb97b646309175680.
Fixes #
```
none
```
> Revert "Add Edge Zone SIG definition (#2398)"

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- pkg/agent/datamodel/types.go
> add mariner trusted launch sig config

- parts/linux/cloud-init/artifacts/sysctl-d-60-CIS.conf
- pkg/templates/templates_generated.go
> fix inotify max user instances to 1024

- vhdbuilder/packer/components.json
/kind feature
Fixes #
```
none
```
> Add newer images for azure monitor metrics

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
> update container insight image

- vhdbuilder/packer/init-variables.sh
> bug: remove dead mariner tl code

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> fix: pin mariner v1 to 2022.11.12 due to app armor issue

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> fix: pin mariner v1 to 2022.11.12 due to app armor issue (#2483)

- .github/workflows/validate-components.yml
- .pipelines/scripts/verify_shell.sh
> fix required checks

- apiserver/getdistrosigimageconfig.go
- apiserver/getlatestsigimageconfig.go
- apiserver/getnodebootstrapdata.go
- apiserver/routers.go
- go.mod
- go.sum
> fix: add timeout and panic recovery handler for all absvc routes

- apiserver/getdistrosigimageconfig.go
- apiserver/getlatestsigimageconfig.go
- apiserver/getnodebootstrapdata.go
- apiserver/routers.go
- go.mod
- go.sum
> fix: add timeout and panic recovery handler for all absvc routes (#2496)

- .pipelines/.vsts-vhd-automation.yaml
> fix: go version desync in various checks

- vhdbuilder/packer/windows-image.env
/kind build
Windows security patch 2022-12B
- WS2019: [December 13, 2022—KB5021237 (OS Build 17763.3770)](https://support.microsoft.com/en-gb/topic/december-13-2022-kb5021237-os-build-17763-3770-8c1506cc-e030-4cf1-8cd6-774091f46f34)
- WS2022: [December 13, 2022—KB5021249 (OS Build 20348.1366)](https://support.microsoft.com/en-us/topic/december-13-2022-kb5021249-os-build-20348-1366-d5fe7608-bc9d-4055-a88c-fb2fd3d5fd45)
Fixes #
```
none
```
> chore: Update Windows base images with 2022.12B

- .pipelines/e2e.yaml
> move ab e2e pipeline to nodesigtest-pool

- .pipelines/e2e-windows.yaml
- e2e/e2e-create-windows-nodepool.sh
- e2e/e2e-windows-scenario.sh
- e2e/e2e_test.go
- e2e/matrix-windows.json
- e2e/pod-windows-template.yaml
- e2e/scenarios/windows/property-windows.json
- e2e/windows_vmss_template.json
/kind feature
create a windows e2e pipeline to test windows cse faster.
Fixes #
```
none
```
> chore: create windows e2e pipeline

- .pipelines/e2e-windows.yaml
- e2e/e2e-starter.sh
/kind bug
fix bug of creating new windows cluster with wrong network plugin
add branch condition for e2e-windows.yaml
Fixes #
```
none
```
> fix: fix bug of creating new windows cluster and add branch condition

- e2e/e2e-windows-scenario.sh
/kind bug
fix: fix useless use of cat
Fixes #
```
none
```
> fix: fix useless use of cat

- Makefile
- parts/windows/windowscsehelper.tests.ps1
- pkg/templates/templates_generated.go
- staging/cse/windows/cse.tests.ps1
/kind bug
run renamed unit test for windows cse
Fixes #
```
none
```
> fix: run renamed unit test

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
chore: bump cloud-node-manager images v1.23.24, v1.24.11, v1.25.5 and v1.26.0, remove old ones.
Fixes #
```
none
```
> chore: bump cloud-node-manager images

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
regularly upgrade. cache secrets-store-csi-driver v1.4.0
Fixes #
```
chore: cache secrets-store-csi-driver v1.3.0
```
> chore: cache secrets-store-csi-driver v1.3.0

- vhdbuilder/packer/windows-image.env
/kind build
Windows security patch 2023-1B
- WS2019: [January 10, 2023—KB5022286 (OS Build 17763.3887)](https://support.microsoft.com/en-gb/topic/january-10-2023-kb5022286-os-build-17763-3887-48683103-7b22-4f36-aa98-0049c7a6e579)
- WS2022: [January 10, 2023—KB5022291 (OS Build 20348.1487)](https://support.microsoft.com/en-us/topic/january-10-2023-kb5022291-os-build-20348-1487-38772acf-103f-463e-9d60-486174e806b2)
Fixes #
```
none
```
> chore: Update Windows base images with 2023.1B

- vhdbuilder/packer/components.json
Add latest Managed Prometheus addon image
Fixes #
See [here](https://github.com/Azure/prometheus-collector/blob/main/RELEASENOTES.md#release-01-11-2023)
> Update Managed Prometheus image for 01/11/23 release

- parts/windows/windowscsehelper.tests.ps1
/kind bug
Update Windows unit tests
Fixes #
```
none
```
> fix: Update Windows unit tests

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> fix: unpin mariner v1 image from apparmor issues

- vhdbuilder/packer/install-dependencies.sh
just naming convention things that bother me.
sanity
Fixes #
```
none
```
> clearer cni naming

- pkg/agent/bakerapi.go
- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- pkg/agent/datamodel/types.go
> Add Edge Zone SIG definition

- .pipelines/.vsts-vhd-automation.yaml
> fix: Update go version in automation

- parts/linux/cloud-init/artifacts/cse_main.sh
- pkg/templates/templates_generated.go
> refactor: remove sgx code

- parts/linux/cloud-init/artifacts/dhcpv6.service
- parts/linux/cloud-init/nodecustomdata.yml
- pkg/templates/templates_generated.go
> refactor: dhcpv6 without go template

- .pipelines/e2e.yaml
> switch to 1es msi for abe2e

- vhdbuilder/packer/packer_source.sh
- vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
- vhdbuilder/packer/vhd-image-builder-base.json
- vhdbuilder/packer/vhd-image-builder-mariner-gen2.json
- vhdbuilder/packer/vhd-image-builder-mariner.json
- vhdbuilder/packer/vhd-image-builder-mariner2-arm64.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2-kata.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2.json
- vhdbuilder/packer/vhd-image-builder-sigminimal.json
> refactor: add reconcile-private-hosts script to vhd

- vhdbuilder/packer/packer_source.sh
- vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
- vhdbuilder/packer/vhd-image-builder-base.json
- vhdbuilder/packer/vhd-image-builder-mariner-gen2.json
- vhdbuilder/packer/vhd-image-builder-mariner.json
- vhdbuilder/packer/vhd-image-builder-mariner2-arm64.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2-kata.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2.json
- vhdbuilder/packer/vhd-image-builder-sigminimal.json
> refactor: add mig partition script to vhd

- vhdbuilder/packer/packer_source.sh
- vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
- vhdbuilder/packer/vhd-image-builder-base.json
- vhdbuilder/packer/vhd-image-builder-mariner-gen2.json
- vhdbuilder/packer/vhd-image-builder-mariner.json
- vhdbuilder/packer/vhd-image-builder-mariner2-arm64.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2-kata.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2.json
- vhdbuilder/packer/vhd-image-builder-sigminimal.json
> refactor: add kubelet service to vhd; fix indentation of arm64 mariner2

- parts/linux/cloud-init/artifacts/crictl.yaml
- parts/linux/cloud-init/artifacts/nvidia-modprobe.service
- parts/linux/cloud-init/artifacts/sync-tunnel-logs.service
- parts/linux/cloud-init/artifacts/teleportd.service
- pkg/templates/templates_generated.go
- vhdbuilder/packer/packer_source.sh
- vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
- vhdbuilder/packer/vhd-image-builder-base.json
- vhdbuilder/packer/vhd-image-builder-mariner-gen2.json
- vhdbuilder/packer/vhd-image-builder-mariner.json
- vhdbuilder/packer/vhd-image-builder-mariner2-arm64.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2-kata.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2.json
- vhdbuilder/packer/vhd-image-builder-sigminimal.json
> refactor: add all missing non-core files to vhd

- vhdbuilder/packer/packer_source.sh
- vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
- vhdbuilder/packer/vhd-image-builder-base.json
- vhdbuilder/packer/vhd-image-builder-mariner-gen2.json
- vhdbuilder/packer/vhd-image-builder-mariner.json
- vhdbuilder/packer/vhd-image-builder-mariner2-arm64.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2-kata.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2.json
- vhdbuilder/packer/vhd-image-builder-sigminimal.json
> refactor: add all missing core files to vhd

- pkg/agent/datamodel/edge_zone_sig_version.json
> Bumping edge zone sig version to 2023.01.25

- vhdbuilder/packer/post-install-dependencies.sh
Co-authored-by: Charlie Li <charlili@microsoft.com>
Fixes #
```
none
```
> fix content of /proc/sys/crypto/fips_enabled on FIPS VHDs (#2709)

- e2e/e2e-windows-scenario.sh
- e2e/scenarios/windows/property-windows-template.json
test changes in windows cse package automatically
Fixes #
```
none
```
> chore: test changes in windows cse package automatically

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> bump: vhd to 2023.01.26 for fips fix

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> bump: 2023.01.20 vhd for fips issue

- pkg/agent/datamodel/linux_sig_version.json
- pkg/agent/datamodel/sig_config_test.go
Bumps the VHD version (for weekly Agentbaker release)
Fixes #
```
none
```
> Bump VHD to 2023.02.01

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Update Azure CNI to v1.4.41
lastest release https://github.com/Azure/azure-container-networking/releases/tag/v1.4.41
cache azure cni
Fixes #
```
none
```
> chore: cache windows azure cni v1.4.41

- pkg/agent/datamodel/linux_sig_version.json
- pkg/agent/datamodel/sig_config_test.go
> bump vhd to 0206

- vhdbuilder/packer/components.json
> remove unused cilium images

- pkg/agent/datamodel/linux_sig_version.json
- pkg/agent/datamodel/sig_config_test.go
> bump vhd to 0209

- .pipelines/e2e-windows.yaml
- .pipelines/templates/e2e-windows-template.yaml
- e2e/e2e-create-windows-nodepool.sh
- e2e/e2e-starter.sh
- e2e/e2e-windows-scenario.sh
- e2e/pod-windows-template.yaml
- e2e/scenarios/windows/property-windows-template.json
- e2e/windows_vmss_template.json
Support WS2022 and WS2022-gen2 in AgentBaker Windows E2E
Fixes #
```
none
```
> chore: support WS2022 and WS2022-gen2 in AgentBaker Windows E2E

- .pipelines/.vsts-vhd-builder-release.yaml
- pkg/agent/datamodel/mariner_v2_kata_gen2_tl_sig_version.json
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- pkg/agent/datamodel/types.go
> add kata TL sig config + release TL images weekly

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Update Windows Azure CNI to v1.4.43
https://github.com/Azure/azure-container-networking/releases/tag/v1.4.43
Fixes #
```
none
```
> chore: Update Windows Azure CNI to v1.4.43

- vhdbuilder/packer/windows-image.env
/kind build
Windows security patch 2023-02B
- WS2019: [February 14, 2023—KB5022840 (OS Build 17763.4010)](https://support.microsoft.com/en-us/topic/february-14-2023-kb5022840-os-build-17763-4010-e914539f-d2bc-4af9-bc01-5964c0ab3903)
- WS2022: [February 14, 2023—KB5022842 (OS Build 20348.1547)](https://support.microsoft.com/en-us/topic/february-14-2023-kb5022842-os-build-20348-1547-be155955-29f7-47c4-855c-34bd43895940)
Fixes #
```
none
```
> chore: update windows 2023 2b base image

- vhdbuilder/packer/generate-vhd-publishing-info.sh
/kind fix
fix vhd storage container name in #2765 
Fixes #
```
none
```
> fix: fix vhd storage container name

- vhdbuilder/packer/convert-sig-to-classic-storage-account-blob.sh
- vhdbuilder/packer/generate-vhd-publishing-info.sh
/kind feature
Validate generated sas token before publishing artifacts
Fixes #
Validated it in https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=68716276&view=logs&j=26d3b11b-de37-5bdb-7f8b-686d226a8fb0&t=e57474fd-ef2a-530e-8fb7-25622dad9b67 with reverting @junjiezhang1997 's fix.
```
none
```
> feat: Validate generated sas token before publishing artifacts

- pkg/agent/datamodel/linux_sig_version.json
- pkg/agent/datamodel/sig_config_test.go
> bump version v20230215

- staging/cse/windows/provisioningscripts/hnsremediator.ps1
/kind bug
Sometimes the cpu is very hot so `Get-WmiObject -Class Win32_Service -Filter "name='hns'" | Select-Object -ExpandProperty ProcessId` may return empty value. It is better to exit than restarting the services.
Fixes #
```
none
```
> fix: Validate whether the PID of HNS service is valid

- vhdbuilder/release-notes/AKSWindows/2019-containerd/17763.4010.230223.txt
- vhdbuilder/release-notes/AKSWindows/2019/17763.4010.230223.txt
- vhdbuilder/release-notes/AKSWindows/2022-containerd-gen2/20348.1547.230223.txt
- vhdbuilder/release-notes/AKSWindows/2022-containerd/20348.1547.230223.txt
Add release notes for new Windows image versions 230223 which have the same VHDs in 230216.
Fixes #
```
none
```
> doc: Add release notes for new Windows image versions 230223

- e2e/e2e-scenario.sh
> bump: test vhd to newer version

- vhdbuilder/packer/install-dependencies.sh
> chore: tidy up gpu install to save space

- vhdbuilder/packer/generate-vhd-publishing-info.sh
- vhdbuilder/scripts/automate_version_bump.sh
> feat: make vhd dates sortable

- e2e/e2e-scenario.sh
> fix: ssh logs for ab e2e

- pkg/agent/datamodel/const.go
> feat: add new a100 and h100 sku support

- pkg/agent/datamodel/const.go
> feat: add one more a100 sku to avoid naming issues

- .pipelines/.vsts-vhd-builder-release.yaml
- .pipelines/.vsts-vhd-builder.yaml
- .pipelines/templates/.builder-release-template.yaml
- vhdbuilder/packer/post-install-dependencies.sh
- vhdbuilder/packer/pre-install-dependencies.sh
> Build 2004fipscontainerd and 2004gen2fipscontainerd VHD images

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- pkg/agent/datamodel/types.go
> add sig image def for 2004 fips

- .pipelines/.vsts-vhd-builder-release.yaml
/kind cleanup
SGX is for Intel x64 architecture, there is no container images available for arm64 architecture. Trying to install it in install-dependencies.sh on arm64 has no effects, just a few failed pull attempts.
Fixes #
```
none
```
> Not install SGX on arm64 VHD

- .pipelines/.vsts-vhd-automation.yaml
- pkg/agent/datamodel/sig_config_test.go
- vhdbuilder/scripts/automate_version_bump.sh
> fix automation pipeline + bug fixes

- .pipelines/.vsts-vhd-automation.yaml
- pkg/agent/datamodel/linux_sig_version.json
- pkg/agent/datamodel/sig_config_test.go
- vhdbuilder/scripts/automate_version_bump.sh
> Bumping image version to 202303.06.0 (#2849)

- go.mod
- go.sum
- pkg/agent/baker.go
- pkg/agent/baker_test.go
/kind test
enable testing on generated testdata instead of using human eyeballs to guide snapshots
Fixes #
```
none
```
> test: decode customdata/cse and enable testing against contents

- vhdbuilder/packer/install-dependencies.sh
/kind cleanup
Clean up hardcoded logging for packages in favor of a dynamically generated list which is already there
Fixes #
```
none
```
> fix: drop logging packages hard-coded

- .clusterfuzzlite/Dockerfile
- .clusterfuzzlite/README.md
- .clusterfuzzlite/build.sh
- .clusterfuzzlite/project.yaml
- .github/workflows/cflite_batch.yaml
- .github/workflows/cflite_build.yaml
- .github/workflows/cflite_prune.yaml
- fuzz/README.md
- fuzz/csecmd/main.go
- fuzz/customdata/main.go
> test: fuzz with clusterfuzzlite

- README.md
> doc: contributing/testing

- vhdbuilder/packer/install-dependencies.sh
> bump cached nginx image to 1.21.6, only pull from MCR

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind feature
Retag Windows images for AzureChinaCloud to avoid downloading cached images in AzureChinaCloud.
Fixes #
```
none
```
> feat: Retag Windows images for AzureChinaCloud

- vhdbuilder/packer/windows-image.env
/kind feature
1. WS2019: [March 14, 2023—KB5023702 (OS Build 17763.4131)](https://support.microsoft.com/en-gb/topic/march-14-2023-kb5023702-os-build-17763-4131-f3e27d13-7dcc-4d32-826b-8d57e1600ccf)
2. WS2022: [March 14, 2023—KB5023705 (OS Build 20348.1607)](https://support.microsoft.com/en-us/topic/march-14-2023-kb5023705-os-build-20348-1607-31770c64-430e-4b0e-8eb4-175980e29f3b) 
Fixes #
```
none
```
> chore: Update Windows base image to 2023.03B

- staging/cse/windows/debug/collect-windows-logs.ps1
- staging/cse/windows/provisioningscripts/loggenerator.ps1
Add more Container Platform logs to collect-windows-logs.ps1 and loggenerator.ps1
Exclude commands of shimdiag.exe and hcsdiag.exe in loggenrator.ps1 to save the running time of it.
Fixes #
```
none
```
> chore: add more Container Platform logs to collect-windows-logs.ps1 and loggenerator.ps1

- CODEOWNERS
> ci: add owners file for temporary enforcement

- .github/workflows/golangci-lint-pr.yml
- .github/workflows/golangci-lint.yml
- .golangci.yaml
- README.md
- hack/tools/Makefile
> ci: add golangci-lint

- .pipelines/.vsts-vhd-builder.yaml
- .pipelines/templates/.builder-release-template.yaml
- vhdbuilder/packer/list-images.sh
- vhdbuilder/packer/trivy-scan.sh
- vhdbuilder/packer/vhd-image-builder-arm64-gen2.json
- vhdbuilder/packer/vhd-image-builder-base.json
- vhdbuilder/packer/vhd-image-builder-mariner-gen2.json
- vhdbuilder/packer/vhd-image-builder-mariner.json
- vhdbuilder/packer/vhd-image-builder-mariner2-arm64.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2-kata.json
- vhdbuilder/packer/vhd-image-builder-mariner2-gen2.json
- vhdbuilder/packer/vhd-image-builder-sigminimal.json
- vhdbuilder/release-notes/autonotes/main.go
> ci: add trivy scanner to vhd

- vhdbuilder/packer/install-dependencies.sh
> deps: bump nvidia-device-plugin to v0.13.0.7 to fix many cves

- .pipelines/e2e-windows.yaml
- .pipelines/templates/e2e-windows-template.yaml
- e2e/e2e-create-windows-nodepool.sh
- e2e/e2e-helper.sh
- e2e/e2e-starter.sh
- e2e/e2e-windows-scenario.sh
- e2e/e2e_test.go
/kind fix
1. Conflict may happen in AgentBaker Windows E2E pipeline when multiple pipelines try to create new clusters or nodepools at the same time. Add code to resolve conflict.
2. Conflict may happen in AgentBaker Windows E2E pipeline when multiple pipelines try to execute "kubectl" command after creating the cluster. Use "az vmss run-command" to upload linux cert files.
3. Add missing "retval=$?" in previous code.
Fixes #
```
none
```
> chore: resolve conflict of creating in AgentBaker Windows E2E

- CODEOWNERS
good to have a second approver with Abel or else he's blocked most of his working hours.
Fixes #
```
none
```
> owners: add thomas1206

- e2e/nsenter.go
- e2e/retry.go
- e2e/suite_test.go
> add retries to cluster creation fix

- vhdbuilder/packer/components.json
> chore: remove various components due to deprecation or lack of usage

- .github/workflows/commit-lint.yaml
github actions show it as "build" for a required status
Fixes #
```
none
```
> ci: rename lint message job for clarity

- fuzz/README.md
/kind cleanup
fix fuzzing docs after internal agentbaker refactor
Fixes #
```
none
```
> docs: fix fuzz docs

- .github/workflows/validate-windows-ut.yml
- staging/cse/windows/README
- staging/cse/windows/cse.tests.ps1
/kind feature
1. create a unit test pipleine for windows powershell unit test scripts.
2. remove cse.tests.ps1 since all .tests.ps1 files will be executed on ut pipeline.
3. update README for the remove of cse.tests.ps1.
Fixes #
```
none
```
> feat: create a unit test pipleine for windows powershell unit test scripts

- e2e/e2e-windows-scenario.sh
/kind bug
Add necessary permission for token to download cse logs and delete uploaded files in storage account.
Fixes #
```
none
```
> fix: add necessary permission for token

- e2e/cases.go
- e2e/cluster.go
- e2e/suite_test.go
- e2e/vmss.go
/kind feature
adds FIPS and Kata AgentBaker E2E scenarios
Fixes #
```
none
```
> feat: add fips and kata abe2e scenarios

- apiserver/apiserver.go
- apiserver/routers.go
- cmd/main.go
- cmd/starter/start.go
- e2e/e2e_test.go
- e2e/nsenter.go
- e2e/regex.go
- e2e/template_test.go
- e2e/vmss.go
- pkg/agent/baker.go
- pkg/agent/baker_test.go
- pkg/agent/const.go
- pkg/agent/datamodel/azenvtypes.go
- pkg/agent/datamodel/const.go
- pkg/agent/datamodel/helper.go
- pkg/agent/datamodel/helper_test.go
- pkg/agent/datamodel/mocks.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/types.go
- pkg/agent/datamodel/types_test.go
- pkg/agent/datamodel/versions.go
- pkg/agent/datamodel/versions_test.go
- pkg/agent/k8s_versions_for_baker_test.go
- pkg/agent/params.go
- pkg/agent/utils.go
- pkg/agent/variables.go
**What this PR does / why we need it**: Cleaning up lint errors. Comments and trailing white spaces fixed here
Fixes #
```
none
```
> style: reformatting all comments

- .golangci.yaml
> refactor: increase line length linter to 150

- vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind test
It's too slow to download the file from the China Cloud. So we only compare the file size.
Fixes #
```
none
```
> test: compare file size for China Cloud

- e2e/deploy.yaml
/kind bug
ensure abe2e debug pods are scheduled onto the correct nodepool
Fixes #
```
none
```
> fix: ensure e2e debug pods are scheduled onto aks nodepool

- e2e/template_test.go
> fix: really fix abe2e debug pod scheduling

- pkg/agent/baker.go
- pkg/agent/baker_test.go
- pkg/agent/bakerapi.go
- pkg/agent/bakerapi_test.go
- pkg/agent/datamodel/helper.go
- pkg/agent/datamodel/helper_test.go
- pkg/agent/datamodel/types.go
- pkg/agent/datamodel/types_test.go
- pkg/agent/datamodel/versions.go
- pkg/agent/datamodel/versions_test.go
- pkg/agent/utils.go
- pkg/agent/utils_test.go
- pkg/agent/variables.go
> refactor: fix lint errors for line length linter

- pkg/agent/baker.go
- pkg/agent/baker_test.go
- pkg/agent/datamodel/mocks.go
- pkg/agent/datamodel/types.go
- pkg/agent/params.go
- pkg/agent/utils.go
> refactor: refactor functions over 100 lines and complexity over 20

- vhdbuilder/release-notes/AKSUbuntu/gen1/1804gpucontainerd/latest-image-list.json
Add latest-image-list.json for 1804gpucontainerd release notes, since it was not added by the automated step.
Fixes #
```
none
```
> Update latest-image-list.json for 1804gpucontainerd

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Add AKS Windows CSE pacakge v0.0.23. NOTE: We do not update the version in Windows CSE.
Fixes #
```
none
```
> chore: add AKS Windows CSE pacakge v0.0.23

- .pipelines/e2e-windows.yaml
- .pipelines/templates/e2e-windows-template.yaml
- e2e/windows/scenarios/windows/property-windows-template.json
/kind cleanup
1. remove unnecessary properties (duplicate properties in nodebootstrapping_template.json and properties for linux) for windows e2e.
2. specify distro and node image version to avoid ambiguity.
Fixes #
```
none
```
> chore: clarify properties for windows e2e

- e2e/windows/README.md
/kind doc
Add README for Windows E2E.
Fixes #
```
none
```
> doc: add README for windows e2e

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
**What this PR does / why we need it**: Adding CNI & CNS update to support AKS Overlay on WS19.
```
none
```
> feat: Updating CNI & CNS to Support AKS Overlay on WS19

- vhdbuilder/scripts/automate_helpers.sh
- vhdbuilder/scripts/automate_version_bump.sh
> refactor: update automated commit messages to adhere to new rules

- vhdbuilder/packer/test/run-test.sh
This PR enables running post VHD content test on 22.04 images. Successful VHD run with all 22.04 images
https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=71507820&view=results
Fixes #
```
none
```
> refactor: run post VHD tests for 22.04

- e2e/suite_test.go
/kind bug
fixes nil pointer deref when abe2e fails due to a CSE error when provisioning vmss
Fixes #
```
none
```
> fix: nil dereference abe2e cse error case

- staging/cse/windows/debug/collect-windows-logs.ps1
/kind fix
Add file check for windows log script to avoid failing in the step of copying file.
Fixes #
```
none
```
> fix: add file check for windows log script

- e2e/suite_test.go
Fixes #
https://goplay.tools/snippet/wpHOkmnHEKD
```
none
```
> fix: only defer cleanupVMSS() if function is not nil

- vhdbuilder/packer/components.json
/kind update
These components are using an older version with CVEs, that has been flagged. Updating to fix that.
Fixes #
```
none
```
> fix: update addon-resizer and cluster-proportional-autoscaler to fix CVEs

- vhdbuilder/packer/test/run-test.sh
/kind fix
Add os type check for run-test.sh.
Fixes #
```
none
```
> fix: add os type check for run-test.sh

- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Add AKS Windows CSE pacakge v0.0.24. 
NOTE: We do not update the version in Windows CSE.
Fixes #
```
none
```
> chore: add AKS Windows CSE pacakge v0.0.24

- apiserver/routers.go
- cmd/starter/start.go
- pkg/agent/baker.go
- pkg/agent/baker_test.go
- pkg/agent/bakerapi.go
- pkg/agent/datamodel/helper.go
- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/types.go
- pkg/agent/datamodel/types_test.go
- pkg/agent/datamodel/versions.go
- pkg/agent/datamodel/versions_test.go
- pkg/agent/params.go
- pkg/agent/utils.go
- pkg/agent/variables.go
> refactor: fix unparm, gocritic, and errorlint lint errors

- .pipelines/.vsts-vhd-builder-release.yaml
This PR cleans up the docker SKUs we no longer build from the weekly build pipeline, reducing clutter.
Fixes #
```
none
```
> refactor: cleanup docker SKUs from weekly yaml

- vhdbuilder/packer/components.json
Update version for monitoring addon
It updates the image for monitoring addon
Fixes #
```
* Change log -
* Linux image - `mcr.microsoft.com/azuremonitor/containerinsights/ciprod/prometheus-collector/images:6.6.0-main-04-25-2023-2eb2a81c`
* Windows image - `mcr.microsoft.com/azuremonitor/containerinsights/ciprod/prometheus-collector/images:6.6.0-main-04-25-2023-2eb2a81c-win`
* Change log -
* feat: Add priorityclass system node critical for RS, DS & KSM pods
* fix:  Upgrades
Fluent bit           - from: `v1.9.6` to:`v2.0.9`
Telegraf(windows)    - from: `v1.23.4` to:`v1.24.2`
Otelcol              - from:`v0.66.0` …
```
> feat: update managed prometheus image april

- e2e/scenario/images.go
/kind fix
restores abe2e testing images
Fixes #
```
none
```
> fix: restore abe2e testing images

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
Fixes #
```
https://github.com/microsoft/Docker-Provider/blob/ci_prod/ReleaseNotes.md
```
> feat: containerinsights 3.1.7 release

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
- regularly upgrade. cache secrets-store-csi-driver v1.3.3.
- regularly upgrade. cache secrets-store-provider-azure v1.4.1.
- remove unused versions.
Fixes #
```
chore: cache secrets-store-csi-driver v1.3.3
```
> chore: cache secrets-store-csi-driver v1.3.3

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
upgrade CSI sidecar image versions to fix CVEs
This PR also removed unused sidecar images.
Fixes #
```
none
```
> chore: upgrade CSI sidecar image versions to fix CVEs

- vhdbuilder/packer/components.json
/kind feature
Adds the latest image for Managed Prometheus addon
Fixes #
Our release notes are [here](https://github.com/Azure/prometheus-collector/blob/main/RELEASENOTES.md)
> feat: Managed Prometheus 6.7.0 release image

- .pipelines/.vsts-vhd-builder-release-windows.yaml
- .pipelines/.vsts-vhd-builder-windows.yaml
/kind cleanup
disable building VHD for Windows 2019 with docker
Fixes #
```
none
```
> chore: disable building VHD for Windows 2019 with docker

- .pipelines/.vsts-vhd-automation.yaml
- .pipelines/e2e-windows.yaml
/kind cleanup
switch to use the variable ref on which pool to run the job, so we can do blue/green easier.
Fixes #
```
none
```
> chore: switch to use the variable ref on the agent.

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
> chore: bump vhd version to 0508, unpin cvm image (#3173)

- vhdbuilder/packer/windows-vhd-builder-sig.json
/kind bug
fix the managed image exists when multiple builds are run in parallel.
Run multiple builds in parallel or rerun a failed build to build a SIG image will hit below error.
1. Run multiple builds in parallel
https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=73036133&view=logs&j=05b0285b-7424-5da1-4fe4-29b48f7b1d3a&t=4f5de716-8c9d-57d8-0c59-15d673379c58&s=010eafe0-8ce4-5b6b-965b-36382273592e
```
==> azure-arm: Capturing image ...
==> azure-arm:  -> Compute ResourceGroupName : 'pkr-Resource-Group-pstvbj3tcd'
==> azure-arm:  -> Compute Name              : 'pkrvmpstvbj3tcd'
==> azure-arm:  -> Compute Location          : 'eastus'
==> azure-arm:  -> Image ResourceGroupName   : …
```
> fix: fix the managed image exists when multiple builds are run in parallel

- .pipelines/.vsts-vhd-builder-release-windows.yaml
- .pipelines/.vsts-vhd-builder-windows.yaml
- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
- vhdbuilder/packer/windows-vhd-builder-sig.json
- vhdbuilder/packer/write-release-notes-windows.ps1
/kind cleanup
clean: clean up build code for WS2019 with docker
Fixes #
Test SIG mode in https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=73167364&view=results
```
none
```
> build: clean up build code for WS2019 with docker

- staging/cse/windows/README
add doc to introduce how to test AKS Windows CSE scripts
Fixes #
```
none
```
> docs: add doc to introduce how to test AKS Windows CSE scripts

- .pipelines/.vsts-vhd-automation.yaml
> bump: vhd-automation go version

- parts/windows/kuberneteswindowssetup.ps1
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- pkg/templates/templates_generated.go
- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
update AKS Windows CSE script package to v0.0.25
Fixes #
```
none
```
> feat: update AKS Windows CSE script package to v0.0.25

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
cleanup: remove outdated csi images which has CVEs
all those images are not used by AKS rp, and contain CVEs
Fixes #
```
none
```
> cleanup: remove outdated csi images which has CVEs

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/write-release-notes-windows.ps1
…otes
/kind update
add the registry keys for bug fixes of Windows OS in release notes.
Fixes #
```
none
```
> chore: add the registry keys for bug fixes of Windows OS in release notes

- vhdbuilder/scripts/automate_helpers.sh
- vhdbuilder/scripts/automate_version_bump.sh
This PR should help fix commit lint for squash and merge while updating local branches since original automated PR titles did not adhere to commit lint.
Fixes #
```
none
```
> fix: change automated PR title format for commit lint

- .pipelines/.vsts-vhd-automation.yaml
Bump golang version to 1.20.4 for vhd automation
Fixes #
```
none
```
> bump: golang version for automation to 1.20.4

- .pipelines/templates/e2e-windows-template.yaml
/kind fix
Change condition of uploading artifacts to avoid uploading artifacts when step fails.
Fixes #
```
none
```
> fix: change condition of uploading artifacts

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
chore: cleanup unused CSI images
Fixes #
```
none
```
> chore: cleanup unused CSI images

- e2e/README.md
add section to abe2e docs on changing abe2e test images
Fixes #
```
none
```
> feat: add guidance for changing test images to abe2e docs

- .pipelines/.vsts-vhd-builder-release-windows.yaml
- .pipelines/.vsts-vhd-builder-windows.yaml
- .pipelines/templates/.builder-release-template-windows-cleanup.yaml
- .pipelines/templates/.builder-release-template-windows.yaml
- vhdbuilder/packer/init-variables.sh
/kind migration
Use windows ame subscription to build vhd.
Fixes #
```
none
```
> chore: use windows ame sub to build vhd

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind cleanup
chore: remove unused azure file v1.24.1 image cache
Fixes #
```
none
```
> chore: remove unused azure file v1.24.1 image cache

- vhdbuilder/packer/components.json
Updating image version for azure monitor metrics addon
/kind feature
> feat: update managed prometheus image june

- vhdbuilder/scripts/automate_ev2pipeline_trigger.sh
This PR updates automation pipeline to use the new official onebranch ev2 vhd artifacts pipeline for SIG release.
This is the pipeline that will be used: https://msazure.visualstudio.com/CloudNativeCompute/_build?definitionId=319030
Fixes #
```
none
```
> fix: change ev2 artifact pipeline ID to official onebranch

- vhdbuilder/packer/components.json
/kind cleanup
Fixes #
```
cache Cilium 1.12.10
```
> chore: cache cilium 1.12.10

- vhdbuilder/packer/components.json
/kind cleanup
Fixes #
Keeping v0.1.6 for now to reduce load on MCR as this rolls out.
```
cache ip-masq-agent-v2 v0.1.7
```
> chore: cache ip-masq-agent-v2 v0.1.7

- e2e/exec.go
- e2e/suite_test.go
- e2e/vmss.go
fixes log collection when cse fails during abe2e tests
Fixes #
```
none
```
> fix: abe2e log collection when cse fails

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind
Optionally add one or more of the following kinds if applicable:
/kind api-change
/kind flake
-->
Fixes #
```
https://github.com/microsoft/Docker-Provider/blob/ci_prod/ReleaseNotes.md
```
> chore: update ciprod images to win-3.1.9 and 3.1.9

- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
- vhdbuilder/packer/windows-image.env
- vhdbuilder/packer/write-release-notes-windows.ps1
/kind feature
1. update Windows base images to 2023.06B
WS2019: [June 13, 2023—KB5027222 (OS Build 17763.4499)](https://support.microsoft.com/en-us/topic/june-13-2023-kb5027222-os-build-17763-4499-8aa0687f-06aa-4789-ab4e-6bff4897a33e)
WS2022: [June 13, 2023—KB5027225 (OS Build 20348.1787)](https://support.microsoft.com/en-us/topic/june-13-2023-kb5027225-os-build-20348-1787-d2b4b682-935f-4afb-8de0-2265ae7d67e9)
2. setting registry keys to enable some fixes
Fixes #
```
none
```
> chore: update Windows base images to 2023.06B with setting registry keys

- .pipelines/.vsts-vhd-automation.yaml
> bump: golang version for automation

- .pipelines/.vsts-vhd-automation.yaml
> chore: use curl to get go version

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
Adds CNS v1.4.44.1 which is the upgrade to 1.4.44* in all of prod - 1.5.3 is baking for certain subs only.
Fixes #
```
none
```
> chore: add cns v1.4.44.1

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: upgrade Azure Disk and File CSI driver versions in vhd cache 
Fixes #
```
chore: upgrade Azure Disk and File CSI driver versions in vhd cache 
```
> chore: upgrade Azure Disk and File CSI driver versions in vhd cache 

- e2e/scenario/scenario_marinerv2-custom-sysctls.go
- e2e/scenario/scenario_ubuntu2204-custom-sysctls.go
- pkg/agent/baker.go
- pkg/agent/datamodel/types.go
> fix: change nofile ulimit to string

- e2e/scenario/scenario_marinerv2-custom-sysctls.go
- e2e/scenario/scenario_ubuntu2204-custom-sysctls.go
- pkg/agent/baker.go
- pkg/agent/datamodel/types.go
> fix: cherry pick change nofile ulimit to string

- .pipelines/templates/.builder-release-template-windows.yaml
- vhdbuilder/packer/list-images.ps1
- vhdbuilder/packer/windows-vhd-builder-sig.json
/kind feature
generate image bom for Windows VHDs
Fixes #
```
none
```
> feat: generate image bom for Windows VHDs

- vhdbuilder/release-notes/autonotes/main.go
> docs: fips notes for mariner skus

- e2e/scenario/images.go
This PR updates AB e2e images to incorporate for newer changes.
Fixes #
```
none
```
> bump: update ab e2e VHDs

- parts/windows/kuberneteswindowssetup.ps1
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- pkg/templates/templates_generated.go
- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
bump Windows CSE script package to v0.0.26
Fixes #
```
none
```
> chore: bump Windows CSE script package to v0.0.26

- .pipelines/templates/.builder-release-template.yaml
- vhdbuilder/packer/test/linux-vhd-content-test.sh
- vhdbuilder/packer/test/run-test.sh
This reverts commit 2bbf1058c89e5c5ff2f314fcb9bda13cd79da66e.
/kind bug
/kind test
The aforementioned commit checks out the git branch passed to use by the build pipeline in our tests. However, it doesn't work in all cases (notably pull request branches), so reverting it while figuring out the right solution.
```
none
```
> Revert "test: clone the branch from the build rather main for testing (#3342)"

- staging/cse/windows/provisioningscripts/loggenerator.ps1
/kind feature
collect windowslogscleanup.log in GuestVMLogs
Fixes #
```
none
```
> feat: collect windowslogscleanup.log in GuestVMLogs

- pkg/agent/baker.go
/kind feature
only enable HNSRemediator for Windows 2019.
Fixes #
```
none
```
> feat: only enable HNSRemediator for Windows 2019

- e2e/windows/e2e-starter.sh
/kind fix
Add judgement of different provisioning states for cluster in Windows e2e
Fixes #
```
none
```
> fix: add judgement of different provisioning states for cluster in Windows e2e

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
- vhdbuilder/packer/install-dependencies.sh
- vhdbuilder/packer/test/windows-vhd-content-test.ps1
/kind feature
Upgrading Azure CNS to v1.4.44.2 and v1.5.5; adding CNI v1.5.5, and adding dropgz v0.0.9
Fixes #
[v1.4.44.2](https://github.com/Azure/azure-container-networking/releases/tag/v1.4.44.2)
> chore: upgrade acn components

- e2e/windows/e2e-helper.sh
- e2e/windows/e2e-starter.sh
- e2e/windows/scenarios/windows/property-windows-template.json
Clean up created storage container in cse validation
Fixes #
```
none
```
> fix: clean up created storage container in cse validation

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: upgrade CSI driver image versions
Fixes #
```
none
```
> chore: upgrade CSI driver image versions

- parts/linux/cloud-init/artifacts/aks-rsyslog
- pkg/templates/templates_generated.go
/kind bug
This PR adds /var/log/secure to the rsyslog logrotate file. The file is present in the /etc/logrotate.d/rsyslog [shipped with Azure Linux](https://github.com/microsoft/CBL-Mariner/blob/9765a16d34a7f726960da6cb0d27841aa46c9366/SPECS/rsyslog/rsyslog.logrotate#L2C6-L2C6), but the file is replaced during AgentBaker image builds.
This change won't have any impact on the Ubuntu hosts since the file is not present and the rotate is defined with `missingok`
This file is one of the locations on AzureLinux where audit data gets logged and it needs to be rotated or else it will gradually fill up the disk.
Fixes #
``` …
```
> fix: add /var/log/secure to rsyslog logrotate

- vhdbuilder/packer/windows-image.env
/kind feature
Update Windows base image to get .net 202306OOB fix.
Fixes #
```
none
```
> chore: update Windows base image to get .net 202306OOB fix

- pkg/agent/datamodel/sig_config.go
- pkg/agent/datamodel/sig_config_test.go
- pkg/agent/datamodel/types.go
This PR adds sig config for Ubuntu Minimal VHD.
Fixes #
```
none
```
> chore: add sig config for ubuntu minimal

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
> feat: containerinsights 3.1.10 release

- vhdbuilder/packer/post-install-dependencies.sh
- vhdbuilder/packer/pre-install-dependencies.sh
> fix: installDeps with UA attached to install from ESM

- staging/cse/windows/configfunc.ps1
/kind feature
retag images for AzureChinaCloud in provisioning Windows nodes. We will remove retagging images in building Windows VHDs soon
Fixes #
```
none
```
> feat: retag images for AzureChinaCloud in provisioning Windows nodes

- .pipelines/scripts/verify_shell.sh
> fix: ignore .git dir in shell-check

- staging/cse/windows/configfunc.ps1
/kind feature
clear existing images tags in non-AzureChinaCloud
Fixes #
```
none
```
> feat: clear existing images tags in non-AzureChinaCloud

- parts/windows/kuberneteswindowssetup.ps1
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- pkg/templates/templates_generated.go
- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
1. bump Windows CSE script package to v0.0.27
2. Clear tags for AzureChinaCloud in non-AzureChinaCloud
3. Add tags for AzureChinaCloud in AzureChinaCloud
Fixes #
```
none
```
> chore: bump Windows CSE script package to v0.0.27

- e2e/windows/scenarios/windows/property-windows-template.json
- parts/windows/kuberneteswindowssetup.ps1
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- pkg/templates/templates_generated.go
- staging/cse/windows/kubeletfunc.ps1
/kind cleanup
remove unused function
Fixes #967
```
none
```
> chore: remove unused function

- staging/cse/windows/debug/collect-windows-logs.ps1
/kind bug
fix the bug in collect-windows-logs.ps1
Fixes #
```
none
```
> fix: fix the bug in collect-windows-logs.ps1

- staging/cse/windows/debug/collect-windows-logs.ps1
/kind bug
fix wrong log in Windows debug script
Fixes #
```
none
```
> fix: fix wrong log in Windows debug script

- parts/windows/kuberneteswindowssetup.ps1
- pkg/agent/testdata/AKSWindows2019+CustomCloud/CustomData
- pkg/agent/testdata/AKSWindows2019+CustomVnet/CustomData
- pkg/agent/testdata/AKSWindows2019+EnablePrivateClusterHostsConfigAgent/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S116/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S117/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S118/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+CSI/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119+FIPS/CustomData
- pkg/agent/testdata/AKSWindows2019+K8S119/CustomData
- pkg/agent/testdata/AKSWindows2019+KubeletClientTLSBootstrapping/CustomData
- pkg/agent/testdata/AKSWindows2019+ManagedIdentity/CustomData
- pkg/templates/templates_generated.go
- staging/cse/windows/README
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
bump Windows CSE script package to v0.0.29
Fixes #
```
none
```
> chore: bump Windows CSE script package to v0.0.29

- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: add azurefile-csi:v1.28.1-windows-hp image in vhd image cache
Fixes #
```
none
```
> chore: add azurefile-csi:v1.28.1-windows-hp image in vhd image cache

- .pipelines/e2e-windows.yaml
/kind modification
Modify trigger condition of windows e2e pipeline to keep it the same as that of trigger settings in pipeline.
- "trigger: none" is used to disable CI trigger.
- Add additional path for pr trigger.
Fixes #
```
none
```
> chore: modify trigger condition of windows e2e pipeline

- parts/linux/cloud-init/artifacts/mariner/cse_install_mariner.sh
- vhdbuilder/scripts/linux/mariner/tool_installs_mariner.sh
Replace old loader with new loader.
There is an issue with crashkernel triggering cloud-init to fail upon deployment... will need to remove that until we can get a handle on that issue
```
none
```
> feat: Replace old loader with new loader.

- .pipelines/.vsts-vhd-builder-release-windows.yaml
- .pipelines/.vsts-vhd-builder-windows.yaml
- .pipelines/templates/.builder-release-template-windows.yaml
- vhdbuilder/packer/configure-windows-vhd.ps1
- vhdbuilder/packer/init-variables.sh
- vhdbuilder/packer/windows-vhd-builder-sig.json
/kind feature
support caching private packages on Windows VHDs
Fixes #
```
none
```
> feat: support caching private packages on Windows VHDs

- parts/linux/cloud-init/artifacts/mariner/cse_install_mariner.sh
- vhdbuilder/scripts/linux/mariner/tool_installs_mariner.sh
> fix: Stop stomping kernel-mshv with LSG's version in kata images

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
adding CNS v1.4.44.4
diff of update https://github.com/Azure/azure-container-networking/compare/v1.4.44.3...v1.4.44.4
Fixes #
```
none
```
> chore: add cns v1.4.44.4

- vhdbuilder/packer/components.json
/kind cleanup
Remove the images for HTTP App Routing feature, which is deprecated.
Fixes #
```
none
```
> chore: remove HTTP App Routing Images

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
> feat: containerinsights 3.1.11 release

- vhdbuilder/packer/components.json
- vhdbuilder/packer/generate-windows-vhd-configuration.ps1
/kind feature
chore: upgrade CSI driver versions
This PR upgrades Azure Disk CSI driver to v1.26.6 and v1.28.2, upgrades Azure File CSI driver to v1.24.4 and v1.26.4, mainly for fixing CVEs
Fixes #
```
none
```
> chore: upgrade CSI driver versions to fix CVEs
